### ISSUE TITLE
unet预测的时候出现异常

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleSeg#1017]
在预测的时候出现以下异常，观察到时conv2D的时候不支持uint8，代码没有改动过，训练的时候正常，预测的时候突然出现的异常
`Traceback (most recent call last):
  File "predict.py", line 184, in <module>
    main(args)
  File "predict.py", line 178, in main
    stride=args.stride,
  File "/home/aistudio/work/PaddleSeg/paddleseg/core/predict.py", line 115, in predict
    crop_size=crop_size)
  File "/home/aistudio/work/PaddleSeg/paddleseg/core/infer.py", line 203, in inference
    logits = model(im)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/PaddleSeg/paddleseg/models/unet.py", line 63, in forward
    x, short_cuts = self.encode(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/PaddleSeg/paddleseg/models/unet.py", line 95, in forward
    x = self.double_conv(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/container.py", line 95, in forward
    input = layer(input)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/PaddleSeg/paddleseg/models/layers/layer_libs.py", line 45, in forward
    x = self._conv(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 660, in forward
    use_cudnn=self._use_cudnn)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 119, in _conv_nd
    pre_bias = getattr(core.ops, op_type)(x, weight, *attrs)
RuntimeError: (NotFound) Operator conv2d does not have kernel for data_type[uint8_t]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[CUDNN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:128)
  [operator < conv2d > error]`

**Comment by BeyondYourself** [comment]
@wuyefeilin 大神帮忙看看是什么问题

**Comment by michaelowenliu** [comment]
@BeyondYourself Hi, could you please show the prediction code? before that, you may check the tensor type.

**Comment by BeyondYourself** [comment]
ok, thanks , I've solved it
