### ISSUE TITLE
Unet3+跑自定义数据集时可以训练但验证出现错误

### ISSUE THREAD

**Issue by yangkerrr** [PaddlePaddle/PaddleSeg#1062]
Traceback (most recent call last):
  File "train.py", line 169, in <module>
    main(args)
  File "train.py", line 164, in main
    test_config=cfg.test_config)
  File "/home/aistudio/PaddleSeg/paddleseg/core/train.py", line 214, in train
    model, val_dataset, num_workers=num_workers, **test_config)
  File "/home/aistudio/PaddleSeg/paddleseg/core/val.py", line 117, in evaluate
    crop_size=crop_size)
  File "/home/aistudio/PaddleSeg/paddleseg/core/infer.py", line 216, in inference
    logits = model(im)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleSeg/paddleseg/models/unet_3plus.py", line 88, in forward
    hds = self.decoder(hs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleSeg/paddleseg/models/unet_3plus.py", line 226, in forward
    hd5_UT_hd1 = self.hd5_UT_hd1_cbr(self.hd5_UT_hd1(hd5))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/common.py", line 373, in forward
    name=self.name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/common.py", line 457, in interpolate
    out = core.ops.bilinear_interp_v2(x, *dy_attr)
ValueError: (InvalidArgument) element count should be greater than 0, but received value is: -1978662912.
  [Hint: Expected element_count > 0, but received element_count:-1978662912 <= 0:0.] (at /paddle/paddle/fluid/platform/gpu_launch_config.h:54)
  [operator < bilinear_interp_v2 > error]

**Comment by haoyuying** [comment]
您好，请给出一个可以复现问题的aistudio环境，方便我们查找问题。

**Comment by lipanr** [comment]
在Paddle2.0版本跑VOC数据集时一直出现这个错误，训练几十条图片后出现的。

**Comment by haoyuying** [comment]
您好，是这样，unet系列对于图片的大小有很强的限制，如果您不是一定要用该模型，建议不要使用unet系列模型，这系列的模型主要是针对医疗场景，验证图片和训练图片都有固定尺寸的场景。
