### ISSUE TITLE
训练自定义数据集出现异常

### ISSUE THREAD

**Issue by a2824256** [PaddlePaddle/PaddleSeg#1089]
paddle版本：2.1
PaddleSeg：release/2.1
cuda: 10.2

报错信息如下, 省略一部分重复。
```
2021-06-16 01:43:01 [INFO]
------------Environment Information-------------
platform: Windows-10-10.0.19041-SP0
Python: 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]
Paddle compiled with cuda: True
NVCC: Not Available
cudnn: 7.6
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU:  Can not get GPU information. Please make sure CUDA have been installed successfully.
PaddlePaddle: 2.1.0
OpenCV: 4.5.2
------------------------------------------------
2021-06-16 01:43:01 [INFO]
---------------Config Information---------------
batch_size: 1
iters: 1000
loss:
  coef:
  - 1
  types:
  - ignore_index: 255
    type: CrossEntropyLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 0.01
  power: 0.9
  type: PolynomialDecay
model:
  in_channels: 3
  is_CGM: false
  is_batchnorm: true
  is_deepsup: false
  num_classes: 8
  type: UNet3Plus
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 4.0e-05
train_dataset:
  dataset_root: data/ct
  mode: train
  num_classes: 8
  train_path: data/ct/train_list.txt
  transforms:
  - target_size:
    - 512
    - 512
    type: Resize
  - type: RandomHorizontalFlip
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: data/ct
  mode: val
  num_classes: 8
  transforms:
  - target_size:
    - 512
    - 512
    type: Resize
  - type: Normalize
  type: Dataset
  val_path: data/ct/train_list.txt
------------------------------------------------
W0616 01:43:01.585747 14868 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.3, Runtime API Version: 10.2
W0616 01:43:01.585747 14868 device_context.cc:422] device: 0, cuDNN Version: 7.6.
Error: C:/home/workspace/Paddle_release/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == igno
re_idx_` failed. The value of label[70484] expected >= 0 and < 0, or == 8,but got 0. Please check input value.
Error: C:/home/workspace/Paddle_release/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == igno
re_idx_` failed. The value of label[70484] expected >= 0 and < 0, or == 8,but got 0. Please check input value.
Error: C:/home/workspace/Paddle_release/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == igno
re_idx_` failed. The value of label[70484] expected >= 0 and < 0, or == 8,but got 0. Please check input value.
Error: C:/home/workspace/Paddle_release/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == igno
re_idx_` failed. The value of label[70484] expected >= 0 and < 0, or == 8,but got 0. Please check input value.
Error: C:/home/workspace/Paddle_release/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == igno
re_idx_` failed. The value of label[70484] expected >= 0 and < 0, or == 8,but got 0. Please check input value.
Error: C:/home/workspace/Paddle_release/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == igno
re_idx_` failed. The value of label[70484] expected >= 0 and < 0, or == 8,but got 0. Please check input value.
Error: C:/home/workspace/Paddle_release/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == igno
re_idx_` failed. The value of label[70484] expected >= 0 and < 0, or == 8,but got 0. Please check input value.
Error: C:/home/workspace/Paddle_release/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == igno
re_idx_` failed. The value of label[70484] expected >= 0 and < 0, or == 8,but got 0. Please check input value.
Error: C:/home/workspace/Paddle_release/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == igno
re_idx_` failed. The value of label[70483] expected >= 0 and < 0, or == 8,but got 0. Please check input value.
Error: C:/home/workspace/Paddle_release/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == igno
re_idx_` failed. The value of label[70483] expected >= 0 and < 0, or == 8,but got 0. Please check input value.
Error: C:/home/workspace/Paddle_release/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == igno
re_idx_` failed. The value of label[70483] expected >= 0 and < 0, or == 8,but got 0. Please check input value.
Error: C:/home/workspace/Paddle_release/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == igno
re_idx_` failed. The value of label[70483] expected >= 0 and < 0, or == 8,but got 0. Please check input value.
------------------------------------------省略一部分差不多的信息------------------------------------------
Error: C:/home/workspace/Paddle_release/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == igno
re_idx_` failed. The value of label[140683] expected >= 0 and < 0, or == 8,but got 0. Please check input value.
Error: C:/home/workspace/Paddle_release/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == igno
re_idx_` failed. The value of label[140683] expected >= 0 and < 0, or == 8,but got 0. Please check input value.
Error: C:/home/workspace/Paddle_release/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == igno
re_idx_` failed. The value of label[140683] expected >= 0 and < 0, or == 8,but got 0. Please check input value.
Error: C:/home/workspace/Paddle_release/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0 && labels_[idx_lbl] < d_ || labels_[idx_lbl] == igno
re_idx_` failed. The value of label[140683] expected >= 0 and < 0, or == 8,but got 0. Please check input value.
Traceback (most recent call last):
  File "train.py", line 168, in <module>
    main(args)
  File "train.py", line 163, in main
    keep_checkpoint_max=args.keep_checkpoint_max)
  File "E:\PaddleSeg\paddleseg\core\train.py", line 163, in train
    avg_loss += loss.numpy()[0]
OSError: (External)  Cuda error(719), unspecified launch failure.
  [Advise: Please search for the error code(719) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c217824
6db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at C:\home\workspace\Paddle_release\paddle\fluid\platform\gpu_info.cc:394)
```

配置文件ct.yml, 内容如下：
```
batch_size: 1
iters: 1000

train_dataset:
  type: Dataset
  dataset_root: data/ct
  train_path: data/ct/train_list.txt
  num_classes: 8
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: data/ct
  num_classes: 8
  val_path: data/ct/train_list.txt
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: Normalize
  mode: val

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]

model:
  type: UNet3Plus
  in_channels: 3
  num_classes: 8
  is_batchnorm: True
  is_deepsup: False
  is_CGM: False
```

训练指令：
```
python train.py --config configs/ct.yml --do_eval --save_interval 500  --save_dir output
```

labels.txt文件内容
```
背景
动脉
骨骼
肝脏
肺
静脉
肾脏
脾

```

输入图片是RGB的jpg，label是8位png
训练quick_start一切正常

**Comment by haoyuying** [comment]
这个问题可能是由于您自定义的dataset在调用paddle.io.DataLoader前已经把数据转成了tensor的形式。在定义dataset数据时在__getitem__传回的数据要保证numpy的形式。

**Comment by a2824256** [comment]
@haoyuying 我打印了一下，数据还是numpy形式的
![image](https://user-images.githubusercontent.com/7108023/122339098-360de100-cf73-11eb-86b1-92fb0ff0206b.png)

**Comment by a2824256** [comment]
目前怀疑是图片问题，图片是8位的jpg，用PIL.Image输出图片的mode是L

我将配置文件的in_channels从3改成1的时候就会报下面的错误，改成3就会报上面的错误。用optic_disc_seg数据集的，三通道就正常。

```
ValueError: (InvalidArgument) The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 3, the input's shape is [1,
3, 512, 512]; the filter's channels is 1, the filter's shape is [64, 1, 3, 3]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:3 != filter_dims[1] * groups:1.] (at C:/home/workspace/Paddle_release/paddle/fluid/operators/conv_
op.cc:100)
  [operator < conv2d > error]
```

**Comment by a2824256** [comment]
图片的属性
![image](https://user-images.githubusercontent.com/7108023/122340299-b41eb780-cf74-11eb-99dd-9e7d0b097b7a.png)

**Comment by a2824256** [comment]
>  But received: the input's channels is 3, the input's shape is [1,
> 3, 512, 512]; the filter's channels is 1, the filter's shape is [64, 1, 3, 3]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.

我有点没搞懂这里，提示输入的通道是3，但是我图片和in_channels都已经设置为1了

**Comment by a2824256** [comment]
是否是因为PIL.Image.open打开单通道的图都会变成三通道？

**Comment by a2824256** [comment]
刚尝试了一下，输入单通道的图片，在Dataset的__getitem__函数return的im是三通道的

**Comment by a2824256** [comment]
你们用cv2.imread来读，读出来的ndarray是三通道的，我换成PIL.Image.open来读，读出来单通道，Resize又会有个通道检测
```
        if len(im.shape) != 3:
            raise ValueError('Resize: image is not 3-dimensional.')
```
目前框架是不支持单通道灰度图是吧？

**Comment by haoyuying** [comment]
因为在对数据读取的时候使用了cv2,cv2在读取灰度图时候仍然会把它变成三通道。
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.1/paddleseg/datasets/dataset.py#L146
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.1/paddleseg/transforms/transforms.py#L56

且图像在输入时img要为float32，lable类型要为int64, 请与quick_start提供的数据集的img和label保持相同的数据类型。

**Comment by a2824256** [comment]
现在问题是我网络输入的是单通道，我单通道的图片会被转成三通道，我也调试过源码，用PIL.Image.open，在Compose里面有些数据增强方法（例如Resize）检测到shape < 3的时候就会抛出异常，我把（512,512）的图片数据维度改成（512,512,1）还是（1,512,512）这种情况，又会报其他错误，太难受了。不改源码，网络的输入是单通道，但是数据在输入前会被转为三通道，到输入网络的时候又会报维度错误。而且我看你们的教程的输入都是三通道的图像，医学图像有的数据是单通道灰度图，希望完善一下教程吧。

**Comment by haoyuying** [comment]
您好，因为常用的图像处理都是对三通道的处理，如果您的图像是的单通道图像，由于cv2读取，对于seg本身提供的模型是不影响的。若您想使用自己的网络和数据集，对图像的处理也和三通道图像是不同的，所以需要自己对图像进行预处理。seg目前暂时不支持医学影像数据集，感谢您的建议，我们会给予高度重视并在日后完善单通道处理问题。

**Comment by a2824256** [comment]
谢谢
