### ISSUE TITLE
训练AttentionUnet出现报错AttributeError: 'AttentionUNet' object has no attribute 'data_format'

### ISSUE THREAD

**Issue by deadkany** [PaddlePaddle/PaddleSeg#1155]
Traceback (most recent call last):
  File "train.py", line 182, in <module>
    main(args)
  File "train.py", line 177, in main
    fp16=args.fp16)
  File "/export/home/yaopu/ylx/PaddleSeg/paddleseg/core/train.py", line 155, in train
    if model.data_format == 'NHWC':
  File "/export/home/yaopu/anaconda3/envs/ylx/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1050, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'AttentionUNet' object has no attribute 'data_format'

**Comment by wuyefeilin** [comment]
请更新下版本哈

**Comment by deadkany** [comment]
> 请更新下版本哈

Paddleseg吗，是最新的呀

**Comment by wuyefeilin** [comment]
目前最新的是2.2分支哈
