### ISSUE TITLE
使用labelme2seg.py进行数据类型转换时报错

### ISSUE THREAD

**Issue by BBBBing** [PaddlePaddle/PaddleSeg#1166]
class_names: ('_background_', 'edge')
Saved class_names: \\PaddleSeg\\Data\class_names.txt
Generating dataset from: \\PaddleSeg\\Data\scene00001.json
Traceback (most recent call last):
  File "\PaddleSeg\legacy\contrib\NeurIPS_SN7\pdseg\tools\labelme2seg.py", line 126, in <module>
    main(args)
  File "\PaddleSeg\legacy\contrib\NeurIPS_SN7\pdseg\tools\labelme2seg.py", line 87, in main
    class_name_mapping=class_name_to_id,
  File "\PaddleSeg\legacy\contrib\NeurIPS_SN7\pdseg\tools\labelme2seg.py", line 119, in shape2label
    label_mask = shape2mask(img_size[:2], points)
  File \PaddleSeg\legacy\contrib\NeurIPS_SN7\pdseg\tools\labelme2seg.py", line 104, in shape2mask
    label_mask = PIL.Image.fromarray(np.zeros(img_size[:2], dtype=np.uint8))
  File "\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2778, in fromarray
    size = 1 if ndim == 1 else shape[1], shape[0]
IndexError: tuple index out of range

我是用labelme标注好的jpg和json，请问有什么解决思路吗

**Comment by BBBBing** [comment]
> class_names: ('_background_', 'edge')
> Saved class_names: \PaddleSeg\Data\class_names.txt
> Generating dataset from: \PaddleSeg\Data\scene00001.json
> Traceback (most recent call last):
> File "\PaddleSeg\legacy\contrib\NeurIPS_SN7\pdseg\tools\labelme2seg.py", line 126, in
> main(args)
> File "\PaddleSeg\legacy\contrib\NeurIPS_SN7\pdseg\tools\labelme2seg.py", line 87, in main
> class_name_mapping=class_name_to_id,
> File "\PaddleSeg\legacy\contrib\NeurIPS_SN7\pdseg\tools\labelme2seg.py", line 119, in shape2label
> label_mask = shape2mask(img_size[:2], points)
> File \PaddleSeg\legacy\contrib\NeurIPS_SN7\pdseg\tools\labelme2seg.py", line 104, in shape2mask
> label_mask = PIL.Image.fromarray(np.zeros(img_size[:2], dtype=np.uint8))
> File "\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2778, in fromarray
> size = 1 if ndim == 1 else shape[1], shape[0]
> IndexError: tuple index out of range
> 
> 我是用labelme标注好的jpg和json，请问有什么解决思路吗

paddlepaddle 21.1.3
paddleseg 21.1.3

**Comment by BBBBing** [comment]
![image](https://user-images.githubusercontent.com/41807655/125776719-8cb1d8b6-7459-427b-8db7-445ab2f2ae0b.png)

**Comment by BBBBing** [comment]
for label_file in glob.glob(osp.join(input_dir, '*.json')):
    print('Generating dataset from:', label_file)
    with open(label_file) as f:
        base = osp.splitext(osp.basename(label_file))[0]
        out_png_file = osp.join(output_dir, base + '.png')

        
        data = json.load(f)

        img_file = osp.join(osp.dirname(label_file), data['imagePath'])
        **img = np.asarray(cv2.imread(img_file))**
---改成---
        **img = np.asarray(PIL.Image.open(img_file))**

拆开看了一下，是这个步骤没有读到jpg，改成PIL读取就好了
