### ISSUE TITLE
PaddleSeg训练模型，转换为PaddleServing模型时出错

### ISSUE THREAD

**Issue by Deo0330** [PaddlePaddle/PaddleSeg#1188]
使用paddleseg0.5.0 paddle1.8.0
!python PaddleSeg/PaddleSeg/pdseg/export_serving_model.py --cfg PaddleSeg/configs/unet_optic.yaml TEST.TEST_MODEL work/PaddleSeg-release-v0.5.0/saved_model/unet_optic/final
错误提示：
Exporting serving model...
load test model: work/PaddleSeg-release-v0.5.0/saved_model/unet_optic/final
Traceback (most recent call last):
  File "PaddleSeg/PaddleSeg/pdseg/export_serving_model.py", line 135, in <module>
    main()
  File "PaddleSeg/PaddleSeg/pdseg/export_serving_model.py", line 131, in main
    export_serving_model(args)
  File "PaddleSeg/PaddleSeg/pdseg/export_serving_model.py", line 109, in export_serving_model
    from paddle_serving_client.io import save_model
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle_serving_client/io/__init__.py", line 24, in <module>
    from paddle.fluid.core import CipherUtils
ImportError: cannot import name 'CipherUtils' from 'paddle.fluid.core_avx' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/core_avx.so)

**Comment by haoyuying** [comment]
您好，您使用的paddleseg和paddle版本过于陈旧，请安装2.0版本以上的paddleseg及paddle获得更好的体验。

**Comment by Deo0330** [comment]
> 您好，您使用的paddleseg和paddle版本过于陈旧，请安装2.0版本以上的paddleseg及paddle获得更好的体验。

感谢您的回复，在换为2.0.版本paddle和2.2版本paddleseg后，问题解决了
