### ISSUE TITLE
deeplabv3p export 错误

### ISSUE THREAD

**Issue by yuemengrui** [PaddlePaddle/PaddleSeg#1239]
报错如下：
Traceback (most recent call last):
  File "export_1.py", line 135, in <module>
    main(args)
  File "export_1.py", line 114, in main
    paddle.jit.save(new_net, save_path)
  File "<decorator-gen-67>", line 2, in save
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 719, in save
    inner_input_spec)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-65>", line 2, in from_func_spec
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 658, in from_func_spec
    error_data.raise_new_exception()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 192, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AssertionError: In transformed code:

    File "export_1.py", line 68, in forward (* user code *)
        outs = self.net(x)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
        outputs = self.forward(*inputs, **kwargs)
    File "/home/aistudio/My_PaddleSeg/paddleseg/models/deeplab.py", line 83, in forward (* user code *)
        logit_list = self.head(feat_list)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
        outputs = self.forward(*inputs, **kwargs)
    File "/home/aistudio/My_PaddleSeg/paddleseg/models/deeplab.py", line 155, in forward (* user code *)
        logit = self.decoder(x, low_level_feat)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
        outputs = self.forward(*inputs, **kwargs)
    File "/home/aistudio/My_PaddleSeg/paddleseg/models/deeplab.py", line 305, in forward (* user code *)
        data_format=self.data_format)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/common.py", line 365, in interpolate
        "Each dimension size given in out_shape must be greater than 0."
    AssertionError: Each dimension size given in out_shape must be greater than 0.

**Comment by nepeplwu** [comment]
@yuemengrui 你的paddle版本和paddleseg版本分别是多少呢？

**Comment by yuemengrui** [comment]
> @yuemengrui 你的paddle版本和paddleseg版本分别是多少呢？

paddlepaddle-gpu       2.1.0.post101

paddleseg是直接clone PaddleSeg本仓库的

我之前的deeplabv3p是可以成功导出的，我之前用的paddleseg是在这个提交之前的版本
![image](https://user-images.githubusercontent.com/24349763/128699492-3eab7b75-50eb-4f8f-b171-a66ee702d383.png)
在这个提交之后的export有错误

**Comment by nepeplwu** [comment]
@yuemengrui 试试更新到最新代码，最新代码中已经修复过了

**Comment by yuemengrui** [comment]
> @yuemengrui 试试更新到最新代码，最新代码中已经修复过了

最新的代码可以正确导出， 谢谢！
