### ISSUE TITLE
SFnet  训练到中途报错

### ISSUE THREAD

**Issue by 534114658** [PaddlePaddle/PaddleSeg#1264]
SFnet  训练到中途报错

报错内容如下：

2021-08-19 19:12:33 [INFO]      [TRAIN] epoch: 166, iter: 16350/20000, loss: 0.0527, lr: 0.002164, batch_cost: 0.7536, reader_cost: 0.28205, ips: 21.2319 samples/sec | ETA 00:45:50
2021-08-19 19:12:41 [INFO]      [TRAIN] epoch: 166, iter: 16360/20000, loss: 0.0464, lr: 0.002159, batch_cost: 0.7421, reader_cost: 0.28185, ips: 21.5600 samples/sec | ETA 00:45:01
WARNING:root:DataLoader reader thread raised an exception.
Traceback (most recent call last):
Exception in thread   File "train.py", line 190, in <module>
Thread-168:
Traceback (most recent call last):
      File "D:\\lib\threading.py", line 932, in _bootstrap_inner
main(args)
  File "train.py", line 169, in main
    train(
  File "D:\paddleseg\core\train.py", line 143, in train
    for data in loader:
  File "D:\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 204, in __next__
    self.run()
  File "D:\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 199, in _thread_loop
        data = self._reader.read_next_var_list()six.reraise(*sys.exc_info())

SystemError  File "D:\\lib\site-packages\six.py", line 719, in reraise
: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/operators/reader/blocking_queue.h:166)

    raise value
  File "D:\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 167, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "D:\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 66, in fetch
    data = self.collate_fn(data)
  File "D:\lib\site-packages\paddle\fluid\dataloader\collate.py", line 77, in default_collate_fn
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "D:\lib\site-packages\paddle\fluid\dataloader\collate.py", line 77, in <listcomp>
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "D:\lib\site-packages\paddle\fluid\dataloader\collate.py", line 58, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 5, in stack
  File "D:\lib\site-packages\numpy\core\shape_base.py", line 434, in stack
    return _nx.concatenate(expanded_arrays, axis=axis, out=out)
  File "<__array_function__ internals>", line 5, in concatenate
MemoryError: Unable to allocate 44.2 MiB for an array with shape (16, 3, 471, 512) and data type float32

这是什么问题？

**Comment by LutaoChu** [comment]
看报错信息是训练过程内存不够了，可以缩小batch size试试

**Comment by 534114658** [comment]
好的
