### ISSUE TITLE
Multi-gpu error

### ISSUE THREAD

**Issue by AKMourato** [PaddlePaddle/PaddleSeg#1283]
Greetings. I cannot find a way to solve the supposed issue of NCCL for distributed training.
```python
$python -m paddle.distributed.launch train.py --config unet22.yml --do_eval --use_vdl --save_interval 6000  --save_dir unet22-alldata
-----------  Configuration Arguments -----------
gpus: None
heter_worker_num: None
heter_workers: 
http_port: None
ips: 127.0.0.1
log_dir: log
nproc_per_node: None
run_mode: None
server_num: None
servers: 
training_script: train.py
training_script_args: ['--config', 'unet22.yml', '--do_eval', '--use_vdl', '--save_interval', '6000', '--save_dir', 'unet22-alldata']
worker_num: None
workers: 
------------------------------------------------
WARNING 2021-08-24 16:30:34,253 launch.py:358] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
launch train in GPU mode!
INFO 2021-08-24 16:30:34,254 launch_utils.py:507] Local start 2 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:44337               |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:44337,127.0.0.1:43683       |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                       0,1                     |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2021-08-24 16:30:34,254 launch_utils.py:512] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
launch proc_id:834345 idx:0
launch proc_id:834350 idx:1
2021-08-24 16:30:35 [INFO]
------------Environment Information-------------
platform: Linux-5.4.0-80-generic-x86_64-with-glibc2.17
Python: 3.8.11 (default, Aug  3 2021, 15:09:35) [GCC 7.5.0]
Paddle compiled with cuda: True
NVCC: Build cuda_11.4.r11.4/compiler.30188945_0
cudnn: 7.6
GPUs used: 2
CUDA_VISIBLE_DEVICES: 1,3
GPU: ['GPU 0: NVIDIA GeForce', 'GPU 1: NVIDIA GeForce', 'GPU 2: NVIDIA GeForce', 'GPU 3: NVIDIA GeForce']
GCC: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
PaddlePaddle: 2.1.2
OpenCV: 4.5.3
------------------------------------------------
2021-08-24 16:30:35 [INFO]
---------------Config Information---------------
batch_size: 1
iters: 160000
loss:
  coef:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  types:
  - ignore_index: 255
    type: CrossEntropyLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 0.0003
  power: 0.9
  type: PolynomialDecay
model:
  num_classes: 2
  pretrained: null
  type: U2Net
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 4.0e-05
train_dataset:
  dataset_root: /home/amourato/VM/New_COCO_DPD/train/
  mode: train
  num_classes: 2
  train_path: /home/amourato/VM/New_COCO_DPD/train/train.txt
  transforms:
  - target_size:
    - 1024
    - 1024
    type: Resize
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 900
    - 900
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.1
    contrast_range: 0.1
    saturation_range: 0.1
    type: RandomDistort
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: /home/amourato/VM/New_COCO_DPD/test/
  mode: val
  num_classes: 2
  transforms:
  - target_size:
    - 1024
    - 1024
    type: Resize
  - type: Normalize
  type: Dataset
  val_path: /home/amourato/VM/New_COCO_DPD/test/test.txt
------------------------------------------------
W0824 16:30:35.857435 834345 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.4, Runtime API Version: 10.2
W0824 16:30:35.857457 834345 device_context.cc:422] device: 0, cuDNN Version: 7.6.
W0824 16:30:38.437281 834345 dynamic_loader.cc:238] You may need to install 'nccl2' from NVIDIA official website: https://developer.nvidia.com/nccl/nccl-downloadbefore install PaddlePaddle.
Traceback (most recent call last):
  File "train.py", line 190, in <module>
    main(args)
  File "train.py", line 169, in main
    train(
  File "/home/amourato/VM/paddle/PaddleSeg/paddleseg/core/train.py", line 106, in train
    paddle.distributed.fleet.init(is_collective=True)
  File "/home/amourato/anaconda3/envs/segm/lib/python3.8/site-packages/paddle/distributed/fleet/base/fleet_base.py", line 247, in init
    paddle.distributed.init_parallel_env()
  File "/home/amourato/anaconda3/envs/segm/lib/python3.8/site-packages/paddle/distributed/parallel.py", line 196, in init_parallel_env
    parallel_helper._init_parallel_ctx()
  File "/home/amourato/anaconda3/envs/segm/lib/python3.8/site-packages/paddle/fluid/dygraph/parallel_helper.py", line 42, in _init_parallel_ctx
    __parallel_ctx__clz__.init()
RuntimeError: (PreconditionNotMet) The third-party dynamic library (libnccl.so) that Paddle depends on is not configured correctly. (error code is libnccl.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at /paddle/paddle/fluid/platform/dynload/dynamic_loader.cc:265)

INFO 2021-08-24 16:30:43,286 launch_utils.py:327] terminate all the procs
ERROR 2021-08-24 16:30:43,286 launch_utils.py:582] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-08-24 16:30:46,289 launch_utils.py:327] terminate all the procs
```
I've nccl installed, it runs properly in detectron2 and in openmmlab, but not here.
I've tried to add the library to the path variable but without success so far.
```
export LD_LIBRARY_PATH=/home/amourato/anaconda3/envs/segm/lib/libnccl.so.2.10.3:$LD_LIBRARY_PATH
```
Any solution?

**Comment by qili93** [comment]
@AKMourato Please try the following alternatives:

1. set `FLAGS_nccl_dir` in your environment and softlink `libnccl.so.2.10.3` to `librccl.so`, then run your training script again

```bash
export FLAGS_nccl_dir="/home/amourato/anaconda3/envs/segm/lib/"
cd /home/amourato/anaconda3/envs/segm/lib/
ln -s libnccl.so.2.10.3 libnccl.so
```

2. use official paddle docker image of CUDA 10.2
doc here: https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/en/install/docker/linux-docker.html

```bash
nvidia-docker pull registry.baidubce.com/paddlepaddle/paddle:2.1.2-gpu-cuda10.2-cudnn7
nvidia-docker run --name paddle -it -v $PWD:/paddle registry.baidubce.com/paddlepaddle/paddle:2.1.2-gpu-cuda10.2-cudnn7 /bin/bash
```
