### ISSUE TITLE
学习率读取错误

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/PaddleSeg#1302]
**问题：**
在使用OCRNet.yml，配置学习率调度器如下：
lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  power: 0.9

**报错：**
Traceback (most recent call last):
  File "/home/aistudio/PaddleSeg/train.py", line 168, in <module>
    main(args)
  File "/home/aistudio/PaddleSeg/train.py", line 153, in main
    optimizer=cfg.optimizer,
  File "/home/aistudio/PaddleSeg/paddleseg/cvlibs/config.py", line 186, in optimizer
    lr = self.lr_scheduler
  File "/home/aistudio/PaddleSeg/paddleseg/cvlibs/config.py", line 157, in lr_scheduler
    return getattr(paddle.optimizer.lr, lr_type)(**params)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/lr.py", line 647, in __init__
    verbose)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/lr.py", line 99, in __init__
    self.step()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/lr.py", line 122, in step
    self.last_lr = self.get_lr()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/lr.py", line 662, in get_lr
    return (self.base_lr - self.end_lr) * (
TypeError: unsupported operand type(s) for -: 'float' and 'str'

**可能的原因：**
end_lr被解析为str类型
{'learning_rate': 0.03, 'end_lr': '1e-8', 'power': 0.9, 'decay_steps': 10000}
![7YGL(%XZPU2_8G%F}C{SQRA](https://user-images.githubusercontent.com/36887207/131234440-885d4d81-cd59-4fdb-8b57-6a853a44dbec.png)

**解决方法：**
在代码PaddleSeg/paddleseg/cvlibs/config.py 第152行之后加入1行代码才可运行：
params['end_lr'] = float(params['end_lr'])

![L51RRGU6PT$~KCQNN3D3HYA](https://user-images.githubusercontent.com/36887207/131234494-027eaf44-5cd1-46df-b3ac-21ef77399fa0.png)

**注：**
paddleseg2.2
ocrnet之前一直可以直接运行，直到昨天运行脚本任务，重新clone paddleseg才报错

**Comment by juncaipeng** [comment]
请说一下2.2版本的commit id，我用最新的没有复现该问题。
