### ISSUE TITLE
刚开始训练就遇到这个问题，一直解决不了，求助

### ISSUE THREAD

**Issue by pussss** [PaddlePaddle/PaddleSeg#1320]
WARNING:root:DataLoader reader thread raised an exception.
Traceback (most recent call last):
  File "/home/aistudio/PaddleSeg/train.py", line 190, in <module>
    main(args)
  File "/home/aistudio/PaddleSeg/train.py", line 185, in main
    fp16=args.fp16)
  File "/home/aistudio/PaddleSeg/paddleseg/core/train.py", line 143, in train
    for data in loader:
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 197, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

**Comment by juncaipeng** [comment]
数据配置部分错误，可以调试输出dataloader部分。

**Comment by pussss** [comment]
> 数据配置部分错误，可以调试输出数据加载器部分。
我没听懂···小白一个，可以说详细点吗？

**Comment by juncaipeng** [comment]
建议先学习一下
paddle教程：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/index_cn.html
paddleseg教程：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/README_CN.md

**Comment by hhxdestiny** [comment]
#921
