### ISSUE TITLE
dataloader error when eval my model

### ISSUE THREAD

**Issue by PearlDzzz** [PaddlePaddle/PaddleSeg#1342]
Hi，
I use your provieded code on /contrib/PP-HumanSeg/train.py , use mini supervisely data.
But when I eval the trained model on EG1800 test, it raise an error:

2021-09-13 14:28:59 [INFO]      Loading pretrained model from pretrained_model/fcn_hrnetw18_small_v1_humanseg_192x192/model.pdparams
2021-09-13 14:28:59 [INFO]      There are 363/363 variables loaded into FCN.
2021-09-13 14:28:59 [INFO]      Loading pretrained model from saved_model/0910_fcn_hrnetw18_small_v1_humanseg_192x192_mini_supervisely/best_model/model.pdparams
2021-09-13 14:28:59 [INFO]      There are 363/363 variables loaded into FCN.
2021-09-13 14:28:59 [INFO]      Loaded trained params of model successfully
2021-09-13 14:28:59 [INFO]      Start evaluating (total_samples: 289, total_iters: 289)...
2021-09-13 14:28:59,893 - WARNING - DataLoader reader thread raised an exception.
Traceback (most recent call last):
  File "val.py", line 144, in <module>
    main(args)
  File "val.py", line 138, in main
    num_workers=args.num_workers,
  File "/home/yayun.ren/.conda/envs/ryyenv/lib/python3.6/site-packages/paddleseg/core/val.py", line 92, in evaluate
    for iter, (im, label) in enumerate(loader):
  File "/home/yayun.ren/.conda/envs/ryyenv/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 351, in __next__
    return self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

**Comment by juncaipeng** [comment]
Please refer to the [Preparation of Annotation Data](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/docs/data/marker/marker.md) and check whether the config is correctly set.

**Comment by ChristineRYY** [comment]
> Please refer to the [Preparation of Annotation Data](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/docs/data/marker/marker.md) and check whether the config is correctly set.

**Comment by PearlDzzz** [comment]
I use "python tools/gray2pseudo_color.py" to process my data, the annotation is good, but the training still doesn't work.
[Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)


Do I need to make "python tools/gray2pseudo_color.py" for my train dataset, and then use pseudo annotaions for train?
Or, is there any other possible problem may cuase training error？

**Comment by juncaipeng** [comment]
The error is not caused by "python tools/gray2pseudo_color.py".  You should check the dataset and dataloader, please refer to https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/docs/data/marker/marker.md
