### ISSUE TITLE
ModuleNotFoundError: No module named 'PySide'

### ISSUE THREAD

**Issue by LiangYong1216** [PaddlePaddle/PaddleSeg#1357]
(e1) C:\Users\86180\PaddleSeg\contrib\EISeg>python -m eiseg
Traceback (most recent call last):
  File "C:\Users\86180\.conda\envs\e1\lib\site-packages\qtpy\__init__.py", line 210, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\86180\.conda\envs\e1\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\86180\.conda\envs\e1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\86180\PaddleSeg\contrib\EISeg\eiseg\__main__.py", line 1, in <module>
    from run import main
  File "C:\Users\86180\PaddleSeg\contrib\EISeg\eiseg\run.py", line 4, in <module>
    from qtpy.QtWidgets import QApplication  # 导入PyQt相关模块
  File "C:\Users\86180\.conda\envs\e1\lib\site-packages\qtpy\__init__.py", line 216, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

**Comment by haoyuying** [comment]
如果直接用paddleseg下的代码进行使用的话，请先安装eiseg的依赖，在requirements.txt中https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.2/contrib/EISeg/requirements.txt
