### ISSUE TITLE
Model evaluation: AttributeError: 'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by AKMourato** [PaddlePaddle/PaddleSeg#1398]
Hello guys,

For model evaluation (develop branch) I'm getting the following error in the config file:
```
python val.py --config eval_unet.yml --model_path output/unet-newsetup/best_model/model.pdparams
```

```
Traceback (most recent call last):
  File "val.py", line 171, in <module>
    main(args)
  File "val.py", line 158, in main
    model = cfg.model
  File "/home/amourato/VM/paddle/PaddleSeg/paddleseg/cvlibs/config.py", line 284, in model
    model_cfg = self.dic.get('model').copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```
Any solution?

**Comment by juncaipeng** [comment]
Please check whether there are model information in eval_unet.yml, such as 
```
model:
  type: UNet
  num_classes: 19
  use_deconv: False
  pretrained: Null
```

**Comment by AKMourato** [comment]
I was running the _base_ file instead. Thanks @juncaipeng.
Btw, will you guys implement the standard segmentation metrics soon? (precision, recall, f1-score, dice coef)
