### ISSUE TITLE
eiseg COCO 格式用于 paddlex、PaddleDetection 训练报错

### ISSUE THREAD

**Issue by chenglong-do** [PaddlePaddle/PaddleSeg#1461]
**bug描述**
使用 EISEG 标注后保存为 COCO 格式，用于paddlex、PaddleDetection 训练时会报错，请问是需要特别转换么？

```
[10/23 17:12:10] ppdet.data.source.coco WARNING: Found an invalid bbox in annotations: im_id: 346, area: 0.0 x1: 664.0, y1: 690.0, x2: 853.0, y2: 908.0.
Traceback (most recent call last):
  File "tools/train.py", line 138, in <module>
    main()
  File "tools/train.py", line 134, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 100, in run
    trainer = Trainer(cfg, mode='train')
  File "/opt/deeplearning/PaddleDetection/ppdet/engine/trainer.py", line 74, in __init__
    self.loader = create('{}Reader'.format(self.mode.capitalize()))(
  File "/opt/deeplearning/PaddleDetection/ppdet/data/reader.py", line 163, in __call__
    self.dataset.parse_dataset()
  File "/opt/deeplearning/PaddleDetection/ppdet/data/source/coco.py", line 243, in parse_dataset
    assert ct > 0, 'not found any coco record in %s' % (anno_path)
AssertionError: not found any coco record in dataset/splotch_coco/train.json
```

**运行环境（请尽量填写，这可以帮助我们定位问题）：**
 - 系统： Linux
 - 安装方式：pip
 - 软件版本：0.3.0.2

**Comment by haoyuying** [comment]
可以参考https://github.com/PaddlePaddle/PaddleSeg/issues/1437
