### ISSUE TITLE
2.3版本训练时报错

### ISSUE THREAD

**Issue by Darki-luo** [PaddlePaddle/PaddleSeg#1505]
套件版本 paddleseg2.3
2021-11-05 17:21:58 [INFO]      [TRAIN] epoch: 1, iter: 10/60000, loss: 2.8347, lr: 0.009993, batch_cost: 0.8433, reader_cost: 0.03551, ips: 4.7432 samples/sec | ETA 14:03:10
2021-11-05 17:22:05 [INFO]      [TRAIN] epoch: 1, iter: 20/60000, loss: 1.2982, lr: 0.009985, batch_cost: 0.7687, reader_cost: 0.00004, ips: 5.2034 samples/sec | ETA 12:48:28
2021-11-05 17:22:05 [INFO]      Start evaluating (total_samples: 3807, total_iters: 3807)...
Traceback (most recent call last):
  File "train.py", line 198, in <module>
    main(args)
  File "train.py", line 176, in main
    train(
  File "/home/w/python/laaneseg/paddleseg/core/train.py", line 264, in train
    mean_iou, acc, _, _, _ = evaluate(
  File "/home/w/python/laaneseg/paddleseg/core/val.py", line 112, in evaluate
    pred = infer.inference(
  File "/home/w/python/laaneseg/paddleseg/core/infer.py", line 232, in inference
    logits = model(im)
  File "/home/w/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/w/python/laaneseg/paddleseg/models/deeplab.py", line 83, in forward
    feat_list = self.backbone(x)
  File "/home/w/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/w/python/laaneseg/paddleseg/models/backbones/litehrnet.py", line 1103, in forward
    st3 = self.st3(tr2)
  File "/home/w/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/w/python/laaneseg/paddleseg/models/backbones/litehrnet.py", line 991, in forward
    out = self.stage_func_list[idx](out)
  File "/home/w/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/w/python/laaneseg/paddleseg/models/backbones/litehrnet.py", line 950, in forward
    out = self.fuse_func(out)
  File "/home/w/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/w/python/laaneseg/paddleseg/models/backbones/litehrnet.py", line 910, in forward
    y += self.fuse_layers[i][j](x[j])
  File "/home/w/miniconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 250, in __impl__
    return math_op(self, other_var, 'axis', axis)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 40, 270, 480] and the shape of Y = [1, 40, 272, 480]. Received [270] in X is not equal to [272] in Y at i:2.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:169)
  [operator < elementwise_add > error]

**Comment by juncaipeng** [comment]
你好，看你的log是下面这行中y和 self.fuse_layers[i]j的维度不匹配，并不是seg的错误，再检查一下组网代码吧。
`
File "/home/w/python/laaneseg/paddleseg/models/backbones/litehrnet.py", line 910, in forward
y += self.fuse_layers[i]j
`
