### ISSUE TITLE
there‘s 2 ops are not supported yet

### ISSUE THREAD

**Issue by wang971124** [PaddlePaddle/PaddleSeg#1556]
将paddleseg中的sfnetresnet50模型导出之后，将其转化为onnx时报错，提示缺少两个算子：there‘s 2 ops are not supported yet。希望官方尽快可以帮忙修复

**Comment by shiyutang** [comment]
Please elaborate your description and show the name of unsupported ops.

**Comment by wang971124** [comment]
/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/onnx/mapping.py:27: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  int(TensorProto.STRING): np.dtype(np.object)
/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/constant/dtypes.py:45: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool: core.VarDesc.VarType.BOOL,
/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/constant/dtypes.py:46: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.FP32: np.float,
/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/constant/dtypes.py:51: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.BOOL: np.bool
2021-11-18 15:55:09 [WARNING]	You are use develop version of paddlepaddle
Traceback (most recent call last):
  File "/home/imagex/anaconda3/envs/wang/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/command.py", line 148, in main
    program2onnx(
  File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/command.py", line 114, in program2onnx
    p2o.program2onnx(
  File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/convert.py", line 79, in program2onnx
    export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker, operator_export_type)
  File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/convert.py", line 33, in export_onnx
    onnx_graph = ONNXGraph.build(paddle_graph, opset_version, operator_export_type, verbose)
  File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/graph/onnx_graph.py", line 240, in build
    onnx_graph = ONNXGraph(paddle_graph, opset_version=opset_version, operator_export_type=operator_export_type)
  File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/graph/onnx_graph.py", line 79, in __init__
    self.update_opset_version()
  File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/graph/onnx_graph.py", line 194, in update_opset_version
    self.opset_version = OpMapper.get_recommend_opset_version(node_map, self.opset_version)
  File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 127, in get_recommend_opset_version
    recommend_opset_version = OpMapper.check_support_status(node_map, opset_version, True)
  File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 168, in check_support_status
    raise NotImplementedError(error_info)
NotImplementedError: 
There's 2 ops are not supported yet

**Comment by wang971124** [comment]
使用的模型时sfnet_res50,模型参数时在官网下载的

**Comment by jiangjiajun** [comment]
Hi, @wang971124

It seems the problem is caused by [Paddle2ONNX](https://github.com/PaddlePaddle/Paddle2ONNX.git), although you didn't put enough error message here, the name of unsupported operator is key information.

Could you seed a same issue to Paddle2ONNX, and it is recommend that you upload your PaddlePaddle model for Paddle2ONNX to debug quickly.
