### ISSUE TITLE
CityscapesSOTA conversion issue

### ISSUE THREAD

**Issue by 95maddycode** [PaddlePaddle/PaddleSeg#1574]
Hi,

After preparing the cityscapes data following your scripts, and having the right folder structure, I came across this error:

ValueError: The number of images = 19998 is not equal to the number of labels = 19999 in Cityscapes Autolabeling dataset.

After some investigation, I saw that the convert_autolabelled folder has a folder named "tmp" with only one image in it (wurzburg_000000_001584_leftImg8bit.png). This is a duplicate, because the "original" one can also be found in cnvert_autolabelled/wurzburg. After the deletetion of this folder, the error disappeared. 

1. Is there a purpose of the folder "tmp"? Why does it cause this error?

After the removal, I run the script again. However, now I get the following error:

  File "train.py", line 159, in <module>
    main(args)
  File "train.py", line 132, in main
    train(
  File "/data/repos/CityscapesSOTA/scripts/train.py", line 149, in train
    logits_list = model(images)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/data/repos/CityscapesSOTA/models/mscale_ocrnet.py", line 42, in forward
    return self.two_scale_forward(x)
  File "/data/repos/CityscapesSOTA/models/mscale_ocrnet.py", line 74, in two_scale_forward
    p_lo = scale_as(p_lo, p_1x)
  File "/data/repos/CityscapesSOTA/models/mscale_ocrnet.py", line 198, in scale_as
    x_scaled = nn.functional.interpolate(
  File "/usr/local/lib/python3.8/dist-packages/paddle/nn/functional/common.py", line 361, in interpolate
    out_shape[i] = dim.numpy()[0]
TypeError: 'tuple' object does not support item assignment

2.) What is going on here? It seems like there is something going wrong with training or the input of the model. I have not changed anything in the scripts, I just ran it according to your CityscapseSOTA documentation.

Thanks in advance for answering my questions.

**Comment by jbh1998** [comment]
same to you. have you solved this issue?

**Comment by LutaoChu** [comment]
@95maddycode @jbh1998 hi，
1. The TMP directory comes with the original author's dataset and needs to be removed manually. I don't find any use. I think the author forgot to delete it when publishing. The reason for this error is that we will check whether the number of labels is consistent with the number of images, to ensure that the training pictures and labels can correspond one by one
2. Let me check. What are your paddle version and paddleseg version

**Comment by jbh1998** [comment]
paddle=2.2
paddleseg=2.3

**Comment by jbh1998** [comment]
@LutaoChu looking forward to your help, thanks

**Comment by LutaoChu** [comment]
PR has been submitted, waiting for merge. You can modify it according to PR first
https://github.com/PaddlePaddle/PaddleSeg/pull/1595

**Comment by jbh1998** [comment]
Traceback (most recent call last):
  File "train.py", line 151, in <module>
    main(args)
  File "train.py", line 131, in main
    cfg.model,
  File "/home/work/anaconda3/envs/jbh/lib/python3.6/site-packages/paddleseg/cvlibs/config.py", line 288, in model
    self._model = self._load_object(model_cfg)
  File "/home/work/anaconda3/envs/jbh/lib/python3.6/site-packages/paddleseg/cvlibs/config.py", line 341, in _load_object
    component = self._load_component(cfg.pop('type'))
  File "/home/work/anaconda3/envs/jbh/lib/python3.6/site-packages/paddleseg/cvlibs/config.py", line 334, in _load_component
    'The specified component was not found {}.'.format(com_name))
RuntimeError: The specified component was not found SegFormer_B5.





hello, I want to use segformer_B5 in CityscapesSOTA(paddleseg=2.2 doesn't contain this model), it came with this error. but when I use paddleseg 2.3, it also threw errors. Is there any solutions ? thanks !
@LutaoChu

**Comment by LutaoChu** [comment]
Check that you have run the following code
```
pip install paddleseg
```
If it still doesn't work, try to import SegFormer_B5 class in the train.py
