### ISSUE TITLE
lebelme转换真值文件时出错？

### ISSUE THREAD

**Issue by doubridge** [PaddlePaddle/PaddleSeg#164]
Traceback (most recent call last):
  File ".\pdseg\tools\labelme2seg.py", line 94, in <module>
    main(args)
  File ".\pdseg\tools\labelme2seg.py", line 81, in main
    if lbl.min() >= 0 and lbl.max() <= 255:
AttributeError: 'tuple' object has no attribute 'min'

**Comment by doubridge** [comment]
labelme的版本不对，已经解决。
