### ISSUE TITLE
【论文复现】动态图模式下训练结束后计算flops错误 

### ISSUE THREAD

**Issue by ETTR123** [PaddlePaddle/PaddleSeg#1646]
1）PaddlePaddle版本：2.2.1
      [PR地址：https://github.com/PaddlePaddle/PaddleSeg/pull/1623](https://github.com/PaddlePaddle/PaddleSeg/pull/1623)

训练命令：

`python PaddleSeg/train.py --config PaddleSeg/configs/enet/enet_cityscapes_1024x512_adam_0.002_80k.yml`

     W1218 13:14:42.893093   301 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W1218 13:14:42.893141   301 device_context.cc:465] device: 0, cuDNN Version: 7.6.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/norm.py:653: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:253: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.int64, the right dtype will convert to paddle.float32
  format(lhs_dtype, rhs_dtype, lhs_dtype))
2021-12-18 13:14:58 [INFO]	[TRAIN] epoch: 1, iter: 10/10, loss: 2.2953, lr: 0.001259, batch_cost: 1.1241, reader_cost: 0.85701, ips: 7.1169 samples/sec | ETA 00:00:00
<class 'paddle.nn.layer.conv.Conv2D'>'s flops has been counted
Cannot find suitable count function for <class 'paddle.nn.layer.pooling.MaxPool2D'>. Treat it as zero FLOPs.
<class 'paddle.nn.layer.norm.BatchNorm2D'>'s flops has been counted
Cannot find suitable count function for <class 'paddle.nn.layer.activation.PReLU'>. Treat it as zero FLOPs.
Cannot find suitable count function for <class 'paddle.nn.layer.common.Dropout2D'>. Treat it as zero FLOPs.
<class 'paddle.nn.layer.activation.ReLU'>'s flops has been counted
<class 'paddle.nn.layer.conv.Conv2DTranspose'>'s flops has been counted
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Traceback (most recent call last):
  File "PaddleSeg/train.py", line 199, in <module>
    main(args)
  File "PaddleSeg/train.py", line 194, in main
    to_static_training=cfg.to_static_training)
  File "/home/aistudio/PaddleSeg/paddleseg/core/train.py", line 311, in train
    custom_ops={paddle.nn.SyncBatchNorm: op_flops_funs.count_syncbn})
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/dynamic_flops.py", line 113, in flops
    print_detail=print_detail)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/dynamic_flops.py", line 254, in dynamic_flops
    model(inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleSeg/paddleseg/models/enet.py", line 199, in forward
    x, max_indices1_0 = self.downsample1_0(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleSeg/paddleseg/models/enet.py", line 504, in forward
    main, max_indices = self.main_max1(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    hook_result = forward_post_hook(self, inputs, outputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/dynamic_flops.py", line 184, in count_io_info
    m.register_buffer('output_shape', paddle.to_tensor(y.shape))
AttributeError: 'tuple' object has no attribute 'shape'

PS:
1:self.main_max1 = paddle.nn.MaxPool2D(2, stride=2, return_mask=return_indices)
2:将File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/dynamic_flops.py", line 184, in count_io_info：
    m.register_buffer('output_shape', paddle.to_tensor(y.shape))
 改为
    m.register_buffer('output_shape', paddle.to_tensor(y[0].shape))后，错误消除。

**Comment by shiyutang** [comment]
This should be a problem in paddle.flops. We will look at it asap.

**Comment by shiyutang** [comment]
This issue has been solved here. https://github.com/PaddlePaddle/Paddle/pull/38850

**Comment by kjdhbcs** [comment]
您好请问在aistudio中怎么修改"/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/hapi/dynamic_flops.py"文件的内容呀？
