### ISSUE TITLE
在paddle cloud上使用PaddleSeg-release-2.2中的模型训练时出现ModuleNotFoundError类型的错误

### ISSUE THREAD

**Issue by xinliyangguang** [PaddlePaddle/PaddleSeg#1652]
我在paddle cloud中使用集群训练PaddleSeg-releasev2.0的模型，数据放在了afs集群上，代码放在了开发机上，提交作业之后报错如下：

/root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-v2.0/paddleseg/cvlibs/param_init.py:89: DeprecationWarning: invalid escape sequence \s
"""
Traceback (most recent call last):
File "zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-v2.0/train.py", line 21, in
from paddleseg.cvlibs import manager, Config
File "/root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-v2.0/paddleseg/init.py", line 15, in
from . import models, datasets, transforms
File "/root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-v2.0/paddleseg/models/init.py", line 15, in
from .backbones import *
File "/root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-v2.0/paddleseg/models/backbones/init.py", line 16, in
from .resnet_vd import *
File "/root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-v2.0/paddleseg/models/backbones/resnet_vd.py", line 21, in
from paddleseg.utils import utils
File "/root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-v2.0/paddleseg/utils/init.py", line 18, in
from .env import seg_env, get_sys_env
ModuleNotFoundError: No module named 'paddleseg.utils.env'

**Comment by shiyutang** [comment]
please update paddleseg to 2.3

**Comment by xinliyangguang** [comment]
> please update paddleseg to 2.3

仍然出现此类错误，错误信息相同：
Traceback (most recent call last):
  File "zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-2.3/train.py", line 21, in <module>
    from paddleseg.cvlibs import manager, Config
  File "/root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-2.3/paddleseg/__init__.py", line 15, in <module>
    from . import models, datasets, transforms
  File "/root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-2.3/paddleseg/models/__init__.py", line 15, in <module>
    from .backbones import *
  File "/root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-2.3/paddleseg/models/backbones/__init__.py", line 15, in <module>
    from .hrnet import *
  File "/root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-2.3/paddleseg/models/backbones/hrnet.py", line 21, in <module>
    from paddleseg.cvlibs import manager, param_init
  File "/root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-2.3/paddleseg/cvlibs/__init__.py", line 17, in <module>
    from .config import Config
  File "/root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-2.3/paddleseg/cvlibs/config.py", line 23, in <module>
    from paddleseg.utils import logger
  File "/root/paddlejob/workspace/env_run/zhaoxin34/baidu/personal-code/icoding/PaddleSeg-release-2.3/paddleseg/utils/__init__.py", line 18, in <module>
    from .env import seg_env, get_sys_env
ModuleNotFoundError: No module named 'paddleseg.utils.env'

**Comment by shiyutang** [comment]
please provide a link to the code that can reproduce the error, and how to reproduce it. since we do not see this happen.

**Comment by shiyutang** [comment]
This issue has no response for a long time. I will close it now. If you have further questions, please reopen it.

**Comment by haozizhuimao** [comment]
这个问题解决了吗，我在ubuntu 22.04 系统上安装环境，运行测试代码时会报了相同bug
