### ISSUE TITLE
多卡训练出错

### ISSUE THREAD

**Issue by Huihuihh** [PaddlePaddle/PaddleSeg#1694]
利用多卡训练报错
```
(base) [root@ai-dev-node1 PaddleSeg]# python -m paddle.distributed.launch train.py --config mydeeplabv3p.yml --do_eval --use_vdl --save_interval 500 --save_dir output --resume_model output/iter_34500/
-----------  Configuration Arguments -----------
gpus: None
heter_worker_num: None
heter_workers:
http_port: None
ips: 127.0.0.1
log_dir: log
nproc_per_node: None
run_mode: None
server_num: None
servers:
training_script: train.py
training_script_args: ['--config', 'mydeeplabv3p.yml', '--do_eval', '--use_vdl', '--save_interval', '500', '--save_dir', 'output', '--resume_model', 'output/iter_34500/']
worker_num: None
workers:
------------------------------------------------
WARNING 2022-01-06 20:45:07,766 launch.py:357] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
launch train in GPU mode!
INFO 2022-01-06 20:45:07,769 launch_utils.py:510] Local start 2 processes. First process distributed environment info (Only For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:55501               |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:55501,127.0.0.1:45135       |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                       0,1                     |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2022-01-06 20:45:07,769 launch_utils.py:514] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
launch proc_id:11192 idx:0
launch proc_id:11253 idx:1
/root/miniconda3/lib/python3.7/site-packages/scipy/linalg/__init__.py:212: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
  from numpy.dual import register_func
/root/miniconda3/lib/python3.7/site-packages/scipy/special/orthogonal.py:81: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,
/root/miniconda3/lib/python3.7/site-packages/scipy/sparse/sputils.py:16: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
  supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
2022-01-06 20:45:09 [INFO]
------------Environment Information-------------
platform: Linux-4.18.7-1.el7.elrepo.x86_64-x86_64-with-centos-7.5.1804-Core
Python: 3.7.6 (default, Jan  8 2020, 19:59:22) [GCC 7.3.0]
Paddle compiled with cuda: True
NVCC: Cuda compilation tools, release 10.0, V10.0.130
cudnn: 7.6
GPUs used: 2
CUDA_VISIBLE_DEVICES: 0,1
GPU: ['GPU 0: GeForce GTX', 'GPU 1: GeForce GTX']
GCC: gcc (GCC) 4.9.2
PaddlePaddle: 2.1.0
OpenCV: 3.4.5
------------------------------------------------
2022-01-06 20:45:09 [INFO]
---------------Config Information---------------
batch_size: 4
iters: 1000000
loss:
  coef:
  - 1
  types:
  - ignore_index: 255
    type: CrossEntropyLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 0.01
  power: 0.9
  type: PolynomialDecay
model:
  align_corners: false
  aspp_out_channels: 256
  aspp_ratios:
  - 1
  - 12
  - 24
  - 36
  backbone:
    multi_grid:
    - 1
    - 2
    - 4
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
    type: ResNet50_vd
  backbone_indices:
  - 0
  - 3
  pretrained: null
  type: DeepLabV3P
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 4.0e-05
test_dataset:
  dataset_root: /root/th/PaddleSeg/fenge-all/
  mode: test
  num_classes: 5
  test_path: /root/th/PaddleSeg/fenge-all/test.txt
  transforms:
  - type: Normalize
  type: Dataset
train_dataset:
  dataset_root: /root/th/PaddleSeg/fenge-all/
  mode: train
  num_classes: 5
  train_path: /root/th/PaddleSeg/fenge-all/train.txt
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 512
    - 512
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
    type: RandomDistort
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: /root/th/PaddleSeg/fenge-all/
  mode: val
  num_classes: 5
  transforms:
  - type: Normalize
  type: Dataset
  val_path: /root/th/PaddleSeg/fenge-all/val.txt
------------------------------------------------
W0106 20:45:09.797680 11192 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.0, Runtime API Version: 10.2
W0106 20:45:09.797749 11192 device_context.cc:422] device: 0, cuDNN Version: 7.6.
2022-01-06 20:45:12 [INFO]      Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
2022-01-06 20:45:14 [INFO]      There are 275/275 variables loaded into ResNet_vd.
2022-01-06 20:45:14 [INFO]      Resume model from output/iter_34500/
Traceback (most recent call last):
  File "train.py", line 198, in <module>
    main(args)
  File "train.py", line 193, in main
    profiler_options=args.profiler_options)
  File "/root/th/Paddle/PaddleSeg/paddleseg/core/train.py", line 101, in train
    start_iter = resume(model, optimizer, resume_model)
  File "/root/th/Paddle/PaddleSeg/paddleseg/utils/utils.py", line 111, in resume
    optimizer.set_state_dict(opti_state_dict)
  File "<decorator-gen-188>", line 2, in set_state_dict
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 240, in set_state_dict
    "optimizer Tensor {} not found".format( var_tmp.name )
AssertionError: optimizer Tensor sync_batch_norm_0.w_0_velocity_0 not found
INFO 2022-01-06 20:45:22,814 launch_utils.py:327] terminate all the procs
ERROR 2022-01-06 20:45:22,815 launch_utils.py:584] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
INFO 2022-01-06 20:45:25,817 launch_utils.py:327] terminate all the procs
```

**Comment by Huihuihh** [comment]
resume恢复训练，不支持多卡训练？

**Comment by Huihuihh** [comment]
没有--resume_model参数，能够成功使用多卡训练

**Comment by wuyefeilin** [comment]
确保训练的模型和resume的model时一致的

**Comment by LutaoChu** [comment]
检查一下 resume_model指定的目录下是否有.pdopt文件

**Comment by wuyefeilin** [comment]
output/iter_34500/模型的训练命令时什么，是单卡训练的吗？

**Comment by Huihuihh** [comment]
> 检查一下 resume_model指定的目录下是否有.opt文件

有.opt文件
```
model.pdopt
model.pdparams
```

**Comment by Huihuihh** [comment]
> output/iter_34500/模型的训练命令时什么，是单卡训练的吗？

对，训练的时候是单卡训练的。
```
python train.py --config mydeeplabv3p.yml --do_eval --use_vdl --save_interval 500 --save_dir output
```

**Comment by LutaoChu** [comment]
单卡训练使用的是batch_norm op，多卡训练需要用sync_batch_norm，所以报错了。原先是怎样训练，resume需要相同的训练方式

**Comment by Huihuihh** [comment]
> 单卡训练使用的是batch_norm op，多卡训练需要用sync_batch_norm，所以报错了。原先是怎样训练，resume需要相同的训练方式

所以是多卡训练的模型，恢复训练得用多卡恢复训练；单卡训练的模型，得用单卡的恢复训练？

**Comment by LutaoChu** [comment]
you are right
