### ISSUE TITLE
Paddle 多卡训练

### ISSUE THREAD

**Issue by zhijiejia** [PaddlePaddle/PaddleSeg#1713]
Paddle多卡训练出现这个错误？？？

![image](https://user-images.githubusercontent.com/43838913/149124704-1d1209cc-ad52-4aa2-8391-43a27b642f12.png)

**Comment by shiyutang** [comment]
please go to worklog.0 to see the exact error information.

**Comment by zhijiejia** [comment]
```
[INFO]	There are 1573/2027 variables loaded into OCRNet.
train has image: 43078
train has image: 43078
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:57487']
I0112 18:33:17.212489 10443 nccl_context.cc:74] init nccl context nranks: 2 local rank: 0 gpu id: 0 ring id: 0
I0112 18:33:17.343999 10443 nccl_context.cc:107] init nccl context nranks: 2 local rank: 0 gpu id: 0 ring id: 10
Traceback (most recent call last):
  File "/home/jzj/paddleseg_remote_segementation/train.py", line 199, in <module>
    main(args)
  File "/home/jzj/paddleseg_remote_segementation/train.py", line 177, in main
    train(
  File "/home/jzj/paddleseg_remote_segementation/paddleseg/core/train.py", line 109, in train
    paddle.distributed.fleet.init(is_collective=True)
  File "/home/jzj/miniconda3/lib/python3.9/site-packages/paddle/distributed/fleet/base/fleet_base.py", line 282, in init
    self._init_hybrid_parallel_env()
  File "/home/jzj/miniconda3/lib/python3.9/site-packages/paddle/distributed/fleet/base/fleet_base.py", line 367, in _init_hybrid_parallel_env
    self._hcg = tp.HybridCommunicateGroup(self._topology)
  File "/home/jzj/miniconda3/lib/python3.9/site-packages/paddle/distributed/fleet/base/topology.py", line 139, in __init__
    self._dp_group, self._dp_comm_group = self._set_comm_group("data")
  File "/home/jzj/miniconda3/lib/python3.9/site-packages/paddle/distributed/fleet/base/topology.py", line 199, in _set_comm_group
    comm_group = paddle.distributed.new_group(ranks=group)
  File "/home/jzj/miniconda3/lib/python3.9/site-packages/paddle/distributed/collective.py", line 277, in new_group
    paddle.distributed.all_reduce(tmp, use_calc_stream=True)
  File "/home/jzj/miniconda3/lib/python3.9/site-packages/paddle/distributed/collective.py", line 456, in all_reduce
    return _C_ops.c_allreduce_sum_(tensor, 'use_calc_stream',
OSError: (External) NCCL error(1), unhandled cuda error. 
  [Hint: 'ncclUnhandledCudaError'. A call to a CUDA function failed.] (at /paddle/paddle/fluid/operators/collective/c_allreduce_op.h:390)
  [operator < c_allreduce_sum > error]

```

**Comment by shiyutang** [comment]
It seems to be a hardware problem as mentioned [here](https://github.com/pytorch/pytorch/issues/11756#issuecomment-423599445), you can try to open a new environment to install Cuda and cudnn or change you device.

**Comment by shiyutang** [comment]
If you have any further questions, you are very welcome to reopen it.
