### ISSUE TITLE
[Bug]eiseg运行错误 name 'osr' is not defined

### ISSUE THREAD

**Issue by x12901** [PaddlePaddle/PaddleSeg#1738]
1. PaddleSeg版本：PaddleSeg release/2.4
 2. PaddlePaddle版本：PaddlePaddle 2.2 cpu
 3. 操作系统信息：Windows
 4. Python版本号：Python3.8
 5. 运行指令或复现步骤：
 运行`pip install eiseg`之后出现
```
(PP) D:\CODE\PaddleSeg-release-2.4\EISeg\eiseg>eiseg
Traceback (most recent call last):
  File "E:\Anaconda\envs\PP\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "E:\Anaconda\envs\PP\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "E:\Anaconda\envs\PP\Scripts\eiseg.exe\__main__.py", line 4, in <module>
    # you may not use this file except in compliance with the License.
  File "E:\Anaconda\envs\PP\lib\site-packages\eiseg\run.py", line 26, in <module>
    from app import APP_EISeg  # 导入带槽的界面
  File "D:\CODE\PaddleSeg-release-2.4\EISeg\eiseg\app.py", line 50, in <module>
    import plugin.remotesensing as rs
  File "D:\CODE\PaddleSeg-release-2.4\EISeg\eiseg\plugin\remotesensing\__init__.py", line 16, in <module>
    from .shape import *
  File "D:\CODE\PaddleSeg-release-2.4\EISeg\eiseg\plugin\remotesensing\shape.py", line 56, in <module>
    ct: osr.CoordinateTransformation) -> List[str]:
NameError: name 'osr' is not defined
```

**Comment by luokunman** [comment]
遇见了一样的问题  您有解决该问题吗

**Comment by haoyuying** [comment]
您好，请问您是怎么安装的eiseg呢，，具体怎么执行，按道理pip install eiseg的话报错不会出现这种目录结构“D:\CODE\PaddleSeg-release-2.4\EISeg\eiseg\plugin\remotesensing\shape.py”，因为那样eiseg就是单独安装的，您的报错问题是环境没安装好遥感相关依赖导致的。安装下这个文件夹下的依赖https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/EISeg/requirements-rs.txt

**Comment by luokunman** [comment]
我就是pip install eiseg安装的eiseg

**Comment by luokunman** [comment]
> 您好，请问您是怎么安装的eiseg呢，，具体怎么执行，按道理pip install eiseg的话报错不会出现这种目录结构“D:\CODE\PaddleSeg-release-2.4\EISeg\eiseg\plugin\remotesensing\shape.py”，因为那样eiseg就是单独安装的，您的报错问题是环境没安装好遥感相关依赖导致的。安装下这个文件夹下的依赖https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/EISeg/requirements-rs.txt

我这边再检查一下~非常感谢您的回复

**Comment by haoyuying** [comment]
遥感环境要单独安装，文档参考这里https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/EISeg/docs/remote_sensing.md

**Comment by AICVHub** [comment]
遥感相关requirements安装后,依然报这个错...

**Comment by haoyuying** [comment]
可以看下你gdal安装版本是否符合要求，是否单独import osr也会出错，这个报错是依赖没有安装好，再检查下环境问题吧
