### ISSUE TITLE
ValueError: (InvalidArgument) The input tensor's dimension should be equal to the axis's size. But received input tensor's dimension is 5, axis's size is 4

### ISSUE THREAD

**Issue by Yasminbr** [PaddlePaddle/PaddleSeg#1774]
1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (PaddlePaddle 2.1.0)
 3. Operation system: (Windows)
 4. Python version: (3.8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2)
 6. Additional context: 

Hey, im trying to train a Unet  and get those issues : 

Traceback (most recent call last):
  File "train.py", line 199, in <module>
    main(args)
  File "train.py", line 194, in main
    to_static_training=cfg.to_static_training)
  File "C:\Users\yasminbr\PycharmProjects\PaddleSeg\paddleseg\core\train.py", line 208, in train
    edges=edges)
  File "C:\Users\yasminbr\PycharmProjects\PaddleSeg\paddleseg\core\train.py", line 57, in loss_computation
    loss_list.append(coef_i * loss_i(logits, labels))
  File "C:\Users\yasminbr\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\dygraph\layers.py", line 884, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "C:\Users\yasminbr\PycharmProjects\PaddleSeg\paddleseg\models\losses\dice_loss.py", line 41, in forward
    labels_one_hot = paddle.transpose(labels_one_hot, [0, 3, 1, 2,])
  File "C:\Users\yasminbr\AppData\Roaming\Python\Python37\site-packages\paddle\fluid\layers\nn.py", line 5471, in transpose
    out, _ = core.ops.transpose2(x, 'axis', perm)
ValueError: (InvalidArgument) The input tensor's dimension should be equal to the axis's size. But received input tensor's dimension is 5, axis's size is 4
  [Hint: Expected x_rank == axis_size, but received x_rank:5 != axis_size:4.] (at D:\2.0.0rc1\paddle\paddle\fluid\operators\transpose_op.cc:47)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]
  [operator < transpose2 > error]

my .ymlconfig file liooks like this : 

batch_size: 1
iters: 1000

train_dataset:
  type: Dataset
  dataset_root: -------------
  num_classes: 3
  train_path: ---------
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: ----
  num_classes: 3
  val_path: -------
  transforms:
    - type: Normalize
  mode: val

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: DiceLoss
  coef: [0 1]

model:
  type: UNet
  num_classes: 3
  use_deconv: False
  pretrained: Null

--

I use tif images and png masks 
X.shape is - [1,3,512,512] 

would be happy to get some help, thanks :)

**Comment by Yasminbr** [comment]
sorry i edit - 
X = [1,512,512,3,3]
