### ISSUE TITLE
训练的时候出现错误：AttributeError: module 'paddle' has no attribute 'int8'

### ISSUE THREAD

**Issue by dapsjj** [PaddlePaddle/PaddleSeg#1781]
欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：PaddleSeg release/2.4
 2. PaddlePaddle版本：PaddlePaddle 2.0.0
 3. 操作系统信息：Windows10
 4. Python版本号：Python3.8
 5. CUDA/cuDNN版本： 如CUDA10.1/cuDNN 7.6.0

使用自己的数据集训练的时候，`python train.py --config configs/butterfly_squirrel.yml --do_eval --use_vdl --save_interval 500 --save_dir output`
提示错误：
```
Traceback (most recent call last):
  File "train.py", line 199, in <module>
    main(args)
  File "train.py", line 176, in main
    train(
  File "E:\test_opencv\PaddleSeg-release-2.4\paddleseg\core\train.py", line 280, in train
    mean_iou, acc, _, _, _ = evaluate(
  File "E:\test_opencv\PaddleSeg-release-2.4\paddleseg\core\val.py", line 116, in evaluate
    pred, logits = infer.inference(
  File "E:\test_opencv\PaddleSeg-release-2.4\paddleseg\core\infer.py", line 243, in inference
    logit = reverse_transform(logit, ori_shape, transforms, mode='bilinear')
  File "E:\test_opencv\PaddleSeg-release-2.4\paddleseg\core\infer.py", line 102, in reverse_transform
    intTypeList = [paddle.int8, paddle.int16, paddle.int32, paddle.int64]
AttributeError: module 'paddle' has no attribute 'int8'

```

`

**Comment by dapsjj** [comment]
已经解决了，我的原来的PaddlePaddle 2.0的版本不对，升级到PaddlePaddle 2.2就没有这个错误了
