### ISSUE TITLE
使用attention_unet，模型能跑动，但预测时出现boardcast维度问题，如下图，能帮忙解决吗[Bug]

### ISSUE THREAD

**Issue by ttttnnnn13** [PaddlePaddle/PaddleSeg#1857]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.4）
 2. PaddlePaddle版本：（PaddlePaddle 2.1.2）
 3. 操作系统信息：（Windows）
 4. Python版本号：（Python3.6）
 5. CUDA/cuDNN版本：（CUDA10.1）
`2022-03-10 09:34:54 [INFO]      Number of predict images = 1
2022-03-10 09:34:54 [INFO]      Loading pretrained model from output/iter_500/model.pdparams
2022-03-10 09:34:55 [INFO]      There are 206/206 variables loaded into AttentionUNet.
2022-03-10 09:34:55 [INFO]      Start to predict...
Traceback (most recent call last):
  File "predict.py", line 177, in <module>
    main(args)
  File "predict.py", line 172, in main
    **test_config)
  File "D:\PaddleSeg\paddleseg\core\predict.py", line 118, in predict
    crop_size=crop_size)
  File "D:\PaddleSeg\paddleseg\core\infer.py", line 232, in inference
    logits = model(im)
  File "D:\anaconda3\envs\paddleseg\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\PaddleSeg\paddleseg\models\attention_unet.py", line 74, in forward
    x4 = self.att5(g=d5, x=x4)
  File "D:\anaconda3\envs\paddleseg\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\PaddleSeg\paddleseg\models\attention_unet.py", line 122, in forward
    psi = self.relu(g1 + x1)
  File "D:\anaconda3\envs\paddleseg\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py", line 264, in __impl__
    return math_op(self, other_var, 'axis', axis)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 256, 112, 148] and the shape of Y = [1, 256, 113, 149]. Received [112] in X is not equ
al to [113] in Y at i:2.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != tr
ue:1.] (at ..\paddle/fluid/operators/elementwise/elementwise_op_function.h:240)
  [operator < elementwise_add > error]
`

**Comment by michaelowenliu** [comment]
@ttttnnnn13 Thanks for your issue. To help us solve the issue better, please use the issue template for bug report properly.

**Comment by justld** [comment]
可以查看下数据的维度，看报错是特征图的维度没对上，看一下预测数据的（H, W）和训练集是否一致

**Comment by ttttnnnn13** [comment]
可是为什么模型可以跑通了，我这个是三分类，之前二分类倒是没这个问题，会是其他原因吗，换个Ubuntu系统会好些吗

 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月10日(星期四) 上午9:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/PaddleSeg] 使用attention_unet，模型能跑动，但预测时出现boardcast维度问题，如下图，能帮忙解决吗[Bug] (Issue #1857)





 
可以查看下数据的维度，看报错是特征图的维度没对上，看一下预测数据的（H, W）和训练集是否一致
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by haoyuying** [comment]
因为训练和测试时候图的size是不一样的，训练的 时候图像进行了剪切等操作，在predict时候图像没有进行尺寸的变化。
