### ISSUE TITLE
RuntimeError: The length of logits_list should equal to the types of loss config: 2 != 1.

### ISSUE THREAD

**Issue by ql390962** [PaddlePaddle/PaddleSeg#1866]
环境：PaddleSeg release/2.3，PaddlePaddle 2.2.1，Windows，Python3.7，CUDA11.2/CUDNN8.1.1

使用paddleseg.core.train和paddleseg.model做语义分割。输入图像为两图像叠加，6通道，unet和unet++可以正常运行。使用ocrnet，backbone用ResNet50_vd报错。

Traceback (most recent call last):
  File "C:/Users/li/Desktop/unet/paddle-unet/train_ocrnet.py", line 45, in <module>
    use_vdl=True)
  File "C:\Anaconda3\lib\site-packages\paddleseg\core\train.py", line 197, in train
    edges=edges)
  File "C:\Anaconda3\lib\site-packages\paddleseg\core\train.py", line 38, in loss_computation
    check_logits_losses(logits_list, losses)
  File "C:\Anaconda3\lib\site-packages\paddleseg\core\train.py", line 34, in check_logits_losses
    .format(len_logits, len_losses))
RuntimeError: The length of logits_list should equal to the types of loss config: 2 != 1.

应该怎么解决。

**Comment by justld** [comment]
检查一下，是不是网络输出的logits数量和损失函数数量不符合，如果返回2个logits，那么config的损失函数应该有2个。

**Comment by shiyutang** [comment]
What he said is correct.

**Comment by shiyutang** [comment]
If you have any further questions, you are very welcome to reopen it.
