### ISSUE TITLE
[General Issue] EOFError: marshal data too short

### ISSUE THREAD

**Issue by SurvivorNo1** [PaddlePaddle/PaddleSeg#1867]
请问训练时出现这种情况是什么原因啊，我以1024\*1024训练是没有这个问题，当我修改为512\*512时就出现了如下错误：下面是报错信息和配置文件以及环境信息

```
- Traceback (most recent call last):
-   File "/home/aistudio/work/PaddleSeg/train.py", line 199, in <module>
-     main(args)
-   File "/home/aistudio/work/PaddleSeg/train.py", line 194, in main
-     to_static_training=cfg.to_static_training)
-   File "/mnt/aistudio_20220312230814/work/PaddleSeg/paddleseg/core/train.py", line 297, in train
-     shutil.rmtree(model_to_remove)
-   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/shutil.py", line 498, in rmtree
-     onerror(os.rmdir, path, sys.exc_info())
-   File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/shutil.py", line 496, in rmtree
-     os.rmdir(path)
- OSError: [Errno 5] Input/output error: '/home/aistudio/work/PaddleSeg/output/iter_80000'
- Traceback (most recent call last):
-   File "work/PaddleSeg/export.py", line 21, in <module>
-     from paddleseg.cvlibs import Config
-   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
-   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
-   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
-   File "<frozen importlib._bootstrap_external>", line 724, in exec_module
-   File "<frozen importlib._bootstrap_external>", line 857, in get_code
-   File "<frozen importlib._bootstrap_external>", line 525, in _compile_bytecode
- EOFError: marshal data too short
```

```
------------Environment Information-------------
platform: Linux-4.4.0-150-generic-x86_64-with-debian-stretch-sid
Python: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
Paddle compiled with cuda: True
NVCC: Cuda compilation tools, release 10.1, V10.1.243
cudnn: 7.6
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: Tesla V100-SXM2-32GB']
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
PaddleSeg: 2.4.0
PaddlePaddle: 2.2.2
OpenCV: 4.1.1
------------------------------------------------
2022-03-12 23:10:15 [INFO]	
---------------Config Information---------------
batch_size: 8
iters: 160000
loss:
  coef:
  - 1
  types:
  - ignore_index: 255
    loss_th: 0.3
    min_K: 4096
    type: BootstrappedCrossEntropyLoss
lr_scheduler:
  learning_rate: 0.025
  type: PolynomialDecay
model:
  pretrained: /home/aistudio/work/PaddleSeg/pretrained/model.pdparams
  type: HarDNet
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 0.0005
train_dataset:
  dataset_root: /home/aistudio/data/data_2022
  mode: train
  num_classes: 4
  train_path: /home/aistudio/data/data_2022/train.txt
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - interp: LINEAR
    target_size:
    - 512
    - 512
    type: Resize
  - type: RandomHorizontalFlip
  - brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
    type: RandomDistort
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: /home/aistudio/data/data_2022
  mode: val
  num_classes: 4
  transforms:
  - interp: LINEAR
    target_size:
    - 512
    - 512
    type: Resize
  - type: Normalize
  type: Dataset
  val_path: /home/aistudio/data/data_2022/val.txt
------------------------------------------------
W0312 23:10:15.903532   458 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0312 23:10:15.903626   458 device_context.cc:465] device: 0, cuDNN Version: 7.6.
```

**Comment by juncaipeng** [comment]
从log来看是删除过多的checkpoint错误，应该不是该size的问题。你尝试换一个输出路径进行保存。

**Comment by SurvivorNo1** [comment]
> 从log来看是删除过多的checkpoint错误，应该不是该size的问题。你尝试换一个输出路径进行保存。

谢谢啦，按您说的已解决
