### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'astype'   报错求救，文件路径是对的

### ISSUE THREAD

**Issue by Jinji97** [PaddlePaddle/PaddleSeg#1884]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 213, in _thread_loop
    self._thread_done_event)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "/home/aistudio/paddleseg/datasets/dataset.py", line 153, in __getitem__
    im, label = self.transforms(im=image_path, label=label_path)
  File "/home/aistudio/paddleseg/transforms/transforms.py", line 57, in __call__
    im = cv2.imread(im).astype('float32')
AttributeError: 'NoneType' object has no attribute 'astype'

**Comment by juncaipeng** [comment]
错误显示是读取图像错误，应该是路径配置不对。可以多参考seg文档，调试一下。

**Comment by Jinji97** [comment]
我调了好多次，还是不行，你能发个参考的格式么，比如链接文档这些

**Comment by juncaipeng** [comment]
参考seg首页文档：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/README_CN.md
<img width="352" alt="image" src="https://user-images.githubusercontent.com/52520497/159827976-a4d535c4-47ae-466f-9124-01e88c8a9d14.png">

**Comment by zhuangqirong** [comment]
> 我调了好多次，还是不行，你能发个参考的格式么，比如链接文档这些

调试好了么老哥？

**Comment by zhuangqirong** [comment]
> 我调了好多次，还是不行，你能发个参考的格式么，比如链接文档这些

找到原因了，dataset   train.txt 文件 JPEGimages\1.jpg，中间的\不正确，在aistudio中，应该是/才对。
