### ISSUE TITLE
[General Issue] ValueError: all input arrays must have the same shape

### ISSUE THREAD

**Issue by debug851** [PaddlePaddle/PaddleSeg#1889]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/data/program/miniconda3/envs/wj/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/data/program/miniconda3/envs/wj/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/data/program/miniconda3/envs/wj/lib/python3.6/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 213, in _thread_loop
    self._thread_done_event)
  File "/data/program/miniconda3/envs/wj/lib/python3.6/site-packages/paddle/fluid/dataloader/fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "/data/program/miniconda3/envs/wj/lib/python3.6/site-packages/paddle/fluid/dataloader/collate.py", line 77, in default_collate_fn
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "/data/program/miniconda3/envs/wj/lib/python3.6/site-packages/paddle/fluid/dataloader/collate.py", line 77, in <listcomp>
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "/data/program/miniconda3/envs/wj/lib/python3.6/site-packages/paddle/fluid/dataloader/collate.py", line 58, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "/data/program/miniconda3/envs/wj/lib/python3.6/site-packages/numpy/core/shape_base.py", line 427, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
-------------
明明已经resize了，还是报错

**Comment by juncaipeng** [comment]
你可以代码中打印出来dataset每次返回的tensor shape。
你如果是使用config配置模型的train dataset，需要明确RandomPaddingCrop预处理后不要再调整图像size。

**Comment by raykindle** [comment]
> 


```
------------------------------------------------
W0429 11:23:46.498219 32689 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0429 11:23:46.498323 32689 device_context.cc:465] device: 0, cuDNN Version: 7.6.
2022-04-29 11:23:53 [INFO]      Loading pretrained model from checkpoints/pretrain/SegFormer_B3.pdparams
2022-04-29 11:23:53 [WARNING]   [SKIP] Shape of pretrained params linear_pred.weight doesn't match.(Pretrained: [19, 768, 1, 1], Actual: [4, 768, 1, 1])
2022-04-29 11:23:53 [WARNING]   [SKIP] Shape of pretrained params linear_pred.bias doesn't match.(Pretrained: [19], Actual: [4])
2022-04-29 11:23:53 [INFO]      There are 585/587 variables loaded into SegFormer.
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:39845', '127.0.0.1:34815']
I0429 11:23:56.598202 32689 nccl_context.cc:74] init nccl context nranks: 4 local rank: 0 gpu id: 0 ring id: 0
I0429 11:23:56.814556 32689 nccl_context.cc:107] init nccl context nranks: 4 local rank: 0 gpu id: 0 ring id: 10
2022-04-29 11:23:56,892-INFO: [topology.py:169:__init__] HybridParallelInfo: rank_id: 0, mp_degree: 1, sharding_degree: 1, pp_degree: 1, dp_degree: 4, mp_group: [0],  sharding_group: [0], pp_group: [0], dp_group: [0, 1, 2, 3], check/clip group: [0]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 213, in _thread_loop
    self._thread_done_event)
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 77, in default_collate_fn
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 77, in <listcomp>
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 58, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "/opt/conda/lib/python3.7/site-packages/numpy/core/shape_base.py", line 426, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape

/opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:253: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.int64, the right dtype will convert to paddle.float32
  format(lhs_dtype, rhs_dtype, lhs_dtype))
```


我也遇到相同的问题，   原来的配置是这样的 :
```
train_dataset:
  transforms:
    - type: RandomPaddingCrop
      crop_size: [1024, 1024]
```


但是我的数据尺度只有266 x 266的大小，所以，我修改成了如下的配置，报错了:
```
train_dataset:
  transforms:
    - type: RandomPaddingCrop
      crop_size: [256, 256]
```


我想要的crop_size为256 x 256，请教一下，我应该怎么修改呢？谢谢

**Comment by raykindle** [comment]
基于`segformer_b3_cityscapes_1024x1024_160k.yml`配置修改而来

**Comment by Nomination-NRB** [comment]
> > 
> 
> ```
> ------------------------------------------------
> W0429 11:23:46.498219 32689 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
> W0429 11:23:46.498323 32689 device_context.cc:465] device: 0, cuDNN Version: 7.6.
> 2022-04-29 11:23:53 [INFO]      Loading pretrained model from checkpoints/pretrain/SegFormer_B3.pdparams
> 2022-04-29 11:23:53 [WARNING]   [SKIP] Shape of pretrained params linear_pred.weight doesn't match.(Pretrained: [19, 768, 1, 1], Actual: [4, 768, 1, 1])
> 2022-04-29 11:23:53 [WARNING]   [SKIP] Shape of pretrained params linear_pred.bias doesn't match.(Pretrained: [19], Actual: [4])
> 2022-04-29 11:23:53 [INFO]      There are 585/587 variables loaded into SegFormer.
> server not ready, wait 3 sec to retry...
> not ready endpoints:['127.0.0.1:39845', '127.0.0.1:34815']
> I0429 11:23:56.598202 32689 nccl_context.cc:74] init nccl context nranks: 4 local rank: 0 gpu id: 0 ring id: 0
> I0429 11:23:56.814556 32689 nccl_context.cc:107] init nccl context nranks: 4 local rank: 0 gpu id: 0 ring id: 10
> 2022-04-29 11:23:56,892-INFO: [topology.py:169:__init__] HybridParallelInfo: rank_id: 0, mp_degree: 1, sharding_degree: 1, pp_degree: 1, dp_degree: 4, mp_group: [0],  sharding_group: [0], pp_group: [0], dp_group: [0, 1, 2, 3], check/clip group: [0]
> Exception in thread Thread-2:
> Traceback (most recent call last):
>   File "/opt/conda/lib/python3.7/threading.py", line 926, in _bootstrap_inner
>     self.run()
>   File "/opt/conda/lib/python3.7/threading.py", line 870, in run
>     self._target(*self._args, **self._kwargs)
>   File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 213, in _thread_loop
>     self._thread_done_event)
>   File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 134, in fetch
>     data = self.collate_fn(data)
>   File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 77, in default_collate_fn
>     return [default_collate_fn(fields) for fields in zip(*batch)]
>   File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 77, in <listcomp>
>     return [default_collate_fn(fields) for fields in zip(*batch)]
>   File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 58, in default_collate_fn
>     batch = np.stack(batch, axis=0)
>   File "<__array_function__ internals>", line 6, in stack
>   File "/opt/conda/lib/python3.7/site-packages/numpy/core/shape_base.py", line 426, in stack
>     raise ValueError('all input arrays must have the same shape')
> ValueError: all input arrays must have the same shape
> 
> /opt/conda/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:253: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.int64, the right dtype will convert to paddle.float32
>   format(lhs_dtype, rhs_dtype, lhs_dtype))
> ```
> 
> 我也遇到相同的问题， 原来的配置是这样的 :
> 
> ```
> train_dataset:
>   transforms:
>     - type: RandomPaddingCrop
>       crop_size: [1024, 1024]
> ```
> 
> 但是我的数据尺度只有266 x 266的大小，所以，我修改成了如下的配置，报错了:
> 
> ```
> train_dataset:
>   transforms:
>     - type: RandomPaddingCrop
>       crop_size: [256, 256]
> ```
> 
> 我想要的crop_size为256 x 256，请教一下，我应该怎么修改呢？谢谢

把原图按照图片比例扩大几倍，让图片大小再2000以上就可以用512*512了
