### ISSUE TITLE
dim模型训练时的问题

### ISSUE THREAD

**Issue by zhenzi0322** [PaddlePaddle/PaddleSeg#1900]
dim.yml
```yml
batch_size: 16
iters: 100000

train_dataset:
  type: MattingDataset
  dataset_root: data/demo1
  train_file: train.txt
  transforms:
    - type: LoadImages
    - type: RandomCropByAlpha
      crop_size: [[320, 320], [480, 480], [640, 640]]
    - type: Resize
      target_size: [320, 320]
    - type: RandomDistort
    - type: RandomBlur
    - type: RandomHorizontalFlip
    - type: Normalize
  mode: train
  get_trimap: False

val_dataset:
  type: MattingDataset
  dataset_root: data/demo1
  val_file: val.txt
  transforms:
    - type: LoadImages
    - type: LimitLong
      max_long: 3840
    - type: Normalize
  mode: val
  get_trimap: False

model:
  type: DIM
  backbone:
    type: VGG16
    input_channels: 4
    pretrained: https://paddleseg.bj.bcebos.com/matting/models/DIM_VGG16_pretrained/model.pdparams
  pretrained: Null

optimizer:
  type: adam

learning_rate:
  value: 0.001
```

采用`dim`进行训练出现如下错误：
```
2022-03-22 12:04:01 [WARNING]   `learning_rate` in configuration file will be deprecated, please use `lr_scheduler` instead. E.g
            lr_scheduler:
                type: PolynomialDecay
                learning_rate: 0.01
Traceback (most recent call last):
  File "train.py", line 181, in <module>
    main(args)
  File "train.py", line 176, in main
    eval_begin_iters=args.eval_begin_iters)
  File "/home/ubuntu/mattings/core/train.py", line 149, in train
    logit_dict = model(data)
  File "/home/ubuntu/anaconda3/envs/mattings/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/ubuntu/anaconda3/envs/mattings/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/ubuntu/mattings/model/dim.py", line 68, in forward
    x = paddle.concat([inputs['img'], inputs['trimap'] / 255], axis=1)
KeyError: 'trimap'
```

**Comment by wuyefeilin** [comment]
dim需要提供trimap进行训练，get_trimap: True
