### ISSUE TITLE
启动VisualDL查看日志，报以下错误是什么原因，help

### ISSUE THREAD

**Issue by Jinji97** [PaddlePaddle/PaddleSeg#1932]
(paddle) E:\Program Files\model\PaddleSeg-release-2.4\PaddleSeg-release-2.4>visualdl --logdir output1/
VisualDL 2.2.3
Traceback (most recent call last):
  File "D:\ProgramFiles\Anaconda\envs\paddle\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ProgramFiles\Anaconda\envs\paddle\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\ProgramFiles\Anaconda\envs\paddle\Scripts\visualdl.exe\__main__.py", line 7, in <module>
  File "D:\ProgramFiles\Anaconda\envs\paddle\lib\site-packages\visualdl\server\app.py", line 177, in main
    _run(args)
  File "D:\ProgramFiles\Anaconda\envs\paddle\lib\site-packages\visualdl\server\app.py", line 158, in _run
    app.run(debug=False, host=args.host, port=args.port, threaded=False)
  File "D:\ProgramFiles\Anaconda\envs\paddle\lib\site-packages\flask\app.py", line 920, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "D:\ProgramFiles\Anaconda\envs\paddle\lib\site-packages\werkzeug\serving.py", line 1017, in run_simple
    inner()
  File "D:\ProgramFiles\Anaconda\envs\paddle\lib\site-packages\werkzeug\serving.py", line 957, in inner
    srv = make_server(
  File "D:\ProgramFiles\Anaconda\envs\paddle\lib\site-packages\werkzeug\serving.py", line 804, in make_server
    return BaseWSGIServer(
  File "D:\ProgramFiles\Anaconda\envs\paddle\lib\site-packages\werkzeug\serving.py", line 693, in __init__
    super().__init__(server_address, handler)  # type: ignore
  File "D:\ProgramFiles\Anaconda\envs\paddle\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "D:\ProgramFiles\Anaconda\envs\paddle\lib\http\server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "D:\ProgramFiles\Anaconda\envs\paddle\lib\socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。

**Comment by juncaipeng** [comment]
请到visual repo下提issue:https://github.com/PaddlePaddle/VisualDL
