### ISSUE TITLE
infer_dataset.py在测试cityscapes时dataset_mode可以设置为test吗

### ISSUE THREAD

**Issue by Pr0Wh1teGive** [PaddlePaddle/PaddleSeg#1944]
1. PaddleSeg version: 2.4
 2. PaddlePaddle version: 2.2.2
 3. Operation system: Linux
 4. Python version: 3.7
 5. CUDA/cuDNN version: CUDA10.2/cuDNN 7.6.5
 请问infer_dataset.py的dataset_mode参数在测试cityscapes数据集的时候可以设置为"test"吗，目前会报错:

2022-03-29 15:42:49 [INFO]      Use GPU
Traceback (most recent call last):
  File "deploy/python/infer_dataset.py", line 321, in <module>
    main(args)
  File "deploy/python/infer_dataset.py", line 294, in main
    predictor.run_dataset()
  File "deploy/python/infer_dataset.py", line 249, in run_dataset
    self.predictor.run()
ValueError: In user code:

    File "./export.py", line 143, in <module>
      main(args)
    File "./export.py", line 122, in main
      paddle.jit.save(new_net, save_path)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 744, in save
      inner_input_spec)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 517, in concrete_program_specify_input_spec      *desired_input_spec)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 427, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in _build_once
      **cache_key.kwargs)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 662, in from_func_spec
      outputs = static_func(*inputs)
    File "./export.py", line 74, in forward
      outs = self.net(x)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/home/s2182537/PaddleSeg/paddleseg/models/bisenetv1.py", line 86, in forward
      context_blocks = self.backbone(x)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/home/s2182537/PaddleSeg/paddleseg/models/backbones/resnet_vd.py", line 349, in forward
      y = self.conv1_1(inputs)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/home/s2182537/PaddleSeg/paddleseg/models/backbones/resnet_vd.py", line 70, in forward
      y = self._conv(inputs)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 677, in forward
      use_cudnn=self._use_cudnn)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 148, in _conv_nd
      type=op_type, inputs=inputs, outputs=outputs, attrs=attrs)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3184, in append_op
      attrs=kwargs.get("attrs", None))
    File "/home/s2182537/miniconda3/envs/paddle_env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The input's dimension of Operator(Conv2DFusion) is expected to be 4. But received: input's dimension = 5, shape = [1, 1, 3, 1024, 2048].
      [Hint: Expected in_dims.size() == 4U, but received in_dims.size():5 != 4U:4.] (at /paddle/paddle/fluid/operators/fused/conv_fusion_op.cc:77)
      [operator < conv2d_fusion > error]

**Comment by wuyefeilin** [comment]
不行哈，test没有提供标签的
