### ISSUE TITLE
vis.py运行报错

### ISSUE THREAD

**Issue by jbq123** [PaddlePaddle/PaddleSeg#195]
我在运行的时候跑预训练的模型时python pdseg/vis.py --cfg configs/deeplabv3p_xception65_cityscapes.yaml --use_gpu --vis_dir visual TEST.TEST_MODEL "pretrained_model/deeplabv3p_xception65_gn_cityscapes" EVAL_CROP_SIZE "(2049, 1025)"。
遇到了这个报错：Error: Cannot open file pretrained_model/deeplabv3p_xception65_gn_cityscapes/xception_65/middle_flow/block11/separable_conv1/pointwise/BatchNorm/moving_variance for load op at (/paddle/paddle/fluid/operators/load_op.h:38)
  [operator < load > error]
没找到BatchNorm这个目录，请问该怎么解决。

**Comment by LutaoChu** [comment]
先确认一下本地是否存在这个路径`pretrained_model/deeplabv3p_xception65_gn_cityscapes/xception_65/middle_flow/block11/separable_conv1/pointwise/BatchNorm/moving_variance`。
如果不是路径问题，提供一下PaddleSeg和PaddlePaddle的版本吧

**Comment by jbq123** [comment]
您好，我在jetson TX2上跑pdseg/vis.py的时候出现了这个报错：
W0324 16:37:16.218273  8639 operator.cc:181] elementwise_add raises an exception thrust::system::system_error, parallel_for failed: too many resources requested for launch
/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "pdseg/vis.py", line 219, in <module>
    visualize(cfg, **args.__dict__)
  File "pdseg/vis.py", line 134, in visualize
    return_numpy=True)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/dist-packages/six.py", line 696, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 831, in _run_impl
    use_program_cache=use_program_cache)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/executor.py", line 905, in _run_program
    fetch_var_name)
RuntimeError: parallel_for failed: too many resources requested for launch
请问该怎么解决。

**Comment by lyc1995452-star** [comment]
请问你们在运行可视化时，出现这种情况没？
Traceback (most recent call last):
File "vis.py", line 212, in
visualize(cfg, **args.dict)
File "vis.py", line 133, in visualize
for imgs, grts, img_names, valid_shapes, org_shapes in test_reader:
File "/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 136, in batch_reader
for img, grt, img_name, valid_shape, org_shape in reader():
File "/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 81, in generator
yield self.process_image(line, self.data_dir, self.mode)
File "/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 251, in process_image
line, data_dir, mode=mode)
File "/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 205, in load_image
grt_height = grt.shape[0]
IndexError: tuple index out of range
