### ISSUE TITLE
[Bug]模型量化错误

### ISSUE THREAD

**Issue by x12901** [PaddlePaddle/PaddleSeg#1968]
量化训练的时候运行出现错误，'NoneType' object has no attribute 'train'
```
(PP) D:\PaddleSeg-release-2.4>python slim/quant/qat_train.py --config configs/deeplabv3p/deeplabv3p_resnet50_os8_cityscapes_1024x512_80k.yml --model_path output-dpv3p/best_model/model.pdparams --learning_rate 0.001 --do_eval --use_vdl --save_interval 250 --save_dir output_quant
C:\ProgramData\Anaconda3\envs\PP\lib\site-packages\paddleslim\core\graph_wrapper.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  from collections import Iterable
'C:\Program' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
2022-04-07 11:43:53 [INFO]
------------Environment Information-------------
platform: Windows-10-10.0.19042-SP0
Python: 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]
Paddle compiled with cuda: True
NVCC: Not Available
cudnn: 7.6
GPUs used: 1
CUDA_VISIBLE_DEVICES: 0,1,2
GPU: ['GPU 0: GeForce GTX', 'GPU 1: GeForce GTX', 'GPU 2: GeForce GTX']
GCC: gcc (MinGW.org GCC Build-2) 9.2.0
PaddleSeg: 2.4.0
PaddlePaddle: 2.2.1
OpenCV: 4.5.5
------------------------------------------------
2022-04-07 11:43:53 [INFO]
---------------Config Information---------------
batch_size: 2
iters: 80000
loss:
  coef:
  - 1
  types:
  - ignore_index: 255
    type: CrossEntropyLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 0.001
  power: 0.9
  type: PolynomialDecay
model:
  align_corners: false
  aspp_out_channels: 256
  aspp_ratios:
  - 1
  - 12
  - 24
  - 36
  backbone:
    multi_grid:
    - 1
    - 2
    - 4
    output_stride: 8
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
    type: ResNet50_vd
  backbone_indices:
  - 0
  - 3
  pretrained: null
  type: DeepLabV3P
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 4.0e-05
train_dataset:
  dataset_root: data/bg
  mode: train
  num_classes: 7
  train_path: data/bg/train_list.txt
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 1024
    - 512
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
    type: RandomDistort
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: data/bg
  mode: val
  num_classes: 7
  transforms:
  - type: Normalize
  type: Dataset
  val_path: data/bg/val_list.txt
------------------------------------------------
W0407 11:43:53.833144 27676 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.1, Runtime API Version: 10.2
W0407 11:43:53.834144 27676 device_context.cc:465] device: 0, cuDNN Version: 7.6.
2022-04-07 11:43:59 [INFO]      Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
2022-04-07 11:44:00 [INFO]      There are 275/275 variables loaded into ResNet_vd.
2022-04-07 11:44:00 [INFO]      Loading pretrained model from output-dpv3p/best_model/model.pdparams
2022-04-07 11:44:01 [INFO]      There are 360/360 variables loaded into DeepLabV3P.
2022-04-07 11:44:01 [INFO]      Loaded trained params of model successfully
2022-04-07 11:44:01 [INFO]      Quantize all target ops in backbone
2022-04-07 11:44:02 [INFO]      Quantize the model successfully
Traceback (most recent call last):
  File "slim/quant/qat_train.py", line 212, in <module>
    main(args)
  File "slim/quant/qat_train.py", line 193, in main
    train(
  File "D:\PaddleSeg-release-2.4\paddleseg\core\train.py", line 103, in train
    model.train()
AttributeError: 'NoneType' object has no attribute 'train'
```
 1. PaddleSeg版本：PaddleSeg release/2.4
 2. PaddlePaddle版本：如PaddlePaddle 2.1.0
 3. 操作系统信息：Windows
 4. Python版本号：Python3.8
 5. CUDA/cuDNN版本：CUDA11.0

**Comment by haoyuying** [comment]
模型初始化存在问题，查看下model从哪里开始变为None的
