### ISSUE TITLE
[Bug].使用eiseg的时候导致显存溢出

### ISSUE THREAD

**Issue by liyaoshun** [PaddlePaddle/PaddleSeg#1993]
1. PaddleSeg version:  PaddleSeg release/2.3
 2. PaddlePaddle version: PaddlePaddle 2.2.2
 3. Operation system: Linux
 4. Python version: Python3.8
 5. CUDA/cuDNN version:  CUDA11.1/cuDNN 8.1.0
 6. Full codes: 没有修改任何代码
 7. Detailed error information, releated running log: 

(paddleseg)  /media/robot/4T/5_segmentation/PaddleSeg/EISeg/eiseg /release/2.3: CUDA_VISIBLE_DEVICES=1 python exe.py
W0411 18:27:11.660653 10514 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.1
W0411 18:27:11.662276 10514 device_context.cc:465] device: 0, cuDNN Version: 8.1.
/media/robot/4T/5_segmentation/PaddleSeg/EISeg/eiseg/model/modeling/hrnet_ocr.py:206: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  last_inp_channels = np.int(np.sum(pre_stage_channels))
param_path HRNet18_OCR64 /media/robot/4T/5_segmentation/PaddleSeg/EISeg/eiseg/model/hrnet18_ocr64_cocolvis.pdparams
Gtk-Message: 18:27:19.384: GtkDialog mapped without a transient parent. This is discouraged.
param_path HRNet18_OCR64 /media/robot/4T/5_segmentation/PaddleSeg/EISeg/eiseg/model/hrnet18_ocr64_cocolvis.pdparams
Gtk-Message: 18:27:27.132: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: 18:27:31.753: GtkDialog mapped without a transient parent. This is discouraged.
/home/robot/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Traceback (most recent call last):
  File "/media/robot/4T/5_segmentation/PaddleSeg/EISeg/eiseg/app.py", line 1383, in canvasClick
    self.controller.addClick(x, y, isLeft)
  File "/media/robot/4T/5_segmentation/PaddleSeg/EISeg/eiseg/controller.py", line 202, in addClick
    pred = self.predictor.get_prediction(self.clicker)
  File "/media/robot/4T/5_segmentation/PaddleSeg/EISeg/eiseg/inference/predictor/base.py", line 71, in get_prediction
    pred_logits = self._get_prediction(image_nd, clicks_lists, is_image_changed)
  File "/media/robot/4T/5_segmentation/PaddleSeg/EISeg/eiseg/inference/predictor/base.py", line 86, in _get_prediction
    return self.net(image_nd, points_nd)['instances']
  File "/home/robot/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/robot/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/media/robot/4T/5_segmentation/PaddleSeg/EISeg/eiseg/model/is_model.py", line 68, in forward
    outputs = self.backbone_forward(image, coord_features)
  File "/media/robot/4T/5_segmentation/PaddleSeg/EISeg/eiseg/model/is_hrnet_model.py", line 14, in backbone_forward
    net_outputs = self.feature_extractor(image, coord_features)
  File "/home/robot/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/robot/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/media/robot/4T/5_segmentation/PaddleSeg/EISeg/eiseg/model/modeling/hrnet_ocr.py", line 327, in forward
    feats = self.compute_hrnet_feats(x, additional_features)
  File "/media/robot/4T/5_segmentation/PaddleSeg/EISeg/eiseg/model/modeling/hrnet_ocr.py", line 357, in compute_hrnet_feats
    y_list = self.stage3(x_list)
  File "/home/robot/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/robot/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/robot/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/container.py", line 98, in forward
    input = layer(input)
  File "/home/robot/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/robot/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/media/robot/4T/5_segmentation/PaddleSeg/EISeg/eiseg/model/modeling/hrnet_ocr.py", line 131, in forward
    x[i] = self.branches[i](x[i])
  File "/home/robot/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/robot/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/robot/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/container.py", line 98, in forward
    input = layer(input)
  File "/home/robot/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/robot/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/media/robot/4T/5_segmentation/PaddleSeg/EISeg/eiseg/model/modeling/resnetv1b.py", line 28, in forward
    out = self.bn2(out)
  File "/home/robot/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/robot/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/robot/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/nn/layer/norm.py", line 655, in forward
    return batch_norm(
  File "/home/robot/anaconda3/envs/paddleseg/lib/python3.8/site-packages/paddle/nn/functional/norm.py", line 189, in batch_norm
    batch_norm_out, _, _, _, _, _ = _C_ops.batch_norm(
SystemError: (Fatal) Operator batch_norm raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 1.373535MB memory on GPU 0, 9.780823GB memory has been allocated and available memory is only 2.500000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
. (at /paddle/paddle/fluid/imperative/tracer.cc:221)

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1649672888 (unix time) try "date -d @1649672888" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800002912) received by PID 10514 (TID 0x7f95e19a8240) from PID 10514 ***]

[1]    10514 abort (core dumped)  CUDA_VISIBLE_DEVICES=1 python exe.py

 8. Running command or reproduce details：
       1.直接运行exe.py 
       2.选择需要标注的类别后连续多点击几次后就会显示显存移除(怀疑是每次再点击的时候都会重新new显存同时没有释放之前的显存)
 10. Additional context: (Add any other context about the problem)

---

**Comment by haoyuying** [comment]
您好，请给出具体使用的模型，eiseg的版本，点击次数及您显卡的信息，您是如何操作的呢，如果在尺幅比较大的单张图上无意义的点击，由于静态图在预测中途不释放显存，会导致最终占用变大问题。

**Comment by liyaoshun** [comment]
> 您好，请给出具体使用的模型，eiseg的版本，点击次数及您显卡的信息，您是如何操作的呢，如果在尺幅比较大的单张图上无意义的点击，由于静态图在预测中途不释放显存，会导致最终占用变大问题。

1. 模型为：[hrnet18_ocr64_cocolvis](https://bj.bcebos.com/paddleseg/dygraph/interactive_segmentation/ritm/hrnet18_ocr64_cocolvis.pdparams)

2. 点击了大概7次就会爆炸，图像大小为1280*720。
3.  显卡为GTX3080
4.  不是无意义的点击，是在目标上进行点击的时候出现的显存增加，我之前使用这个代码标注相同数据点击很多次都不会溢出。我使用的是clone代码然后运行代码的方式进行打开软件的。我前几天更新了一下代码，然后就出现这个问题了，返回到了去年的代码也是不行的，就很奇怪。
5. eiseg版本为paddleseg release/2.3中自带的。

同时追问一下：静态图不是应该推理完一次后再进行下一次推理的么，然后输入图像不变的条件下显存是不会增加的。我使用其他框架在部署的时候除非是动态的shape等会导致显存增加外其他操作是不会增加显存的。

**Comment by haoyuying** [comment]
您可先尝试在用pip安装eiseg0.4版本，然后做相同的操作，看是否会出现该问题，您的图不算小，并使用的是64的大模型，如果点击增加很多，是会出现该问题。如果0.4eiseg没出现这个问题，请给我一个反馈。

**Comment by liyaoshun** [comment]
> 您可先尝试在用pip安装eiseg0.4版本，然后做相同的操作，看是否会出现该问题，您的图不算小，并使用的是64的大模型，如果点击增加很多，是会出现该问题。如果0.4eiseg没出现这个问题，请给我一个反馈。

验证了使用pip装0.4版本，点击多次后是会增长一点点，点击20几次后显存是稳定的。

**Comment by haoyuying** [comment]
OK， 我们会排查该问题的，感谢您的反馈。您方便把测试图给我们一张吗？

**Comment by liyaoshun** [comment]
> 
![00000505](https://user-images.githubusercontent.com/15494652/162864998-6e066f25-0294-4b3b-ac46-98ac90ebd07f.jpg)

没问题
