### ISSUE TITLE
[General Issue]ValueError: (InvalidArgument) Broadcast dimension mismatch

### ISSUE THREAD

**Issue by weiluonika** [PaddlePaddle/PaddleSeg#1997]
这个报错原因是什么内？

**Comment by juncaipeng** [comment]
模型中相加的两个tensor维度不对应，你具体看下log和代码。

**Comment by weiluonika** [comment]
> 
1/459 [..............................] - ETA: 43s - batch_cost: 0.0954 - reader cost: 0.0362
  2/459 [..............................] - ETA: 35s - batch_cost: 0.0782 - reader cost: 0.0181Traceback (most recent call last):
  File "train.py", line 199, in <module>
    main(args)
  File "train.py", line 194, in main
    to_static_training=cfg.to_static_training)
  File "/lzl/PaddleSeg/paddleseg/core/train.py", line 281, in train
    model, val_dataset, num_workers=num_workers, **test_config)
  File "/lzl/PaddleSeg/paddleseg/core/val.py", line 123, in evaluate
    crop_size=crop_size)
  File "/lzl/PaddleSeg/paddleseg/core/infer.py", line 232, in inference
    logits = model(im)
  File "/Envs/lzl/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/lzl/PaddleSeg/paddleseg/models/attention_unet.py", line 74, in forward
    x4 = self.att5(g=d5, x=x4)
  File "/Envs/lzl/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/lzl/PaddleSeg/paddleseg/models/attention_unet.py", line 122, in forward
    psi = self.relu(g1 + x1)
  File "/Envs/lzl/lib/python3.6/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 250, in __impl__
    return math_op(self, other_var, 'axis', axis)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 256, 72, 44] and the shape of Y = [1, 256, 72, 45]. Received [44] in X is not equal to [45] in Y at i:3.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:169)
  [operator < elementwise_add > error]


检查出来是因为数据尺寸在评估的时候不一致造成的，我使用的是develope版本的 有没有什么解决办法？

**Comment by juncaipeng** [comment]
你这是什么模型？提供一下复现的方法。

**Comment by weiluonika** [comment]
> 你这是什么模型？提供一下复现的方法。

直接使用的项目的attention_unet 算法，只是修改了config的数据集路径，使用的自己的数据集合  数据集合分辨率有576x720x3 576x360x3  这两种，感觉像是因为数据的原因

**Comment by juncaipeng** [comment]
训练集中可以有不同尺寸的图片，但是经过预处理都需要变为固定尺寸输入模型进行训练。你可以参考configs/_base_/cityscapes.ymyaml文件，其中有crop操作，得到固定尺寸的图片。
