### ISSUE TITLE
[Bug] list of dicts for optimizer gives weird results

### ISSUE THREAD

**Issue by 95maddycode** [PaddlePaddle/PaddleSeg#2001]
1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3) 2.4
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0) 2.2.0 
 3. Operation system: (e.g. Linux/Windows/MacOS) Linux
 5. Python version: (e.g. Python3.6/7/8) 3.8
 6. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5) CUDA10.2, cuDNN
7. Full codes: (if you modify any original code，please show the comparison of the codes before and after)
 8. Detailed error information, releated running log: (if using multi-gpus，the log is saved to log/worklog.0 by default)
 9. Running command or reproduce details：
 10. Additional context: (Add any other context about the problem)

Hi, I am running the repo from: https://github.com/zackzhao1/BackgroundMattingV2-paddle

I have a question about TWO possible bugs.

1). FIRST ISSUE

Everything works perfectly fine in this repo, untill I wanted to implement different learning rates for different parts of the model, like so:

  optimizer =  paddle.optimizer.Adam(parameters=[
  {'params': model.backbone.parameters(), 'learning_rate': 1e-4},
  {'params': model.aspp.parameters(), 'learning_rate': 5e-4},
  {'params': model.decoder.parameters(), 'learning_rate': 5e-4}
  ])

However, during training and executing the following lines of code from the repo, I got an error.

    scaled = scaler.scale(loss) # Scale the loss
    scaled.backward() # Do backwards pass
    scaler.minimize(optimizer, scaled) # Update the parameters
    optimizer.clear_grad() # Set gradients to 0 again
            
Traceback (most recent call last):
  File "train.py", line 137, in <module>
    main(args)
  File "train.py", line 119, in main
    train(model=model,
  File "/data/repos/BackgroundMattingV2Paddle/core/train_bmv2.py", line 173, in train
    scaler.minimize(optimizer, scaled)
  File "/usr/local/lib/python3.8/dist-packages/paddle/amp/grad_scaler.py", line 157, in minimize
    return super(GradScaler, self).minimize(optimizer, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/amp/loss_scaler.py", line 222, in minimize
    optimize_ops, params_grads = optimizer.minimize(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/base.py", line 276, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/optimizer/optimizer.py", line 1088, in minimize
    params_grads = self.backward(
  File "/usr/local/lib/python3.8/dist-packages/paddle/optimizer/optimizer.py", line 792, in backward
    if param.stop_gradient:
AttributeError: 'dict' object has no attribute 'stop_gradient'

Seems like a bug to me? I followed the example from https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/optimizer/adam.py in lines 137-158

2) SECOND ISSUE

Because the dict does not work together with scaler.minimize, I had to take another approach I tried around a little bit, and came to the following conclusion. In the original code, I changed 

            scaled = scaler.scale(loss) # Scale the loss
            scaled.backward() # Do backwards pass
            scaler.minimize(optimizer, scaled) # Update the parameters
            optimizer.clear_grad() # Set gradients to 0 again

to 

            scaled = scaler.scale(loss)  # scale the loss
            scaled.backward()            # do backward
            scaler.step(optimizer)       # update parameters
            scaler.update()              # update the loss scaling ratio
            optimizer.clear_grad()

Which works perfectly all fine. However when I change

optimizer = paddle.optimizer.Adam(learning_rate=0.0001, parameters=model.parameters())

to

    optimizer = paddle.optimizer.Adam(parameters=[
        {'params': model.parameters(), 'learning_rate': 0.0001}
    ])

I get completely different and weird results, as if the model is not learning anything anymore. I have the feeling that the optimizer can't really handle the dictionary properly.

Thanks in advance

**Comment by 95maddycode** [comment]
fixed by adding learning rate parameter

optimizer = paddle.optimizer.Adam(learning_rate=0.1, parameters=[
    {'params': model.parameters(), 'learning_rate': 0.0001}
])
