### ISSUE TITLE
RuntimeError: The specified component was not found PPLiteSeg

### ISSUE THREAD

**Issue by liuzimo** [PaddlePaddle/PaddleSeg#2021]
Thanks for your bug report. To help us solve the issue better, please provide following information：
python setup.py install
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    import paddleseg
  File "D:\下载\PaddleSeg-develop\PaddleSeg-develop\paddleseg\__init__.py", line 15, in <module>
    from . import models, datasets, transforms
  File "D:\下载\PaddleSeg-develop\PaddleSeg-develop\paddleseg\models\__init__.py", line 15, in <module>
    from .backbones import *
  File "D:\下载\PaddleSeg-develop\PaddleSeg-develop\paddleseg\models\backbones\__init__.py", line 15, in <module>
    from .hrnet import *
  File "D:\下载\PaddleSeg-develop\PaddleSeg-develop\paddleseg\models\backbones\hrnet.py", line 22, in <module>
    from paddleseg.models import layers
  File "D:\下载\PaddleSeg-develop\PaddleSeg-develop\paddleseg\models\layers\__init__.py", line 21, in <module>
    from .tensor_fusion import UAFM_SpAtten, UAFM_SpAtten_S, UAFM_ChAtten, UAFM_ChAtten_S
  File "D:\下载\PaddleSeg-develop\PaddleSeg-develop\paddleseg\models\layers\tensor_fusion.py", line 20, in <module>
    import paddleseg.models.layers.tensor_fusion_helper as helper
AttributeError: module 'paddleseg' has no attribute 'models'

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：develop
 2. PaddlePaddle版本：PaddlePaddle 2.2.1）
 3. 操作系统信息：Windows cpu
 4. Python版本号：Python3.6

**Comment by juncaipeng** [comment]
你好，你执行的命令是什么啊？
你有执行‘pip install paddleseg’吗？ 建议先执行‘pip uninstall paddleseg’卸载paddleseg。

**Comment by liuzimo** [comment]
> 你好，请问你有执行‘pip install paddleseg’吗？ 建议先执行‘pip uninstall paddleseg’卸载paddleseg。

卸载过了 貌似是导入有问题
![image](https://user-images.githubusercontent.com/25811500/163744148-33046a15-5ff0-4e78-a867-1cbeda47b9c0.png)

**Comment by juncaipeng** [comment]
你改为  from paddleseg.models.layers import tensor_fusion_helper as helper  试下看

**Comment by liuzimo** [comment]
> 

![image](https://user-images.githubusercontent.com/25811500/163744422-36728c49-040b-4e77-a147-61ea33f3be8d.png)

**Comment by liuzimo** [comment]
![image](https://user-images.githubusercontent.com/25811500/163744456-0ec2b423-b339-40d6-905f-3a8c6931610d.png)

**Comment by juncaipeng** [comment]
PaddleSeg训练、验证、测试的命令，都需要在paddleseg的根目录下执行。  如果在PaddleSeg根目录执行，不需要pip install 了，会直接加载执行。
你现在还有问题吗？
