### ISSUE TITLE
Evaluation error

### ISSUE THREAD

**Issue by panovr** [PaddlePaddle/PaddleSeg#205]
The training and visualizing are fine, but the evaluation has some errors:

```
Traceback (most recent call last):
  File ".\pdseg\eval.py", line 179, in <module>
    main()
  File ".\pdseg\eval.py", line 175, in main
    evaluate(cfg, **args.__dict__)
  File ".\pdseg\eval.py", line 141, in evaluate
    conf_mat.calculate(pred, grts, masks)
  File "E:\ZYL\Project\PaddleSeg\pdseg\metrics.py", line 47, in calculate
    shape=(self.num_classes, self.num_classes))
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\scipy\sparse\compressed.py", line 57, in __init__
    other = self.__class__(coo_matrix(arg1, shape=shape))
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\scipy\sparse\coo.py", line 198, in __init__
    self._check()
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\scipy\sparse\coo.py", line 285, in _check
    raise ValueError('row index exceeds matrix dimensions')
ValueError: row index exceeds matrix dimensions
```

**Comment by wuyefeilin** [comment]
应该是类别数的设置跟你的实际输出类别数不一致，比如有可能你网络的预测输出包含9类，而你的类别数设置成了8.

**Comment by panovr** [comment]
我的类别数目在配置文件里面设置为2。有合适的调试方法吗？

**Comment by wuyefeilin** [comment]
PaddleSeg采用单通道的标注图片，每一种像素值代表一种类别，像素标注类别需要从0开始递增，例如0，1，2，3表示有4种类别。这时候你的类别数应为设置为4。

你跑一下数据与配置校验看是否有配置出错，https://github.com/PaddlePaddle/PaddleSeg/blob/release/v0.4.0/docs/check.md

**Comment by panovr** [comment]
确实，数据与配置校验结果有错：
```
NOT PASS label class check!
fatal error: label class is out of range [0, 1]
```

顺便问一句，这部分信息的含义：
```
1. Check train dataset...
STREAM b'IHDR' 16 13
STREAM b'tIME' 41 7
b'tIME' 41 7 (unknown)
STREAM b'IDAT' 60 3488
STREAM b'IHDR' 16 13
STREAM b'tIME' 41 7
```

**Comment by wuyefeilin** [comment]
这个是日志输出的问题，只要没有提示检查不通过就没问题哈。这个日志输出的问题我们正在解决
