### ISSUE TITLE
模型裁剪后，infer出现维度问题，eval以及vis都未出现

### ISSUE THREAD

**Issue by Diuyon** [PaddlePaddle/PaddleSeg#206]
# 再进行trian、eval、vis操作均正常后，将模型裁剪导出却出现维度不匹配的问题

---

### 错误日志：
```
I0325 17:23:17.724233  1492 analysis_predictor.cc:462] ======= optimize end =======
Traceback (most recent call last):
  File "d:/work/cut_face/paddlePredict/infer.py", line 319, in <module>
    run(gflags.FLAGS.conf, gflags.FLAGS.input_dir, gflags.FLAGS.ext)
  File "d:/work/cut_face/paddlePredict/infer.py", line 301, in run
    seg_predictor.predict(imgs)
  File "d:/work/cut_face/paddlePredict/infer.py", line 272, in predict
    output_data = self.predictor.run(input_data)[0]
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 243, in __impl__
    attrs={'axis': axis})
  File "/home/aistudio/work/PaddleSeg/pdseg/models/model_builder.py", line 152, in export_preprocess
    image = (image / 255 - mean) / std
  File "/home/aistudio/work/PaddleSeg/pdseg/models/model_builder.py", line 184, in build_model
    origin_image)
  File "pdseg/export_model.py", line 88, in export_inference_model
    infer_prog, startup_prog, phase=ModelPhase.PREDICT)
  File "pdseg/export_model.py", line 124, in main
    export_inference_model(args)
  File "pdseg/export_model.py", line 128, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: ShapeError: broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 1000, 1000, 1000] and the shape of Y = [1, 3, 1, 1]. Received [1000] in X is not equal to [3] in Y at (D:\1.7.1\paddle\paddle/fluid/operators/elementwise/elementwise_op_function.h:145)
  [operator < elementwise_sub > error]
```
---

### 调试结果：
![1(1K8XG_FIX9RTWTN 9BKQK](https://user-images.githubusercontent.com/48786733/77521271-5c061c00-6ebd-11ea-8fdc-f41f9b31a1fe.png)
----

### deploy.yaml文件
```
DEPLOY:
        USE_GPU : 0
        USE_PR : 1
        MODEL_PATH : "freeze_model"
        MODEL_FILENAME : "model"
        PARAMS_FILENAME : "params"
        EVAL_CROP_SIZE : (1000, 1000)
        MEAN : [0.5, 0.5, 0.5]
        STD : [0.5, 0.5, 0.5]
        IMAGE_TYPE : "rgb"
        NUM_CLASSES : 2
        CHANNELS : 3
        PRE_PROCESSOR : "SegPreProcessor"
        PREDICTOR_MODE : "ANALYSIS"
        BATCH_SIZE : 1
    
```

**Comment by ieee820** [comment]
我也遇到了同样的问题，正在找解决方案

**Comment by ieee820** [comment]
@Diuyon 请问您的问题解决了吗？

**Comment by ieee820** [comment]
@LutaoChu 请问大概是什么原因呢？和paddleseg版本有关吗？

**Comment by Diuyon** [comment]
@ieee820 没有解决，我直接拿未裁剪的模型来使用的，没办法，将就下

**Comment by ieee820** [comment]
@Diuyon 您指的未裁剪的模型是指vis.py和eval.py中用到的saved_model文件夹里面的吗？那些文件挺大的挺分散是吧？

**Comment by ieee820** [comment]
> @LutaoChu 请问大概是什么原因呢？和paddleseg版本有关吗？

需要的话，我可以把freeze_model和我用于测试的图片数据发给您。@LutaoChu

**Comment by ieee820** [comment]
@Diuyon @LutaoChu 我把paddlepadel1.7 降级到1.6.2, 然后把paddleseg 降级到0.3.0就运行正常了，不确定是不是版本的原因。

**Comment by Diuyon** [comment]
对，我用的就是saved_model中的文件，降级能裁剪的话，那可能是版本问题了

**Comment by LutaoChu** [comment]
看起来是导出模型那块减均值除方差的问题，我们先确认一下原因

**Comment by wuyefeilin** [comment]
你输入网络之前的图像的shape是多少，看样子是图像图像shape的问题，是（batch_size, h, w, c)吗？
![image](https://user-images.githubusercontent.com/30919197/78975356-822aed80-7b46-11ea-97f9-22cffc55f16b.png)
use_pr设置为True试一下

**Comment by ieee820** [comment]
@Diuyon @LutaoChu  刚才又测试了一下paddlepadel1.7，不用降级paddlepaddle可以的，只需要降级paddleseg

**Comment by ieee820** [comment]
> 你输入网络之前的图像的shape是多少，看样子是图像图像shape的问题，是（batch_size, h, w, c)吗？
> ![image](https://user-images.githubusercontent.com/30919197/78975356-822aed80-7b46-11ea-97f9-22cffc55f16b.png)
> use_pr设置为True试一下

试过了，此项不行

**Comment by ieee820** [comment]
> > 你输入网络之前的图像的shape是多少，看样子是图像图像shape的问题，是（batch_size, h, w, c)吗？
> > ![image](https://user-images.githubusercontent.com/30919197/78975356-822aed80-7b46-11ea-97f9-22cffc55f16b.png)
> > use_pr设置为True试一下
> 
> 试过了，此项不行

不work

**Comment by Diuyon** [comment]
@wuyefeilin 输入的size是512，应该是eval设置为1000，所以到这里就调成了1000，按道理这个[1 3 1000 1000] 应该是正确的，但是错误报告的[1 1000 1000 1000]肯定是错误的，use_pr 之前设置过，没有用

**Comment by jaffe-fly** [comment]
大佬 怎么获取的卷积名称那一段，就是PRUNE_PARAMS: '和'PRUNE_RATIOS: []这两个参数怎么设置的，save_model下面的参数文件一堆
