### ISSUE TITLE
[General Issue]Got an Error while evaluating the official given model

### ISSUE THREAD

**Issue by RD-Zhou31** [PaddlePaddle/PaddleSeg#2080]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: 2.5.0
 2. PaddlePaddle version: 2.2.2
 3. Operation system: Win10
 4. Python version: 3.6
 5. CUDA/cuDNN version: cpu version
 6. Additional context: 

2022-05-05 00:46:58 [INFO]      Loading pretrained model from https://paddleseg.bj.bcebos.com/matting/models/MobileNetV2_pretrained/model.pdparams
2022-05-05 00:46:58 [INFO]      There are 265/265 variables loaded into MobileNet.
2022-05-05 00:46:59 [INFO]      Loading pretrained model from output/best_model/model.pdiparams
Traceback (most recent call last):
  File "val.py", line 98, in <module>
    main(args)
  File "val.py", line 85, in main
    utils.load_entire_model(model, args.model_path)
  File "f:\chrome_download\paddleseg-release-2.5\paddleseg\utils\utils.py", line 39, in load_entire_model
    load_pretrained_model(model, pretrained)
  File "f:\chrome_download\paddleseg-release-2.5\paddleseg\utils\utils.py", line 87, in load_pretrained_model
    if k not in para_state_dict:
  File "C:\Users\drizz\Anaconda3\envs\cpu36\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py", line 233, in __impl__
    value=other_var, dtype=lhs_dtype)
  File "C:\Users\drizz\Anaconda3\envs\cpu36\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py", line 79, in create_scalar
    return create_tensor(value, dtype, shape=[1])
  File "<decorator-gen-132>", line 2, in create_tensor
  File "C:\Users\drizz\Anaconda3\envs\cpu36\lib\site-packages\paddle\fluid\dygraph\base.py", line 296, in __impl__
    return func(*args, **kwargs)
  File "C:\Users\drizz\Anaconda3\envs\cpu36\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py", line 74, in create_tensor
    value, 'force_cpu', False)
ValueError: (InvalidArgument) fill_constant(): argument (position 6) must be float, but got str (at C:\home\workspace\Paddle_release\paddle/fluid/pybind/op_function.h:305)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

**Comment by Tongfengyu** [comment]
+1

**Comment by wuyefeilin** [comment]
请给一下你的评估命令

**Comment by hzhao1997** [comment]
The same problem occurs when I run` python predict.py     --config configs/modnet/modnet-hrnet_w18.yml     --model_path model_path/pp-matting-hrnet_w18-human_1024/model.pdiparams     --image_path /home/zhao/PPM-100/val/fg/     --save_dir ./output/results `.

**Comment by YangYangTaoTao** [comment]
that's terrible!

**Comment by wuyefeilin** [comment]
> The same problem occurs when I run`python predict.py --config configs/modnet/modnet-hrnet_w18.yml --model_path model_path/pp-matting-hrnet_w18-human_1024/model.pdiparams --image_path /home/zhao/PPM-100/val/fg/ --save_dir ./output/results`.

模型和配置文件不对应，配置是modnet，请下载modnet-hrnet_w18的模型
