### ISSUE TITLE
[Bug]pp_liteseg导出错误

### ISSUE THREAD

**Issue by fanweiya** [PaddlePaddle/PaddleSeg#2081]
报错
```
python export.py        --config pp_liteseg_stdc1_leiqiguan_huizhong_702x1032.yml        --model_path pp_liteseg_stdc1_leiqiguan_huizhong_702x1032/iter_10000/model.pdparams
W0505 14:06:22.168138 63739 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.0
W0505 14:06:22.170897 63739 device_context.cc:422] device: 0, cuDNN Version: 8.2.
2022-05-05 14:06:25 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet1.tar.gz
2022-05-05 14:06:25 [INFO]	There are 295/295 variables loaded into STDCNet.
2022-05-05 14:06:25 [INFO]	Loaded trained params of model successfully.
/data/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  return (isinstance(seq, collections.Sequence) and
Traceback (most recent call last):
  File "export.py", line 144, in <module>
    main(args)
  File "export.py", line 123, in main
    paddle.jit.save(new_net, save_path)
  File "<decorator-gen-67>", line 2, in save
  File "/data/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/data/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/data/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 719, in save
    inner_input_spec)
  File "/data/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/data/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/data/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/data/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-65>", line 2, in from_func_spec
  File "/data/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/data/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
    return func(*args, **kwargs)
  File "/data/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 658, in from_func_spec
    error_data.raise_new_exception()
  File "/data/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 192, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "export.py", line 74, in forward (* user code *)
	outs = self.net(x)
    File "/data/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "/data/PaddleSeg-2.5/paddleseg/models/pp_liteseg.py", line 107, in forward (* user code *)
	feats_backbone = self.backbone(x)  # [x2, x4, x8, x16, x32]
    File "/data/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "/data/PaddleSeg-2.5/paddleseg/models/backbones/stdcnet.py", line 90, in forward (* user code *)
	feat8 = self.x8(feat4)
    File "/data/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_call_func.py", line 167, in convert_call
	if is_builtin(func) or is_unsupported(func):
    File "/data/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_call_func.py", line 91, in is_unsupported
	func_in_dict = any(func_in_dict)
    ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```
config
```
batch_size: 2
iters: 10000
loss:
  coef:
  - 1
  - 1
  - 1
  types:
  - min_kept: 250000
    type: OhemCrossEntropyLoss
  - min_kept: 250000
    type: OhemCrossEntropyLoss
  - min_kept: 250000
    type: OhemCrossEntropyLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 0.01
  power: 0.9
  type: PolynomialDecay
  warmup_iters: 200
  warmup_start_lr: 1.0e-05
model:
  arm_out_chs:
  - 32
  - 64
  - 128
  backbone:
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet1.tar.gz
    type: STDC1
  seg_head_inter_chs:
  - 32
  - 64
  - 64
  type: PPLiteSeg
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 0.0005
train_dataset:
  dataset_root: data/leiqiguan_huizhong
  mode: train
  num_classes: 2
  train_path: data/leiqiguan_huizhong/train_list.txt
  transforms:
  - max_scale_factor: 2.5
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 1032
    - 702
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.5
    contrast_range: 0.5
    saturation_range: 0.5
    type: RandomDistort
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: data/leiqiguan_huizhong
  mode: val
  num_classes: 2
  transforms:
  - type: Normalize
  type: Dataset
  val_path: data/leiqiguan_huizhong/val_list.txt
```

**Comment by fanweiya** [comment]
paddlpaddle版本问题，最新的paddlpaddle没有问题
