### ISSUE TITLE
报错：label should not out of bound, but gotTensor

### ISSUE THREAD

**Issue by LGadore** [PaddlePaddle/PaddleSeg#2084]
在安装后，按照步骤[全流程跑通PaddleSeg](https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/docs/whole_process_cn.md)，但是老是运行出错，就是下面这些，折腾了一天实在是搞不定。希望有大佬给解释一下，感谢！！！
"""
Traceback (most recent call last):
  File "train.py", line 230, in <module>
    main(args)
  File "train.py", line 206, in main
    train(
  File "F:\PaddleSeg\PaddleSeg-release-2.5\paddleseg\core\train.py", line 205, in train
    loss_list = loss_computation(
  File "F:\PaddleSeg\PaddleSeg-release-2.5\paddleseg\core\train.py", line 53, in loss_computation
    loss_list.append(coef_i * loss_i(logits, labels))
  File "D:\Anaconda\envs\paddleseg\lib\site-packages\paddle\fluid\dygraph\layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda\envs\paddleseg\lib\site-packages\paddle\fluid\dygraph\layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "F:\PaddleSeg\PaddleSeg-release-2.5\paddleseg\models\losses\cross_entropy_loss.py", line 81, in forward
    loss = F.cross_entropy(
  File "D:\Anaconda\envs\paddleseg\lib\site-packages\paddle\nn\functional\loss.py", line 1658, in cross_entropy
    raise ValueError("label should not out of bound, but got{}".
ValueError: label should not out of bound, but gotTensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [4398046511104])
"""

**Comment by ly706** [comment]
请问解决了吗？我也遇到了

**Comment by LGadore** [comment]
> 请问解决了吗？我也遇到了

没有，后来用cpu版本可以跑起来

**Comment by juncaipeng** [comment]
请问你们环境配置是什么？ 
* 操作系统
* python
* PaddlePaddle版本
* PaddleSeg版本

**Comment by LGadore** [comment]
> 请问你们环境配置是什么？
> 
> * 操作系统
> * python
> * PaddlePaddle版本
> * PaddleSeg版本

- win10
- python3.8
- paddlepaddle-gpu   2.2.2.post110
- paddleseg   2.5.0

**Comment by jiguanglu** [comment]
@LGadore @ly706 @juncaipeng  请问解决了吗？是不是标注数据的时候，分割的物体正好在边界上？

**Comment by juncaipeng** [comment]
建议升级为paddle 2.3.

```
raise ValueError("label should not out of bound, but got{}".
ValueError: label should not out of bound, but gotTensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
[4398046511104])
```
这个错误信息是说label标注中存在数值为4398046511104，这明显是不对的。

**Comment by wayneck** [comment]
`   ....
  File "/home/project/baidu/PaddleSeg/paddleseg/models/losses/cross_entropy_loss.py", line 85, in forward
    loss = F.cross_entropy(
  File "/home/.local/lib/python3.8/site-packages/paddle/nn/functional/loss.py", line 1661, in cross_entropy
    raise ValueError("label should not out of bound, but got{}".
ValueError: label should not out of bound, but gotTensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [700])`

MY annotations file is gray png file, got the same error.   
It look like paddle read annotations file error.

**Comment by juncaipeng** [comment]
> ` .... File "/home/project/baidu/PaddleSeg/paddleseg/models/losses/cross_entropy_loss.py", line 85, in forward loss = F.cross_entropy( File "/home/.local/lib/python3.8/site-packages/paddle/nn/functional/loss.py", line 1661, in cross_entropy raise ValueError("label should not out of bound, but got{}". ValueError: label should not out of bound, but gotTensor(shape=[1], dtype=int64, place=CUDAPlace(0), stop_gradient=True, [700])`
> 
> MY annotations file is gray png file, got the same error. It look like paddle read annotations file error.

The max value of the label is 700, could you send the annotations file to me for checking the problem?
