### ISSUE TITLE
TypeError: dtype: int32 is not supported.  Process finished with exit code 1[Bug]

### ISSUE THREAD

**Issue by baoqicha** [PaddlePaddle/PaddleSeg#2091]
2022-05-05 15:51:33 [INFO]	Start evaluating (total_samples: 5, total_iters: 5)...
Traceback (most recent call last):
  File "E:\Anaconda3\lib\site-packages\SimpleITK\extra.py", line 184, in _get_sitk_pixelid
    return _np_sitk[numpy_array_type.dtype]
KeyError: dtype('int32')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/medicalseg3D/PaddleSeg-release-2.5/contrib/MedicalSeg/train.py", line 196, in <module>
    main(args)
  File "D:/medicalseg3D/PaddleSeg-release-2.5/contrib/MedicalSeg/train.py", line 191, in main
    to_static_training=cfg.to_static_training)
  File "D:\medicalseg3D\PaddleSeg-release-2.5\contrib\MedicalSeg\medicalseg\core\train.py", line 226, in train
    save_dir=save_dir)
  File "D:\medicalseg3D\PaddleSeg-release-2.5\contrib\MedicalSeg\medicalseg\core\val.py", line 155, in evaluate
    'format': "xyz"
  File "D:\medicalseg3D\PaddleSeg-release-2.5\contrib\MedicalSeg\medicalseg\utils\utils.py", line 244, in save_array
    img_itk_new = sitk.GetImageFromArray(val)
  File "E:\Anaconda3\lib\site-packages\SimpleITK\extra.py", line 292, in GetImageFromArray
    id = _get_sitk_pixelid(z)
  File "E:\Anaconda3\lib\site-packages\SimpleITK\extra.py", line 189, in _get_sitk_pixelid
    raise TypeError('dtype: {0} is not supported.'.format(numpy_array_type.dtype))
TypeError: dtype: int32 is not supported.

Process finished with exit code 1

**Comment by baoqicha** [comment]
将\medicalseg\core\val.py文件中save_array函数注释掉即可

 # if iter < 5:
            #     save_array(
            #         save_path=os.path.join(
            #             save_dir,
            #             str(iter)),
            #         save_content={
            #             'pred': pred.numpy(),
            #             'label': label.numpy(),
            #             'img': im.numpy()
            #         },
            #         form=('npy', 'nii.gz'),
            #         image_infor={
            #             "spacing": image_json["spacing_resample"],
            #             'direction': image_json["direction"],
            #             "origin": image_json["origin"],
            #             'format': "xyz"
            #         })

**Comment by shiyutang** [comment]
it seems there is problem with saving array in windows, we will fix it soon
