### ISSUE TITLE
自定义数据集在进行可视化时报错 The verification dataset is not specified in the configuration

### ISSUE THREAD

**Issue by SoUHoo** [PaddlePaddle/PaddleSeg#2092]
1. PaddleSeg version:  PaddleSeg release/2.4
 2. PaddlePaddle version: PaddlePaddle 2.2.0
 3. Operation system: Linux
 4. Python version: Python3.7
 5. CUDA/cuDNN version: CUDA10.2/cuDNN 7.6.5
 6. Additional context: 
 python predict.py --config out_export_bisev2_lapb/deploy.yaml \
--model_path out_bisev2_lapb_camvid_2/best_model/model.pdparams \
--image_path 0006R0_f00930.png --save_dir output_bisev2_lapb/result
Traceback (most recent call last):
  File "predict.py", line 175, in <module>
    main(args)
  File "predict.py", line 147, in main
    'The verification dataset is not specified in the configuration file.'
RuntimeError: The verification dataset is not specified in the configuration file.

**Comment by SoUHoo** [comment]
另外在部署推理数据集时报错
python deploy/python/infer_dataset.py --config out_export_bisev2_lapb/deploy.yaml \
--dataset_type Dataset --dataset_path /home/work/data/camvid
2022-05-08 15:56:51 [INFO]      Use GPU
Traceback (most recent call last):
  File "deploy/python/infer_dataset.py", line 324, in <module>
    main(args)
  File "deploy/python/infer_dataset.py", line 297, in main
    predictor.run_dataset()
  File "deploy/python/infer_dataset.py", line 230, in run_dataset
    dataset = get_dataset(self.args)
  File "deploy/python/infer_dataset.py", line 168, in get_dataset
    dataset = comp[args.dataset_type](**kwargs)
TypeError: __init__() missing 1 required positional argument: 'num_classes'

**Comment by juncaipeng** [comment]
第一个问题，请升级到使用PaddleSeg 2.5版本。
第二个问题，这个脚本此前没有支持Dataset类数据集，我们会尽快修复改问题，请使用infer.py脚本测试部署。
