### ISSUE TITLE
我在运行tools/analyze_model.py 时遇到如下报错，ddrnet39是我个人添加的网络，train时没有问题。

### ISSUE THREAD

**Issue by Murphy-MML** [PaddlePaddle/PaddleSeg#2154]
2022-05-25 07:32:20 [INFO]      config:configs/ddrnet/ddrnet39_cityscapes_1024x1024_120k.yml
2022-05-25 07:32:20 [INFO]      input_size:
2022-05-25 07:32:20 [INFO]      [1, 3, 1024, 1024]
2022-05-25 07:32:20 [INFO]
------------Environment Information-------------
platform: Linux-5.4.0-90-generic-x86_64-with-Ubuntu-18.04-bionic
Python: 3.7.13 (default, Apr 24 2022, 01:04:09) [GCC 7.5.0]
Paddle compiled with cuda: True
NVCC: Build cuda_11.2.r11.2/compiler.29558016_0
cudnn: 8.1
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce']
GCC: gcc (GCC) 8.2.0
PaddleSeg: 2.5.0
PaddlePaddle: 2.3.0
OpenCV: 4.5.5
------------------------------------------------
Traceback (most recent call last):
  File "tools/analyze_model.py", line 161, in <module>
    analyze(args)
  File "tools/analyze_model.py", line 150, in analyze
    _dynamic_flops(cfg.model, inputs, custom_ops=custom_ops, print_detail=True)
  File "/usr/local/lib/python3.7/dist-packages/paddleseg/cvlibs/config.py", line 338, in model
    self._model = self._load_object(model_cfg)
  File "/usr/local/lib/python3.7/dist-packages/paddleseg/cvlibs/config.py", line 391, in _load_object
    component = self._load_component(cfg.pop('type'))
  File "/usr/local/lib/python3.7/dist-packages/paddleseg/cvlibs/config.py", line 384, in _load_component
    'The specified component was not found {}.'.format(com_name))
RuntimeError: The specified component was not found DDRNet_39.

**Comment by juncaipeng** [comment]
从log来看，是该模型没有注册，你可以在tools/analyze_model.py中import一下新增模型的文件。
