### ISSUE TITLE
IC net  eval报错什么原因

### ISSUE THREAD

**Issue by jaffe-fly** [PaddlePaddle/PaddleSeg#217]
!!! The default number of CPU_NUM=1.
#Device count: 1
load test model: ./saved_model/icnet_optic/best_model
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:782: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "PaddleSeg/pdseg/eval.py", line 179, in <module>
    main()
  File "PaddleSeg/pdseg/eval.py", line 175, in main
    evaluate(cfg, **args.__dict__)
  File "PaddleSeg/pdseg/eval.py", line 136, in evaluate
    test_prog, fetch_list=fetch_list, return_numpy=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 783, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 778, in run
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 831, in _run_impl
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 905, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string>(std::string&&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
2   paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, paddle::platform::Place const&) const
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
5   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
6   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
7   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2525, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 6884, in image_resize
    attrs=attrs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 7374, in resize_nearest
    data_format=data_format)
  File "/home/aistudio/PaddleSeg/pdseg/loss.py", line 118, in multi_softmax_with_loss
    label = fluid.layers.resize_nearest(label, logit.shape[2:])
  File "/home/aistudio/PaddleSeg/pdseg/models/model_builder.py", line 230, in build_model
    multi_softmax_with_loss(logits, label, mask, class_num, weight))
  File "PaddleSeg/pdseg/eval.py", line 96, in evaluate
    test_prog, startup_prog, phase=ModelPhase.EVAL)
  File "PaddleSeg/pdseg/eval.py", line 175, in main
    evaluate(cfg, **args.__dict__)
  File "PaddleSeg/pdseg/eval.py", line 179, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: op nearest_interp does not have kernel for data_type[int]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN] at (/paddle/paddle/fluid/framework/operator.cc:1065)
  [operator < nearest_interp > error]

**Comment by LielinJiang** [comment]
抱歉，icnet暂时不支持在cpu上训练和评估。
![image](https://user-images.githubusercontent.com/50691816/79193038-6bdda400-7e5c-11ea-8c5c-f7b45e51a714.png)

**Comment by jaffe-fly** [comment]
上面就是在GPU上做的评估，不清楚为什么报错开始为什么还是CPU_NUM

**Comment by jaffe-fly** [comment]
在命令中加了一个 --use_gpu    重新运行还是报错的

----------------------
Error Message Summary:
----------------------
Error: Cannot open file saved_model/icnet_optic/best_model/st4_1_branch_layer_1_2_conv2_bn_variance for load op at (/paddle/paddle/fluid/operators/load_op.h:38)
  [operator < load > error]

**Comment by LielinJiang** [comment]
这个一般是路径问题，检测一下这个路径是否存在。icnet中好像没有这个参数，你自己修改了网络？

**Comment by jaffe-fly** [comment]
问题解决 还是命令行参数错误，TEST.TEST_MODEL后面的地址和hrnet_optic.yaml中的地址不一样导致的
