### ISSUE TITLE
[General Issue] installation error

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#2208]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g.PaddleSeg release/2.5)
2. PaddlePaddle version: (e.g.  paddlepaddle-gpu==2.3.0.post112)
3. Operation system: (Windows)
 4. Python version: (e.g. Python3..7 anaconda)
 5. CUDA/cuDNN version: (e.g. CUDA11.2/cuDNN 8.2.1)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg version: (please specify the branch as well，e.g.PaddleSeg release/2.5)
 2. PaddlePaddle version: (e.g.  paddlepaddle-gpu==2.3.0.post112)
 3. Operation system: (Windows)
 4. Python version: (e.g. Python3..7 anaconda)
 5. CUDA/cuDNN version: (e.g. CUDA11.2/cuDNN 8.2.1)
 6. 其他内容: （增加其他与问题相关的内容）
```
pip install -r requirements.txt
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pyyaml>=5.1 in d:\anaconda3\envs\paddleseg\lib\site-packages (from -r requirements.txt (line 1)) (6.0)
Requirement already satisfied: visualdl>=2.0.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from -r requirements.txt (line 2)) (2.2.3)
Requirement already satisfied: opencv-python in d:\anaconda3\envs\paddleseg\lib\site-packages (from -r requirements.txt (line 3)) (4.6.0.66)
Requirement already satisfied: tqdm in d:\anaconda3\envs\paddleseg\lib\site-packages (from -r requirements.txt (line 4)) (4.64.0)
Requirement already satisfied: filelock in d:\anaconda3\envs\paddleseg\lib\site-packages (from -r requirements.txt (line 5)) (3.7.1)
Requirement already satisfied: scipy in d:\anaconda3\envs\paddleseg\lib\site-packages (from -r requirements.txt (line 6)) (1.7.3)
Requirement already satisfied: prettytable in d:\anaconda3\envs\paddleseg\lib\site-packages (from -r requirements.txt (line 7)) (3.3.0)
Requirement already satisfied: sklearn in d:\anaconda3\envs\paddleseg\lib\site-packages (from -r requirements.txt (line 8)) (0.0)
Requirement already satisfied: Pillow>=7.0.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from visualdl>=2.0.0->-r requirements.txt (line 2)) (9.1.1)
Requirement already satisfied: flake8>=3.7.9 in d:\anaconda3\envs\paddleseg\lib\site-packages (from visualdl>=2.0.0->-r requirements.txt (line 2)) (4.0.1)
Requirement already satisfied: flask>=1.1.1 in d:\anaconda3\envs\paddleseg\lib\site-packages (from visualdl>=2.0.0->-r requirements.txt (line 2)) (2.1.2)
Requirement already satisfied: requests in d:\anaconda3\envs\paddleseg\lib\site-packages (from visualdl>=2.0.0->-r requirements.txt (line 2)) (2.28.0)
Requirement already satisfied: pre-commit in d:\anaconda3\envs\paddleseg\lib\site-packages (from visualdl>=2.0.0->-r requirements.txt (line 2)) (2.19.0)
Requirement already satisfied: six>=1.14.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from visualdl>=2.0.0->-r requirements.txt (line 2)) (1.16.0)
Requirement already satisfied: bce-python-sdk in d:\anaconda3\envs\paddleseg\lib\site-packages (from visualdl>=2.0.0->-r requirements.txt (line 2)) (0.8.73)
Requirement already satisfied: pandas in d:\anaconda3\envs\paddleseg\lib\site-packages (from visualdl>=2.0.0->-r requirements.txt (line 2)) (1.3.5)
Requirement already satisfied: matplotlib in d:\anaconda3\envs\paddleseg\lib\site-packages (from visualdl>=2.0.0->-r requirements.txt (line 2)) (3.5.2)
Requirement already satisfied: Flask-Babel>=1.0.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from visualdl>=2.0.0->-r requirements.txt (line 2)) (2.0.0)
Requirement already satisfied: protobuf>=3.11.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from visualdl>=2.0.0->-r requirements.txt (line 2)) (4.21.1)
Requirement already satisfied: shellcheck-py in d:\anaconda3\envs\paddleseg\lib\site-packages (from visualdl>=2.0.0->-r requirements.txt (line 2)) (0.8.0.4)
Requirement already satisfied: numpy in d:\anaconda3\envs\paddleseg\lib\site-packages (from visualdl>=2.0.0->-r requirements.txt (line 2)) (1.21.6)
Requirement already satisfied: colorama in d:\anaconda3\envs\paddleseg\lib\site-packages (from tqdm->-r requirements.txt (line 4)) (0.4.4)
Requirement already satisfied: wcwidth in d:\anaconda3\envs\paddleseg\lib\site-packages (from prettytable->-r requirements.txt (line 7)) (0.2.5)
Requirement already satisfied: importlib-metadata in d:\anaconda3\envs\paddleseg\lib\site-packages (from prettytable->-r requirements.txt (line 7)) (4.2.0)
Requirement already satisfied: scikit-learn in d:\anaconda3\envs\paddleseg\lib\site-packages (from sklearn->-r requirements.txt (line 8)) (1.0.2)
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from flake8>=3.7.9->visualdl>=2.0.0->-r requirements.txt (line 2)) (0.6.1)
Requirement already satisfied: pycodestyle<2.9.0,>=2.8.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from flake8>=3.7.9->visualdl>=2.0.0->-r requirements.txt (line 2)) (2.8.0)
Requirement already satisfied: pyflakes<2.5.0,>=2.4.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from flake8>=3.7.9->visualdl>=2.0.0->-r requirements.txt (line 2)) (2.4.0)
Requirement already satisfied: Jinja2>=3.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from flask>=1.1.1->visualdl>=2.0.0->-r requirements.txt (line 2)) (3.1.2)
Requirement already satisfied: itsdangerous>=2.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from flask>=1.1.1->visualdl>=2.0.0->-r requirements.txt (line 2)) (2.1.2)
Requirement already satisfied: click>=8.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from flask>=1.1.1->visualdl>=2.0.0->-r requirements.txt (line 2)) (8.1.3)
Requirement already satisfied: Werkzeug>=2.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from flask>=1.1.1->visualdl>=2.0.0->-r requirements.txt (line 2)) (2.1.2)
Requirement already satisfied: pytz in d:\anaconda3\envs\paddleseg\lib\site-packages (from Flask-Babel>=1.0.0->visualdl>=2.0.0->-r requirements.txt (line 2)) (2022.1)
Requirement already satisfied: Babel>=2.3 in d:\anaconda3\envs\paddleseg\lib\site-packages (from Flask-Babel>=1.0.0->visualdl>=2.0.0->-r requirements.txt (line 2)) (2.10.1)
Requirement already satisfied: zipp>=0.5 in d:\anaconda3\envs\paddleseg\lib\site-packages (from importlib-metadata->prettytable->-r requirements.txt (line 7)) (3.8.0)
Requirement already satisfied: typing-extensions>=3.6.4 in d:\anaconda3\envs\paddleseg\lib\site-packages (from importlib-metadata->prettytable->-r requirements.txt (line 7)) (4.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from Jinja2>=3.0->flask>=1.1.1->visualdl>=2.0.0->-r requirements.txt (line 2)) (2.1.1)
Requirement already satisfied: pycryptodome>=3.8.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from bce-python-sdk->visualdl>=2.0.0->-r requirements.txt (line 2)) (3.14.1)
Requirement already satisfied: future>=0.6.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from bce-python-sdk->visualdl>=2.0.0->-r requirements.txt (line 2)) (0.18.2)
Requirement already satisfied: kiwisolver>=1.0.1 in d:\anaconda3\envs\paddleseg\lib\site-packages (from matplotlib->visualdl>=2.0.0->-r requirements.txt (line 2)) (1.4.2)
Requirement already satisfied: cycler>=0.10 in d:\anaconda3\envs\paddleseg\lib\site-packages (from matplotlib->visualdl>=2.0.0->-r requirements.txt (line 2)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from matplotlib->visualdl>=2.0.0->-r requirements.txt (line 2)) (4.33.3)
Requirement already satisfied: pyparsing>=2.2.1 in d:\anaconda3\envs\paddleseg\lib\site-packages (from matplotlib->visualdl>=2.0.0->-r requirements.txt (line 2)) (3.0.9)
Requirement already satisfied: packaging>=20.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from matplotlib->visualdl>=2.0.0->-r requirements.txt (line 2)) (21.3)
Requirement already satisfied: python-dateutil>=2.7 in d:\anaconda3\envs\paddleseg\lib\site-packages (from matplotlib->visualdl>=2.0.0->-r requirements.txt (line 2)) (2.8.2)
Requirement already satisfied: cfgv>=2.0.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from pre-commit->visualdl>=2.0.0->-r requirements.txt (line 2)) (3.3.1)
Requirement already satisfied: virtualenv>=20.0.8 in d:\anaconda3\envs\paddleseg\lib\site-packages (from pre-commit->visualdl>=2.0.0->-r requirements.txt (line 2)) (20.14.1)
Requirement already satisfied: identify>=1.0.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from pre-commit->visualdl>=2.0.0->-r requirements.txt (line 2)) (2.5.1)
Requirement already satisfied: nodeenv>=0.11.1 in d:\anaconda3\envs\paddleseg\lib\site-packages (from pre-commit->visualdl>=2.0.0->-r requirements.txt (line 2)) (1.6.0)
Requirement already satisfied: toml in d:\anaconda3\envs\paddleseg\lib\site-packages (from pre-commit->visualdl>=2.0.0->-r requirements.txt (line 2)) (0.10.2)
Requirement already satisfied: distlib<1,>=0.3.1 in d:\anaconda3\envs\paddleseg\lib\site-packages (from virtualenv>=20.0.8->pre-commit->visualdl>=2.0.0->-r requirements.txt (line 2)) (0.3.4)
Requirement already satisfied: platformdirs<3,>=2 in d:\anaconda3\envs\paddleseg\lib\site-packages (from virtualenv>=20.0.8->pre-commit->visualdl>=2.0.0->-r requirements.txt (line 2)) (2.5.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from requests->visualdl>=2.0.0->-r requirements.txt (line 2)) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\anaconda3\envs\paddleseg\lib\site-packages (from requests->visualdl>=2.0.0->-r requirements.txt (line 2)) (1.26.9)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda3\envs\paddleseg\lib\site-packages (from requests->visualdl>=2.0.0->-r requirements.txt (line 2)) (2022.5.18.1)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda3\envs\paddleseg\lib\site-packages (from requests->visualdl>=2.0.0->-r requirements.txt (line 2)) (3.3)
Requirement already satisfied: joblib>=0.11 in d:\anaconda3\envs\paddleseg\lib\site-packages (from scikit-learn->sklearn->-r requirements.txt (line 8)) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in d:\anaconda3\envs\paddleseg\lib\site-packages (from scikit-learn->sklearn->-r requirements.txt (line 8)) (3.1.0)
(PaddleSeg) PS D:\0SDXX\PaddleSeg> python setup.py install
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    import paddleseg
  File "D:\0SDXX\PaddleSeg\paddleseg\__init__.py", line 15, in <module>
    from . import models, datasets, transforms
  File "D:\0SDXX\PaddleSeg\paddleseg\models\__init__.py", line 15, in <module>
    from .backbones import *
  File "D:\0SDXX\PaddleSeg\paddleseg\models\backbones\__init__.py", line 15, in <module>
    from .hrnet import *
  File "D:\0SDXX\PaddleSeg\paddleseg\models\backbones\hrnet.py", line 17, in <module>
    import paddle
  File "D:\anaconda3\envs\PaddleSeg\lib\site-packages\paddle\__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "D:\anaconda3\envs\PaddleSeg\lib\site-packages\paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "D:\anaconda3\envs\PaddleSeg\lib\site-packages\paddle\framework\random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "D:\anaconda3\envs\PaddleSeg\lib\site-packages\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "D:\anaconda3\envs\PaddleSeg\lib\site-packages\paddle\fluid\framework.py", line 35, in <module>
    from .proto import framework_pb2
  File "D:\anaconda3\envs\PaddleSeg\lib\site-packages\paddle\fluid\proto\framework_pb2.py", line 36, in <module>
    type=None),
  File "D:\anaconda3\envs\PaddleSeg\lib\site-packages\google\protobuf\descriptor.py", line 755, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

```

1.Downgrade the protobuf package to 3.20.x or lower，
2.Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

**Comment by juncaipeng** [comment]
You can check the version of protobuf and  reinstall the required protobuf.

**Comment by kushan-gunasekera** [comment]
For anyone who is looking for a proper solution,

answer:- [https://stackoverflow.com/a/72493690/6194097](https://stackoverflow.com/a/72493690/6194097)
