### ISSUE TITLE
[General Issue]eiseg,self.input_handle_2 = self.net.get_input_handle(input_names[1]),eiseg 调用PaddleX 导出的模型

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#2209]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g.PaddleSeg release/2.5)
2. PaddlePaddle version: (e.g.  paddlepaddle-gpu==2.3.0.post112)
3. Operation system: (Windows)
 4. Python version: (e.g. Python3..7 anaconda)
 5. CUDA/cuDNN version: (e.g. CUDA11.2/cuDNN 8.2.1)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg version: (please specify the branch as well，e.g.PaddleSeg release/2.5)
 2. PaddlePaddle version: (e.g.  paddlepaddle-gpu==2.3.0.post112)
 3. Operation system: (Windows)
 4. Python version: (e.g. Python3..7 anaconda)
 5. CUDA/cuDNN version: (e.g. CUDA11.2/cuDNN 8.2.1)
 6. 其他内容: （增加其他与问题相关的内容）

```

python -m eiseg
I0610 23:58:11.551416 11984 analysis_predictor.cc:937] MKLDNN is enabled
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [mkldnn_placement_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [layer_norm_fuse_pass]e[0m
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
e[32m--- Running IR pass [attention_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [seqconv_eltadd_relu_fuse_pass]e[0m
e[32m--- Running IR pass [seqpool_cvm_concat_fuse_pass]e[0m
e[32m--- Running IR pass [mul_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [fc_gru_fuse_pass]e[0m
e[37m---    fused 0 pairs of fc gru patternse[0m
e[32m--- Running IR pass [mul_gru_fuse_pass]e[0m
e[32m--- Running IR pass [seq_concat_fc_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [matmul_v2_scale_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]e[0m
e[32m--- Running IR pass [matmul_scale_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [repeated_fc_relu_fuse_pass]e[0m
e[32m--- Running IR pass [squared_mat_sub_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0610 23:58:13.123603 11984 fuse_pass_base.cc:57] ---  detected 305 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
I0610 23:58:13.217900 11984 fuse_pass_base.cc:57] ---  detected 1 subgraphs
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[32m--- Running IR pass [depthwise_conv_mkldnn_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bias_mkldnn_fuse_pass]e[0m
I0610 23:58:13.495914 11984 fuse_pass_base.cc:57] ---  detected 2 subgraphs
e[32m--- Running IR pass [conv_transpose_bias_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_mkldnn_fuse_pass]e[0m
e[37m---    Fused 1 projection conv (as y) + elementwise_add patternse[0m
e[37m---    Fused 107 conv (as x) + elementwise_add patternse[0m
e[37m---    Fused 0 conv (as y) + elementwise_add patternse[0m
I0610 23:58:31.357085 11984 fuse_pass_base.cc:57] ---  detected 108 subgraphs
e[32m--- Running IR pass [conv_concat_relu_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_relu_mkldnn_fuse_pass]e[0m
I0610 23:58:31.891326 11984 fuse_pass_base.cc:57] ---  detected 243 subgraphs
e[32m--- Running IR pass [conv_leaky_relu_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_relu6_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_swish_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_hard_swish_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_mish_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_hard_sigmoid_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_gelu_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [scale_matmul_fuse_pass]e[0m
e[37m---    fused 0 scale with matmule[0m
e[32m--- Running IR pass [reshape_transpose_matmul_mkldnn_fuse_pass]e[0m
e[37m---    Fused 0 ReshapeTransposeMatmul patterns for matmul Ope[0m
e[37m---    Fused 0 ReshapeTransposeMatmul patterns for matmul Op with transpose's xshapee[0m
e[37m---    Fused 0 ReshapeTransposeMatmul patterns for matmul Op with reshape's xshapee[0m
e[37m---    Fused 0 ReshapeTransposeMatmul patterns for matmul Op with reshape's xshape with transpose's xshapee[0m
e[32m--- Running IR pass [reshape_transpose_matmul_v2_mkldnn_fuse_pass]e[0m
e[37m---    Fused 0 ReshapeTransposeMatmul patterns for matmul_v2 Ope[0m
e[37m---    Fused 0 ReshapeTransposeMatmul patterns for matmul_v2 Op with transpose's xshapee[0m
e[37m---    Fused 0 ReshapeTransposeMatmul patterns for matmul_v2 Op with reshape's xshapee[0m
e[37m---    Fused 0 ReshapeTransposeMatmul patterns for matmul_v2 Op with reshape's xshape with transpose's xshapee[0m
e[32m--- Running IR pass [matmul_transpose_reshape_fuse_pass]e[0m
e[37m---    Fused 0 MatmulTransposeReshape patterns for matmul Ope[0m
e[32m--- Running IR pass [matmul_v2_transpose_reshape_fuse_pass]e[0m
e[37m---    Fused 0 MatmulTransposeReshape patterns for matmul_v2 Ope[0m
e[32m--- Running IR pass [batch_norm_act_fuse_pass]e[0m
e[37m---    fused 0 batch norm with relu activatione[0m
e[32m--- Running IR pass [softplus_activation_mkldnn_fuse_pass]e[0m
e[37m---    fused 0 softplus with relu activatione[0m
e[37m---    fused 0 softplus with tanh activatione[0m
e[37m---    fused 0 softplus with leaky_relu activatione[0m
e[37m---    fused 0 softplus with swish activatione[0m
e[37m---    fused 0 softplus with hardswish activatione[0m
e[37m---    fused 0 softplus with sqrt activatione[0m
e[37m---    fused 0 softplus with abs activatione[0m
e[37m---    fused 0 softplus with clip activatione[0m
e[37m---    fused 0 softplus with gelu activatione[0m
e[37m---    fused 0 softplus with relu6 activatione[0m
e[37m---    fused 0 softplus with sigmoid activatione[0m
e[32m--- Running IR pass [elt_act_mkldnn_fuse_pass]e[0m
I0610 23:58:33.080482 11984 fuse_pass_base.cc:57] ---  detected 26 subgraphs
e[37m---    fused 26 elementwise_add with relu activatione[0m
e[37m---    fused 0 elementwise_add with tanh activatione[0m
e[37m---    fused 0 elementwise_add with leaky_relu activatione[0m
e[37m---    fused 0 elementwise_add with swish activatione[0m
e[37m---    fused 0 elementwise_add with hardswish activatione[0m
e[37m---    fused 0 elementwise_add with sqrt activatione[0m
e[37m---    fused 0 elementwise_add with abs activatione[0m
e[37m---    fused 0 elementwise_add with clip activatione[0m
e[37m---    fused 0 elementwise_add with gelu activatione[0m
e[37m---    fused 0 elementwise_add with relu6 activatione[0m
e[37m---    fused 0 elementwise_add with sigmoid activatione[0m
e[37m---    fused 0 elementwise_sub with relu activatione[0m
e[37m---    fused 0 elementwise_sub with tanh activatione[0m
e[37m---    fused 0 elementwise_sub with leaky_relu activatione[0m
e[37m---    fused 0 elementwise_sub with swish activatione[0m
e[37m---    fused 0 elementwise_sub with hardswish activatione[0m
e[37m---    fused 0 elementwise_sub with sqrt activatione[0m
e[37m---    fused 0 elementwise_sub with abs activatione[0m
e[37m---    fused 0 elementwise_sub with clip activatione[0m
e[37m---    fused 0 elementwise_sub with gelu activatione[0m
e[37m---    fused 0 elementwise_sub with relu6 activatione[0m
e[37m---    fused 0 elementwise_sub with sigmoid activatione[0m
e[37m---    fused 0 elementwise_mul with relu activatione[0m
e[37m---    fused 0 elementwise_mul with tanh activatione[0m
e[37m---    fused 0 elementwise_mul with leaky_relu activatione[0m
e[37m---    fused 0 elementwise_mul with swish activatione[0m
e[37m---    fused 0 elementwise_mul with hardswish activatione[0m
e[37m---    fused 0 elementwise_mul with sqrt activatione[0m
e[37m---    fused 0 elementwise_mul with abs activatione[0m
e[37m---    fused 0 elementwise_mul with clip activatione[0m
e[37m---    fused 0 elementwise_mul with gelu activatione[0m
e[37m---    fused 0 elementwise_mul with relu6 activatione[0m
e[37m---    fused 0 elementwise_mul with sigmoid activatione[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0610 23:58:33.440529 11984 analysis_predictor.cc:1007] ======= optimize end =======
I0610 23:58:33.440529 11984 naive_executor.cc:102] ---  skip [feed], feed -> image
I0610 23:58:33.447522 11984 naive_executor.cc:102] ---  skip [argmax_0.tmp_0], fetch -> fetch
I0610 23:58:33.448458 11984 naive_executor.cc:102] ---  skip [transpose_0.tmp_0], fetch -> fetch
W0610 23:58:34.422415 11984 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.2
W0610 23:58:34.429071 11984 gpu_context.cc:306] device: 0, cuDNN Version: 8.2.
I0610 23:58:52.445581 23200 analysis_predictor.cc:937] MKLDNN is enabled
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_clean_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [mkldnn_placement_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [layer_norm_fuse_pass]e[0m
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
e[32m--- Running IR pass [attention_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [seqconv_eltadd_relu_fuse_pass]e[0m
e[32m--- Running IR pass [seqpool_cvm_concat_fuse_pass]e[0m
e[32m--- Running IR pass [mul_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [fc_gru_fuse_pass]e[0m
e[37m---    fused 0 pairs of fc gru patternse[0m
e[32m--- Running IR pass [mul_gru_fuse_pass]e[0m
e[32m--- Running IR pass [seq_concat_fc_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [matmul_v2_scale_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]e[0m
e[32m--- Running IR pass [matmul_scale_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
e[32m--- Running IR pass [repeated_fc_relu_fuse_pass]e[0m
e[32m--- Running IR pass [squared_mat_sub_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0610 23:58:53.932404 23200 fuse_pass_base.cc:57] ---  detected 305 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
I0610 23:58:54.026430 23200 fuse_pass_base.cc:57] ---  detected 1 subgraphs
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[32m--- Running IR pass [depthwise_conv_mkldnn_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bias_mkldnn_fuse_pass]e[0m
I0610 23:58:54.294723 23200 fuse_pass_base.cc:57] ---  detected 2 subgraphs
e[32m--- Running IR pass [conv_transpose_bias_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_elementwise_add_mkldnn_fuse_pass]e[0m
e[37m---    Fused 1 projection conv (as y) + elementwise_add patternse[0m
e[37m---    Fused 107 conv (as x) + elementwise_add patternse[0m
e[37m---    Fused 0 conv (as y) + elementwise_add patternse[0m
I0610 23:59:03.490278 23200 fuse_pass_base.cc:57] ---  detected 108 subgraphs
e[32m--- Running IR pass [conv_concat_relu_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_relu_mkldnn_fuse_pass]e[0m
I0610 23:59:03.764508 23200 fuse_pass_base.cc:57] ---  detected 243 subgraphs
e[32m--- Running IR pass [conv_leaky_relu_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_relu6_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_swish_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_hard_swish_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_mish_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_hard_sigmoid_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_gelu_mkldnn_fuse_pass]e[0m
e[32m--- Running IR pass [scale_matmul_fuse_pass]e[0m
e[37m---    fused 0 scale with matmule[0m
e[32m--- Running IR pass [reshape_transpose_matmul_mkldnn_fuse_pass]e[0m
e[37m---    Fused 0 ReshapeTransposeMatmul patterns for matmul Ope[0m
e[37m---    Fused 0 ReshapeTransposeMatmul patterns for matmul Op with transpose's xshapee[0m
e[37m---    Fused 0 ReshapeTransposeMatmul patterns for matmul Op with reshape's xshapee[0m
e[37m---    Fused 0 ReshapeTransposeMatmul patterns for matmul Op with reshape's xshape with transpose's xshapee[0m
e[32m--- Running IR pass [reshape_transpose_matmul_v2_mkldnn_fuse_pass]e[0m
e[37m---    Fused 0 ReshapeTransposeMatmul patterns for matmul_v2 Ope[0m
e[37m---    Fused 0 ReshapeTransposeMatmul patterns for matmul_v2 Op with transpose's xshapee[0m
e[37m---    Fused 0 ReshapeTransposeMatmul patterns for matmul_v2 Op with reshape's xshapee[0m
e[37m---    Fused 0 ReshapeTransposeMatmul patterns for matmul_v2 Op with reshape's xshape with transpose's xshapee[0m
e[32m--- Running IR pass [matmul_transpose_reshape_fuse_pass]e[0m
e[37m---    Fused 0 MatmulTransposeReshape patterns for matmul Ope[0m
e[32m--- Running IR pass [matmul_v2_transpose_reshape_fuse_pass]e[0m
e[37m---    Fused 0 MatmulTransposeReshape patterns for matmul_v2 Ope[0m
e[32m--- Running IR pass [batch_norm_act_fuse_pass]e[0m
e[37m---    fused 0 batch norm with relu activatione[0m
e[32m--- Running IR pass [softplus_activation_mkldnn_fuse_pass]e[0m
e[37m---    fused 0 softplus with relu activatione[0m
e[37m---    fused 0 softplus with tanh activatione[0m
e[37m---    fused 0 softplus with leaky_relu activatione[0m
e[37m---    fused 0 softplus with swish activatione[0m
e[37m---    fused 0 softplus with hardswish activatione[0m
e[37m---    fused 0 softplus with sqrt activatione[0m
e[37m---    fused 0 softplus with abs activatione[0m
e[37m---    fused 0 softplus with clip activatione[0m
e[37m---    fused 0 softplus with gelu activatione[0m
e[37m---    fused 0 softplus with relu6 activatione[0m
e[37m---    fused 0 softplus with sigmoid activatione[0m
e[32m--- Running IR pass [elt_act_mkldnn_fuse_pass]e[0m
I0610 23:59:04.404881 23200 fuse_pass_base.cc:57] ---  detected 26 subgraphs
e[37m---    fused 26 elementwise_add with relu activatione[0m
e[37m---    fused 0 elementwise_add with tanh activatione[0m
e[37m---    fused 0 elementwise_add with leaky_relu activatione[0m
e[37m---    fused 0 elementwise_add with swish activatione[0m
e[37m---    fused 0 elementwise_add with hardswish activatione[0m
e[37m---    fused 0 elementwise_add with sqrt activatione[0m
e[37m---    fused 0 elementwise_add with abs activatione[0m
e[37m---    fused 0 elementwise_add with clip activatione[0m
e[37m---    fused 0 elementwise_add with gelu activatione[0m
e[37m---    fused 0 elementwise_add with relu6 activatione[0m
e[37m---    fused 0 elementwise_add with sigmoid activatione[0m
e[37m---    fused 0 elementwise_sub with relu activatione[0m
e[37m---    fused 0 elementwise_sub with tanh activatione[0m
e[37m---    fused 0 elementwise_sub with leaky_relu activatione[0m
e[37m---    fused 0 elementwise_sub with swish activatione[0m
e[37m---    fused 0 elementwise_sub with hardswish activatione[0m
e[37m---    fused 0 elementwise_sub with sqrt activatione[0m
e[37m---    fused 0 elementwise_sub with abs activatione[0m
e[37m---    fused 0 elementwise_sub with clip activatione[0m
e[37m---    fused 0 elementwise_sub with gelu activatione[0m
e[37m---    fused 0 elementwise_sub with relu6 activatione[0m
e[37m---    fused 0 elementwise_sub with sigmoid activatione[0m
e[37m---    fused 0 elementwise_mul with relu activatione[0m
e[37m---    fused 0 elementwise_mul with tanh activatione[0m
e[37m---    fused 0 elementwise_mul with leaky_relu activatione[0m
e[37m---    fused 0 elementwise_mul with swish activatione[0m
e[37m---    fused 0 elementwise_mul with hardswish activatione[0m
e[37m---    fused 0 elementwise_mul with sqrt activatione[0m
e[37m---    fused 0 elementwise_mul with abs activatione[0m
e[37m---    fused 0 elementwise_mul with clip activatione[0m
e[37m---    fused 0 elementwise_mul with gelu activatione[0m
e[37m---    fused 0 elementwise_mul with relu6 activatione[0m
e[37m---    fused 0 elementwise_mul with sigmoid activatione[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0610 23:59:04.637152 23200 analysis_predictor.cc:1007] ======= optimize end =======
I0610 23:59:04.638072 23200 naive_executor.cc:102] ---  skip [feed], feed -> image
I0610 23:59:04.645150 23200 naive_executor.cc:102] ---  skip [argmax_0.tmp_0], fetch -> fetch
I0610 23:59:04.645150 23200 naive_executor.cc:102] ---  skip [transpose_0.tmp_0], fetch -> fetch
Traceback (most recent call last):
  File "D:\0SDXX\PaddleSeg\EISeg\eiseg\app.py", line 1628, in canvasClick
    self.controller.addClick(x, y, isLeft)
  File "D:\0SDXX\PaddleSeg\EISeg\eiseg\controller.py", line 214, in addClick
    pred = self.predictor.get_prediction(self.clicker)
  File "D:\0SDXX\PaddleSeg\EISeg\eiseg\inference\predictor\base.py", line 97, in get_prediction
    is_image_changed)
  File "D:\0SDXX\PaddleSeg\EISeg\eiseg\inference\predictor\base.py", line 146, in _get_prediction
    self.input_handle_2 = self.net.get_input_handle(input_names[1])
IndexError: list index out of range
```
eiseg 调用PaddleX 导出的模型
```

Model: HRNet
Transforms:
- Resize:
    interp: LINEAR
    keep_ratio: false
    target_size:
    - 1536
    - 1024
- Normalize:
    is_scale: true
    max_val:
    - 255.0
    - 255.0
    - 255.0
    mean:
    - 0.5
    - 0.5
    - 0.5
    min_val:
    - 0
    - 0
    - 0
    std:
    - 0.5
    - 0.5
    - 0.5
_Attributes:
  eval_metrics:
    miou: 0.9684597849845886
  fixed_input_shape:
  - -1
  - 3
  - -1
  - -1
  labels:
  - '0'
  - '1'
  model_type: segmenter
  num_classes: 2
_init_params:
  num_classes: 2
  use_mixed_loss: false
completed_epochs: 0
status: Infer
version: 2.1.0

```

**Comment by haoyuying** [comment]
eiseg不支持导入paddlex模型。目前支持的模型可在此处查找：https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.5/EISeg
