### ISSUE TITLE
CrossEntropyWithSoftmaxCUDAKernel

### ISSUE THREAD

**Issue by cccrice** [PaddlePaddle/PaddleSeg#2256]
欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：无
 2. PaddlePaddle版本：PaddlePaddle 2.3.0
 3. 操作系统信息：Windows10
 4. Python版本号：Python3.6
 5. CUDA/cuDNN版本：CUDA10.2/cuDNN 7.6.5
 6. 完整的代码：(若修改过原代码，请提供修改前后代码对比）
 7. 详细的错误信息、相关log：Traceback (most recent call last):
File "G:/学习/飞桨学习课程/语义分割/case_pet_seg/Unet.py", line 163, in
batch_size=2)
File "C:\Program Files\Python36\lib\site-packages\paddle\hapi\model.py", line 1767, in fit
logs = self._run_one_epoch(train_loader, cbks, 'train')
File "C:\Program Files\Python36\lib\site-packages\paddle\hapi\model.py", line 2097, in _run_one_epoch
outs = getattr(self, mode + '_batch')(_inputs)
File "C:\Program Files\Python36\lib\site-packages\paddle\hapi\model.py", line 1093, in train_batch
loss = self._adapter.train_batch(inputs, labels, update)
File "C:\Program Files\Python36\lib\site-packages\paddle\hapi\model.py", line 730, in train_batch
losses = self.model._loss((to_list(outputs) + labels))
File "C:\Program Files\Python36\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in call
return self._dygraph_call_func(*inputs, **kwargs)
File "C:\Program Files\Python36\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
outputs = self.forward(*inputs, **kwargs)
File "C:\Program Files\Python36\lib\site-packages\paddle\nn\layer\loss.py", line 406, in forward
name=self.name)
File "C:\Program Files\Python36\lib\site-packages\paddle\nn\functional\loss.py", line 1734, in cross_entropy
'use_softmax', use_softmax)
SystemError: (Fatal) Operator softmax_with_cross_entropy raises an struct paddle::PD_Exception exception.
The exception content is
:function "CrossEntropyWithSoftmaxCUDAKernel" is not implemented for data type float32
[../paddle/phi/kernels/gpu/cross_entropy_kernel.cu:1544]. (at ..\paddle\fluid\imperative\tracer.cc:307)
 9. 运行指令或复现步骤：
 10. 其他内容: （增加其他与问题相关的内容）

**Comment by juncaipeng** [comment]
你看下使用的是那个loss api，参考官方api的说明检查一下输入类型是否匹配。
