### ISSUE TITLE
[General Issue] 我发现只能在：ai Studio , 但我是在本地的怎么办？ 没有configs/modnet/modnet-mobilenetv2.yml 这个文件

### ISSUE THREAD

**Issue by gg22mm** [PaddlePaddle/PaddleSeg#2302]
我的没有configs/modnet/modnet-mobilenetv2.yml 这个文件，我用Matting里面的报错：

(paddle2.3) E:\wll\phpsys\WWW\start\dzjk\txsb\api\resnet\paddle\PaddleSeg>python train.py --config ./Matting/configs/modnet/modnet-mobilenetv2.yml  --do_eval --use_vdl --save_interval 5000 --num_workers 0 --save_dir output
2022-07-08 09:30:51 [INFO]
------------Environment Information-------------
platform: Windows-10-10.0.17133-SP0
Python: 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)]
Paddle compiled with cuda: False
PaddleSeg: 2.5.0
PaddlePaddle: 2.3.0
OpenCV: 4.5.4
------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 230, in <module>
    main(args)
  File "train.py", line 184, in main
    train_dataset = cfg.train_dataset
  File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddleseg\cvlibs\config.py", line 364, in train_dataset
    return self._load_object(_train_dataset)
  File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddleseg\cvlibs\config.py", line 391, in _load_object
    component = self._load_component(cfg.pop('type'))
  File "d:\Anaconda3\envs\paddle2.3\lib\site-packages\paddleseg\cvlibs\config.py", line 384, in _load_component
    'The specified component was not found {}.'.format(com_name))
RuntimeError: The specified component was not found MattingDataset.

(paddle2.3) E:\wll\phpsys\WWW\start\dzjk\txsb\api\resnet\paddle\PaddleSeg>

，我发现只能在：ai Studio , 但我是在本地的怎么办？

**Comment by gg22mm** [comment]
有办法了，去ai Studio中下载出来
