### ISSUE TITLE
[General Issue] Training Custom Data - Labels not getting read properly 

### ISSUE THREAD

**Issue by cspearl** [PaddlePaddle/PaddleSeg#2362]
2022-07-24 17:44:52 [INFO] Start evaluating (total_samples: 150, total_iters: 150)...
Traceback (most recent call last):
File "train.py", line 230, in
main(args)
File "train.py", line 225, in main
to_static_training=cfg.to_static_training)
File "/content/drive/MyDrive/amazon/PaddleSeg/paddleseg/core/train.py", line 289, in train
**test_config)
File "/content/drive/MyDrive/amazon/PaddleSeg/paddleseg/core/val.py", line 165, in evaluate
ignore_index=eval_dataset.ignore_index)
File "/content/drive/MyDrive/amazon/PaddleSeg/paddleseg/utils/metrics.py", line 43, in calculate_area
label.shape))
ValueError: Shape of pred and `label should be equal, but there are [1, 512, 512] and [1, 4, 1].

**Comment by cspearl** [comment]
I have tried to train on my dataset using the instructions given, but the following error pops up out of nowhere after 500 iterations 
------------------------------------------------------------------------------------------------------
2022-07-23 15:50:18 [INFO]	[TRAIN] epoch: 2, iter: 500/1000, loss: 0.4193, lr: 0.000537, batch_cost: 0.2036, reader_cost: 0.01543, ips: 4.9111 samples/sec | ETA 00:01:41
2022-07-23 15:50:18 [INFO]	Start evaluating (total_samples: 150, total_iters: 150)...
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/dataloader_iter.py", line 218, in _thread_loop
    self._thread_done_event)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "/content/drive/MyDrive/amazon/PaddleSeg/paddleseg/datasets/dataset.py", line 151, in __getitem__
    data['label'] = data['label'][np.newaxis, :, :]
TypeError: 'bool' object is not subscriptable
