### ISSUE TITLE
PP-LiteSeg model not suport export onnx Dynamic dimension 

### ISSUE THREAD

**Issue by fanweiya** [PaddlePaddle/PaddleSeg#2369]
```
0725 14:18:20.160902 34786 gpu_context.cc:244] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.2
W0725 14:18:20.164794 34786 gpu_context.cc:272] device: 0, cuDNN Version: 8.4.
2022-07-25 14:18:22 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet2.tar.gz
2022-07-25 14:18:22 [INFO]	There are 265/265 variables loaded into STDCNet.
2022-07-25 14:18:23 [INFO]	Loaded trained params of model successfully.
/data/anaconda3/envs/paddlex2/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  return (isinstance(seq, collections.Sequence) and
/data/anaconda3/envs/paddlex2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:341: UserWarning: /tmp/tmpcrharxub.py:26
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/data/anaconda3/envs/paddlex2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:341: UserWarning: /tmp/tmpsjgbcdzg.py:16
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/data/anaconda3/envs/paddlex2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:341: UserWarning: /tmp/tmpsjgbcdzg.py:16
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/data/anaconda3/envs/paddlex2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:341: UserWarning: /tmp/tmpy3slin_o.py:16
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/data/anaconda3/envs/paddlex2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:341: UserWarning: /tmp/tmpy3slin_o.py:16
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/data/anaconda3/envs/paddlex2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:341: UserWarning: /tmp/tmpfrggj1xh.py:16
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/data/anaconda3/envs/paddlex2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py:341: UserWarning: /tmp/tmpfrggj1xh.py:16
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
2022-07-25 14:18:25 [INFO]	Model is saved in pp_liteseg_stdc2_CHO115huizong_20220708_1024x1024/deploy_model.
2022-07-25 14:18:26 [WARNING]	[Deprecated] `paddle2onnx.command.program2onnx` will be deprecated in the future version, the recommended usage is `paddle2onnx.export`
Traceback (most recent call last):
  File "/data/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle2onnx/legacy/op_mapper/op_mapper.py", line 132, in mapping
    mapper_func(graph, node, **kw)
  File "/data/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle2onnx/legacy/op_mapper/nn.py", line 168, in opset_1
    "Converting this model to ONNX need with static input shape," \
Exception: Converting this model to ONNX need with static input shape, please fix input shape of this model, see doc Q2 in https://github.com/PaddlePaddle/paddle2onnx/blob/develop/docs/en/FAQ.md.

```

**Comment by juncaipeng** [comment]
PP-LiteSeg does not support exporting to ONNX with dynamic dimension for  adaptive average pooling op.  
To solve the problem , the first method is setting fix dimension for PP-LiteSeg, the second method is setting cm_bin_sizes as 1 as follows, i.e. only use global adaptive average pooling.

![image](https://user-images.githubusercontent.com/52520497/180735064-0a8f08a4-31f6-426e-8d94-22f230c3a8c3.png)

**Comment by fanweiya** [comment]
请问一下，cm_bin_sizes as 1s这个是仅在导出时设置，还是训练前设置，设置后会不会影响模型的性能？

> PP-LiteSeg does not support exporting to ONNX with dynamic dimension for adaptive average pooling op. To solve the problem , the first method is setting fix dimension for PP-LiteSeg, the second method is setting cm_bin_sizes as 1 as follows, i.e. only use global adaptive average pooling.
> 
> ![image](https://user-images.githubusercontent.com/52520497/180735064-0a8f08a4-31f6-426e-8d94-22f230c3a8c3.png)

**Comment by juncaipeng** [comment]
训练前设置，需要重新训练。
