### ISSUE TITLE
[Bug] paddle2onnx 导出出现了问题

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleSeg#2380]
欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：PaddleSeg==2.6
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：Linux
 4. Python版本号：Python3.6.13
 5. CUDA/cuDNN版本：CUDA11.2
 

Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 119, in mapping
    mapper_func(graph, node, **kw)
  File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle2onnx/op_mapper/nn.py", line 186, in opset_1
    node.input_shape('X', 0), node.output_shape('Out', 0)))
Exception: Cannot convert adaptive pool with input_size: (1, 24, 32, 32), output_size: (1, 24, 3, 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/d2l/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle2onnx/command.py", line 195, in main
    input_shape_dict=input_shape_dict)
  File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle2onnx/command.py", line 159, in program2onnx
    operator_export_type=operator_export_type)
  File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle2onnx/convert.py", line 88, in program2onnx
    auto_update_opset)
  File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle2onnx/convert.py", line 36, in export_onnx
    auto_update_opset)
  File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle2onnx/graph/onnx_graph.py", line 262, in build
    onnx_graph.build_op_nodes(paddle_graph.node_map)
  File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle2onnx/graph/onnx_graph.py", line 209, in build_op_nodes
    OpMapper.mapping(self, node, self.operator_export_type)
  File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 124, in mapping
    node.outputs) + str(e))
Exception: Error happened when mapping node ['pool2d_3'] to onnx, which op_type is 'pool2d' with inputs: {'X': ['elementwise_add_0']} and outputs: {'Out': ['pool2d_11.tmp_0']}, specific error: Cannot convert adaptive pool with input_size: (1, 24, 32, 32), output_size: (1, 24, 3, 3)

导出出现了问题，使用所有的模型导出为onnx还是失败

**Comment by shiyutang** [comment]
关于 paddle2onnx 的问题欢迎前往https://github.com/PaddlePaddle/Paddle2ONNX 提问～
