### ISSUE TITLE
[General Issue]使用python inference部署推理，开启--benchmark=True报错

### ISSUE THREAD

**Issue by 1344265305** [PaddlePaddle/PaddleSeg#2437]
命令：
python deploy/python/infer.py \--config output/dynamic_model/deploy.yaml \--image_path deploy/cpp/demo \--use_trt=True \--enable_auto_tune=True --benchmark=True

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1660205219 (unix time) try "date -d @1660205219" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x7ff194ad1be0) received by PID 3541090 (TID 0x7ff1bfb95340) from PID 18446744071908957152 ***]

Segmentation fault (core dumped)
(pp) speed@speedNode:~/Segmentation/paddleseg$ /home/speed/Segmentation/paddleseg/deploy/python/../../paddleseg/models/losses/decoupledsegnet_relax_boundary_loss.py:19: DeprecationWarning: Please use `shift` from the `scipy.ndimage` namespace, the `scipy.ndimage.interpolation` namespace is deprecated.
  from scipy.ndimage.interpolation import shift
/home/speed/Segmentation/paddleseg/deploy/python/../../paddleseg/transforms/functional.py:18: DeprecationWarning: Please use `distance_transform_edt` from the `scipy.ndimage` namespace, the `scipy.ndimage.morphology` namespace is deprecated.
  from scipy.ndimage.morphology import distance_transform_edt
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/home/speed/.conda/envs/pp/lib/python3.9/site-packages/psutil/_common.py", line 442, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/speed/.conda/envs/pp/lib/python3.9/site-packages/psutil/_pslinux.py", line 1642, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/speed/.conda/envs/pp/lib/python3.9/site-packages/psutil/_common.py", line 445, in wrapper
    return fun(self)
  File "/home/speed/.conda/envs/pp/lib/python3.9/site-packages/psutil/_pslinux.py", line 1684, in _parse_stat_file
    data = bcat("%s/%s/stat" % (self._procfs_path, self.pid))
  File "/home/speed/.conda/envs/pp/lib/python3.9/site-packages/psutil/_common.py", line 775, in bcat
    return cat(fname, fallback=fallback, _open=open_binary)
  File "/home/speed/.conda/envs/pp/lib/python3.9/site-packages/psutil/_common.py", line 763, in cat
    with _open(fname) as f:
  File "/home/speed/.conda/envs/pp/lib/python3.9/site-packages/psutil/_common.py", line 727, in open_binary
    return open(fname, "rb", buffering=FILE_READ_BUFFER_SIZE)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/3541090/stat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/speed/.conda/envs/pp/lib/python3.9/site-packages/psutil/__init__.py", line 361, in _init
    self.create_time()
  File "/home/speed/.conda/envs/pp/lib/python3.9/site-packages/psutil/__init__.py", line 714, in create_time
    self._create_time = self._proc.create_time()
  File "/home/speed/.conda/envs/pp/lib/python3.9/site-packages/psutil/_pslinux.py", line 1642, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/speed/.conda/envs/pp/lib/python3.9/site-packages/psutil/_pslinux.py", line 1852, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
  File "/home/speed/.conda/envs/pp/lib/python3.9/site-packages/psutil/_pslinux.py", line 1649, in wrapper
    raise NoSuchProcess(self.pid, self._name)
psutil.NoSuchProcess: process no longer exists (pid=3541090)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/speed/.conda/envs/pp/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/speed/.conda/envs/pp/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/speed/.conda/envs/pp/lib/python3.9/site-packages/auto_log/device.py", line 219, in get_mem_subprocess_start
    cpu_infos, gpu_infos = self.mem_info.get_avg_mem_mb()
  File "/home/speed/.conda/envs/pp/lib/python3.9/site-packages/auto_log/device.py", line 195, in get_avg_mem_mb
    cpu_infos, gpu_infos = self.summary_mem(return_str=False)
  File "/home/speed/.conda/envs/pp/lib/python3.9/site-packages/auto_log/device.py", line 183, in summary_mem
    cpu_infos[str(p)] = self.get_cpu_current_memory_mb(p)
  File "/home/speed/.conda/envs/pp/lib/python3.9/site-packages/auto_log/device.py", line 37, in get_cpu_current_memory_mb
    p = psutil.Process(pid)
  File "/home/speed/.conda/envs/pp/lib/python3.9/site-packages/psutil/__init__.py", line 332, in __init__
    self._init(pid)
  File "/home/speed/.conda/envs/pp/lib/python3.9/site-packages/psutil/__init__.py", line 373, in _init
    raise NoSuchProcess(pid, msg='process PID not found')
psutil.NoSuchProcess: process PID not found (pid=3541090)
/home/speed/.conda/envs/pp/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 3 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

**Comment by Bobholamovic** [comment]
请给出具体的复现方法。

**Comment by 1344265305** [comment]
> 请给出具体的复现方法。

不开启benchmark正常运行；按照https://github.com/LDOUBLEV/AutoLog的方法安装autolog，然后在infer.py的配置上启用了--benchmark=True，问题出现

**Comment by Bobholamovic** [comment]
『具体的复现方法』应当包含使用的模型、数据、PaddleRS版本、硬件设备、环境依赖等信息。

**Comment by 1344265305** [comment]
> 『具体的复现方法』应当包含使用的模型、数据、PaddleRS版本、硬件设备、环境依赖等信息。

模型是ppliteseg
数据是自己的数据集
paddleSeg版本：2.6.0
PaddlePaddle版本：2.3.1
系统信息：Ubuntu18.04 +3090
Python版本号：3.9
CUDA/cuDNN版本：11.6/8.4.1

**Comment by Bobholamovic** [comment]
收到。这个问题看起来像是AutoLog库对psutil库的使用不当，在处理时出现了data race，试图去访问已经被销毁的进程的信息。建议在[AutoLog](https://github.com/LDOUBLEV/AutoLog/issues)反映此issue。另外可参考psutil库的[这个issue](https://github.com/giampaolo/psutil/issues/1925)。

**Comment by 1344265305** [comment]
> 收到。这个问题看起来像是AutoLog库对psutil库的使用不当，在处理时出现了data race，试图去访问已经被销毁的进程的信息。建议在[AutoLog](https://github.com/LDOUBLEV/AutoLog/issues)反映此issue。另外可参考psutil库的[这个issue](https://github.com/giampaolo/psutil/issues/1925)。

感谢回复
