### ISSUE TITLE
[General Issue]RuntimeError: The specified component was not found MattingDataset.

### ISSUE THREAD

**Issue by lfbcccc** [PaddlePaddle/PaddleSeg#2483]
1.按照PP-Matting说明文档安装了Matting下的 requirements.txt后  按照下命令训练模型
python train.py      --config  Matting/configs/quick_start/modnet-mobilenetv2.yml   
                               --do_eval  --use_vdl  --save_interval 500  --num_workers 5 
                               --save_dir output/ppmating_coal
出现
 File "train.py", line 230, in <module>
    main(args)
  File "train.py", line 184, in main
    train_dataset = cfg.train_dataset
  File "G:\PaddleSeg-release-2.6\paddleseg\cvlibs\config.py", line 373, in train_dataset
    return self._load_object(_train_dataset)
  File "G:\PaddleSeg-release-2.6\paddleseg\cvlibs\config.py", line 400, in _load_object
    component = self._load_component(cfg.pop('type'))
  File "G:\PaddleSeg-release-2.6\paddleseg\cvlibs\config.py", line 392, in _load_component
    raise RuntimeError(
RuntimeError: The specified component was not found MattingDataset.
请问是什么原因？

**Comment by wuyefeilin** [comment]
请在Matting 目录下运行目录哈

**Comment by lfbcccc** [comment]
> 请在Matting 目录下运行目录哈
Matting没有train.py文件  我复制了根目录下的train文件后运行还是出现这样
PS G:\PaddleSeg-release-2.6\Matting> python train.py      --config G:\PaddleSeg-release-2.6\Matting\configs\quick_start\modnet-mobilenetv2.yml     --do_eval   --use_vdl    --save_interval 500      --num_workers 5      --
save_dir output/PPmating
2022-08-29 16:01:14 [INFO]
------------Environment Information-------------
platform: Windows-10-10.0.19041-SP0
Python: 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)]
Paddle compiled with cuda: True
NVCC: Build cuda_11.3.r11.3/compiler.29745058_0
cudnn: 8.2
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce']
PaddleSeg: 2.5.0
PaddlePaddle: 2.3.2
OpenCV: 4.5.4
------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 230, in <module>
    main(args)
  File "train.py", line 184, in main
    train_dataset = cfg.train_dataset
  File "E:\Anaconda\envs\npy\lib\site-packages\paddleseg\cvlibs\config.py", line 364, in train_dataset
    return self._load_object(_train_dataset)
  File "E:\Anaconda\envs\npy\lib\site-packages\paddleseg\cvlibs\config.py", line 391, in _load_object
    component = self._load_component(cfg.pop('type'))
  File "E:\Anaconda\envs\npy\lib\site-packages\paddleseg\cvlibs\config.py", line 383, in _load_component
    raise RuntimeError(
RuntimeError: The specified component was not found MattingDataset.

**Comment by wuyefeilin** [comment]
进入Matting目录后，参考教程运行https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.6/Matting#training-evaluation-and-prediction

**Comment by XUZHOUWANG** [comment]
we want to integrate the matting to our python project，but it report “    raise RuntimeError("The specified component ({}) was not found.".format(
RuntimeError: The specified component (STDC1) was not found.”。we  want to know，why so？
