### ISSUE TITLE
 启动 EISeg 报错  What's the problem

### ISSUE THREAD

**Issue by liuguicen** [PaddlePaddle/PaddleSeg#2536]
安装教程操作，启动EISeg直接报错 

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本： PaddleSeg release/2.6
 2. PaddlePaddle版本：  paddlepaddle-gpu==2.3.2 
 3. 操作系统信息： Windows 
 4. Python版本号：如Python3 7
 5. CUDA/cuDNN版本： CUDA10.2/cuDNN 7.6.5 
 
 启动 EISeg 报错 
 AttributeError: __getattribute__

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.2.4\helpers\pydev\pydevd.py", line 1415, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.2.4\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/tools/PaddleSeg/EISeg/eiseg/exe.py", line 23, in <module>
    main()
  File "D:\tools\PaddleSeg\EISeg\eiseg\run.py", line 76, in main
    window = APP_EISeg()  # 创建对象
  File "D:\tools\PaddleSeg\EISeg\eiseg\app.py", line 92, in __init__
    self.setupUi(self)
  File "D:\tools\PaddleSeg\EISeg\eiseg\ui.py", line 425, in setupUi
    QtCore.QMetaObject.connectSlotsByName(MainWindow)
SystemError: <built-in function connectSlotsByName> returned a result with an error set

**Comment by haoyuying** [comment]
报错显示qt没安装上，我安装的pyqt5的版本为 5.15.6，您可以参考一下

**Comment by liuguicen** [comment]
谢谢

**Comment by liuguicen** [comment]
安装QT5 过程中spyder没安装上，手动安装了 另外还提示其它的版本不匹配什么的，然后有的安装了，有的没安装
最后还是可以用了
