### ISSUE TITLE
[Bug]ValueError: Target 160 is out of upper bound?

### ISSUE THREAD

**Issue by lvsh2012** [PaddlePaddle/PaddleSeg#2583]
/home/aistudio/work/PaddleSeg
2022-09-29 10:52:04 [INFO]	
------------Environment Information-------------
platform: Linux-4.15.0-140-generic-x86_64-with-debian-stretch-sid
Python: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
Paddle compiled with cuda: True
NVCC: Build cuda_11.2.r11.2/compiler.29618528_0
cudnn: 8.2
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: Tesla V100-SXM2-16GB']
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
PaddleSeg: 2.6.0
PaddlePaddle: 2.3.2
OpenCV: 4.1.1
------------------------------------------------
2022-09-29 10:52:04 [INFO]	
---------------Config Information---------------
batch_size: 4
iters: 1000
loss:
  coef:
  - 1
  - 1
  - 1
  types:
  - ignore_index: 255
    type: CrossEntropyLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 0.01
  power: 0.9
  type: PolynomialDecay
model:
  backbone:
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet2.tar.gz
    type: STDC2
  type: PPLiteSeg
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 4.0e-05
train_dataset:
  dataset_root: data/mine
  mode: train
  num_classes: 4
  train_path: data/mine/train.txt
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 512
    - 512
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.5
    contrast_range: 0.5
    saturation_range: 0.5
    type: RandomDistort
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: data/mine
  mode: val
  num_classes: 4
  transforms:
  - type: Normalize
  type: Dataset
  val_path: data/mine/valid.txt
------------------------------------------------
W0929 10:52:04.378280  4902 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2
W0929 10:52:04.378324  4902 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
2022-09-29 10:52:05 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet2.tar.gz
2022-09-29 10:52:05 [INFO]	There are 265/265 variables loaded into STDCNet.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/norm.py:654: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
Traceback (most recent call last):
  File "train.py", line 230, in <module>
    main(args)
  File "train.py", line 225, in main
    to_static_training=cfg.to_static_training)
  File "/home/aistudio/work/PaddleSeg/paddleseg/core/train.py", line 211, in train
    losses=losses)
  File "/home/aistudio/work/PaddleSeg/paddleseg/core/train.py", line 55, in loss_computation
    loss_list.append(coef_i * loss_i(logits, labels))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/PaddleSeg/paddleseg/models/losses/cross_entropy_loss.py", line 86, in forward
    weight=self.weight)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/loss.py", line 1723, in cross_entropy
    label_max.item()))
**ValueError: Target 160 is out of upper bound.**

**Comment by Bobholamovic** [comment]
Please check if there are illegal values in the labels, say, 160 (given that the number of classes is 4).
