### ISSUE TITLE
[General Issue]: RuntimeError: (PreconditionNotMet) The meta data must be valid when call the mutable data function. (at /paddle/paddle/phi/core/dense_tensor.cc:105)

### ISSUE THREAD

**Issue by dutsc** [PaddlePaddle/PaddleSeg#2613]
It bothered me for a long time. I don't know where to start debugging. Could you please give me some advice?

I use two GPUs for distributed training.

Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: PaddleSeg 2.6.0
 2. PaddlePaddle version: paddle 2.3.2
 3. Operation system: Linux ubuntu 16.04
 4. Python version: Python 3.7.14
 5. CUDA/cuDNN version: CUDA11.2/cudnn8. I pull registry.baidubce.com/paddlepaddle/paddle:2.3.2-gpu-cuda11.2-cudnn8 from docker hub.
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

```python
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
LAUNCH INFO 2022-10-13 07:07:21,933 -----------  Configuration  ----------------------
LAUNCH INFO 2022-10-13 07:07:21,934 devices: None
LAUNCH INFO 2022-10-13 07:07:21,934 elastic_level: -1
LAUNCH INFO 2022-10-13 07:07:21,934 elastic_timeout: 30
LAUNCH INFO 2022-10-13 07:07:21,934 gloo_port: 6767
LAUNCH INFO 2022-10-13 07:07:21,934 host: None
LAUNCH INFO 2022-10-13 07:07:21,934 job_id: default
LAUNCH INFO 2022-10-13 07:07:21,934 legacy: False
LAUNCH INFO 2022-10-13 07:07:21,934 log_dir: log
LAUNCH INFO 2022-10-13 07:07:21,934 log_level: INFO
LAUNCH INFO 2022-10-13 07:07:21,934 master: None
LAUNCH INFO 2022-10-13 07:07:21,934 max_restart: 3
LAUNCH INFO 2022-10-13 07:07:21,934 nnodes: 1
LAUNCH INFO 2022-10-13 07:07:21,934 nproc_per_node: None
LAUNCH INFO 2022-10-13 07:07:21,934 rank: -1
LAUNCH INFO 2022-10-13 07:07:21,934 run_mode: collective
LAUNCH INFO 2022-10-13 07:07:21,934 server_num: None
LAUNCH INFO 2022-10-13 07:07:21,934 servers: 
LAUNCH INFO 2022-10-13 07:07:21,934 trainer_num: None
LAUNCH INFO 2022-10-13 07:07:21,934 trainers: 
LAUNCH INFO 2022-10-13 07:07:21,934 training_script: /home/PaddleSeg/train.py
LAUNCH INFO 2022-10-13 07:07:21,934 training_script_args: ['--config', '/home/PaddleSeg/configs/segmenter/segmenter_vit_base_linear_ade20k_512x512_160k.yml', '--use_vdl', '--save_interval', '5000', '--log_iters', '50', '--save_dir', '/home/PaddleSeg/output/segmenter_vit_base_linear_ade20k_512x512_160k']
LAUNCH INFO 2022-10-13 07:07:21,934 with_gloo: 0
LAUNCH INFO 2022-10-13 07:07:21,934 --------------------------------------------------
LAUNCH WARNING 2022-10-13 07:07:21,934 Compatible mode enable with args ['--selected_gpus=0,1']
-----------  Configuration Arguments -----------
backend: auto
cluster_topo_path: None
elastic_pre_hook: None
elastic_server: None
enable_auto_mapping: False
force: False
gpus: 0,1
heter_devices: 
heter_worker_num: None
heter_workers: 
host: None
http_port: None
ips: 127.0.0.1
job_id: None
log_dir: log
np: None
nproc_per_node: None
rank_mapping_path: None
run_mode: None
scale: 0
server_num: None
servers: 
training_script: /home/PaddleSeg/train.py
training_script_args: ['--config', '/home/PaddleSeg/configs/segmenter/segmenter_vit_base_linear_ade20k_512x512_160k.yml', '--use_vdl', '--save_interval', '5000', '--log_iters', '50', '--save_dir', '/home/PaddleSeg/output/segmenter_vit_base_linear_ade20k_512x512_160k']
worker_num: None
workers: 
------------------------------------------------
WARNING 2022-10-13 07:07:21,935 launch.py:519] Not found distinct arguments and compiled with cuda or xpu or npu or mlu. Default use collective mode
WARNING 2022-10-13 07:07:21,935 launch.py:519] Not found distinct arguments and compiled with cuda or xpu or npu or mlu. Default use collective mode
launch train in GPU mode!
INFO 2022-10-13 07:07:21,936 launch_utils.py:679] Change selected_gpus into reletive values. --ips:0,1 will change into relative_ips:[0, 1] according to your CUDA_VISIBLE_DEVICES:['0', '1']
INFO 2022-10-13 07:07:21,936 launch_utils.py:679] Change selected_gpus into reletive values. --ips:0,1 will change into relative_ips:[0, 1] according to your CUDA_VISIBLE_DEVICES:['0', '1']
INFO 2022-10-13 07:07:21,936 launch_utils.py:561] Local start 2 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:36435               |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:36435,127.0.0.1:48607       |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                       0,1                     |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2022-10-13 07:07:21,936 launch_utils.py:561] Local start 2 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:36435               |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:36435,127.0.0.1:48607       |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                       0,1                     |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2022-10-13 07:07:21,936 launch_utils.py:566] details about PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
INFO 2022-10-13 07:07:21,936 launch_utils.py:566] details about PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
launch proc_id:18914 idx:0
launch proc_id:18919 idx:1
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
2022-10-13 07:07:23 [INFO]	
------------Environment Information-------------
platform: Linux-4.15.0-142-generic-x86_64-with-Ubuntu-18.04-bionic
Python: 3.7.14 (default, Sep  8 2022, 00:06:44) [GCC 7.5.0]
Paddle compiled with cuda: True
NVCC: Build cuda_11.2.r11.2/compiler.29558016_0
cudnn: 8.1
GPUs used: 2
CUDA_VISIBLE_DEVICES: 0,1
GPU: ['GPU 0: NVIDIA GeForce', 'GPU 1: NVIDIA GeForce']
GCC: gcc (GCC) 8.2.0
PaddleSeg: 2.6.0
PaddlePaddle: 2.3.2
OpenCV: 4.6.0
------------------------------------------------
2022-10-13 07:07:23 [INFO]	
---------------Config Information---------------
batch_size: 1
iters: 160000
loss:
  coef:
  - 1
  types:
  - coef:
    - 0.8
    - 0.2
    losses:
    - type: CrossEntropyLoss
    - type: LovaszSoftmaxLoss
    type: MixedLoss
lr_scheduler:
  end_lr: 1.0e-05
  learning_rate: 0.001
  power: 0.9
  type: PolynomialDecay
model:
  backbone:
    depth: 12
    drop_path_rate: 0.1
    drop_rate: 0.0
    embed_dim: 768
    final_norm: true
    img_size: 256
    mlp_ratio: 4
    num_heads: 12
    patch_size: 16
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/pretrained_models/vit_base_patch16_384_augreg.tar.gz
    qkv_bias: true
    type: VisionTransformer
  type: LinearSegmenter
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 0.0
test_config:
  crop_size:
  - 256
  - 256
  is_slide: true
  stride:
  - 256
  - 256
train_dataset:
  dataset_root: /home/PaddleSeg/datasets
  mode: train
  num_classes: 4
  train_path: /home/PaddleSeg/datasets/train_list.txt
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 256
    - 256
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
    type: RandomDistort
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: /home/PaddleSeg/datasets
  mode: val
  num_classes: 4
  transforms:
  - short_size: 256
    type: ResizeByShort
  - type: Normalize
  type: Dataset
  val_path: /home/PaddleSeg/datasets/val_list.txt
------------------------------------------------
W1013 07:07:24.012264 18914 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 11.2
W1013 07:07:24.012300 18914 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
2022-10-13 07:07:24 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/pretrained_models/vit_base_patch16_384_augreg.tar.gz
2022-10-13 07:07:25 [WARNING]	[SKIP] Shape of pretrained params pos_embed doesn't match.(Pretrained: [1, 577, 768], Actual: [1, 257, 768])
2022-10-13 07:07:25 [INFO]	There are 149/150 variables loaded into VisionTransformer.
2022-10-13 07:07:25 [INFO]	Load pos_embed and resize it from [1, 577, 768] to [1, 257, 768] .
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:48607']
I1013 07:07:28.953081 18914 nccl_context.cc:83] init nccl context nranks: 2 local rank: 0 gpu id: 0 ring id: 0
I1013 07:07:29.097298 18914 nccl_context.cc:115] init nccl context nranks: 2 local rank: 0 gpu id: 0 ring id: 10
2022-10-13 07:07:29,123-INFO: [topology.py:169:__init__] HybridParallelInfo: rank_id: 0, mp_degree: 1, sharding_degree: 1, pp_degree: 1, dp_degree: 2, mp_group: [0],  sharding_group: [0], pp_group: [0], dp_group: [0, 1], check/clip group: [0]
/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/math_op_patch.py:278: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.int64, the right dtype will convert to paddle.float32
  format(lhs_dtype, rhs_dtype, lhs_dtype))
Traceback (most recent call last):
  File "/home/PaddleSeg/train.py", line 230, in <module>
    main(args)
  File "/home/PaddleSeg/train.py", line 225, in main
    to_static_training=cfg.to_static_training)
  File "/home/PaddleSeg/paddleseg/core/train.py", line 212, in train
    loss = sum(loss_list)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/math_op_patch.py", line 299, in __impl__
    return math_op(self, other_var, 'axis', axis)
RuntimeError: (PreconditionNotMet) The meta data must be valid when call the mutable data function. (at /paddle/paddle/phi/core/dense_tensor.cc:105)
  [operator < elementwise_add > error]
INFO 2022-10-13 07:07:34,026 launch_utils.py:322] terminate process group gid:18919
INFO 2022-10-13 07:07:34,026 launch_utils.py:322] terminate process group gid:18919
INFO 2022-10-13 07:07:38,031 launch_utils.py:343] terminate all the procs
INFO 2022-10-13 07:07:38,031 launch_utils.py:343] terminate all the procs
ERROR 2022-10-13 07:07:38,032 launch_utils.py:642] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
ERROR 2022-10-13 07:07:38,032 launch_utils.py:642] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2022-10-13 07:07:42,033 launch_utils.py:343] terminate all the procs
INFO 2022-10-13 07:07:42,033 launch_utils.py:343] terminate all the procs
INFO 2022-10-13 07:07:42,034 launch.py:402] Local processes completed.
INFO 2022-10-13 07:07:42,034 launch.py:402] Local processes completed.
```

**Comment by Bobholamovic** [comment]
Hello, I would suggest that the shape, min value and max value of the network output and each element in `loss_list` can be printed to find out more clues about this error.

**Comment by dutsc** [comment]
I use the followed codes to print them. Is the problem caused by an empty element?

This code is added in File "/home/PaddleSeg/paddleseg/core/train.py", line 212, in train

```python
for i in range(len(loss_list)):
                    ele = loss_list[i]
                    if len(ele)==0:
                        print("the length of ele is 0.")
                        continue
                    print("shape: " + str(ele.shape))
                    print("min: " + str(min(ele)))
                    print("max: " + str(max(ele)))
```

The error information is as follows:
```python
/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/math_op_patch.py:278: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.int64, the right dtype will convert to paddle.float32
  format(lhs_dtype, rhs_dtype, lhs_dtype))
shape: [1]
min: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [2.52797723])
max: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [2.52797723])
shape: [1]
min: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [0.18936983])
max: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [0.18936983])
shape: [1]
min: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [3.23541951])
max: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [3.23541951])
shape: [1]
min: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [0.19459386])
max: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [0.19459386])
shape: [1]
min: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [0.76773149])
max: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [0.76773149])
shape: [1]
min: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [0.12689357])
max: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [0.12689357])
shape: [1]
min: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [3.48766971])
max: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [3.48766971])
shape: [1]
min: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [0.19669694])
max: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [0.19669694])
shape: [1]
min: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [0.])
max: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [0.])
the length of ele is 0.
Traceback (most recent call last):
  File "/home/PaddleSeg/train.py", line 230, in <module>
    main(args)
  File "/home/PaddleSeg/train.py", line 225, in main
    to_static_training=cfg.to_static_training)
  File "/home/PaddleSeg/paddleseg/core/train.py", line 222, in train
    loss = sum(loss_list)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/math_op_patch.py", line 299, in __impl__
    return math_op(self, other_var, 'axis', axis)
RuntimeError: (PreconditionNotMet) The meta data must be valid when call the mutable data function. (at /paddle/paddle/phi/core/dense_tensor.cc:105)
  [operator < elementwise_add > error]
```

**Comment by Bobholamovic** [comment]
I guess the zero-length tensor can be a reason.

**Comment by dutsc** [comment]
Have you ever encountered this bug? When I started training pspnet yesterday, everything was OK. But there is a problem when I start training segmenter.

**Comment by Bobholamovic** [comment]
I'll try it on my computer. Please give **a minimum example** to reproduce the problem, say, the instructions.
