### ISSUE TITLE
[General Issue] 知识蒸馏报错

### ISSUE THREAD

**Issue by top18981725185** [PaddlePaddle/PaddleSeg#2626]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version: (please specify the branch as well，e.g. PaddleSeg release/2.3)
 2. PaddlePaddle version: (e.g. PaddlePaddle 2.1.0)
 3. Operation system: (e.g. Linux/Windows/MacOS)
 4. Python version: (e.g. Python3.6/7/8)
 5. CUDA/cuDNN version: (e.g. CUDA10.2/cuDNN 7.6.5)
 6. Additional context: (Add any other context about the problem)

---

欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：（请提供版本号和分支信息，如PaddleSeg release/2.3）
 2. PaddlePaddle版本：（如PaddlePaddle 2.1.0）
 3. 操作系统信息：（如Linux/Windows/MacOS）
 4. Python版本号：（如Python3.6/7/8）
 5. CUDA/cuDNN版本：（ 如CUDA10.2/cuDNN 7.6.5等）
 6. 其他内容: （增加其他与问题相关的内容）

Traceback (most recent call last):   File "slim/distill/distill_train.py", line 224, in <module>     main(args)   File "slim/distill/distill_train.py", line 219, in main     test_config=s_cfg.test_config, )   File "/home/aistudio/work/PaddleSeg/slim/distill/distill_utils.py", line 177, in distill_train     images = data[0] KeyError: 0xdm,知识蒸馏报这个错有知道的吗？之前都没有，重新拉了代码也不行

**Comment by juncaipeng** [comment]
这个是跑seg的蒸馏示例吗？  还是说改动了什么？

**Comment by top18981725185** [comment]
是seg的，没有改动，跑通一次，重新启动了GPU就不行了，重新创建了项目拉取代码报一样的错

**Comment by top18981725185** [comment]
配置文件不使用蒸馏训练可以跑通

**Comment by OroChippw** [comment]
你好，我想问一下这个问题解决了吗 谢谢
