### ISSUE TITLE
为什么输入的图片数组尺寸不是相同的？

### ISSUE THREAD

**Issue by zjliu-cs** [PaddlePaddle/PaddleSeg#2635]
Thanks for your issue. To help us solve the issue better, please provide following information：
 1. PaddleSeg version:  2.5
 2. PaddlePaddle-gpu version: 2.3.2.post112
 3. Operation system: Linux
 4. Python version:  3.7
 5. CUDA/cuDNN version: cuDNN 8.2
 6. Additional context: (Add any other context about the problem)

我已经设置了Resize，将图片全部转化为1444*1444大小，为什么输入的图片数组大小不同呢？

错误信息
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 218, in _thread_loop
    self._thread_done_event)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 77, in default_collate_fn
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 77, in <listcomp>
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 58, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/core/shape_base.py", line 427, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape
```
```
import paddle
from paddleseg.models import UNet
import paddleseg.transforms as T
from paddleseg.datasets import Dataset
from paddleseg.models.losses import CrossEntropyLoss
from paddleseg.core import train

train_transforms = [
    T.Resize(target_size=(1444,1444)),  
    T.RandomHorizontalFlip(0.3), 
    T.RandomVerticalFlip(0.3),  
    T.RandomRotation(30),  
    T.RandomScaleAspect(),  
    T.RandomDistort(),  
    T.Normalize()  
]

train_dataset = Dataset(
    transforms=train_transforms,
    dataset_root='./',
    num_classes=2,
    mode='train',
    train_path='./PaddleSeg/dataset/train.txt',
    separator=' ',
)

val_transforms = [
    T.Resize(target_size=(1444,1444)),
    T.Normalize()
]

val_dataset = Dataset(
    transforms=val_transforms,
    dataset_root='./',
    num_classes=2,
    mode='val',
    val_path='./PaddleSeg/dataset/val.txt',
    separator=' ',
)


epochs = 10000
batch_size = 4
iters = epochs * 30 // batch_size
base_lr = 1e-4
losses = {}
losses['types'] = [CrossEntropyLoss()]
losses['coef'] = [1]

model = UNet(num_classes=2)
optimizer = paddle.optimizer.SGD(learning_rate=0.001, parameters=model.parameters(), weight_decay=4.0e-5)
train(
    model=model,
    train_dataset=train_dataset,
    val_dataset=val_dataset,
    optimizer=optimizer,
    save_dir='./output_unet',
    iters=iters,
    batch_size=batch_size,
    save_interval=200,
    log_iters=10,
    num_workers=0,
    losses=losses,
    use_vdl=True)
```

**Comment by juncaipeng** [comment]
建议对train_dataset进行遍历，看看输出的图片尺寸是否相同，估计还是特定的train_transforms导致这个问题。

**Comment by zjliu-cs** [comment]
输入的图片大小是不一样的，但是transforms中不是设置了resize改变大小吗？

**Comment by juncaipeng** [comment]
```
    T.Resize(target_size=(1444,1444)),  
    T.RandomHorizontalFlip(0.3), 
    T.RandomVerticalFlip(0.3),  
    T.RandomRotation(30),  
    T.RandomScaleAspect(),  
    T.RandomDistort(),  
    T.Normalize()  
```
除了Resize，后面几个操作可能也会改变size，你调试一下看
