### ISSUE TITLE
[Bug] 导出模型的时候出现了问题

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleSeg#2637]
W1020 11:44:16.561498  4588 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.1
W1020 11:44:16.566226  4588 device_context.cc:465] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File "export.py", line 144, in <module>
    main(args)
  File "export.py", line 102, in main
    para_state_dict = paddle.load(args.model_path)
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/site-packages/paddle/framework/io.py", line 985, in load
    load_result = _legacy_load(path, **configs)
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/site-packages/paddle/framework/io.py", line 1028, in _legacy_load
    load_result = _load_state_dict_from_save_params(model_path)
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/site-packages/paddle/framework/io.py", line 112, in _load_state_dict_from_save_params
    attrs={'file_path': os.path.join(model_path, name)})
  File "/home/dell/anaconda3/envs/padclass/lib/python3.6/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
ValueError: (InvalidArgument) Deserialize to tensor failed, maybe the loaded file is not a paddle model(expected file format: 0, but 1989477504 found).
  [Hint: Expected version == 0U, but received version:1989477504 != 0U:0.] (at /paddle/paddle/fluid/framework/lod_tensor.cc:329)
  [operator < load > error]

**Comment by Bobholamovic** [comment]
请确认`--model_path`指定的模型格式是否正确。

**Comment by chen-del** [comment]
我确认路径是正确的，因为模型保存的路径就是和文件命名是相同的，一共是训练了10000iter，但是我指定的时候却是爆出了这个错误，我不知道是哪里出现了问题

**Comment by Bobholamovic** [comment]
请问是静态图还是动态图的模型呢？

**Comment by chen-del** [comment]
是用的best_model动态的转静态

**Comment by chen-del** [comment]
@Bobholamovic 对了我好像是使用了，DiceLoss和MultiClassFocalLoss这两个loss进行组合，这个会不会是原因

**Comment by Bobholamovic** [comment]
> @Bobholamovic 对了我好像是使用了，DiceLoss和MultiClassFocalLoss这两个loss进行组合，这个会不会是原因

应该不是哦，看报错信息应该是在第一步加载模型的时候就出错了，还没有到涉及PaddleSeg的部分~ 请问你的`--model_path`指定的是`best_model`目录还是其中的`model.pdparams`文件呢？

**Comment by chen-del** [comment]
@Bobholamovic 我指定的是目录

**Comment by chen-del** [comment]
我好像知道原因了，我填错了填成了文件路径，其实是动态文件模型是吧

**Comment by Bobholamovic** [comment]
是的，应该填写.pdparams为后缀的模型权重文件。

**Comment by chen-del** [comment]
好的，谢谢
