### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'keys'

### ISSUE THREAD

**Issue by Yang-Changhui** [PaddlePaddle/PaddleSeg#2644]
你好，我在运行LaneSeg的predict时，出现AttributeError: 'numpy.ndarray' object has no attribute 'keys'，请问大家有遇到这样的问题吗
![无标题](https://user-images.githubusercontent.com/71805205/197373359-bfb5ed0f-d692-498a-a109-92a73c27d3c1.png)

**Comment by haoyuying** [comment]
您好，出现这样的问题是因为您图片传入有问题，建议从图片传入路径是否存在及合法进行排查。

**Comment by Yang-Changhui** [comment]
很感谢你的答复。但是问题不在这里，我的图片是可以显示的，经过transforms()出错，我的numpy是1.18，我在想是不是numpy版本太高了

**Comment by chgdwf** [comment]
同样的报错+1，我这里换了paddleseg的版本就正常了，希望有帮助。
操作系统：centos 7；
环境：python 3.6/3.9/3.10；
使用paddleseg2.6版本时报AttributeError: 'numpy.ndarray' object has no attribute 'keys'，更换paddleseg 2.5.0版后，一切正常

**Comment by Bobholamovic** [comment]
您好，`LaneSeg`依赖于旧版本PaddleSeg的transforms接口，可以降级PaddleSeg后再次尝试。

**Comment by Yang-Changhui** [comment]
更改了版本就好了，谢谢啦

**Comment by KyEndeavour** [comment]
PanopticDeepLab也是同样问题，换到2.5.0就能跑通了，感谢！

**Comment by giswrok** [comment]
Exception in thread Thread-2 (_thread_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddle/io/dataloader/dataloader_iter.py", line 245, in _thread_loop
    batch = self._dataset_fetcher.fetch(
  File "/usr/local/lib/python3.10/dist-packages/paddle/io/dataloader/fetcher.py", line 77, in fetch
    data.append(self.dataset[idx])
  File "/usr/local/lib/python3.10/dist-packages/paddleseg/datasets/dataset.py", line 163, in __getitem__
    data = self.transforms(data)
  File "/usr/local/lib/python3.10/dist-packages/paddleseg/transforms/transforms.py", line 128, in __call__
    data = op(data)
  File "/usr/local/lib/python3.10/dist-packages/paddleseg/transforms/transforms.py", line 1138, in __call__
    data['img'] = self._apply_pil_ops(img,ops,params_dict,prob_dict,data)
  File "/usr/local/lib/python3.10/dist-packages/paddleseg/transforms/transforms.py", line 1160, in _apply_pil_ops
    data['img'] = ops[id](**params)
  File "/usr/local/lib/python3.10/dist-packages/paddleseg/transforms/functional.py", line 104, in saturation
    im = ImageEnhance.Color(im).enhance(saturation_delta)
  File "/usr/local/lib/python3.10/dist-packages/PIL/ImageEnhance.py", line 55, in __init__
    if "A" in image.getbands():
AttributeError: 'numpy.ndarray' object has no attribute 'getbands'
请问这个问题怎么解决呢？
