### ISSUE TITLE
[Bug] Cannot predict ocrnet_hrnetw48_voc12aug_512x512_40k

### ISSUE THREAD

**Issue by ukoehler** [PaddlePaddle/PaddleSeg#2666]
Python 3.9.13
paddle-bfloat      0.1.7
paddle2onnx        1.0.1
paddlefsl          1.1.0
paddlehub          2.3.0
paddlenlp          2.4.1
paddlepaddle       2.3.2
paddleseg          2.6.0
Windows 10
CPU only (set CUDA_VISIBLE_DEVICES=0)

When looking at OCRNet, I can predict with ocrnet_hrnetw48_cityscapes_1024x512_160k, however, ocrnet_hrnetw48_voc12aug_512x512_40k.yml fial and cannot find a way to fix that.

```
python predict.py --config configs\ocrnet\ocrnet_hrnetw48_cityscapes_1024x512_160k.yml --model_path OCRNet_HRNet_w48\ocrnet_hrnetw48_cityscapes_1024x512_160k_model.pdparams --image_path "D:\Local\devel\Python\TestImages\Input\city1.png" --save_dir  OCRNet_HRNet_w48\ocrnet_hrnetw48_cityscapes_1024x512_160k_model
```
works fine
```
(.venv) D:\Local\devel\Python\PaddleSeg\PaddleSeg>python predict.py --config con
figs\ocrnet\ocrnet_hrnetw48_cityscapes_1024x512_160k.yml --model_path OCRNet_HRN
et_w48\ocrnet_hrnetw48_cityscapes_1024x512_160k_model.pdparams --image_path "D:\
Local\devel\Python\TestImages\Input\city1.png" --save_dir  OCRNet_HRNet_w48\ocrn
et_hrnetw48_cityscapes_1024x512_160k_model
2022-10-27 11:32:17 [INFO]
---------------Config Information---------------
batch_size: 2
iters: 160000
loss:
  coef:
  - 1
  - 0.4
  types:
  - type: CrossEntropyLoss
  - type: CrossEntropyLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 0.01
  power: 0.9
  type: PolynomialDecay
model:
  backbone:
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz
    type: HRNet_W48
  backbone_indices:
  - 0
  num_classes: 19
  type: OCRNet
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 4.0e-05
train_dataset:
  dataset_root: data/cityscapes
  mode: train
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 1024
    - 512
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
    type: RandomDistort
  - type: Normalize
  type: Cityscapes
val_dataset:
  dataset_root: data/cityscapes
  mode: val
  transforms:
  - type: Normalize
  type: Cityscapes
------------------------------------------------
2022-10-27 11:32:27 [INFO]      Loading pretrained model from https://bj.bcebos.
com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz
2022-10-27 11:32:29 [INFO]      There are 1525/1525 variables loaded into HRNet.

2022-10-27 11:32:30 [INFO]      Number of predict images = 1
2022-10-27 11:32:30 [INFO]      Loading pretrained model from OCRNet_HRNet_w48\o
crnet_hrnetw48_cityscapes_1024x512_160k_model.pdparams
2022-10-27 11:32:33 [INFO]      There are 1583/1583 variables loaded into OCRNet
.
2022-10-27 11:32:33 [INFO]      Start to predict...
1/1 [==============================] - 128s 128s/step
```
while
```
(.venv) D:\Local\devel\Python\PaddleSeg\PaddleSeg>python predict.py --config configs\ocrne\ocrnet_hrnetw48_voc12aug_512x512_40k.yml --model_path OCRNet_HRNet_w48\ocrnet_hrnetw48_voc12aug_512x512_40k_model.pdparams --image_path "D:\Local\devel\Pytho\TestImages\Input\city1.png" --save_dir  OCRNet_HRNet_w48\ocrnet_hrnetw48_voc12aug_512x512_40k_model
```
fails
```
2022-10-27 11:38:56 [INFO]
---------------Config Information---------------
batch_size: 4
iters: 40000
loss:
  coef:
  - 1
  - 1
  types:
  - type: CrossEntropyLoss
  - type: CrossEntropyLoss
lr_scheduler:
  end_lr: 0
  learning_rate: 0.01
  power: 0.9
  type: PolynomialDecay
model:
  backbone:
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz
    type: HRNet_W48
  backbone_indices:
  - 0
  type: OCRNet
optimizer:
  momentum: 0.9
  type: sgd
  weight_decay: 4.0e-05
train_dataset:
  dataset_root: data/VOCdevkit/
  mode: trainaug
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 512
    - 512
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.4
    contrast_range: 0.4
    saturation_range: 0.4
    type: RandomDistort
  - type: Normalize
  type: PascalVOC
val_dataset:
  dataset_root: data/VOCdevkit/
  mode: val
  transforms:
  - target_size:
    - 512
    - 512
    type: Padding
  - type: Normalize
  type: PascalVOC
------------------------------------------------
2022-10-27 11:39:06 [INFO]      Loading pretrained model from https://bj.bcebos.
com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz
2022-10-27 11:39:09 [INFO]      There are 1525/1525 variables loaded into HRNet.

2022-10-27 11:39:10 [INFO]      Number of predict images = 1
2022-10-27 11:39:10 [INFO]      Loading pretrained model from OCRNet_HRNet_w48\o
crnet_hrnetw48_voc12aug_512x512_40k_model.pdparams
2022-10-27 11:39:12 [INFO]      There are 1583/1583 variables loaded into OCRNet
.
2022-10-27 11:39:12 [INFO]      Start to predict...
Traceback (most recent call last):
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\predict.py", line 185, in <mod
ule>
    main(args)
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\predict.py", line 173, in main

    predict(
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\paddleseg\core\predict.py", li
ne 101, in predict
    data = preprocess(im_path, transforms)
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\paddleseg\core\predict.py", li
ne 42, in preprocess
    data = transforms(data)
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\paddleseg\transforms\transform
s.py", line 78, in __call__
    data = op(data)
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\paddleseg\transforms\transform
s.py", line 449, in __call__
    raise ValueError(
ValueError: The size of image should be less than `target_size`, but the size of
 image (2048, 1024) is larger than `target_size` (512, 512)
```

**Comment by Bobholamovic** [comment]
This is because a `Padding` operator is used in the transformations, and `Padding` requires the image size to be smaller than the target size (which is 512x512). 

If your intention is to resize the image of size 2048x1024 into the size of 512x512 and do the prediction, the `Resize` operator should be used in place of `Padding`. This can be done by adding the following lines in`configs/ocrnet/ocrnet_hrnetw48_voc12aug_512x512_40k.yml`:

```yaml
val_dataset:
  type: PascalVOC
  dataset_root: data/VOCdevkit/
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: Normalize
  mode: val
```

Note, however, that due to the scale problem, I don't think it is a good idea to use a model trained with 512x512 patches to infer results on a 2048x1024 image (whether or not the original image is resized to 512x512). Rather, [doing prediction with sliding windows](https://github.com/PaddlePaddle/PaddleSeg/blob/5be2631d7f1a355d5692fd01be0ea8d05d85e50e/predict.py#L76) is a preferred choice.

**Comment by ukoehler** [comment]
Great, that works. For my purposes the results are also better than the city_scapes version. It is just not intuitive for a beginner like me.

**Comment by Bobholamovic** [comment]
I'm closing this issue as it's been solved. We will update the document to make clear this behavior of `Padding`.
