### ISSUE TITLE
dill loss 组合设置占比权重出现报错

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleSeg#2683]
dice loss和Ohem loss组合使用出现问题
loss:
  types:
    - type: MixedLoss
      losses:
        - type: DiceLoss
        - type: OhemCrossEntropyLoss
      coef: [0.8, 0.2]
W1101 11:02:17.162873 37663 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.1
W1101 11:02:17.162928 37663 device_context.cc:465] device: 0, cuDNN Version: 8.2.
2022-11-01 11:02:23 [INFO]      Loading pretrained model from https://paddleseg.bj.bcebos.com/dygraph/backbone/mobilenetv2_x1_0_ssld.tar.gz
2022-11-01 11:02:23 [INFO]      There are 260/260 variables loaded into MobileNetV2.
/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle/nn/layer/norm.py:653: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
Traceback (most recent call last):
  File "train.py", line 230, in <module>
    main(args)
  File "train.py", line 225, in main
    to_static_training=cfg.to_static_training)
  File "/home/dell/bag-torch/darkpull/Paddle/PaddleSeg/paddleseg/core/train.py", line 211, in train
    losses=losses)
  File "/home/dell/bag-torch/darkpull/Paddle/PaddleSeg/paddleseg/core/train.py", line 48, in loss_computation
    mixed_loss_list = loss_i(logits, labels)
  File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/dell/bag-torch/darkpull/Paddle/PaddleSeg/paddleseg/models/losses/mixed_loss.py", line 55, in forward
    output = loss(logits, labels)
  File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/dell/bag-torch/darkpull/Paddle/PaddleSeg/paddleseg/models/losses/dice_loss.py", line 49, in forward
    labels[labels == self.ignore_index] = 0
  File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 637, in __setitem__
    return _setitem_impl_(self, item, value)
  File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle/fluid/variable_index.py", line 584, in _setitem_impl_
    return set_value_for_bool_tensor(var, slice_item, value)
  File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle/fluid/variable_index.py", line 683, in set_value_for_bool_tensor
    "but received {}.".format(var.dtype))
TypeError: Only support float and double tensor for bool index, but received paddle.int64.

**Comment by wuyefeilin** [comment]
麻烦提供一下版本信息哈

**Comment by chen-del** [comment]
paddleseg 使用的版本是release/2.6版本
使用的总体环境如下
2022-11-02 10:21:25 [INFO]	
------------Environment Information-------------
platform: Linux-5.4.0-126-generic-x86_64-with-debian-buster-sid
Python: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) [GCC 7.5.0]
Paddle compiled with cuda: True
NVCC: Build cuda_11.4.r11.4/compiler.30188945_0
cudnn: 8.2
GPUs used: 1
CUDA_VISIBLE_DEVICES: 0
GPU: ['GPU 0: NVIDIA GeForce', 'GPU 1: NVIDIA GeForce']
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PaddleSeg: 2.6.0
PaddlePaddle: 2.2.2
OpenCV: 4.4.0
------------------------------------------------
2022-11-02 10:21:25 [INFO]	
---------------Config Information---------------

**Comment by chen-del** [comment]
@wuyefeilin

**Comment by wuyefeilin** [comment]
PaddlePaddle 升级到2.3.2试试

**Comment by chen-del** [comment]
嗯好的，我尝试升级一下，看看会不会出现这个问题

**Comment by chen-del** [comment]
@wuyefeilin 2.3.2 版本好像不存在这个问题了，可以正常进行了，但是似乎出现了一个新的警告
 UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")这个有影响吗

**Comment by wuyefeilin** [comment]
没影响，可以忽略

**Comment by chen-del** [comment]
@wuyefeilin您好，我还想问题训练的acc评估指标需要设置那个参数打开，因为现在的只有召回率和精确率评估指标
如下：
![6b8a2e24ff79e7237dc0b5b6f4fb19c](https://user-images.githubusercontent.com/58769772/199413210-34fccea5-18cf-44d5-9a02-766117f65dd0.png)
没有看到acc评估指标

**Comment by wuyefeilin** [comment]
输出日志中包含Acc

**Comment by chen-del** [comment]
好像没有我从2.5.0更新到2.6.0之后输出日志中，一直是没有acc精度，只有召回率和精确率就像我刚刚仔细的看了那个日志。

**Comment by chen-del** [comment]
以前的版本中是有的例如：2.30；2.40 还有我有个疑问kappa系数没有达到80%以上是不是意味着分错的概率挺大

2.6.0 信息如下
2022-11-02 16:46:28 [INFO]	[TRAIN] epoch: 12, iter: 71810/100000, loss: 0.8090, lr: 0.000040, batch_cost: 0.1137, reader_cost: 0.00044, ips: 35.1948 samples/sec | ETA 00:53:23
2022-11-02 16:46:29 [INFO]	[TRAIN] epoch: 12, iter: 71820/100000, loss: 0.7323, lr: 0.000040, batch_cost: 0.1107, reader_cost: 0.00036, ips: 36.1319 samples/sec | ETA 00:51:59
2022-11-02 16:46:30 [INFO]	[TRAIN] epoch: 12, iter: 71830/100000, loss: 0.9603, lr: 0.000040, batch_cost: 0.1091, reader_cost: 0.00016, ips: 36.6651 samples/sec | ETA 00:51:13
2022-11-02 16:46:31 [INFO]	[TRAIN] epoch: 12, iter: 71840/100000, loss: 0.8589, lr: 0.000040, batch_cost: 0.1026, reader_cost: 0.00038, ips: 38.9804 samples/sec | ETA 00:48:09
2022-11-02 16:46:32 [INFO]	[TRAIN] epoch: 12, iter: 71850/100000, loss: 0.7872, lr: 0.000040, batch_cost: 0.1091, reader_cost: 0.00017, ips: 36.6723 samples/sec | ETA 00:51:10
2022-11-02 16:46:33 [INFO]	[TRAIN] epoch: 12, iter: 71860/100000, loss: 0.8334, lr: 0.000040, batch_cost: 0.1136, reader_cost: 0.00015, ips: 35.1999 samples/sec | ETA 00:53:17
2022-11-02 16:46:34 [INFO]	[TRAIN] epoch: 12, iter: 71870/100000, loss: 0.9537, lr: 0.000040, batch_cost: 0.1062, reader_cost: 0.00017, ips: 37.6595 samples/sec | ETA 00:49:47
2022-11-02 16:46:35 [INFO]	[TRAIN] epoch: 12, iter: 71880/100000, loss: 0.5440, lr: 0.000040, batch_cost: 0.1058, reader_cost: 0.00038, ips: 37.8226 samples/sec | ETA 00:49:33
2022-11-02 16:46:36 [INFO]	[TRAIN] epoch: 12, iter: 71890/100000, loss: 0.6677, lr: 0.000040, batch_cost: 0.1055, reader_cost: 0.00039, ips: 37.9004 samples/sec | ETA 00:49:26
2022-11-02 16:46:37 [INFO]	[TRAIN] epoch: 12, iter: 71900/100000, loss: 1.1156, lr: 0.000040, batch_cost: 0.1116, reader_cost: 0.00016, ips: 35.8472 samples/sec | ETA 00:52:15
2022-11-02 16:46:38 [INFO]	[TRAIN] epoch: 12, iter: 71910/100000, loss: 0.9631, lr: 0.000040, batch_cost: 0.1089, reader_cost: 0.00015, ips: 36.7315 samples/sec | ETA 00:50:58
2022-11-02 16:46:40 [INFO]	[TRAIN] epoch: 12, iter: 71920/100000, loss: 0.6862, lr: 0.000040, batch_cost: 0.1127, reader_cost: 0.00032, ips: 35.4989 samples/sec | ETA 00:52:44
2022-11-02 16:46:41 [INFO]	[TRAIN] epoch: 12, iter: 71930/100000, loss: 0.7678, lr: 0.000040, batch_cost: 0.1108, reader_cost: 0.00015, ips: 36.1009 samples/sec | ETA 00:51:50
2022-11-02 16:46:42 [INFO]	[TRAIN] epoch: 12, iter: 71940/100000, loss: 0.9305, lr: 0.000040, batch_cost: 0.1055, reader_cost: 0.00034, ips: 37.9139 samples/sec | ETA 00:49:20
2022-11-02 16:46:43 [INFO]	[TRAIN] epoch: 12, iter: 71950/100000, loss: 0.7990, lr: 0.000040, batch_cost: 0.1077, reader_cost: 0.00055, ips: 37.1369 samples/sec | ETA 00:50:21
2022-11-02 16:46:44 [INFO]	[TRAIN] epoch: 12, iter: 71960/100000, loss: 0.9393, lr: 0.000040, batch_cost: 0.1112, reader_cost: 0.00017, ips: 35.9829 samples/sec | ETA 00:51:57
2022-11-02 16:46:45 [INFO]	[TRAIN] epoch: 12, iter: 71970/100000, loss: 0.7939, lr: 0.000040, batch_cost: 0.1104, reader_cost: 0.00036, ips: 36.2170 samples/sec | ETA 00:51:35
2022-11-02 16:46:46 [INFO]	[TRAIN] epoch: 12, iter: 71980/100000, loss: 0.9477, lr: 0.000040, batch_cost: 0.1096, reader_cost: 0.00015, ips: 36.4884 samples/sec | ETA 00:51:11
2022-11-02 16:46:47 [INFO]	[TRAIN] epoch: 12, iter: 71990/100000, loss: 1.0675, lr: 0.000040, batch_cost: 0.1174, reader_cost: 0.00015, ips: 34.0752 samples/sec | ETA 00:54:48
2022-11-02 16:46:49 [INFO]	[TRAIN] epoch: 12, iter: 72000/100000, loss: 0.9235, lr: 0.000040, batch_cost: 0.1198, reader_cost: 0.00018, ips: 33.3805 samples/sec | ETA 00:55:55
2022-11-02 16:46:49 [INFO]	Start evaluating (total_samples: 6383, total_iters: 6383)...
2022-11-02 16:50:06 [INFO]	[EVAL] #Images: 6383 mIoU: 0.6848 Acc: 0.9968 Kappa: 0.7673 Dice: 0.7884
2022-11-02 16:50:06 [INFO]	[EVAL] Class IoU: 
[0.9968 0.6508 0.4068]
2022-11-02 16:50:06 [INFO]	[EVAL] Class Precision: 
[0.998  0.8252 0.727 ]
2022-11-02 16:50:06 [INFO]	[EVAL] Class Recall: 
[0.9988 0.7549 0.4801]
2022-11-02 16:50:06 [INFO]	[EVAL] The model with the best validation mIoU (0.6940) was saved at iter 70000.

**Comment by wuyefeilin** [comment]
<img width="553" alt="image" src="https://user-images.githubusercontent.com/30919197/199446453-ba041a76-6cc0-4a8c-aba3-ba884c314cb5.png">

**Comment by chen-del** [comment]
嗯嗯我好像知道了新的版本是这样的， 这个acc精度是0.99 但是后面的appa似乎效过并没有跟上来，kappa系数偏低没有达到0.93%

2022-11-02 03:56:13 [INFO]	[TRAIN] epoch: 16, iter: 99880/100000, loss: 0.7920, lr: 0.000000, batch_cost: 0.1767, reader_cost: 0.00040, ips: 22.6394 samples/sec | ETA 00:00:21
2022-11-02 03:56:15 [INFO]	[TRAIN] epoch: 16, iter: 99890/100000, loss: 1.0558, lr: 0.000000, batch_cost: 0.1419, reader_cost: 0.00026, ips: 28.1882 samples/sec | ETA 00:00:15
2022-11-02 03:56:16 [INFO]	[TRAIN] epoch: 16, iter: 99900/100000, loss: 0.7914, lr: 0.000000, batch_cost: 0.1181, reader_cost: 0.00017, ips: 33.8659 samples/sec | ETA 00:00:11
2022-11-02 03:56:17 [INFO]	[TRAIN] epoch: 16, iter: 99910/100000, loss: 0.6313, lr: 0.000000, batch_cost: 0.1167, reader_cost: 0.00017, ips: 34.2751 samples/sec | ETA 00:00:10
2022-11-02 03:56:19 [INFO]	[TRAIN] epoch: 16, iter: 99920/100000, loss: 0.6134, lr: 0.000000, batch_cost: 0.1303, reader_cost: 0.00020, ips: 30.6884 samples/sec | ETA 00:00:10
2022-11-02 03:56:20 [INFO]	[TRAIN] epoch: 16, iter: 99930/100000, loss: 1.2362, lr: 0.000000, batch_cost: 0.1446, reader_cost: 0.00059, ips: 27.6574 samples/sec | ETA 00:00:10
2022-11-02 03:56:21 [INFO]	[TRAIN] epoch: 16, iter: 99940/100000, loss: 0.6886, lr: 0.000000, batch_cost: 0.1323, reader_cost: 0.00021, ips: 30.2446 samples/sec | ETA 00:00:07
2022-11-02 03:56:23 [INFO]	[TRAIN] epoch: 16, iter: 99950/100000, loss: 0.8378, lr: 0.000000, batch_cost: 0.1159, reader_cost: 0.00016, ips: 34.5112 samples/sec | ETA 00:00:05
2022-11-02 03:56:24 [INFO]	[TRAIN] epoch: 16, iter: 99960/100000, loss: 0.8077, lr: 0.000000, batch_cost: 0.1456, reader_cost: 0.00109, ips: 27.4778 samples/sec | ETA 00:00:05
2022-11-02 03:56:26 [INFO]	[TRAIN] epoch: 16, iter: 99970/100000, loss: 0.7490, lr: 0.000000, batch_cost: 0.1815, reader_cost: 0.00130, ips: 22.0395 samples/sec | ETA 00:00:05
2022-11-02 03:56:28 [INFO]	[TRAIN] epoch: 16, iter: 99980/100000, loss: 0.9520, lr: 0.000000, batch_cost: 0.1876, reader_cost: 0.00042, ips: 21.3181 samples/sec | ETA 00:00:03
2022-11-02 03:56:30 [INFO]	[TRAIN] epoch: 16, iter: 99990/100000, loss: 0.7256, lr: 0.000000, batch_cost: 0.2114, reader_cost: 0.02613, ips: 18.9259 samples/sec | ETA 00:00:02
2022-11-02 03:56:32 [INFO]	[TRAIN] epoch: 16, iter: 100000/100000, loss: 0.6402, lr: 0.000000, batch_cost: 0.2351, reader_cost: 0.04643, ips: 17.0173 samples/sec | ETA 00:00:00
2022-11-02 03:56:32 [INFO]	Start evaluating (total_samples: 6383, total_iters: 6383)...
2022-11-02 04:01:13 [INFO]	[EVAL] #Images: 6383 mIoU: 0.7172 Acc: 0.9969 Kappa: 0.7830 Dice: 0.8182
2022-11-02 04:01:13 [INFO]	[EVAL] Class IoU: 
[0.9969 0.6653 0.4893]
2022-11-02 04:01:13 [INFO]	[EVAL] Class Precision: 
[0.9982 0.825  0.7078]
2022-11-02 04:01:13 [INFO]	[EVAL] Class Recall:
[0.9987 0.7747 0.6131]
2022-11-02 04:01:13 [INFO]	[EVAL] The model with the best validation mIoU (0.7197) was saved at iter 95000.
@wuyefeilin ，这个有什么办法提升上来嘛

**Comment by chen-del** [comment]
而且这个acc精度过高是因为我的样本中负样本居多，比例正负1:9的样子，所以只使用acc评估指标似乎效果也不是很好

**Comment by wuyefeilin** [comment]
样本不均衡可以使用dice loss和带权重的ce loss试试。

可以从数据增强方面入手，提升正样本的比例

**Comment by chen-del** [comment]
@wuyefeilin ,我也是第一次遇到这么复杂的场景，背景有时候和要分类类别特别像，正负比严重偏向负样本，dice loss 加上ce loss嘛，我好像使用过了dice loss 和 带了ce权重的focaloss但是明显出现了精确率比召回率还低了40%，误检更多了。

**Comment by wuyefeilin** [comment]
通过数据增强手段提升正样本比例可以试试哈。 另外适当增大训练的iters试试

**Comment by chen-del** [comment]
dataloader里面有没有判断正样本类别的函数，或者是统计图片不同像素点的函数。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月7日(周一) 上午10:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/PaddleSeg] dill loss 组合设置占比权重出现报错 (Issue #2683)




 
通过数据增强手段提升正样本比例可以试试哈。 另外适当增大训练的iters试试

**Comment by wuyefeilin** [comment]
这个没有哈，如果只是统计当前的不同类别的像素个数，可以直接使用np.unique(x, return_counts=True)

**Comment by chen-del** [comment]
@wuyefeilin ,尝试过了感觉还是差不多，但背景还是会出现意外的误分割，因为是红外数据集对于一些样本背景和分类特征区分不是很明显

**Comment by chen-del** [comment]
提升好像不是很明显
