### ISSUE TITLE
3Dslicer导入PaddleSeg/EISeg/med3d目录报错

### ISSUE THREAD

**Issue by Spinexiang** [PaddlePaddle/PaddleSeg#2718]
选择PaddleSeg/EISeg/med3d 目录，并点击加载对应模块，Slicer 进行加载后报错显示：没有paddleseg模块

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Slicer 5.0.3\lib\Python\Lib\imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "E:/GitHub/PaddleSeg/EISeg/med3d/EISegMed3D/EISegMed3D.py", line 45, in <module>
    import inference
  File "E:\GitHub\PaddleSeg\EISeg\med3d\EISegMed3D\inference\__init__.py", line 1, in <module>
    from .models import VNetModel
  File "E:\GitHub\PaddleSeg\EISeg\med3d\EISegMed3D\inference\models.py", line 212, in <module>
    from paddleseg.utils import uTraceback (most recent call last):
  File "E:/GitHub/PaddleSeg/EISeg/med3d/EISegMed3D/EISegMed3D.py", line 37, in <module>
    import paddleseg
ModuleNotFoundError: No module named 'paddleseg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Slicer 5.0.3\lib\Python\Lib\imp.py", line 169, in load_source
    module = _exec(spec, sys.modules[name])
  File "<frozen importlib._bootstrap>", line 613, in _exec
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "E:/GitHub/PaddleSeg/EISeg/med3d/EISegMed3D/EISegMed3D.py", line 42, in <module>
    slicer.util.pip_install("paddleseg")
  File "D:\Slicer 5.0.3\bin\Python\slicer\util.py", line 3527, in pip_install
    _executePythonModule('pip', args)
  File "D:\Slicer 5.0.3\bin\Python\slicer\util.py", line 3490, in _executePythonModule
    logProcessOutput(proc)
  File "D:\Slicer 5.0.3\bin\Python\slicer\util.py", line 3459, in logProcessOutput
    raise CalledProcessError(retcode, proc.args, output=proc.stdout, stderr=proc.stderr)
subprocess.CalledProcessError: Command '['D:/Slicer 5.0.3/bin/../bin\\PythonSlicer.EXE', '-m', 'pip', 'install', 'paddleseg']' returned non-zero exit status 1.
The module factory manager reported an error. One or more of the requested module(s) and/or dependencies thereof may not have been loaded.
tils
ModuleNotFoundError: No module named 'paddleseg'

**Comment by shiyutang** [comment]
在slicer 的python解释器中输入下面的指令：

```bash
os.system(f"'{sys.executable}' -m pip install paddleseg simpleitk")
```

**Comment by masamimayu** [comment]
> 在slicer 的python解释器中输入下面的指令：
> 
> ```shell
> os.system(f"'{sys.executable}' -m pip install paddleseg simpleitk")
> ```

安装后会提示ERROR: No .egg-info directory found in C:\Users\masami\AppData\Local\Temp\pip-pip-egg-info-e42vy5mz

**Comment by shiyutang** [comment]
尝试升级setuptools，这里有一个相关的帖子：https://github.com/actions/setup-python/issues/165

**Comment by shiyutang** [comment]
尝试下面代码可以消除错误。
```
"D:/xxxx/Slicer 5.0.3/bin/PythonSlicer.exe" -m pip uninstall setuptools
```
