### ISSUE TITLE
Cannot export EMANet models

### ISSUE THREAD

**Issue by ukoehler** [PaddlePaddle/PaddleSeg#2724]
System:
Windows 10
Python 3.9.13
paddle-bfloat 0.1.7
paddle2onnx 1.0.1
paddlefsl 1.1.0
paddlehub 2.3.0
paddlenlp 2.4.1
paddlepaddle 2.3.2
paddleseg 2.6.0

Executing the following command to export EMANet (I tried emanet_resnet101_os8_cityscapes_1024x512_80k and emanet_resnet101_os8_voc12aug_512x512_40k)
```
(.venv) D:\Local\devel\Python\PaddleSeg\PaddleSeg>python export.py --config conf
igs/emanet/emanet_resnet101_os8_voc12aug_512x512_40k.yml --model_path EMANet/ema
net_resnet101_os8_voc12aug_512x512_40k/model.pdparams --save_dir EMANet/emanet_r
esnet101_os8_voc12aug_512x512_40k --without_argmax --with_softmax --input_shape
1 3 512 512
```
leads to following error
```
2022-11-16 10:45:19 [INFO]      Loading pretrained model from https://bj.bcebos.
com/paddleseg/dygraph/resnet101_vd_ssld.tar.gz
2022-11-16 10:45:21 [INFO]      There are 530/530 variables loaded into ResNet_v
d.
D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dygraph\lay
ers.py:1492: UserWarning: Skip loading for head.cls.1.weight. head.cls.1.weight
receives a shape [19, 256, 1, 1], but the expected shape is [21, 256, 1, 1].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dygraph\lay
ers.py:1492: UserWarning: Skip loading for head.cls.1.bias. head.cls.1.bias rece
ives a shape [19], but the expected shape is [21].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dygraph\lay
ers.py:1492: UserWarning: Skip loading for head.aux.2.weight. head.aux.2.weight
receives a shape [19, 256, 1, 1], but the expected shape is [21, 256, 1, 1].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dygraph\lay
ers.py:1492: UserWarning: Skip loading for head.aux.2.bias. head.aux.2.bias rece
ives a shape [19], but the expected shape is [21].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
2022-11-16 10:45:24 [INFO]      Loaded trained params of model successfully.
[main 2022-11-16T09:45:25.803Z] update#setState checking for updates
[main 2022-11-16T09:45:25.807Z] update#setState available for download
D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dygraph\dyg
raph_to_static\grad_transformer.py:87: UserWarning: paddle.no_grad is only suppo
rted for inference model, and not supported for training under @to_static.
  warnings.warn(
Traceback (most recent call last):
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\export.py", line 144, in <modu
le>
    main(args)
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\export.py", line 123, in main
    paddle.jit.save(new_net, save_path)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\jit.py", line 631, in wrapper
    func(layer, path, input_spec, **configs)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\decorator.py", l
ine 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\wra
pped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\jit.py", line 860, in save
    concrete_program = static_func.concrete_program_specify_input_spec(
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\dygraph_to_static\program_translator.py", line 527, in concrete_program_spe
cify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\dygraph_to_static\program_translator.py", line 436, in get_concrete_program

    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\dygraph_to_static\program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\dygraph_to_static\program_translator.py", line 785, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\decorator.py", l
ine 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\wra
pped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\dygraph_to_static\program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\dygraph_to_static\error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\export.py", line 74, in forw
ard
        outs = self.net(x)
    File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\paddleseg\models\emanet.py",
 line 77, in forward
        logit_list = self.head(feats)
    File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\paddleseg\models\emanet.py",
 line 151, in forward
        recon = self.emau(feats)
    File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\paddleseg\models\emanet.py",
 line 197, in forward
        for i in range(self.stage_num):
            x_t = paddle.transpose(x, [0, 2, 1])
            z = paddle.bmm(x_t, mu)
            ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            z = F.softmax(z, axis=2)
            z_ = F.normalize(z, axis=1, p=1)

    File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\tensor\
linalg.py", line 1408, in bmm
        raise ValueError(

    ValueError: x's batch (shape[0]) must be equal with y's batch (shape[0]). Bu
t received x's shape: (1, 4096, 512), y's shape: (-1, 512, 64)

```

**Comment by Bobholamovic** [comment]
Please try `--input_shape -1 3 512 512`.

**Comment by ukoehler** [comment]
Dear @Bobholamovic, 

I tried you workaround and managed to create a ONNX that opens fine in Netron. However, my inference engine OpenCV will not read the ONNX and I cannot tell if the resulting ONNX produces sensible results.

See https://github.com/opencv/opencv/issues/22823

**Comment by Bobholamovic** [comment]
Seems that some layer in the ONNX file has not been correctly registered, and this function returns an empty pointer:

https://github.com/opencv/opencv/blob/347246901eccabe503985a64f16813ca859af25a/modules/dnn/src/layer_factory.cpp#L88

Perhaps you can seek help from the Paddle2ONNX developers as well.

**Comment by ukoehler** [comment]
Thanks,

it is not the first time OpenCV fails to import valid ONNX. I will wait for OpenCV feedback, since Netron opens the ONNX file exported by Paddle2ONNX just fine.

**Comment by ukoehler** [comment]
No changes for version 2.7.0

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
