### ISSUE TITLE
[Bug]Panoptic-Deeplab 全景分割使用predict.py推理时报错

### ISSUE THREAD

**Issue by yrksteven** [PaddlePaddle/PaddleSeg#2727]
欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：paddleseg-2.6.0
 2. PaddlePaddle版本：2.3.2
 3. 操作系统信息：Linux
 4. Python版本号：Python3.9
 5. CUDA/cuDNN版本：Cuda 11.6 /cuDNN Version: 8.4
 6. 完整的代码：(若修改过原代码，请提供修改前后代码对比）
 7. 详细的错误信息、相关log：（若使用多卡，log默认保存在log/worklog.0）
 8. 运行指令或复现步骤：
python predict.py --config configs/panoptic_deeplab/panoptic_deeplab_resnet50_os32_cityscapes_1025x513_bs8_90k_lr00005.yml --model_path output/iter_90000/model.pdparams --image_path data/cityscapes/leftImg8bit/val/ --save_dir output/result

 10. 其他内容: （增加其他与问题相关的内容）

W1116 16:58:28.025022 131316 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.6
W1116 16:58:28.025050 131316 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
2022-11-16 16:58:30 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
2022-11-16 16:58:30 [INFO]	There are 275/275 variables loaded into ResNet_vd.
2022-11-16 16:58:30 [INFO]	Number of predict images = 500
2022-11-16 16:58:31 [INFO]	Loading pretrained model from output_new/iter_90000/model.pdparams
2022-11-16 16:58:31 [INFO]	There are 461/461 variables loaded into PanopticDeepLab.
2022-11-16 16:58:31 [INFO]	Start to predict...
Traceback (most recent call last):
  File "/home/kangkang/PaddleSeg/contrib/PanopticDeepLab/predict.py", line 148, in <module>
    main(args)
  File "/home/kangkang/PaddleSeg/contrib/PanopticDeepLab/predict.py", line 130, in main
    predict(
  File "/home/kangkang/PaddleSeg/contrib/PanopticDeepLab/core/predict.py", line 111, in predict
    im, _ = transforms(ori_im)
  File "/home/kangkang/anaconda3/envs/mypaddle/lib/python3.9/site-packages/paddleseg-2.6.0-py3.9.egg/paddleseg/transforms/transforms.py", line 56, in __call__
AttributeError: 'numpy.ndarray' object has no attribute 'keys'

**Comment by Bobholamovic** [comment]
你好，Panoptic-Deeplab无法适应新版本PaddleSeg API，请降级PaddleSeg到v2.5.0版本后尝试。

**Comment by yrksteven** [comment]
降级后推理成功了
