### ISSUE TITLE
[Bug]semantic2instance.py转换EISeg的数据报错error: (-210:Unsupported format or combination of formats) [Start]FindContours supports only CV_8UC1 images when mode != CV_RETR_FLOODFILL otherwise supports CV_32SC1 images only in function 'cvStartFindContours_Impl'

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleSeg#2733]
```
paddlepaddle-gpu       0.0.0.post116
paddleseg              2.6.0
opencv-python          4.6.0.66
opencv-python-headless 4.6.0.66
```

`python semantic2instance.py -o F:\00Biaozhu\SEG\label -d F:\00Biaozhu\SEG\save_path`

```


  0%|                                                                                           | 0/52 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "semantic2instance.py", line 77, in <module>
    _segMaskB2I(label, saver)
  File "semantic2instance.py", line 37, in _segMaskB2I
    results = cv2.findContours(img, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)
cv2.error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\contours.cpp:197: error: (-210:Unsupported format or combination of formats) [Start]FindContours supports only CV_8UC1 images when mode != CV_RETR_FLOODFILL otherwise supports CV_32SC1 images only in function 'cvStartFindContours_Impl'
```

图片目录
-- *.jpg

label 
00001.png
00001_cutout.png
00001_pseudo.png
00002.png
00002_cutout.png
00002_pseudo.png
.....

save_path 文件夹
只有00001.png

**Comment by monkeycc** [comment]
原来要把所有 _cutout  _pseudo 删除
