### ISSUE TITLE
Cannot export GSCNN models

### ISSUE THREAD

**Issue by ukoehler** [PaddlePaddle/PaddleSeg#2760]
System:
Windows 10
Python 3.9.13
paddle-bfloat 0.1.7
paddle2onnx 1.0.1
paddlefsl 1.1.0
paddlehub 2.3.0
paddlenlp 2.4.1
paddlepaddle 2.3.2
paddleseg 2.6.0

Executing the following command to export GSCNN:
```
(.venv) D:\Local\devel\Python\PaddleSeg\PaddleSeg>python export.py --config conf
igs/gscnn/gscnn_resnet50_os8_cityscapes_1024x512_80k.yml --model_path GSCNN/mode
l.pdparams --save_dir GSCNN --without_argmax --with_softmax --input_shape 1 3 10
24 512
```
leads to the following error message:
```
2022-11-24 14:37:59 [INFO]      Loading pretrained model from https://bj.bcebos.
com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
2022-11-24 14:38:00 [INFO]      There are 275/275 variables loaded into ResNet_v
d.
2022-11-24 14:38:02 [INFO]      Loaded trained params of model successfully.
Traceback (most recent call last):
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\export.py", line 144, in <modu
le>
    main(args)
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\export.py", line 123, in main
    paddle.jit.save(new_net, save_path)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\jit.py", line 631, in wrapper
    func(layer, path, input_spec, **configs)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\decorator.py", l
ine 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\wra
pped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\jit.py", line 860, in save
    concrete_program = static_func.concrete_program_specify_input_spec(
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\dygraph_to_static\program_translator.py", line 527, in concrete_program_spe
cify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\dygraph_to_static\program_translator.py", line 436, in get_concrete_program

    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\dygraph_to_static\program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\dygraph_to_static\program_translator.py", line 785, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\decorator.py", l
ine 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\wra
pped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\dygraph_to_static\program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\dygraph_to_static\error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
TypeError: In transformed code:

    File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\export.py", line 74, in forw
ard
        outs = self.net(x)
    File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\paddleseg\models\gscnn.py",
line 69, in forward
        logit_list = self.head(x, feat_list, self.backbone.conv1_logit)
    File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\paddleseg\models\gscnn.py",
line 173, in forward
        im_arr = x.numpy().transpose((0, 2, 3, 1))
        im_arr = ((im_arr * 0.5 + 0.5) * 255).astype(np.uint8)
        canny = np.zeros((input_shape[0], 1, input_shape[2], input_shape[3]))
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <-
-- HERE
        for i in range(input_shape[0]):
            canny[i] = cv2.Canny(im_arr[i], 10, 100)


    TypeError: 'Variable' object cannot be interpreted as an integer
```

**Comment by shiyutang** [comment]
It is true. I am trying to fix this asap.

**Comment by shiyutang** [comment]
Currently, the static graph doesn't support converting tensor to numpy and calculating. If you really desire to use this model, you can try to replace the cv2.canny in the following image with convolution:
<img width="597" alt="image" src="https://user-images.githubusercontent.com/34859558/203955498-8365ae15-783c-47aa-841a-31bab60dd8d5.png">

**Comment by ukoehler** [comment]
No changes for version 2.7.0

**Comment by shiyutang** [comment]
You need to change the OpenCV canny edge detector with the convolution operator, you can refer to the detail loss of STDC: https://github.com/PaddlePaddle/PaddleSeg/blob/release%2F2.5/paddleseg/models/losses/detail_aggregate_loss.py

**Comment by luoqianhao** [comment]
Has this bug been fixed?
