### ISSUE TITLE
eiseg

### ISSUE THREAD

**Issue by 983183947** [PaddlePaddle/PaddleSeg#2777]
eiseg在m1芯片的mac上会无法安装，pyqt5好像不支持m1
% python exe.py  
Traceback (most recent call last):
  File "/Users/AI/PaddleSeg-release-2.6/EISeg/eiseg/exe.py", line 20, in <module>
    from run import main
  File "/Users/AI/PaddleSeg-release-2.6/EISeg/eiseg/run.py", line 21, in <module>
    from qtpy.QtWidgets import QApplication  # 导入PyQt相关模块
  File "/Users/zhengzijian/miniforge3/envs/paddle_env2/lib/python3.9/site-packages/qtpy/QtWidgets.py", line 14, in <module>
    from PyQt5.QtWidgets import *
ImportError: dlopen(/Users/zhengzijian/miniforge3/envs/paddle_env2/lib/python3.9/site-packages/PyQt5/QtWidgets.abi3.so, 0x0002): tried: '/Users/zhengzijian/Documents/soft/instantclient_19_8/QtWidgets.abi3.so' (no such file), '/Users/zhengzijian/miniforge3/envs/paddle_env2/lib/python3.9/site-packages/PyQt5/QtWidgets.abi3.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))

**Comment by haoyuying** [comment]
您好，建议您从qt社区寻找下解决方案。

**Comment by Harryoung** [comment]
您好，MacOS操作系统请不要使用`python exe.py`，需要使用`python -m eiseg`。如果依然报PyQt5包的错误，可以参考这里https://zhuanlan.zhihu.com/p/497492385.
