### ISSUE TITLE
[Bug] Cannot predict or export PortraitNet: __init__() got an unexpected keyword argument 'channel_ratio'

### ISSUE THREAD

**Issue by ukoehler** [PaddlePaddle/PaddleSeg#2792]
System:
Windows 10
Python 3.9.13
paddle-bfloat 0.1.7
paddle2onnx 1.0.1
paddlefsl 1.1.0
paddlehub 2.3.0
paddlenlp 2.4.1
paddlepaddle 2.3.2
paddleseg 2.6.0

Executing the following command to predict PortraitNet:
```
(.venv) D:\Local\devel\Python\PaddleSeg\PaddleSeg>python predict.py --config con
figs/portraitnet/portraitnet_eg1800_224x224_46k.yml --model_path PortraitNet/por
traitnet_eg1800_224x224_46k/model.pdparams --image_path "D:\Local\devel\Python\T
estImages\Input" --save_dir PortraitNet/portraitnet_eg1800_224x224_46k
```

leads to the following error
```
2022-11-30 15:01:38 [INFO]
---------------Config Information---------------
batch_size: 64
iters: 46000
loss:
  coef:
  - 1
  - 1
  - 0.3
  - 2
  types:
  - type: CrossEntropyLoss
  - type: CrossEntropyLoss
  - type: FocalLoss
  - type: KLLoss
lr_scheduler:
  gamma: 0.95
  learning_rate: 0.001
  step_size: 460
  type: StepDecay
model:
  add_edge: true
  backbone:
    channel_ratio: 1.0
    min_channel: 16
    pretrained: https://paddleseg.bj.bcebos.com/dygraph/backbone/mobilenetv2_x1_
0_ssld.tar.gz
    type: MobileNetV2_x1_0
  num_classes: 2
  type: PortraitNet
optimizer:
  type: adam
  weight_decay: 0.0005
train_dataset:
  common_transforms:
  - max_rotation: 45
    max_scale_factor: 1.5
    min_scale_factor: 0.5
    size:
    - 224
    - 224
    translation_offset: 56
    type: RandomAffine
  - type: RandomHorizontalFlip
  dataset_root: data/EG1800
  mode: train
  transforms1:
  - mean:
    - 0.485
    - 0.458
    - 0.408
    std:
    - 0.23
    - 0.23
    - 0.23
    type: Normalize
  transforms2:
  - brightness_range: 0.6
    contrast_range: 0.4
    hue_prob: 0.0
    saturation_range: 0.6
    sharpness_prob: 0.5
    sharpness_range: 0.2
    type: RandomDistort
  - blur_type: random
    prob: 0.5
    type: RandomBlur
  - type: RandomNoise
  - mean:
    - 0.485
    - 0.458
    - 0.408
    std:
    - 0.23
    - 0.23
    - 0.23
    type: Normalize
  type: EG1800
val_dataset:
  common_transforms:
  - im_padding_value:
    - 127.5
    - 127.5
    - 127.5
    label_padding_value: 0
    target_size:
    - 224
    - 224
    type: ScalePadding
  - mean:
    - 0.485
    - 0.458
    - 0.408
    std:
    - 0.23
    - 0.23
    - 0.23
    type: Normalize
  dataset_root: data/EG1800
  mode: val
  transforms1: null
  transforms2: null
  type: EG1800
------------------------------------------------
Traceback (most recent call last):
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\predict.py", line 185, in <mod
ule>
    main(args)
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\predict.py", line 166, in main

    model = cfg.model
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\paddleseg\cvlibs\config.py", l
ine 347, in model
    self._model = self._load_object(model_cfg)
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\paddleseg\cvlibs\config.py", l
ine 405, in _load_object
    params[key] = self._load_object(val)
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\paddleseg\cvlibs\config.py", l
ine 414, in _load_object
    return component(**params)
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\paddleseg\models\backbones\mob
ilenetv2.py", line 251, in MobileNetV2_x1_0
    model = MobileNetV2(scale=1.0, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'channel_ratio'
```

same for exporting
```
(.venv) D:\Local\devel\Python\PaddleSeg\PaddleSeg>python export.py --config conf
igs/portraitnet/portraitnet_eg1800_224x224_46k.yml --model_path PortraitNet/port
raitnet_eg1800_224x224_46k/model.pdparams --save_dir PortraitNet/portraitnet_eg1
800_224x224_46k --without_argmax --with_softmax --input_shape -1 3 224 224
```
will give this error
```
Traceback (most recent call last):
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\export.py", line 144, in <modu
le>
    main(args)
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\export.py", line 99, in main
    net = cfg.model
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\paddleseg\cvlibs\config.py", l
ine 347, in model
    self._model = self._load_object(model_cfg)
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\paddleseg\cvlibs\config.py", l
ine 405, in _load_object
    params[key] = self._load_object(val)
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\paddleseg\cvlibs\config.py", l
ine 414, in _load_object
    return component(**params)
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\paddleseg\models\backbones\mob
ilenetv2.py", line 251, in MobileNetV2_x1_0
    model = MobileNetV2(scale=1.0, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'channel_ratio'
```
Same happens for the ```supervisely``` version

**Comment by Bobholamovic** [comment]
Hi, this is a bug and I have fixed it in #2797 .
