### ISSUE TITLE
[Bug]windows python 3.9推理paddlereg 2.7.0版本PPmattingV2 报错

### ISSUE THREAD

**Issue by williamlzw** [PaddlePaddle/PaddleSeg#2828]
[Bug]windows python 3.9推理paddlereg 2.7.0版本PPmattingV2 报错

PS D:\PaddleSeg-2.7.0> python tools/predict.py --config D:/ppmatting-hrnet_w18-human_512/ppmattingv2-stdc1-human_512.yml --model_path D:/ppmatting-hrnet_w18-human_512/ppmattingv2-stdc1-human_512.pdparams --image_path D:/microocr.net/data/reg.png --save_dir ./output/results
Traceback (most recent call last):
  File "D:\PaddleSeg-2.7.0\tools\predict.py", line 192, in <module>
    main(args)
  File "D:\PaddleSeg-2.7.0\tools\predict.py", line 166, in main
    cfg.check_sync_info()
  File "E:\Python\Python39\lib\site-packages\paddleseg\cvlibs\config.py", line 478, in check_sync_info
    self._check_sync_num_classes()
  File "E:\Python\Python39\lib\site-packages\paddleseg\cvlibs\config.py", line 487, in _check_sync_num_classes
    if hasattr(self.train_dataset_class, 'NUM_CLASSES'):
  File "E:\Python\Python39\lib\site-packages\paddleseg\cvlibs\config.py", line 387, in train_dataset_class
    return self._load_component(dataset_type)
  File "E:\Python\Python39\lib\site-packages\paddleseg\cvlibs\config.py", line 418, in _load_component
    raise RuntimeError(
RuntimeError: The specified component was not found MattingDataset.

**Comment by wuyefeilin** [comment]
请进入Matting目录运行，另外可以先看一下文档哈

**Comment by ababalaa** [comment]
大家有windows×64的opencv-python的包吗，我在anaconda官网没有找到，可以用opencv替代 opencv-pyhton吗

**Comment by wuyefeilin** [comment]
可以自己编译一个

**Comment by shiyutang** [comment]
由于长期没有回复，本条issue关闭。
