### ISSUE TITLE
[Bug]prune.py问题

### ISSUE THREAD

**Issue by OpenCDR** [PaddlePaddle/PaddleSeg#2829]
欢迎您反馈PaddleSeg使用问题，辛苦您提供以下信息，方便我们快速定位和解决问题：
 1. PaddleSeg版本：PaddleSeg release/2.3
 2. PaddlePaddle版本：如PaddlePaddle 2.3.2
 3. 操作系统信息：Linux
 4. Python版本号：Python3.8
 5. CUDA/cuDNN版本：CUDA11.6/cuDNN 8.4.0
 
使用delop/slim/prune/prune.py时，报错：
`paddlepaddle version: 2.3.2.

/home/xxx/anaconda3/envs/paddleSeg/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
W1210 14:45:21.750331  5789 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 11.6
W1210 14:45:21.750349  5789 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
2022-12-10 14:45:22 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet2.tar.gz
2022-12-10 14:45:22 [INFO]	There are 265/265 variables loaded into STDCNet.
2022-12-10 14:45:22 [INFO]	Loaded trained params of model successfully
2022-12-10 14:45:22 [INFO]	Step 1/3: Start calculating the sensitivity of model parameters...
Traceback (most recent call last):
  File "deploy/slim/prune/prune.py", line 208, in <module>
    main(args)
  File "deploy/slim/prune/prune.py", line 156, in main
    sample_shape = [1] + list(train_dataset[0][0].shape)
KeyError: 0
`
请问这是出现了什么问题呢？

**Comment by Bobholamovic** [comment]
你好，这是一个旧脚本不适配新版本 API 导致的 bug，我们正在修复中，你可以在 #2833 即时查看PR进展。感谢反馈~
