### ISSUE TITLE
跑PP-MattingV2的demo，fg_estimate设为True，会报ValueError: negative dimensions not allowed错误

### ISSUE THREAD

**Issue by zhenhao-huang** [PaddlePaddle/PaddleSeg#2835]
跑PP-MattingV2的demo，fg_estimate设为True，会报ValueError: negative dimensions not allowed错误，跑自己的也会

**Comment by zhenhao-huang** [comment]
如何用视频进行预测

**Comment by wuyefeilin** [comment]
麻烦给一下详细的报错信息

**Comment by wuyefeilin** [comment]
> 如何用视频进行预测

视频预测功能正在实现中，预计这周可以实现，敬请期待哈

**Comment by zhenhao-huang** [comment]
> 麻烦给一下详细的报错信息

    2022-12-13 19:17:07 [INFO]      Start to predict...
    Traceback (most recent call last):
        File "tools/predict.py", line 113, in <module>
            main(args)
        File "tools/predict.py", line 100, in main
            predict(
        File "C:\Users\hzh\Desktop\hzh\PaddleSeg-release-2.7\Matting\tools\..\ppmatting\core\predict.py", line 183, in predict
            fg = save_result(
        File "C:\Users\hzh\Desktop\hzh\PaddleSeg-release-2.7\Matting\tools\..\ppmatting\core\predict.py", line 59, in save_result
            fg = estimate_foreground_ml(im / 255.0, alpha / 255.0) * 255
        File "C:\Users\hzh\Desktop\hzh\PaddleSeg-release-2.7\Matting\tools\..\ppmatting\utils\estimate_foreground_ml.py", line 224, in estimate_foreground_ml
            foreground, background = _estimate_fb_ml(
    ValueError: negative dimensions not allowed

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
