### ISSUE TITLE
[Bug]最新2.7版本无法运行DEMO

### ISSUE THREAD

**Issue by yangtianyu92** [PaddlePaddle/PaddleSeg#2844]
快速开始Config修改了但是没有对train进行适配

 1. PaddleSeg版本：PaddleSeg release/2.7
 2. PaddlePaddle版本：如PaddlePaddle 2.1.0
 3. 操作系统信息：Linux
 4. Python版本号：Python3.7
 5. CUDA/cuDNN版本：CUDA10.2/cuDNN 7.6.5
 6. 完整的代码：(若修改过原代码，请提供修改前后代码对比）
 7. 详细的错误信息、相关log：（若使用多卡，log默认保存在log/worklog.0）
 8. 运行指令或复现步骤：
 9. 其他内容: （增加其他与问题相关的内容）
 λ 3cb542e88c0c /home/PaddleSeg python tools/train.py        --config configs/quick_start/pp_liteseg_optic_disc_512x512_1k.yml        --save_interval 500        --do_eval        --use_vdl        --save_dir output
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/python3.7.0/lib/python3.7/site-packages/paddleseg-2.5.0-py3.7.egg/paddleseg/models/losses/rmi_loss.py:78: DeprecationWarning: invalid escape sequence \i
/usr/local/python3.7.0/lib/python3.7/site-packages/paddleseg-2.5.0-py3.7.egg/paddleseg/models/losses/rmi_loss.py:78: DeprecationWarning: invalid escape sequence \i
2022-12-13 11:49:22 [INFO]	
------------Environment Information-------------
platform: Linux-4.15.0-29-generic-x86_64-with-debian-stretch-sid
Python: 3.7.0 (default, Jan 19 2022, 18:52:27) [GCC 8.2.0]
Paddle compiled with cuda: True
NVCC: Cuda compilation tools, release 10.2, V10.2.89
cudnn: 7.6
GPUs used: 1
CUDA_VISIBLE_DEVICES: 0
GPU: ['GPU 0: Tesla V100-SXM2-32GB', 'GPU 1: Tesla V100-SXM2-32GB', 'GPU 2: Tesla V100-SXM2-32GB', 'GPU 3: Tesla V100-SXM2-32GB', 'GPU 4: Tesla V100-SXM2-32GB', 'GPU 5: Tesla V100-SXM2-32GB', 'GPU 6: Tesla V100-SXM2-32GB', 'GPU 7: Tesla V100-SXM2-32GB']
GCC: gcc (GCC) 8.2.0
PaddleSeg: 2.5.0
PaddlePaddle: 2.2.2
OpenCV: 4.5.5
------------------------------------------------

None
Traceback (most recent call last):
  File "tools/train.py", line 259, in <module>
    main(args)
  File "tools/train.py", line 195, in main
    opts=args.opts)
TypeError: __init__() got an unexpected keyword argument 'opts'

**Comment by yangtianyu92** [comment]
我的错，DOCKER自带PaddleSeg版本和文档内所示不一致
