### ISSUE TITLE
[Bug] Cannot export SETR model

### ISSUE THREAD

**Issue by ukoehler** [PaddlePaddle/PaddleSeg#2850]
System:
Windows 10
Python 3.9.13
paddle-bfloat 0.1.7
paddle2onnx 1.0.1
paddlefsl 1.1.0
paddlehub 2.3.0
paddlenlp 2.4.1
paddlepaddle 2.3.2
paddleseg 2.6.0

Executing the following command to export SETR:
```
(.venv) D:\Local\devel\Python\PaddleSeg\PaddleSeg>python export.py --config conf
igs/setr/setr_pup_large_cityscapes_769x769_40k.yml --model_path SETR/model.pdpar
ams --save_dir SETR --without_argmax --with_softmax --input_shape 1 3 769 769
```
leads to the following error message:
```
2022-12-14 14:38:06 [INFO]      Loading pretrained model from https://bj.bcebos.
com/paddleseg/dygraph/vit_large_patch16_384.tar.gz
2022-12-14 14:38:14 [INFO]      There are 292/292 variables loaded into VisionTr
ansformer.
2022-12-14 14:38:32 [INFO]      Loaded trained params of model successfully.
Traceback (most recent call last):
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\export.py", line 144, in <modu
le>
    main(args)
  File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\export.py", line 123, in main
    paddle.jit.save(new_net, save_path)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\jit.py", line 631, in wrapper
    func(layer, path, input_spec, **configs)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\decorator.py", l
ine 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\wra
pped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\jit.py", line 860, in save
    concrete_program = static_func.concrete_program_specify_input_spec(
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\dygraph_to_static\program_translator.py", line 527, in concrete_program_spe
cify_input_spec
    concrete_program, _ = self.get_concrete_program(
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\dygraph_to_static\program_translator.py", line 436, in get_concrete_program

    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\dygraph_to_static\program_translator.py", line 801, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\dygraph_to_static\program_translator.py", line 785, in _build_once
    concrete_program = ConcreteProgram.from_func_spec(
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\decorator.py", l
ine 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\wra
pped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\base.py", line 51, in __impl__
    return func(*args, **kwargs)
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\dygraph_to_static\program_translator.py", line 740, in from_func_spec
    error_data.raise_new_exception()
  File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\dyg
raph\dygraph_to_static\error.py", line 336, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\export.py", line 74, in forw
ard
        outs = self.net(x)
    File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\paddleseg\models\setr.py", l
ine 93, in forward
        feats, _shape = self.backbone(x)
    File "D:\Local\devel\Python\PaddleSeg\PaddleSeg\paddleseg\models\backbones\v
ision_transformer.py", line 268, in forward
        if paddle.shape(x)[1] == self.pos_embed.shape[1]:
            x = x + self.pos_embed
            ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        else:
            x = x + self.resize_pos_embed(self.pos_embed,

    File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\l
ayers\math_op_patch.py", line 342, in __impl__
        current_block(self).append_op(
    File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\f
ramework.py", line 3615, in append_op
        op = Operator(
    File "D:\Local\devel\Python\PaddleSeg\.venv\lib\site-packages\paddle\fluid\f
ramework.py", line 2764, in __init__
        self.desc.infer_shape(self.block.desc)

    ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could n
ot be broadcast together with the shape of X = [1, 2305, 1024] and the shape of
Y = [1, 577, 1024]. Received [2305] in X is not equal to [577] in Y at i:1.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 ||
y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] ||
 x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at C:\home\workspac
e\Paddle_release\paddle/phi/kernels/funcs/common_shape.h:84)
  [operator < elementwise_add > error]
```

**Comment by Bobholamovic** [comment]
Please try running the command without setting `--input_shape`.

**Comment by ukoehler** [comment]
Yup, that works. However then it is followed by a Paddle2ONNX problem: https://github.com/PaddlePaddle/Paddle2ONNX/issues/986

**Comment by Bobholamovic** [comment]
This is probably because the control flow (such as `if` or `for` clauses) in the network cannot be easily translated into a static graph format like ONNX. I'm sorry that we do not have a workaround at present. One possible solution to this problem would be refactor the network implementation to remove the use of Python control flow.

**Comment by ukoehler** [comment]
No changes for version 2.7.0

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
