### ISSUE TITLE
关于PaddleSeg中使用知识蒸馏报错images = data[0]的问题

### ISSUE THREAD

**Issue by OroChippw** [PaddlePaddle/PaddleSeg#2899]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Traceback (most recent call last): File "slim/distill/distill_train.py", line 225, in main(args) File "slim/distill/distill_train.py", line 220, in main test_config=s_cfg.test_config, ) File "PaddleSeg-release-2.7/develop/slim/distill/distill_utils.py", line 183, in distill_train images = data[0] KeyError: 0
请问一下是我的配置文件出错，还是哪些地方不对，谢谢您~

**Comment by OroChippw** [comment]
已解决，data在seg中是个dict类型
将代码中的
images=data[0]
labels = data[1].astype('int64')
修改为
images=data['img']
labels = data['label'].astype('int64')
即可在paddleseg中进行知识蒸馏

**Comment by haoyuying** [comment]
您好，若您的问题解决，我们将关闭该issue， 若您有其他需求，可以重新打开本issue进行提问。
