### ISSUE TITLE
ESPNetV2网络静态图导出指定input_shape 时报错

### ISSUE THREAD

**Issue by Littlehong-ai** [PaddlePaddle/PaddleSeg#2904]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

PaddleSeg根目录下：
mkdir workspace && cd workspace
mkdir ESPNetV2 && cd ESPNetV2 
wget https://bj.bcebos.com/paddleseg/dygraph/cityscapes/espnet_cityscapes_1024x512_120k/model.pdparams
cd ../../
python tools/export.py        --config configs/espnet/espnet_cityscapes_1024x512_120k.yml     \
                                             --model_path ./workspace/ESPNetV2/model.pdparams  \
                                             --output_op none  \
                                             --save_dir  ./workspace/ESPNetV2/inference_model/  \
                                             --input_shape 1 3 1024 2048
报错log：
W0110 17:42:18.512054 29517 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.2
W0110 17:42:18.513270 29517 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
2023-01-10 17:42:19 [INFO]      Loaded trained params of model successfully.
/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/layers/control_flow.py:1361: UserWarning: In dy2static mode, we attemp to assign a variable with shape (1, 3, 512, 1024) into a variable with shape(1, 3, 1024, 2048), which is not always right.
  input.shape, output.shape
Traceback (most recent call last):
  File "tools/export.py", line 140, in <module>
    main(args)
  File "tools/export.py", line 115, in main
    paddle.jit.save(new_net, save_path)
  File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 649, in wrapper
    func(layer, path, input_spec, **configs)
  File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 67, in __impl__
    return func(*args, **kwargs)
  File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 928, in save
    inner_input_spec, with_hook=with_hook)
  File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 580, in concrete_program_specify_input_spec
    is_train=self._is_train_mode())
  File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 485, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 955, in __getitem__
    self._caches[item_id] = self._build_once(item)
  File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 944, in _build_once
    **cache_key.kwargs)
  File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 67, in __impl__
    return func(*args, **kwargs)
  File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 895, in from_func_spec
    error_data.raise_new_exception()
  File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 350, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
ValueError: In transformed code:

    File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddleseg/models/espnet.py", line 103, in forward
        out_l1, out_l2, out_l3, out_l4 = self.backbone(x)
    File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddleseg/models/espnet.py", line 451, in forward
        out_l2 = self.level2(out_l1, x)
    File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddleseg/models/espnet.py", line 340, in forward
        if inputs is not None:
    File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddleseg/models/espnet.py", line 350, in forward
            # import pdb
            # pdb.set_trace()
            output = output + self.shortcut_layer(inputs)
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        return self._act(output)

    File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 423, in __impl__
        attrs={'axis': axis})
    File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/framework.py", line 4023, in append_op
        attrs=kwargs.get("attrs", None),
    File "/LocalRun/kexin.hong/miniconda3/envs/paddle-gpu/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3016, in __init__
        self.desc.infer_shape(self.block.desc)

    ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 128, 256, 512] and the shape of Y = [1, 128, 512, 1024]. Received [256] in X is not equal to [512] in Y at i:2.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/phi/kernels/funcs/common_shape.h:84)
  [operator < elementwise_add > error]

**Comment by juncaipeng** [comment]
收到，不指定shape是可以的导出成预测模型的。 你是明确需要指定shape吗？

**Comment by Littlehong-ai** [comment]
> 

是的，所用硬件不支持动态shape， 需要指定
