### ISSUE TITLE
eiseg标注好之后的json文件怎么转成paddlex支持的格式

### ISSUE THREAD

**Issue by xxPete** [PaddlePaddle/PaddleSeg#2908]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

因为eiseg标注后保存的只是简单的一些信息，json保存的没办法直接用，coco保存的也有问题，我看文档发现说有支持转paddlex数据集的脚本，可是只找到了一个语义分割转实例分割的脚本，并没有发现转paddlex的

**Comment by haoyuying** [comment]
您好，coco保存的问题是什么呢，如果您本身保存了png格式的结果，可以直接用于paddlex。可以具体说下标注保存的问题吗？
eiseg2paddlex的使用及脚本在这里：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/EISeg/docs/tools_cn.md

**Comment by xxPete** [comment]
> 您好，coco保存的问题是什么呢，如果您本身保存了png格式的结果，可以直接用于paddlex。可以具体说下标注保存的问题吗？ eiseg2paddlex的使用及脚本在这里：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.4/EISeg/docs/tools_cn.md

我把生成的coco从label文件夹拿出来和JPEGImages，label放在同一路径下，把coco.json重命名为paddlex需要的annotations.json,导入数据集会出现以下报错
-------------------------
数据校验失败！

Traceback (most recent call last):
  File "paddlexui\pms\dataset\ins_seg_dataset.py", line 76, in check_dataset
  File "paddlexui\pms\dataset\utils.py", line 175, in read_coco_ann
  File "site-packages\pycocotools\coco.py", line 153, in getAnnIds
  File "site-packages\pycocotools\coco.py", line 153, in <listcomp>
KeyError: 'iscrowd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "paddlexui\pms\dataset\operate.py", line 42, in _check_and_copy
  File "paddlexui\pms\dataset\ins_seg_dataset.py", line 92, in check_dataset
Exception: 标注文件存在错误

**Comment by haoyuying** [comment]
您可以尝试用我提供的脚本进行转化。

**Comment by xxPete** [comment]
> 您可以尝试用我提供的脚本进行转化。

问题已经解决了，不过不是用你提供的脚本，那个脚本虽然能训练，但是效果惨不忍睹，哪个地方有问题我忘了，我后面看了一下eiseg自动生成的coco.json文件，对比了一下之前的正常的可训练文件，发现EISeg自动生成的文件缺少iscrowd这个变量，而且area的值也是0，解决办法是，给annotations列表里面的每个变量赋值iscrowd=0,并计算area的值复制给原本是0的area。修改过后的json文件跑paddlex的实例分割，12轮的map达到了79.3。

**Comment by haoyuying** [comment]
您好，我们会跟进该问题并进行修复，感谢您的反馈。
