### ISSUE TITLE
GPU宫格模式标注图片，点击完成宫格闪退

### ISSUE THREAD

**Issue by jenniferliu221** [PaddlePaddle/PaddleSeg#2912]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

已勾选自动保存，宫格模式标注结束后点击“完成宫格”，不能成功保存并闪退（只保存了黑色同尺寸图和_grid_saved.json文件），报错信息如下：
```Traceback (most recent call last):
  File "D:\Anaconda3\envs\paddle\lib\site-packages\eiseg\app.py", line 2784, in saveGridLabel
    encoding="utf-8").write(json.dumps(self.grid.json_labels))
  File "D:\Anaconda3\envs\paddle\lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "D:\Anaconda3\envs\paddle\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Anaconda3\envs\paddle\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "D:\Anaconda3\envs\paddle\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int32 is not JSON serializable```
![屏幕截图 2023-01-12 020744](https://user-images.githubusercontent.com/62126667/211884273-a5f614d7-fc3a-4d6b-a487-87f06853ca2c.png)


### 复现环境 Environment

- OS: Windows10
- paddlepaddle-gpu: 2.4.1
- paddleseg: 2.7.0
- Python: 3.7.15
- CUDA: 10.0
- CUDNN: 7.6.4
- GCC: 4.7.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.


### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Harryoung** [comment]
same question with #2895

**Comment by haoyuying** [comment]
您好，最新修复代码已经合入到develop分支，请尝试拉取最新代码进行测试。pr地址：https://github.com/PaddlePaddle/PaddleSeg/pull/2902

**Comment by geoyee** [comment]
@jenniferliu221 麻烦您从[develop分支](https://github.com/PaddlePaddle/PaddleSeg/tree/develop/EISeg)尝试下这个问题是否还存在。这个bug应该是有数字是ndarray类型，python内置的json库不知道如何序列化成字符串。在[这个](https://github.com/geoyee/PaddleSeg/commit/293bb1754dd2a1060a9943a4d1805bf5a959d167)修复中尝试将不同类型的ndarray转为int/float/list，应该能解决问题。如果还有问题欢迎继续沟通。
