### ISSUE TITLE
RTFormer训练异常：RuntimeError: The length of logits_list should equal to the types of loss config: 1 != 2.

### ISSUE THREAD

**Issue by ZzyChris97** [PaddlePaddle/PaddleSeg#2922]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

使用RTFormer训练分割模型的时候报异常
```
Traceback (most recent call last):
  File "/home/hr/projects/PaddleSeg/train.py", line 262, in <module>
    main(args)
  File "/home/hr/projects/PaddleSeg/train.py", line 235, in main
    train(
  File "/home/hr/projects/PaddleSeg/paddleseg/core/train.py", line 207, in train
    loss_list = loss_computation(
  File "/home/hr/projects/PaddleSeg/paddleseg/core/train.py", line 38, in loss_computation
    check_logits_losses(logits_list, losses)
  File "/home/hr/projects/PaddleSeg/paddleseg/core/train.py", line 32, in check_logits_losses
    raise RuntimeError(
RuntimeError: The length of logits_list should equal to the types of loss config: 1 != 2.

```
查看其他的issue，更改了loss的coef，异常信息变成了：
```
Traceback (most recent call last):
  File "/home/hr/projects/PaddleSeg/train.py", line 262, in <module>
    main(args)
  File "/home/hr/projects/PaddleSeg/train.py", line 235, in main
    train(
  File "/home/hr/projects/PaddleSeg/paddleseg/core/train.py", line 207, in train
    loss_list = loss_computation(
  File "/home/hr/projects/PaddleSeg/paddleseg/core/train.py", line 38, in loss_computation
    check_logits_losses(logits_list, losses)
  File "/home/hr/projects/PaddleSeg/paddleseg/core/train.py", line 32, in check_logits_losses
    raise RuntimeError(
RuntimeError: The length of logits_list should equal to the types of loss config: 2 != 1.
```
* 原来的loss：
  ```
  loss:
    types:
      - type: CrossEntropyLoss
    coef: [1, 0.4]
  ```
* 更改为：
  ```
  loss:
    types:
      - type: CrossEntropyLoss
    coef: [1]
  ```

完整的配置文件如下：
* rtformer.yml
```
_base_: '../_base_/cityscapes_hr.yml'

batch_size: 2 # total batch size:  4 * 3
iters: 16000
save_interval: 500
output_dir: output/hr
do_eval: True

train_dataset:
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 1024]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

val_dataset:
  transforms:
    - type: Resize
      target_size: [1024, 1024]
      keep_ratio: True
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  
export:
  transforms:
    - type: Resize
      target_size: [1024, 1024]
      keep_ratio: True
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

optimizer:
  _inherited_: False
  type: AdamW
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.0125

lr_scheduler:
  _inherited_: False
  type: PolynomialDecay
  learning_rate: 4.0e-4
  power: 1.
  end_lr: 1.0e-6
  warmup_iters: 1500
  warmup_start_lr: 1.0e-6

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1, 0.4]

model:
  type: RTFormer
  base_channels: 64
  head_channels: 128
  use_injection: [True, False]
  pretrained: https://paddleseg.bj.bcebos.com/dygraph/backbone/rtformer_base_backbone_imagenet_pretrained.zip
  num_classes: 2
```
* cityscapes_hr.yml
```
batch_size: 2
iters: 8000

train_dataset:
  type: Dataset
  dataset_root: /home/hr/projects/PaddleSeg/applications/fake_text_detection/data/create_data
  train_path: /home/hr/projects/PaddleSeg/applications/fake_text_detection/data/create_data/train.txt
  num_classes: 2
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    - type: RandomHorizontalFlip
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: /home/hr/projects/PaddleSeg/applications/fake_text_detection/data/create_data
  val_path: /home/hr/projects/PaddleSeg/applications/fake_text_detection/data/create_data/val.txt
  transforms:
    - type: Normalize
  mode: val


optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.00006
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]
```

**Comment by shiyutang** [comment]
经过测试，现有develop版本下不会出现问题；另外根据你的描述，这个问题属于logits 长度和损失长度不匹配，根据paddleseg config中规则，使用一个loss，多个coeff系数会自动扩充loss和coef长度一致。因此使用修改前配置会有两个损失，但是你报错logits 长度为1， 因此需要查看是否开启rtformer中的aux-head，开启后才会有两个logits用于损失计算。

**Comment by ZzyChris97** [comment]
> 经过测试，现有develop版本下不会出现问题；另外根据你的描述，这个问题属于logits 长度和损失长度不匹配，根据paddleseg config中规则，使用一个loss，多个coeff系数会自动扩充loss和coef长度一致。因此使用修改前配置会有两个损失，但是你报错logits 长度为1， 因此需要查看是否开启rtformer中的aux-head，开启后才会有两个logits用于损失计算。

请问如何查看是否开启rtformer中的aux-head？

**Comment by shiyutang** [comment]
use_aux_head默认是开启的，这个是在model的配置下设置。按照你的配置来看应该是开启的，所以你应该使用有两个系数的损失。你更改前后应该不只更改了损失系数，可以看到logits的个数也从1变到了2。所以你保持现有更改，并把损失的系数变化成两个就可以了。如果依旧存在问题，欢迎本issue回复。或者使用import pdb的形式增加断点，查看logits的系数为多少。

**Comment by ZzyChris97** [comment]
> use_aux_head默认是开启的，这个是在model的配置下设置。按照你的配置来看应该是开启的，所以你应该使用有两个系数的损失。你更改前后应该不只更改了损失系数，可以看到logits的个数也从1变到了2。所以你保持现有更改，并把损失的系数变化成两个就可以了。如果依旧存在问题，欢迎本issue回复。或者使用import pdb的形式增加断点，查看logits的系数为多少。

我把损失系数都设置为两个后：
```
loss:
  types:
    - type: CrossEntropyLoss
  coef: [1, 0.4]
```
训练的第一个epoch是正常的，eval也是正常的，但是在eval结束之后又报错了，这会是从`2 != 1` 变成了 `1 != 2`详细的错误信息如下：

```
Traceback (most recent call last):
  File "/home/hr/projects/PaddleSeg/train.py", line 262, in <module>
    main(args)
  File "/home/hr/projects/PaddleSeg/train.py", line 235, in main
    train(
  File "/home/hr/projects/PaddleSeg/paddleseg/core/train.py", line 207, in train
    loss_list = loss_computation(
  File "/home/hr/projects/PaddleSeg/paddleseg/core/train.py", line 38, in loss_computation
    check_logits_losses(logits_list, losses)
  File "/home/hr/projects/PaddleSeg/paddleseg/core/train.py", line 32, in check_logits_losses
    raise RuntimeError(
RuntimeError: The length of logits_list should equal to the types of loss config: 1 != 2.
```

**Comment by shiyutang** [comment]
logits的个数和网络输出有关，建议查看是否修改了网络部分的代码导致logits个数发生变化。 可以使用pdb调试，查看训练完一个epoch后logits的个数是否变为1个，以及为什么会变为1个。
