### ISSUE TITLE
复现NNUnet报错

### ISSUE THREAD

**Issue by Mia01023** [PaddlePaddle/PaddleSeg#2970]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

按照/home/aistudio/PaddleSeg/contrib/MedicalSeg/configs/nnunet/msd_lung/README.md复现NNUnet网络时，训练时报错。
‘’‘
!python train.py --config configs/nnunet/msd_lung/nnunet_2d_msd_lung_fold0.yml --log_iters 20 --precision fp16 --nnunet --save_dir output/2d_unet/fold0 --save_interval 1000 --use_vdl
’‘’

‘’‘
Error: Can not import paddle core while this file exists: /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    import paddle
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/core.py", line 304, in <module>
    raise e
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/core.py", line 249, in <module>
    from . import libpaddle
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory
’‘’

### 复现环境 Environment

PaddlePaddle 2.4.0
Paddleseg release/2.7
python3.7.4

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by juncaipeng** [comment]
这个报错应该是安装paddle失败，请检查一下

**Comment by shiyutang** [comment]
需要安装和本地机器cuda版本匹配的paddle，如果不匹配就会报错。建议使用nvidia-smi查看cuda版本，并安装相应版本的paddle。

**Comment by Mia01023** [comment]
代码是使用飞桨云端算力执行， 已重新安装paddle，非常感谢！

从 Windows 版邮件发送

发件人: shiyutang
发送时间: 2023年2月14日 10:26
收件人: PaddlePaddle/PaddleSeg
抄送: Mia01023; Author
主题: Re: [PaddlePaddle/PaddleSeg] 复现NNUnet报错 (Issue #2970)

需要安装和本地机器cuda版本匹配的paddle，如果不匹配就会报错。建议使用nvidia-smi查看cuda版本，并安装相应版本的paddle。

**Comment by Mia01023** [comment]
收到，非常感谢！

从 Windows 版邮件发送

发件人: Ccc
发送时间: 2023年2月14日 10:13
收件人: PaddlePaddle/PaddleSeg
抄送: Mia01023; Author
主题: Re: [PaddlePaddle/PaddleSeg] 复现NNUnet报错 (Issue #2970)

这个报错应该是安装paddle失败，请检查一下
