### ISSUE TITLE
训练中出现了一个异常错误

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/PaddleSeg#3002]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

它在前10000轮训练正常，后面直接报错内存错误很奇怪。

Traceback (most recent call last):
  File "train.py", line 230, in <module>
    main(args)
  File "train.py", line 206, in main
    train(
  File "/home/dell/bag-torch/darkpull/Paddle/PaddleSeg/paddleseg/core/train.py", line 207, in train
    loss_list = loss_computation(
  File "/home/dell/bag-torch/darkpull/Paddle/PaddleSeg/paddleseg/core/train.py", line 48, in loss_computation
    mixed_loss_list = loss_i(logits, labels)
  File "/home/dell/anaconda3/envs/bagtorch/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/dell/anaconda3/envs/bagtorch/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/dell/bag-torch/darkpull/Paddle/PaddleSeg/paddleseg/models/losses/mixed_loss.py", line 55, in forward
    output = loss(logits, labels)
  File "/home/dell/anaconda3/envs/bagtorch/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/dell/anaconda3/envs/bagtorch/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/dell/bag-torch/darkpull/Paddle/PaddleSeg/paddleseg/models/losses/ohem_cross_entropy_loss.py", line 78, in forward
    index = prob.argsort()
  File "/home/dell/anaconda3/envs/bagtorch/lib/python3.8/site-packages/paddle/tensor/search.py", line 99, in argsort
    _, ids = _C_ops.argsort(x, 'axis', axis, 'descending', descending)
SystemError: (Fatal) Operator argsort raises an thrust::system::detail::bad_alloc exception.
The exception content is
:std::bad_alloc: cudaErrorMemoryAllocation: out of memory. (at /paddle/paddle/fluid/imperative/tracer.cc:307)

FATAL: exception not rethrown

**Comment by zhaoyantao-murray** [comment]
看起来是显存溢出了，在训练过程中显存占用率很高吗？尝试降低batchsize试一下呢

**Comment by chen-del** [comment]
训练中显存占用不是很高，才使用batch_size 16 占用不是很高，但是报错了，如果batch_size变小的话训练就太慢了我使用的是单卡，有没有办法去规避这个@zhaoyantao-murray

**Comment by juncaipeng** [comment]
估计是随机错误，可以再训练一次看是否稳定出现错误。

**Comment by chen-del** [comment]
同样的在测试了三次都卡在同一个地方

**Comment by chen-del** [comment]
直接误报了，显示cuda显卡占用异常@juncaipeng

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
