### ISSUE TITLE
MedicalSeg nnunet 模块windows无法执行

### ISSUE THREAD

**Issue by huangguoqing** [PaddlePaddle/PaddleSeg#3018]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

MedicalSeg nnunet 模块windows下问题较多，是支持windows的吗？

1.数据预处理部分，数据路径格式都是linux下的

2. python windows下训练和测试nnunet多进程报错

预测：starting prediction...
Traceback (most recent call last):
  File "nnunet/predict.py", line 324, in <module>
    main(args)
  File "nnunet/predict.py", line 319, in main
    postprocessing_json_path=args.postprocessing_json_path)
  File "nnunet/predict.py", line 274, in predict_from_folder
    postprocessing_json_path=postprocessing_json_path)
  File "F:\Medical\PaddleSeg\contrib\MedicalSeg\nnunet\utils\predict_utils.py", line 238, in predict_cases
    for preprocessed in preprocessing:
  File "F:\Medical\PaddleSeg\contrib\MedicalSeg\nnunet\utils\predict_utils.py", line 137, in preprocess_multithreaded
    pr.start()
  File "D:\anaconda\envs\MedicalSeg\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\anaconda\envs\MedicalSeg\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\anaconda\envs\MedicalSeg\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\anaconda\envs\MedicalSeg\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\anaconda\envs\MedicalSeg\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle EagerParamBase objects

训练：
  File "D:\anaconda\envs\MedicalSeg\lib\site-packages\paddle\fluid\core.py", line 274, in <module>
    from . import libpaddle
ImportError: DLL load failed: 页面文件太小，无法完成操作。

是否nnunet目前还不支持windows，AIstdudio快速演示也是Linux

### 复现环境 Environment

2023-03-02 18:18:10 [INFO]
------------Environment Information-------------
platform: Windows-10-10.0.19041-SP0
Python: 3.7.16 (default, Jan 17 2023, 16:06:28) [MSC v.1916 64 bit (AMD64)]
Paddle compiled with cuda: True
NVCC: Not Available
cudnn: 8.4
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce']
GCC: gcc (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 8.1.0
PaddlePaddle: 2.4.2
---------------------------

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Bobholamovic** [comment]
你好，根据错误提示，应该是机器的**内存**（请注意与『显存』区分）不足导致的错误。请确认机器具有足够的内存资源载入Paddle运行时库，以及执行nnUNet模型训练。

**Comment by shiyutang** [comment]
nnUNet没有在Windows下进行测试，且对显存和硬盘的占用均较多，建议优先在Linux下使用。

**Comment by huangguoqing** [comment]
好的，谢谢回复
