### ISSUE TITLE
用自己的数据时出现维度问题

### ISSUE THREAD

**Issue by flyinggx** [PaddlePaddle/PaddleSeg#302]
2020-06-27 13:36:28 [INFO]	12 samples in file work/PaddleSeg/contrib/RemoteSensing/dataset/building/train.txt
2020-06-27 13:36:28 [INFO]	8 samples in file work/PaddleSeg/contrib/RemoteSensing/dataset/building/val.txt
2020-06-27 13:36:28,649-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
W0627 13:36:28.812085   187 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 9.0
W0627 13:36:28.816009   187 device_context.cc:260] device: 0, cuDNN Version: 7.3.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "work/PaddleSeg/contrib/RemoteSensing/train_demo.py", line 123, in <module>
    use_vdl=True)
  File "/home/aistudio/work/PaddleSeg/contrib/RemoteSensing/models/unet.py", line 177, in train
    use_vdl=use_vdl)
  File "/home/aistudio/work/PaddleSeg/contrib/RemoteSensing/models/base.py", line 405, in train
    fetch_list=list(self.train_outputs.values()))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 873, in _run_parallel
    check_feed_shape_type(var, tensor)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 225, in check_feed_shape_type
    (var.name, len(var.shape), var.shape, diff_shape))
ValueError: The fed Variable 'label' should have dimensions = 4, shape = (-1, 1, -1, -1), but received fed shape [4, 1, 512, 512, 3] on each device
label格式为单通道png,请问这个问题如何解决？敬谢！

**Comment by zhupengyang** [comment]
能把自己的数据先转换成单通道的格式吗？

**Comment by nepeplwu** [comment]
@flyinggx 感觉你的label数据有问题，不是单通道图片，麻烦试试下面的代码，看看输出是什么
```python
from PIL import Image
# label_path指定为MASK图片的路径
label_path = ""
data = Image.open(label_path)
print(data.mode)
```

**Comment by flyinggx** [comment]
> @flyinggx 感觉你的label数据有问题，不是单通道图片，麻烦试试下面的代码，看看输出是什么
> 
> ```python
> from PIL import Image
> # label_path指定为MASK图片的路径
> label_path = ""
> data = Image.open(label_path)
> print(data.mode)
> ```

@nepeplwu 果然是label问题，print出来是RGB，三通道，那我应该如何修改呀？是在运行的时候指定channel=3嘛？这个我试了，还是报同样的错误，小白求指教，敬谢！

**Comment by nepeplwu** [comment]
@flyinggx ，运行的时候指定channel=3是没用的，那个设定的是输入图片的channel数量。label必须为单通道图片，你需要将所有label从三通道转为单通道图片

**Comment by flyinggx** [comment]
> @flyinggx ，运行的时候指定channel=3是没用的，那个设定的是输入图片的channel数量。label必须为单通道图片，你需要将所有label从三通道转为单通道图片

感谢，确实是通道问题，目前已经解决。
