### ISSUE TITLE
MscaleOCRNet 无法在aistudio环境运行

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleSeg#3020]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

paddle 2.4 版本，自定义数据集
配置文件如下
[mscale.zip](https://github.com/PaddlePaddle/PaddleSeg/files/10871493/mscale.zip)
启动命令
```
!python /home/aistudio/PaddleSeg-release-2.7/train.py --config  /home/aistudio/mscale.yml \
--do_eval \
--use_vdl \
--save_interval 1000 \
--save_dir /home/aistudio/output \
--log_iters 20 
```

首先是加载预训练模型的一堆warning
```
2023-03-02 20:46:24 [WARNING]	backbone.st4.stage_st4_3.branches_func.bb_st4_3_branch_layer_3_3.deattn.conv_up.weight is not in pretrained model
2023-03-02 20:46:24 [WARNING]	backbone.st4.stage_st4_3.branches_func.bb_st4_3_branch_layer_3_3.deattn.conv_q_left.weight is not in pretrained model
2023-03-02 20:46:24 [WARNING]	backbone.st4.stage_st4_3.branches_func.bb_st4_3_branch_layer_3_3.deattn.conv_v_left.weight is not in pretrained model
2023-03-02 20:46:24 [WARNING]	backbone.st4.stage_st4_3.branches_func.bb_st4_3_branch_layer_3_4.deattn.conv_q_right.weight is not in pretrained model
2023-03-02 20:46:24 [WARNING]	backbone.st4.stage_st4_3.branches_func.bb_st4_3_branch_layer_3_4.deattn.conv_v_right.weight is not in pretrained model
```

保存信息如下
```
2023-03-02 20:46:24 [INFO]	There are 1572/2107 variables loaded into MscaleOCRNet.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/norm.py:712: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance."
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:277: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.int64, the right dtype will convert to paddle.float32
  .format(lhs_dtype, rhs_dtype, lhs_dtype))
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:277: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.bool, the right dtype will convert to paddle.float32
  .format(lhs_dtype, rhs_dtype, lhs_dtype))
shapes [1, 19, 1024, 2048] [1, 2, 1024, 2048]
Traceback (most recent call last):
  File "/home/aistudio/PaddleSeg-release-2.7/train.py", line 262, in <module>
    main(args)
  File "/home/aistudio/PaddleSeg-release-2.7/train.py", line 254, in main
    to_static_training=cfg.to_static_training)
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/core/train.py", line 211, in train
    losses=losses)
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/core/train.py", line 48, in loss_computation
    mixed_loss_list = loss_i(logits, labels)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/models/losses/mixed_loss.py", line 55, in forward
    output = loss(logits, labels)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/models/losses/rmi_loss.py", line 82, in forward
    loss = self.forward_sigmoid(logits_4D, labels_4D, do_rmi=do_rmi)
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/models/losses/rmi_loss.py", line 113, in forward_sigmoid
    rmi_loss = self.rmi_lower_bound(valid_onehot_labels_4D, probs_4D)
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/models/losses/rmi_loss.py", line 128, in rmi_lower_bound
    'shapes', labels_4D.shape, probs_4D.shape)
AssertionError: None
```
看了下，重点在shapes [1, 19, 1024, 2048] [1, 2, 1024, 2048]，是不是就不支持自定义的类别啊？

### 复现环境 Environment

aistudio
- PaddlePaddle: 2.4
- PaddleSeg: release/2.7
初始环境PaddlePaddle: 2.4通过pip -q install paddleseg安装，pip list看了，“paddleseg                      2.7.0”

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Bobholamovic** [comment]
你好，mscaleocrnet使用了RMILoss，如果修改类别则也需要同步修改`RMILoss`的`num_classes`配置。

**Comment by zouhan6806504** [comment]
> 你好，mscaleocrnet使用了RMILoss，如果修改类别则也需要同步修改`RMILoss`的`num_classes`配置。

我把loss加上num_classes，能运行了，但是loss为负值，而且几百步后报错，是不是不止num_classes处，别的地方还有要改的？

```
loss:
  types:
    - type: CrossEntropyLoss
    - type: MixedLoss
      losses:
        - type: RMILoss
          num_classes: 2
        - type: CrossEntropyLoss
      coef: [1.0, 1.0]
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
  coef: [0.4, 1.0, 0.05, 0.05]
```

```
2023-03-03 09:12:01 [INFO]	[TRAIN] epoch: 1, iter: 20/20000, loss: -3.3688, lr: 0.000029, batch_cost: 2.1121, reader_cost: 0.02273, ips: 0.4735 samples/sec | ETA 11:43:18
2023-03-03 09:12:41 [INFO]	[TRAIN] epoch: 1, iter: 40/20000, loss: -2.7055, lr: 0.000049, batch_cost: 1.9797, reader_cost: 0.00027, ips: 0.5051 samples/sec | ETA 10:58:35
2023-03-03 09:13:19 [INFO]	[TRAIN] epoch: 1, iter: 60/20000, loss: -1.2468, lr: 0.000069, batch_cost: 1.9220, reader_cost: 0.00026, ips: 0.5203 samples/sec | ETA 10:38:45
2023-03-03 09:13:58 [INFO]	[TRAIN] epoch: 1, iter: 80/20000, loss: -3.3341, lr: 0.000089, batch_cost: 1.9571, reader_cost: 0.00028, ips: 0.5110 samples/sec | ETA 10:49:45
2023-03-03 09:14:39 [INFO]	[TRAIN] epoch: 1, iter: 100/20000, loss: -3.1971, lr: 0.000109, batch_cost: 2.0521, reader_cost: 0.00029, ips: 0.4873 samples/sec | ETA 11:20:36
2023-03-03 09:15:21 [INFO]	[TRAIN] epoch: 1, iter: 120/20000, loss: -3.0793, lr: 0.000129, batch_cost: 2.0648, reader_cost: 0.00029, ips: 0.4843 samples/sec | ETA 11:24:09
2023-03-03 09:15:59 [INFO]	[TRAIN] epoch: 1, iter: 140/20000, loss: -4.0012, lr: 0.000149, batch_cost: 1.9157, reader_cost: 0.00026, ips: 0.5220 samples/sec | ETA 10:34:06
2023-03-03 09:16:38 [INFO]	[TRAIN] epoch: 1, iter: 160/20000, loss: -2.6796, lr: 0.000169, batch_cost: 1.9248, reader_cost: 0.00027, ips: 0.5195 samples/sec | ETA 10:36:28
2023-03-03 09:17:16 [INFO]	[TRAIN] epoch: 1, iter: 180/20000, loss: -3.1558, lr: 0.000189, batch_cost: 1.9224, reader_cost: 0.00026, ips: 0.5202 samples/sec | ETA 10:35:02
2023-03-03 09:17:55 [INFO]	[TRAIN] epoch: 1, iter: 200/20000, loss: -1.5999, lr: 0.000209, batch_cost: 1.9366, reader_cost: 0.00027, ips: 0.5164 samples/sec | ETA 10:39:04
2023-03-03 09:18:33 [INFO]	[TRAIN] epoch: 1, iter: 220/20000, loss: -4.8670, lr: 0.000229, batch_cost: 1.9306, reader_cost: 0.00025, ips: 0.5180 samples/sec | ETA 10:36:27
2023-03-03 09:19:12 [INFO]	[TRAIN] epoch: 1, iter: 240/20000, loss: -3.3148, lr: 0.000249, batch_cost: 1.9352, reader_cost: 0.00026, ips: 0.5167 samples/sec | ETA 10:37:19
2023-03-03 09:19:52 [INFO]	[TRAIN] epoch: 1, iter: 260/20000, loss: -4.0981, lr: 0.000268, batch_cost: 1.9798, reader_cost: 0.00026, ips: 0.5051 samples/sec | ETA 10:51:22
2023-03-03 09:20:31 [INFO]	[TRAIN] epoch: 1, iter: 280/20000, loss: -3.7916, lr: 0.000288, batch_cost: 1.9889, reader_cost: 0.00027, ips: 0.5028 samples/sec | ETA 10:53:40
2023-03-03 09:21:10 [INFO]	[TRAIN] epoch: 1, iter: 300/20000, loss: -4.2202, lr: 0.000308, batch_cost: 1.9281, reader_cost: 0.00027, ips: 0.5187 samples/sec | ETA 10:33:03
2023-03-03 09:21:49 [INFO]	[TRAIN] epoch: 1, iter: 320/20000, loss: -2.2951, lr: 0.000328, batch_cost: 1.9367, reader_cost: 0.00027, ips: 0.5163 samples/sec | ETA 10:35:13
2023-03-03 09:22:27 [INFO]	[TRAIN] epoch: 1, iter: 340/20000, loss: -2.5583, lr: 0.000348, batch_cost: 1.9123, reader_cost: 0.00028, ips: 0.5229 samples/sec | ETA 10:26:35
2023-03-03 09:23:05 [INFO]	[TRAIN] epoch: 1, iter: 360/20000, loss: -3.3292, lr: 0.000368, batch_cost: 1.9202, reader_cost: 0.00028, ips: 0.5208 samples/sec | ETA 10:28:33
2023-03-03 09:23:44 [INFO]	[TRAIN] epoch: 1, iter: 380/20000, loss: -4.3130, lr: 0.000388, batch_cost: 1.9130, reader_cost: 0.00026, ips: 0.5227 samples/sec | ETA 10:25:33
Traceback (most recent call last):
  File "/home/aistudio/PaddleSeg-release-2.7/train.py", line 262, in <module>
    main(args)
  File "/home/aistudio/PaddleSeg-release-2.7/train.py", line 254, in main
    to_static_training=cfg.to_static_training)
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/core/train.py", line 211, in train
    losses=losses)
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/core/train.py", line 48, in loss_computation
    mixed_loss_list = loss_i(logits, labels)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/models/losses/mixed_loss.py", line 55, in forward
    output = loss(logits, labels)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/models/losses/rmi_loss.py", line 82, in forward
    loss = self.forward_sigmoid(logits_4D, labels_4D, do_rmi=do_rmi)
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/models/losses/rmi_loss.py", line 113, in forward_sigmoid
    rmi_loss = self.rmi_lower_bound(valid_onehot_labels_4D, probs_4D)
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/models/losses/rmi_loss.py", line 202, in rmi_lower_bound
    diag_matrix, dtype='float64') * _POS_ALPHA)
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/models/losses/rmi_loss.py", line 223, in log_det_by_cholesky
    chol = paddle.cholesky(matrix)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/linalg.py", line 1539, in cholesky
    return _C_ops.cholesky(x, upper)
RuntimeError: (PreconditionNotMet) For batch [0]: U(7, 7) is zero, singular U.
  [Hint: Expected error_info[i] == 0, but received error_info[i]:7 != 0:0.] (at /paddle/paddle/phi/kernels/gpu/cholesky_kernel.cu:212)
```

**Comment by Bobholamovic** [comment]
1. 根据 RMILoss [原论文](https://arxiv.org/pdf/1910.12037.pdf)提出的计算方法，loss数值有可能为负数，这是符合预期的。若需要减小负数loss的影响，可考虑降低RMILoss的权重。
2. RMILoss计算过程中需要对矩阵做[柯列斯基分解](https://baike.baidu.com/item/cholesky%E5%88%86%E8%A7%A3/10640395)，这一操作要求输入是正定的埃米特矩阵（特征值必须都大于0），而在上述错误日志的情况下，输入似乎不满足要求。若在减小RMILoss权重后该情况仍持续出现，请向我们汇报。

**Comment by zouhan6806504** [comment]
> 1. 根据 RMILoss [原论文](https://arxiv.org/pdf/1910.12037.pdf)提出的计算方法，loss数值有可能为负数，这是符合预期的。若需要减小负数loss的影响，可考虑降低RMILoss的权重。
> 2. RMILoss计算过程中需要对矩阵做[柯列斯基分解](https://baike.baidu.com/item/cholesky%E5%88%86%E8%A7%A3/10640395)，这一操作要求输入是正定的埃米特矩阵（特征值必须都大于0），而在上述错误日志的情况下，输入似乎不满足要求。若在减小RMILoss权重后该情况仍持续出现，请向我们汇报。

还是有类似的问题，我已经把rmiloss的比重调得很小了
```
loss:
  types:
    - type: CrossEntropyLoss
    - type: MixedLoss
      losses:
        - type: RMILoss
          num_classes: 2
        - type: CrossEntropyLoss
      coef: [0.005, 0.995]
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
  coef: [0.4, 1.0, 0.05, 0.05]
```
有没有什么比较通用的规则，比如MscaleOCRNet比较适用于哪些特征的数据集。我目前的数据集只有两类，而且标注为1的部分很少，比例不到0.002

**Comment by zouhan6806504** [comment]
这次倒是运行得比较长， 1400步才出问题

```
2023-03-03 15:37:00 [INFO]	[TRAIN] epoch: 1, iter: 1380/20000, loss: 0.0199, lr: 0.001386, batch_cost: 1.9204, reader_cost: 0.00022, ips: 0.5207 samples/sec | ETA 09:55:57
2023-03-03 15:37:39 [INFO]	[TRAIN] epoch: 1, iter: 1400/20000, loss: -0.0077, lr: 0.001406, batch_cost: 1.9247, reader_cost: 0.00022, ips: 0.5196 samples/sec | ETA 09:56:39
Traceback (most recent call last):
  File "/home/aistudio/PaddleSeg-release-2.7/train.py", line 262, in <module>
    main(args)
  File "/home/aistudio/PaddleSeg-release-2.7/train.py", line 254, in main
    to_static_training=cfg.to_static_training)
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/core/train.py", line 211, in train
    losses=losses)
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/core/train.py", line 48, in loss_computation
    mixed_loss_list = loss_i(logits, labels)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/models/losses/mixed_loss.py", line 55, in forward
    output = loss(logits, labels)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/models/losses/rmi_loss.py", line 82, in forward
    loss = self.forward_sigmoid(logits_4D, labels_4D, do_rmi=do_rmi)
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/models/losses/rmi_loss.py", line 113, in forward_sigmoid
    rmi_loss = self.rmi_lower_bound(valid_onehot_labels_4D, probs_4D)
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/models/losses/rmi_loss.py", line 202, in rmi_lower_bound
    diag_matrix, dtype='float64') * _POS_ALPHA)
  File "/home/aistudio/PaddleSeg-release-2.7/paddleseg/models/losses/rmi_loss.py", line 223, in log_det_by_cholesky
    chol = paddle.cholesky(matrix)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/linalg.py", line 1539, in cholesky
    return _C_ops.cholesky(x, upper)
RuntimeError: (PreconditionNotMet) For batch [0]: U(7, 7) is zero, singular U.
  [Hint: Expected error_info[i] == 0, but received error_info[i]:7 != 0:0.] (at /paddle/paddle/phi/kernels/gpu/cholesky_kernel.cu:212)
```

**Comment by Bobholamovic** [comment]
看起来RMILoss对你的数据集（特点为：二分类，样本高度不均衡）并不太适用，容易出现极端情况导致RMILoss无法计算。我建议可以从loss列表中去除之。MscaleOCRNet作为一个模型，与RMILoss并不是强绑定。MscaleOCRNet适用于各种高精度语义分割任务。
