### ISSUE TITLE
in_channels:3

### ISSUE THREAD

**Issue by chongchongmao** [PaddlePaddle/PaddleSeg#3061]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

在配置文件中并没有定义in_channels: 3，但是在运行时，却出现了in_channles： 3，
------------------------------------------------
Traceback (most recent call last):
  File "work/paddleSeg/train.py", line 262, in <module>
    main(args)
  File "work/paddleSeg/train.py", line 233, in main
    model = cfg.model
  File "/home/aistudio/work/paddleSeg/paddleseg/cvlibs/config.py", line 373, in model
    self._model = self._load_object(model_cfg)
  File "/home/aistudio/work/paddleSeg/paddleseg/cvlibs/config.py", line 440, in _load_object
    return component(**params)
TypeError: __init__() got an unexpected keyword argument 'in_channels'

**Comment by Bobholamovic** [comment]
你好，新版本PaddleSeg具有自动注入`in_channels`参数的行为。请提供你使用的PaddleSeg版本，检查方式为：
```shell
cd ~
python -c "import paddleseg; print(paddleseg.__version__)"
```

**Comment by chongchongmao** [comment]
ok
