### ISSUE TITLE
undefined symbol: _dl_sym, version GLIBC_PRIVATE

### ISSUE THREAD

**Issue by loxoo6** [PaddlePaddle/PaddleSeg#3088]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

Error: Can not import avx core while this file exists: /home/zly/anaconda3/envs/hjyenv/lib/python3.7/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "/home/zly/hjy_code/train.py", line 18, in <module>
    import paddle
  File "/home/zly/anaconda3/envs/hjyenv/lib/python3.7/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/zly/anaconda3/envs/hjyenv/lib/python3.7/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/zly/anaconda3/envs/hjyenv/lib/python3.7/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/zly/anaconda3/envs/hjyenv/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/zly/anaconda3/envs/hjyenv/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/zly/anaconda3/envs/hjyenv/lib/python3.7/site-packages/paddle/fluid/core.py", line 298, in <module>
    raise e
  File "/home/zly/anaconda3/envs/hjyenv/lib/python3.7/site-packages/paddle/fluid/core.py", line 256, in <module>
    from . import core_avx
ImportError: /home/zly/anaconda3/envs/hjyenv/lib/python3.7/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE

Process finished with exit code 1

### 复现环境 Environment

这是我用的服务器版本：
Linux version 5.19.0-32-generic (buildd@lcy02-amd64-026) (x86_64-linux-gnu-gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #33~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Jan 30 17:03:34 UTC 2

网上有的人说不支持这个版本的Linux，各位大佬帮忙看看还有救吗？

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
建议尝试安装最新版本paddle：https://github.com/PaddlePaddle/Paddle/issues/44571#issuecomment-1268797171

**Comment by skywalk163** [comment]
20.04 ubuntu ，也碰到这个报错，飞桨2.4.2和paddlepaddle-2.4.0rc0 都一样有报错
```pyhton
py39/lib/python3.9/site-packages/paddle_serving_client/client.py", line 149, in __init__
    from .serving_client import PredictorRes
ImportError: /home/skywalk/py39/lib/python3.9/site-packages/paddle_serving_client/serving_client.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE
```

**Comment by shiyutang** [comment]
如果最新版本不能解决，建议前往https://github.com/PaddlePaddle/Paddle/issues 提交issue
