### ISSUE TITLE
train.py训练自己数据集出错

### ISSUE THREAD

**Issue by Dohbby** [PaddlePaddle/PaddleSeg#3100]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

paddleseg-release-2.6
python3.8

--config
configs/newmodeltest/NewModelTest.yaml
--save_interval
50
--do_eval
--use_vdl
--save_dir
output

ValueError: (InvalidArgument) argsort(): argument (position 2) must be int, but got str (at ..\paddle\fluid\pybind\op_function_common.cc:147)

**Comment by Sunting78** [comment]
请把运行命令，配置文件，报错信息贴全。

**Comment by Dohbby** [comment]
运行train.py，控制台报错
2023-03-28 13:13:16 [INFO]	
------------Environment Information-------------
platform: Windows-10-10.0.19041-SP0
Python: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
Paddle compiled with cuda: False
PaddleSeg: 2.6.0
PaddlePaddle: 2.4.1
OpenCV: 4.7.0
------------------------------------------------
2023-03-28 13:13:16 [INFO]	
---------------Config Information---------------
batch_size: 2
iters: 1000
loss:
  coef:
  - 1
  - 0.4
  types:
  - coef:
    - 0.8
    - 0.2
    losses:
    - type: CrossEntropyLoss
    - type: LovaszSoftmaxLoss
    type: MixedLoss
  - coef:
    - 0.8
    - 0.2
    losses:
    - type: CrossEntropyLoss
    - type: LovaszSoftmaxLoss
    type: MixedLoss
lr_scheduler:
  learning_rate: 0.01
  power: 0.9
  type: PolynomialDecay
model:
  backbone:
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
    type: HRNet_W18
  backbone_indices:
  - 0
  type: OCRNet
optimizer:
  type: sgd
train_dataset:
  dataset_root: newdata/dataset-test
  mode: train
  num_classes: 2
  train_path: newdata/dataset-test/train.txt
  transforms:
  - max_scale_factor: 2.0
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 512
    - 512
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.5
    contrast_range: 0.5
    saturation_range: 0.5
    type: RandomDistort
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: newdata/dataset-test
  mode: val
  num_classes: 2
  transforms:
  - type: Normalize
  type: Dataset
  val_path: newdata/dataset-test/val.txt
------------------------------------------------
2023-03-28 13:13:18 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
2023-03-28 13:13:21 [INFO]	There are 1525/1525 variables loaded into HRNet.
D:\Python\lib\site-packages\paddle\nn\layer\norm.py:711: UserWarning: When training, we now always track global mean and variance.
  warnings.warn(
D:\Python\lib\site-packages\paddle\fluid\dygraph\math_op_patch.py:275: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.int64, the right dtype will convert to paddle.float32
  warnings.warn(
Traceback (most recent call last):
  File "C:/Users/罗美丽/Desktop/PaddleSeg-release-2.6/train.py", line 230, in <module>
    main(args)
  File "C:/Users/罗美丽/Desktop/PaddleSeg-release-2.6/train.py", line 206, in main
    train(
  File "C:\Users\罗美丽\Desktop\PaddleSeg-release-2.6\paddleseg\core\train.py", line 207, in train
    loss_list = loss_computation(
  File "C:\Users\罗美丽\Desktop\PaddleSeg-release-2.6\paddleseg\core\train.py", line 48, in loss_computation
    mixed_loss_list = loss_i(logits, labels)
  File "D:\Python\lib\site-packages\paddle\fluid\dygraph\layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\罗美丽\Desktop\PaddleSeg-release-2.6\paddleseg\models\losses\mixed_loss.py", line 55, in forward
    output = loss(logits, labels)
  File "D:\Python\lib\site-packages\paddle\fluid\dygraph\layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\罗美丽\Desktop\PaddleSeg-release-2.6\paddleseg\models\losses\lovasz_loss.py", line 53, in forward
    loss = lovasz_softmax_flat(vprobas, vlabels, classes=self.classes)
  File "C:\Users\罗美丽\Desktop\PaddleSeg-release-2.6\paddleseg\models\losses\lovasz_loss.py", line 184, in lovasz_softmax_flat
    errors_sorted, perm = paddle._C_ops.argsort(errors, 'axis', 0,
**ValueError: (InvalidArgument) argsort(): argument (position 2) must be int, but got str (at ..\paddle\fluid\pybind\op_function_common.cc:147)**

**Comment by Sunting78** [comment]
可以先尝试下把LovaszSoftmaxLoss换成CrossEntropyLoss，看看是否能正常训练，判断下是否是数据问题。

**Comment by Dohbby** [comment]
鞠躬感谢 十分感谢 可以跑起来训练数据集了 谢谢
