### ISSUE TITLE
Windows平台下的推理报错

### ISSUE THREAD

**Issue by 0x00A0** [PaddlePaddle/PaddleSeg#3110]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

nnunet在Windows上训练与验证正常,但是在动态图推理和静态图推理中均出现运行错误,疑似是Windows平台下多线程里的对象无法序列化
---
运行命令:
```shell
python nnunet\infer.py ^
    --image_folder E:\TestNiigz ^
    --output_folder output\nnunet_static\lowres_pred ^
    --plan_path data\preprocessed\nnUNetPlansv2.1_plans_3D.pkl ^
    --model_paths output\static\cascade_lowres\fold0\model.pdmodel ^
                  output\static\cascade_lowres\fold1\model.pdmodel ^
                  output\static\cascade_lowres\fold2\model.pdmodel ^
                  output\static\cascade_lowres\fold3\model.pdmodel ^
                  output\static\cascade_lowres\fold4\model.pdmodel ^
    --param_paths output\static\cascade_lowres\fold0\model.pdiparams ^
                  output\static\cascade_lowres\fold1\model.pdiparams ^
                  output\static\cascade_lowres\fold2\model.pdiparams ^
                  output\static\cascade_lowres\fold3\model.pdiparams ^
                  output\static\cascade_lowres\fold4\model.pdiparams ^
    --postprocessing_json_path output\cascade_lowres_val\postprocessing.json ^
    --model_type cascade_lowres
```

报错信息
```shell
Traceback (most recent call last):
  File "D:\Projects\PaddleSeg\contrib\MedicalSeg\nnunet\infer.py", line 288, in <module>
    main(args)
  File "D:\Projects\PaddleSeg\contrib\MedicalSeg\nnunet\infer.py", line 268, in main
Traceback (most recent call last):
    predict_from_folder(
  File "<string>", line 1, in <module>
  File "D:\Projects\PaddleSeg\contrib\MedicalSeg\nnunet\predict.py", line 262, in predict_from_folder
    return predict_cases(
  File "D:\Projects\PaddleSeg\contrib\MedicalSeg\nnunet\utils\predict_utils.py", line 238, in predict_cases
    for preprocessed in preprocessing:
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
  File "D:\Projects\PaddleSeg\contrib\MedicalSeg\nnunet\utils\predict_utils.py", line 137, in preprocess_multithreaded
    exitcode = _main(fd, parent_sentinel)
    pr.start()
  File "C:\Program Files\Python310\lib\multiprocessing\spawn.py", line 126, in _main
  File "C:\Program Files\Python310\lib\multiprocessing\process.py", line 121, in start
    self = reduction.pickle.load(from_parent)
    self._popen = self._Popen(self)
EOFError: Ran out of input
  File "C:\Program Files\Python310\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Python310\lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python310\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\Python310\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'StaticPredictor.__init__.<locals>.<lambda>'
```

### 复现环境 Environment

- OS: Windows 11 Professional
- PaddlePaddle: 2.4.2.post117
- PaddleSeg: 
- Python: 3.10
- CUDA: 11.7
- CUDNN: 8.7.0
- GCC: 12.2.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
你好，建议尝试替换这个PR中的代码：https://github.com/MIC-DKFZ/nnUNet/pull/1155/files

**Comment by 0x00A0** [comment]
> 你好，建议尝试替换这个PR中的代码：https://github.com/MIC-DKFZ/nnUNet/pull/1155/files

您好，我已将 `contrib/MedicalSeg/nnunet/utils/predict_utils.py`  中的import部分替换成了如下代码：
```python
if 'win' in sys.platform:
    #fix for windows platform
    import pathos
    Process = pathos.helpers.mp.Process
    Queue = pathos.helpers.mp.Queue
    Pool = pathos.helpers.mp.Pool
else:
    from multiprocessing import Process, Queue, Pool
```
但是仍然会出现报错，具体信息如下：

动态图推理：
```shell
Traceback (most recent call last):
  File "D:\Projects\PaddleSeg\contrib\MedicalSeg\nnunet\predict.py", line 323, i
n <module>
    main(args)
  File "D:\Projects\PaddleSeg\contrib\MedicalSeg\nnunet\predict.py", line 303, i
n main
    predict_from_folder(
  File "D:\Projects\PaddleSeg\contrib\MedicalSeg\nnunet\predict.py", line 259, i
n predict_from_folder
    return predict_cases(
  File "D:\Projects\PaddleSeg\contrib\MedicalSeg\nnunet\utils\predict_utils.py",
 line 246, in predict_cases
    for preprocessed in preprocessing:
  File "D:\Projects\PaddleSeg\contrib\MedicalSeg\nnunet\utils\predict_utils.py",
 line 145, in preprocess_multithreaded
    pr.start()
  File "C:\Program Files\Python310\lib\site-packages\multiprocess\process.py", l
ine 121, in start
    self._popen = self._Popen(self)
  File "C:\Program Files\Python310\lib\site-packages\multiprocess\context.py", l
ine 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Python310\lib\site-packages\multiprocess\context.py", l
ine 336, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python310\lib\site-packages\multiprocess\popen_spawn_wi
n32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\Python310\lib\site-packages\multiprocess\reduction.py",
 line 63, in dump
    ForkingPickler(file, protocol, *args, **kwds).dump(obj)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 394, i
n dump
    StockPickler.dump(self, obj)
  File "C:\Program Files\Python310\lib\pickle.py", line 487, in dump
    self.save(obj)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 717, in save_reduce
    save(state)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 1186,
in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Program Files\Python310\lib\pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Program Files\Python310\lib\pickle.py", line 998, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Program Files\Python310\lib\pickle.py", line 902, in save_tuple
    save(element)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 1427,
in save_instancemethod0
    pickler.save_reduce(MethodType, (obj.__func__, obj.__self__), obj=obj)
  File "C:\Program Files\Python310\lib\pickle.py", line 692, in save_reduce
    save(args)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Program Files\Python310\lib\pickle.py", line 887, in save_tuple
    save(element)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 717, in save_reduce
    save(state)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 1186,
in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Program Files\Python310\lib\pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Program Files\Python310\lib\pickle.py", line 998, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 717, in save_reduce
    save(state)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 1186,
in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Program Files\Python310\lib\pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Program Files\Python310\lib\pickle.py", line 998, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 713, in save_reduce
    self._batch_setitems(dictitems)
  File "C:\Program Files\Python310\lib\pickle.py", line 1003, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 717, in save_reduce
    save(state)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 1186,
in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Program Files\Python310\lib\pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Program Files\Python310\lib\pickle.py", line 998, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 713, in save_reduce
    self._batch_setitems(dictitems)
  File "C:\Program Files\Python310\lib\pickle.py", line 998, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 717, in save_reduce
    save(state)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 1186,
in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Program Files\Python310\lib\pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Program Files\Python310\lib\pickle.py", line 998, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 713, in save_reduce
    self._batch_setitems(dictitems)
  File "C:\Program Files\Python310\lib\pickle.py", line 998, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 717, in save_reduce
    save(state)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 1186,
in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Program Files\Python310\lib\pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Program Files\Python310\lib\pickle.py", line 998, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 713, in save_reduce
    self._batch_setitems(dictitems)
  File "C:\Program Files\Python310\lib\pickle.py", line 998, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 717, in save_reduce
    save(state)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 1186,
in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Program Files\Python310\lib\pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Program Files\Python310\lib\pickle.py", line 998, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 713, in save_reduce
    self._batch_setitems(dictitems)
  File "C:\Program Files\Python310\lib\pickle.py", line 1003, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 717, in save_reduce
    save(state)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 1186,
in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Program Files\Python310\lib\pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Program Files\Python310\lib\pickle.py", line 998, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 713, in save_reduce
    self._batch_setitems(dictitems)
  File "C:\Program Files\Python310\lib\pickle.py", line 1003, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 717, in save_reduce
    save(state)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 1186,
in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Program Files\Python310\lib\pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Program Files\Python310\lib\pickle.py", line 998, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 713, in save_reduce
    self._batch_setitems(dictitems)
  File "C:\Program Files\Python310\lib\pickle.py", line 998, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 717, in save_reduce
    save(state)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 1186,
in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Program Files\Python310\lib\pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Program Files\Python310\lib\pickle.py", line 998, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 713, in save_reduce
    self._batch_setitems(dictitems)
  File "C:\Program Files\Python310\lib\pickle.py", line 998, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, i
n save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 578, in save
    rv = reduce(self.proto)
TypeError: cannot pickle 'EagerParamBase' object
```
---
静态图推理：
```shell
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Projects\PaddleSeg\contrib\MedicalSeg\nnunet\infer.py", line 288, in <module>
    main(args)
  File "D:\Projects\PaddleSeg\contrib\MedicalSeg\nnunet\infer.py", line 268, in main
  File "C:\Program Files\Python310\lib\site-packages\multiprocess\spawn.py", line 116, in spawn_main
    predict_from_folder(
  File "D:\Projects\PaddleSeg\contrib\MedicalSeg\nnunet\predict.py", line 259, in predict_from_folder
    exitcode = _main(fd, parent_sentinel)
  File "C:\Program Files\Python310\lib\site-packages\multiprocess\spawn.py", line 126, in _main
    return predict_cases(
  File "D:\Projects\PaddleSeg\contrib\MedicalSeg\nnunet\utils\predict_utils.py", line 246, in predict_cases
    self = reduction.pickle.load(from_parent)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 272, in load
    for preprocessed in preprocessing:
  File "D:\Projects\PaddleSeg\contrib\MedicalSeg\nnunet\utils\predict_utils.py", line 145, in preprocess_multithreaded
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 419, in load
    pr.start()
  File "C:\Program Files\Python310\lib\site-packages\multiprocess\process.py", line 121, in start
    obj = StockUnpickler.load(self)
EOFError: Ran out of input
    self._popen = self._Popen(self)
  File "C:\Program Files\Python310\lib\site-packages\multiprocess\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Program Files\Python310\lib\site-packages\multiprocess\context.py", line 336, in _Popen
    return Popen(process_obj)
  File "C:\Program Files\Python310\lib\site-packages\multiprocess\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Program Files\Python310\lib\site-packages\multiprocess\reduction.py", line 63, in dump
    ForkingPickler(file, protocol, *args, **kwds).dump(obj)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 394, in dump
    StockPickler.dump(self, obj)
  File "C:\Program Files\Python310\lib\pickle.py", line 487, in dump
    self.save(obj)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 717, in save_reduce
    save(state)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 1186, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Program Files\Python310\lib\pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Program Files\Python310\lib\pickle.py", line 998, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Program Files\Python310\lib\pickle.py", line 902, in save_tuple
    save(element)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 1427, in save_instancemethod0
    pickler.save_reduce(MethodType, (obj.__func__, obj.__self__), obj=obj)
  File "C:\Program Files\Python310\lib\pickle.py", line 692, in save_reduce
    save(args)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Program Files\Python310\lib\pickle.py", line 887, in save_tuple
    save(element)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 717, in save_reduce
    save(state)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 1186, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Program Files\Python310\lib\pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Program Files\Python310\lib\pickle.py", line 998, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Program Files\Python310\lib\pickle.py", line 932, in save_list
    self._batch_appends(obj)
  File "C:\Program Files\Python310\lib\pickle.py", line 956, in _batch_appends
    save(x)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Program Files\Python310\lib\pickle.py", line 717, in save_reduce
    save(state)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 1186, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Program Files\Python310\lib\pickle.py", line 972, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Program Files\Python310\lib\pickle.py", line 998, in _batch_setitems
    save(v)
  File "C:\Program Files\Python310\lib\site-packages\dill\_dill.py", line 388, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Program Files\Python310\lib\pickle.py", line 578, in save
    rv = reduce(self.proto)
TypeError: cannot pickle 'paddle.fluid.libpaddle.AnalysisConfig' object
```

**Comment by shiyutang** [comment]
根据报错可以看出pickle过程中存在对象无法打包的问题，同时目前nnUNet没有在windows下测试，建议切换Linux平台获取更好的支持。

**Comment by 0x00A0** [comment]
> 根据报错可以看出pickle过程中存在对象无法打包的问题，同时目前nnUNet没有在windows下测试，建议切换Linux平台获取更好的支持。

我尝试将`contrib/MedicalSeg/nnunet/utils/predict_utils.py`第145行的pr.start()替换为pr.run(),以单线程尝试运行推理,程序在该情况下没有报错,但似乎并没有正常进行推理,GPU与CPU使用率均没有显著变化,并且程序似乎卡在了这之后:
```shell
Resample before: {'spacing': array([5.        , 0.78200001, 0.78200001]), 'spacing_transposed': array([5.        , 0.78200001, 0.78200001]), 'data.shape (data is transposed)': (1, 89, 512, 512)}
Resample after: {'spacing': array([3.35537784, 1.67850664, 1.67850664]), 'data.shape (data is resampled)': (1, 133, 239, 239)}:
Normalize...
Normalize Done.
(1, 133, 239, 239)

```

**Comment by 0x00A0** [comment]
或者请问可以提供单线程下对单个数据进行推理的现成代码吗?

**Comment by 0x00A0** [comment]
自己重写了单线程模式的推理,发现确实可以正常运行,所以猜测与多线程在Windows下的运行方式有关

**Comment by shiyutang** [comment]
好的，欢迎给我们提交相关的PR。

**Comment by kuchen66666** [comment]
> > 根据报错可以看出pickle过程中存在对象无法打包的问题，同时目前nnUNet没有在windows下测试，建议切换Linux平台获取更好的支持。
> 
> 我尝试将`contrib/MedicalSeg/nnunet/utils/predict_utils.py`第145行的pr.start()替换为pr.run(),以单线程尝试运行推理,程序在该情况下没有报错,但似乎并没有正常进行推理,GPU与CPU使用率均没有显著变化,并且程序似乎卡在了这之后:
> 
> ```shell
> Resample before: {'spacing': array([5.        , 0.78200001, 0.78200001]), 'spacing_transposed': array([5.        , 0.78200001, 0.78200001]), 'data.shape (data is transposed)': (1, 89, 512, 512)}
> Resample after: {'spacing': array([3.35537784, 1.67850664, 1.67850664]), 'data.shape (data is resampled)': (1, 133, 239, 239)}:
> Normalize...
> Normalize Done.
> (1, 133, 239, 239)
> ```

你好，谢谢你的提示，我也是在Windows上跑的，按照你的方法也跑通了，但是也是同样卡在你的那个位置，请问你后来是怎么解决的？可以麻烦指点下吗？谢谢
