### ISSUE TITLE
infer.py时加入trimap

### ISSUE THREAD

**Issue by xiangfeidecao** [PaddlePaddle/PaddleSeg#3122]
paddlepaddle 2.3.1,paddleseg-release-2.6。我在Matting路径下，执行python deploy\python\infer.py --image_path E:\iphone14_03152 --save_dir output --config ../models/modnet-mobilenetv2/deploy.yaml --trimap_path D:\PaddleSeg\PaddleSegRembg\Matting\trimap。提示：
I0403 16:03:40.743093 23708 memory_optimize_pass.cc:216] Cluster name : sigmoid_1.tmp_0  size: 5120
I0403 16:03:40.743093 23708 memory_optimize_pass.cc:216] Cluster name : batch_norm_58.tmp_1  size: 128
I0403 16:03:40.743093 23708 memory_optimize_pass.cc:216] Cluster name : batch_norm_47.tmp_1  size: 3840
I0403 16:03:40.743093 23708 memory_optimize_pass.cc:216] Cluster name : batch_norm_42.tmp_3  size: 640
I0403 16:03:40.743093 23708 memory_optimize_pass.cc:216] Cluster name : batch_norm_57.tmp_2  size: 64
I0403 16:03:40.743093 23708 memory_optimize_pass.cc:216] Cluster name : bilinear_interp_v2_3.tmp_0  size: 12
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0403 16:03:40.927600 23708 analysis_predictor.cc:1035] ======= optimize end =======
I0403 16:03:40.927600 23708 naive_executor.cc:102] ---  skip [feed], feed -> img
I0403 16:03:40.933610 23708 naive_executor.cc:102] ---  skip [sigmoid_2.tmp_0], fetch -> fetch
  0%|          | 0/22 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:/PaddleSeg/PaddleSegRembg/Matting/deploy/python/infer.py", line 539, in <module>
    main(args)
  File "D:/PaddleSeg/PaddleSegRembg/Matting/deploy/python/infer.py", line 512, in main
    paddle_masks = predictor.run(imgs=imgs_list, trimaps=trimaps_list, imgs_dir=imgs_dir)
  File "D:/PaddleSeg/PaddleSegRembg/Matting/deploy/python/infer.py", line 398, in run
    input_handle['trimap'].copy_from_cpu(trimap_inputs)
KeyError: 'trimap'

Process finished with exit code 1
应该是提示 input_handle中没有['trimap']，我自己尝试加了个初始化。在infer.py中  
      for i in range(len(input_names)):
            input_handle[input_names[i]] = self.predictor.get_input_handle(
                input_names[i])
            input_handle['trimap'] = input_handle[input_names[i]]  #我加的，值可能不对，但是后面应该重新赋值的，所以没管。执行后提示如下：
I0403 15:10:15.676172 23032 memory_optimize_pass.cc:216] Cluster name : elementwise_add_8  size: 640
I0403 15:10:15.676172 23032 memory_optimize_pass.cc:216] Cluster name : bilinear_interp_v2_2.tmp_0  size: 12
I0403 15:10:15.676172 23032 memory_optimize_pass.cc:216] Cluster name : img  size: 12
I0403 15:10:15.676172 23032 memory_optimize_pass.cc:216] Cluster name : relu6_35.tmp_0  size: 5120
I0403 15:10:15.676172 23032 memory_optimize_pass.cc:216] Cluster name : pool2d_0.tmp_0  size: 5120
I0403 15:10:15.676172 23032 memory_optimize_pass.cc:216] Cluster name : sigmoid_1.tmp_0  size: 5120
I0403 15:10:15.676172 23032 memory_optimize_pass.cc:216] Cluster name : batch_norm_58.tmp_1  size: 128
I0403 15:10:15.676172 23032 memory_optimize_pass.cc:216] Cluster name : batch_norm_47.tmp_1  size: 3840
I0403 15:10:15.676172 23032 memory_optimize_pass.cc:216] Cluster name : batch_norm_42.tmp_3  size: 640
I0403 15:10:15.676172 23032 memory_optimize_pass.cc:216] Cluster name : batch_norm_57.tmp_2  size: 64
I0403 15:10:15.676172 23032 memory_optimize_pass.cc:216] Cluster name : bilinear_interp_v2_3.tmp_0  size: 12
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0403 15:10:15.796185 23032 analysis_predictor.cc:1035] ======= optimize end =======
I0403 15:10:15.796185 23032 naive_executor.cc:102] ---  skip [feed], feed -> img
I0403 15:10:15.811151 23032 naive_executor.cc:102] ---  skip [sigmoid_2.tmp_0], fetch -> fetch
  0%|          | 0/22 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:/PaddleSeg/PaddleSeg-release-2.6/Matting/deploy/python/infer.py", line 500, in <module>
    main(args)
  File "D:/PaddleSeg/PaddleSeg-release-2.6/Matting/deploy/python/infer.py", line 488, in main
    predictor.run(imgs=imgs_list, trimaps=trimaps_list, imgs_dir=imgs_dir)
  File "D:/PaddleSeg/PaddleSeg-release-2.6/Matting/deploy/python/infer.py", line 399, in run
    self.predictor.run()
ValueError: In user code:

    File "tools/export.py", line 116, in <module>
      main(args)
    File "tools/export.py", line 94, in main
      paddle.jit.save(net, save_path)
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 631, in wrapper
      func(layer, path, input_spec, **configs)
    File "<decorator-gen-106>", line 2, in save
      
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 861, in save
      inner_input_spec, with_hook=with_hook)
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec
      *desired_input_spec, with_hook=with_hook)
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once
      **cache_key.kwargs)
    File "<decorator-gen-104>", line 2, in from_func_spec
      
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "/ssd1/home/chenguowei01/github/PaddleSeg/Matting/tools/../ppmatting/models/modnet.py", line 57, in forward
      feat_list = self.backbone(x)
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/ssd1/home/chenguowei01/github/PaddleSeg/Matting/tools/../ppmatting/models/backbone/mobilenet_v2.py", line 224, in forward
      y = self.conv1(inputs, if_act=True)
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/ssd1/home/chenguowei01/github/PaddleSeg/Matting/tools/../ppmatting/models/backbone/mobilenet_v2.py", line 78, in forward
      y = self._conv(inputs)
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 678, in forward
      use_cudnn=self._use_cudnn)
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 169, in _conv_nd
      type=op_type, inputs=inputs, outputs=outputs, attrs=attrs)
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 44, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3621, in append_op
      attrs=kwargs.get("attrs", None))
    File "/ssd1/home/chenguowei01/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 1, the input's shape is [1, 1, 672, 512]; the filter's channels is 3, the filter's shape is [32, 3, 3, 3]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
      [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:1 != filter_dims[1] * groups:3.] (at C:\home\workspace\Paddle_release\paddle/fluid/operators/conv_op.cc:116)
      [operator < conv2d > error]

问题：1.第一段错误理解的对不对？2.第二段错误是什么引起的？3.是不是必须推理的模型需要trimap才能送trimap,否则给了trimap就报错？2.trimap是什么格式的。4 .通道还是1通道，0-128-255这种还是0-0.5-1这种的？

**Comment by xiangfeidecao** [comment]
是不是只有DIM-VGG16这个模型推理才能用trimap.但是我直接下载下来dim-vgg16.执行python deploy\python\infer.py --image_path E:\iphone14_03152 --save_dir output --config ../models/dim-vgg16/deploy.yaml --trimap_path D:\PaddleSeg\PaddleSegRembg\Matting\trimap。卡一分钟后直接退出，一张图也没抠出来。错误也没提示。

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
