### ISSUE TITLE
ImportError: /home/zzh/miniforge3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/fluid/libpaddle.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by LFL19991003** [PaddlePaddle/PaddleSeg#3178]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

I'm using python3 to enter the conda virtual environment on the ubantu18.04 system terminal, and I'm having the following problem when I import paddle. What is the reason for this?

>>> import paddle
Error: Can not import paddle core while this file exists: /home/zzh/miniforge3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/home/zzh/miniforge3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/fluid/core.py", line 274, in <module>
    from . import libpaddle
ImportError: /home/zzh/miniforge3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/fluid/libpaddle.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zzh/miniforge3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/zzh/miniforge3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/zzh/miniforge3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/zzh/miniforge3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/zzh/miniforge3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/zzh/miniforge3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/fluid/core.py", line 333, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined

### 复现环境 Environment

Linux
paddlepaddle-gpu：2.4.2
python：3.8.16

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by juncaipeng** [comment]
You should reinstall the PaddlePaddle that compiled without avx.
