### ISSUE TITLE
您好，我在复现ppmating时，报错。显示cuda内存不够，可是我服务器GPU内存是32G，不应该不够呀。这个问题应该是环境配置问题。请问怎么解决

### ISSUE THREAD

**Issue by largerwxt** [PaddlePaddle/PaddleSeg#3184]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，我在复现ppmating时，报错。显示cuda内存不够，可是我服务器GPU内存是32G，不应该不够呀。这个问题应该是环境配置问题。请问怎么解决？
问题描述如下：
W0417 09:29:40.294329 2889850 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.2
W0417 09:29:40.294353 2889850 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
Traceback (most recent call last):
  File "tools/train.py", line 239, in <module>
    main(args)
  File "tools/train.py", line 212, in main
    model = cfg.model
  File "/home/anaconda/envs/wxt-env/lib/python3.7/site-packages/paddleseg/cvlibs/config.py", line 373, in model
    self._model = self._load_object(model_cfg)
  File "/home/anaconda/envs/wxt-env/lib/python3.7/site-packages/paddleseg/cvlibs/config.py", line 431, in _load_object
    params[key] = self._load_object(val)
  File "/home/anaconda/envs/wxt-env/lib/python3.7/site-packages/paddleseg/cvlibs/config.py", line 440, in _load_object
    return component(**params)
  File "/home/wxt/pp-matting/work/PaddleSeg/Matting/tools/../ppmatting/models/backbone/hrnet.py", line 797, in HRNet_W48
    **kwargs)
  File "/home/wxt/pp-matting/work/PaddleSeg/Matting/tools/../ppmatting/models/backbone/hrnet.py", line 103, in __init__
    bias_attr=False)
  File "/home/anaconda/envs/wxt-env/lib/python3.7/site-packages/paddleseg/models/layers/layer_libs.py", line 45, in __init__
    in_channels, out_channels, kernel_size, padding=padding, **kwargs)
  File "/home/anaconda/envs/wxt-env/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 657, in __init__
    data_format=data_format)
  File "/home/anaconda/envs/wxt-env/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 136, in __init__
    default_initializer=_get_default_param_initializer())
  File "/home/anaconda/envs/wxt-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 424, in create_parameter
    default_initializer)
  File "/home/anaconda/envs/wxt-env/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 381, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/home/anaconda/envs/wxt-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3572, in create_parameter
    initializer(param, self)
  File "/home/anaconda/envs/wxt-env/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 367, in __call__
    'std', self._std_dev, 'seed', self._seed, 'use_mkldnn', False)
OSError: (External) CUDA error(2), out of memory.
  [Hint: 'cudaErrorMemoryAllocation'. The API call failed because it was unable to allocate enough memory to perform the requested operation. ] (at /paddle/paddle/phi/backends/gpu/gpu_resources.cc:120)
  [operator < gaussian_random > error]

**Comment by Stinky-Tofu** [comment]
把batch size调小试试？ @largerwxt
