### ISSUE TITLE
pdseg/train.py报错求助

### ISSUE THREAD

**Issue by Tangzixia** [PaddlePaddle/PaddleSeg#319]
你好，我这边出现了这个问题，应该是加载图像的时候报的错，可是真不知道怎么调试，麻烦帮看一下，谢谢。
Traceback (most recent call last):
  File "/home/vis/kangshuai/apps/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/vis/kangshuai/apps/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vis/kangshuai/apps/anaconda3/lib/python3.6/site-packages/paddle/fluid/reader.py", line 1157, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/home/vis/kangshuai/apps/anaconda3/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/vis/kangshuai/apps/anaconda3/lib/python3.6/site-packages/paddle/fluid/reader.py", line 1137, in __thread_main__
    for tensors in self._tensor_reader():
  File "/home/vis/kangshuai/apps/anaconda3/lib/python3.6/site-packages/paddle/fluid/data_feeder.py", line 204, in __call__
    yield self._done()
  File "/home/vis/kangshuai/apps/anaconda3/lib/python3.6/site-packages/paddle/fluid/data_feeder.py", line 192, in _done
    return [c.done() for c in self.converters]
  File "/home/vis/kangshuai/apps/anaconda3/lib/python3.6/site-packages/paddle/fluid/data_feeder.py", line 192, in <listcomp>
    return [c.done() for c in self.converters]
  File "/home/vis/kangshuai/apps/anaconda3/lib/python3.6/site-packages/paddle/fluid/data_feeder.py", line 157, in done
    arr = np.array(self.data, dtype=self.dtype)
ValueError: could not broadcast input array from shape (3,384,384) into shape (3)

/home/vis/kangshuai/apps/anaconda3/lib/python3.6/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/vis/kangshuai/apps/anaconda3/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/vis/kangshuai/apps/anaconda3/lib/python3.6/site-packages/paddle/fluid/reader.py", line 1079, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "/home/vis/kangshuai/apps/anaconda3/lib/python3.6/site-packages/paddle/fluid/reader.py", line 977, in __init__
    self._init_non_iterable()
  File "/home/vis/kangshuai/apps/anaconda3/lib/python3.6/site-packages/paddle/fluid/reader.py", line 608, in from_generator
    iterable, return_list, drop_last)
  File "/home/vis/kangshuai/procedure/PaddleSeg-release-v0.5.0/pdseg/models/model_builder.py", line 142, in build_model
    use_double_buffer=True)
  File "pdseg/train.py", line 237, in train
    train_prog, startup_prog, phase=ModelPhase.TRAIN)
  File "pdseg/train.py", line 453, in main
    train(cfg)
  File "pdseg/train.py", line 466, in <module>
    main(args)

**Comment by nepeplwu** [comment]
@Tangzixia 请问下你的Paddle版本数多少？另外数据是否检查过？

**Comment by Tangzixia** [comment]
已经找到问题所在了，是数据的问题，谢谢了
