### ISSUE TITLE
使用多卡训练恢复训练时报错AssertionError: Optimizer set error, sync_batch_norm_0.w_0_moment1_0 should in state dict

### ISSUE THREAD

**Issue by ConstantineQAQ** [PaddlePaddle/PaddleSeg#3236]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

在百度aistudio平台上使用V100 4卡运行环境时执行
!export CUDA_VISIBLE_DEVICES=0,1,2,3 # 设置4张可用的卡
!python -m paddle.distributed.launch tools/train.py --config configs/rtformer_car.yml --do_eval --use_ema --resume_model output/iter_30000 --save_interval 1000 --num_workers 16时会报错：

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/lr.py:199: UserWarning: There are some unused values in state_dict. Maybe the optimizer have different 'LearningRateDecay' when invoking state_dict and set_dict
  "There are some unused values in state_dict. Maybe the optimizer have different 'LearningRateDecay' when invoking state_dict and set_dict"
I0426 18:19:54.547080  1567 tcp_utils.cc:181] The server starts to listen on IP_ANY:36001
I0426 18:19:54.547318  1567 tcp_utils.cc:130] Successfully connected to 10.156.6.53:36001
[2023-04-26 18:20:03,050] [    INFO] topology.py:187 - HybridParallelInfo: rank_id: 0, mp_degree: 1, sharding_degree: 1, pp_degree: 1, dp_degree: 4, mp_group: [0],  sharding_group: [0], pp_group: [0], dp_group: [0, 1, 2, 3], check/clip group: [0]
Traceback (most recent call last):
  File "tools/train.py", line 195, in <module>
    main(args)
  File "tools/train.py", line 190, in main
    to_static_training=cfg.to_static_training)
  File "/home/aistudio/PaddleSeg/paddleseg/core/train.py", line 244, in train
    optimizer.step()
  File "<decorator-gen-313>", line 2, in step
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 319, in __impl__
    return func(*args, **kwargs)
  File "<decorator-gen-311>", line 2, in step
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/distributed/fleet/meta_optimizers/dygraph_optimizer/hybrid_parallel_optimizer.py", line 220, in step
    self._inner_opt.step()
  File "<decorator-gen-306>", line 2, in step
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 319, in __impl__
    return func(*args, **kwargs)
  File "<decorator-gen-304>", line 2, in step
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/adamw.py", line 580, in step
    params_grads=params_grads)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 1167, in _apply_optimize
    params_grads, param_group_idx=param_group_idx
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 928, in _create_optimization_pass
    for p in parameters_and_grads
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/adamw.py", line 406, in _create_accumulators
    self._add_moments_pows(p)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/adamw.py", line 371, in _add_moments_pows
    self._add_accumulator(self._moment1_acc_str, p, dtype=acc_dtype)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 756, in _add_accumulator
    var_name
AssertionError: Optimizer set error, sync_batch_norm_0.w_0_moment1_0 should in state dict
I0426 18:20:09.279353  1805 tcp_store.cc:257] receive shutdown event and so quit from MasterDaemon run loop
LAUNCH INFO 2023-04-26 18:20:10,859 Pod failed
LAUNCH ERROR 2023-04-26 18:20:10,860 Container failed !!!
Container rank 0 status failed cmd ['/opt/conda/envs/python35-paddle120-env/bin/python', '-u', 'tools/train.py', '--config', 'configs/rtformer_car.yml', '--do_eval', '--use_ema', '--resume_model', 'output/iter_3000', '--save_interval', '1000'] code 1 log log/workerlog.0 
env {'CUDNN_VERSION': '7.3.1.20', 'STUDIO_STATIC_URL': 'https://ai-studio-static-online.cdn.bcebos.com/studio-notebook/dist/webide', 'STUDIO_SERVING_TOKEN': 'token 6659C41E81D04B59B9C873CE62BFA5C00D0E2CDF6C0342808B7255A17DFC0A55', 'JUPYTER_4190277_6053639_SERVICE_PORT': '8888', 'JUPYTER_2956967_6054762_PORT_8888_TCP_ADDR': '10.157.154.121', 'JUPYTER_2996288_5975202_SERVICE_HOST': '10.157.197.149', 'HOSTNAME': 'jupyter-2956967-6054762', 'IDE_HUB_0_PORT_8771_TCP_PORT': '8771', 'JUPYTER_711434_6054768_SERVICE_HOST': '10.157.126.211', 'IDE_HUB_PROXY_1_PORT_8780_TCP_PROTO': 'tcp', 'JUPYTER_2956967_6054762_PORT_8888_TCP': 'tcp://10.157.154.121:8888', 'JUPYTER_837439_6054593_SERVICE_HOST': '10.157.46.69', 'NVIDIA_REQUIRE_CUDA': 'cuda>=9.2', 'FE_VSCODE_BUTTON_SHOW': 'False', 'JUPYTER_2956967_6054762_SERVICE_PORT_JUPYTER_2956967_6054762': '8888', 'JUPYTER_3277897_6054195_PORT_8888_TCP_PORT': '8888', 'JUPYTER_4190277_6053639_PORT': 'tcp://10.157.139.104:8888', 'JUPYTER_4162641_6022501_SERVICE_PO
LAUNCH INFO 2023-04-26 18:20:10,860 ------------------------- ERROR LOG DETAIL -------------------------
 mp_group: [0],  sharding_group: [0], pp_group: [0], dp_group: [0, 1, 2, 3], check/clip group: [0]
Traceback (most recent call last):
  File "tools/train.py", line 195, in <module>
    main(args)
  File "tools/train.py", line 190, in main
    to_static_training=cfg.to_static_training)
  File "/home/aistudio/PaddleSeg/paddleseg/core/train.py", line 244, in train
    optimizer.step()
  File "<decorator-gen-313>", line 2, in step
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 319, in __impl__
    return func(*args, **kwargs)
  File "<decorator-gen-311>", line 2, in step
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/distributed/fleet/meta_optimizers/dygraph_optimizer/hybrid_parallel_optimizer.py", line 220, in step
    self._inner_opt.step()
  File "<decorator-gen-306>", line 2, in step
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 319, in __impl__
    return func(*args, **kwargs)
  File "<decorator-gen-304>", line 2, in step
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/adamw.py", line 580, in step
    params_grads=params_grads)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 1167, in _apply_optimize
    params_grads, param_group_idx=param_group_idx
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 928, in _create_optimization_pass
    for p in parameters_and_grads
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/adamw.py", line 406, in _create_accumulators
    self._add_moments_pows(p)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/adamw.py", line 371, in _add_moments_pows
    self._add_accumulator(self._moment1_acc_str, p, dtype=acc_dtype)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 756, in _add_accumulator
    var_name
AssertionError: Optimizer set error, sync_batch_norm_0.w_0_moment1_0 should in state dict
I0426 18:20:09.279353  1805 tcp_store.cc:257] receive shutdown event and so quit from MasterDaemon run loop

### 复现环境 Environment

Linux
PaddlePaddle:2.4.0
PaddleSeg:release
python:3.7.0
CUDA:10.2
CUDNN:7.6
GCC:8.2.0
 

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Bobholamovic** [comment]
我在这里找到了一个类似的issue：https://aistudio.baidu.com/paddle/forum/topic/show/989540
建议尝试重启jupyter notebook环境后再执行试试~
