### ISSUE TITLE
如何使用官网提供的模型直接推理自己的图片呢，使用predict.py时发现给的配置文件好像都是训练用的

### ISSUE THREAD

**Issue by zzhmx** [PaddlePaddle/PaddleSeg#3254]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

如何使用官网提供的模型直接推理自己的图片呢，使用predict.py时发现给的配置文件好像都是训练用的，进行预测会报错：
`Traceback (most recent call last):
  File "D:\paddleSeg\tools\predict.py", line 147, in <module>
    main(args)
  File "D:\paddleSeg\tools\predict.py", line 130, in main
    model = builder.model
  File "D:\paddleSeg\paddleseg\utils\utils.py", line 274, in __get__
    val = self.func(obj)
  File "D:\paddleSeg\paddleseg\cvlibs\builder.py", line 123, in model
    assert hasattr(self.train_dataset_class, 'NUM_CLASSES'), \
  File "D:\paddleSeg\paddleseg\utils\utils.py", line 274, in __get__
    val = self.func(obj)
  File "D:\paddleSeg\paddleseg\cvlibs\builder.py", line 286, in train_dataset_class
    return self.load_component_class(dataset_type)
  File "D:\paddleSeg\paddleseg\cvlibs\builder.py", line 86, in load_component_class
    raise RuntimeError("The specified component ({}) was not found.".format(
RuntimeError: The specified component (CityscapesTrain) was not found.
`

**Comment by Stinky-Tofu** [comment]
@zzhmx paddleSeg/deploy/python/infer.py
