### ISSUE TITLE
在对Paddleseg的Sam模型进行动转静时出现的问题：ValueError: The feeded_var_names[0]: 'boxes' doesn't exist in pruned inference program. 

### ISSUE THREAD

**Issue by littlecay** [PaddlePaddle/PaddleSeg#3288]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我现在进行动静转化，调用paddle.jit.save(model, 'model')的时候出现了ValueError: The feeded_var_names[0]: 'boxes' doesn't exist in pruned inference program. 
```
Traceback (most recent call last):
  File "/home/user/deeplearning/PaddleSeg-release-2.8/contrib/SegmentAnything/export.py", line 360, in <module>
    main(args)
  File "/home/user/deeplearning/PaddleSeg-release-2.8/contrib/SegmentAnything/export.py", line 332, in main
    paddle.jit.save(model, os.path.join(args.save_dir, 'model'))
  File "/home/user/Documents/anaconda3/envs/paddle/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/user/Documents/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/user/Documents/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/dygraph/jit.py", line 649, in wrapper
    func(layer, path, input_spec, **configs)
 File "/home/user/Documents/anaconda3/envs/paddle/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/user/Documents/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/user/Documents/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 558, in __impl__
    return func(*args, **kwargs)
  File "/home/user/Documents/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/io.py", line 1403, in save_inference_model
    prepend_feed_ops(main_program, feeded_var_names)
  File "/home/user/Documents/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/io.py", line 1197, in prepend_feed_ops
    raise ValueError(
ValueError: The feeded_var_names[0]: 'boxes' doesn't exist in pruned inference program. Please check whether 'boxes' is a valid feed_var name, or remove it from feeded_var_names if 'boxes' is not involved in the target_vars calculation.
```

我的Input_Spec包括两部分
```
    input_spec = [[{
                    'image': paddle.static.InputSpec(shape=[3, None, None], name='image'),
                    'original_size': paddle.static.InputSpec(shape=[None, None], name='original_size'),
                    'point_coords': paddle.static.InputSpec(shape=[None], name='point_coords'),
                    'point_labels': paddle.static.InputSpec(shape=[None], name='point_labels'),
                    'boxes': paddle.static.InputSpec(shape=[None, None], name='boxes'),
                    'mask_inputs': paddle.static.InputSpec(shape=[None], name='mask_inputs')
                    }],
                  paddle.static.InputSpec(shape=[None], dtype='bool', name='multimask_output')]
```
但是当我注释掉boxes的时候，又提示其他的输入也有问题了。

这个pruned inference program是什么啊，我看着feeded_var_names[0]这个形式有点像预训练模型里的东西，但是model.pdparams打开都是乱码。求大佬指点一二，谢谢

参考了#728，但是似乎不太有帮助，因为他的最终解决方式是修改fetch输出，但是我是直接jit.save，没有读输出的这个步骤。或许我可以在哪里找到一个方式把fetch_var_names之类的参数传入什么地方去？这样就可以让网络不会自动裁减掉与输出有关的输入了

**Comment by shiyutang** [comment]
建议减少forward函数的入参避免被裁减，例如点击的数据point_labels可以直接指定，original_size可以通过类属性获取；另外建议将point、box、mask三种输入进行拆分，分别指定输入获得输出。

**Comment by littlecay** [comment]
> 建议减少forward函数的入参避免被裁减，例如点击的数据point_labels可以直接指定，original_size可以通过类属性获取；另外建议将point、box、mask三种输入进行拆分，分别指定输入获得输出。

其实好几个参数都是None的，但是由于我使用的固定的预训练模型，我担心减少入参是否会引起无法加载预训练模型

**Comment by littlecay** [comment]
减少入参确实不会被裁减了！谢谢你，跑通啦

**Comment by mrljwlm** [comment]
> 减少入参确实不会被裁减了！谢谢你，跑通啦

大佬能share一下具体的导出代码吗，我也折腾很久了还是导出不了

**Comment by littlecay** [comment]
> > 减少入参确实不会被裁减了！谢谢你，跑通啦
> 
> 大佬能share一下具体的导出代码吗，我也折腾很久了还是导出不了

我在我fork的分支里上传了，顺便我也提交了pull request，好像还没有通过。
目前我的导出版本里暂时还不支持prompt，只能全分割
https://github.com/littlecay/PaddleSeg/blob/release/2.8/contrib/SegmentAnything/export.py

**Comment by mrljwlm** [comment]
> > > 减少入参确实不会被裁减了！谢谢你，跑通啦
> > 
> > 
> > 大佬能share一下具体的导出代码吗，我也折腾很久了还是导出不了
> 
> 我在我fork的分支里上传了，顺便我也提交了pull request，好像还没有通过。 目前我的导出版本里暂时还不支持prompt，只能全分割 https://github.com/littlecay/PaddleSeg/blob/release/2.8/contrib/SegmentAnything/export.py

大佬，我用了你的方法来进行导出，导出是成功了，但是我用c++加载模型会报错，你导出后的模型能正常加载推断吗
![image](https://github.com/PaddlePaddle/PaddleSeg/assets/23266835/07dc7349-51ab-44dc-adf0-3b62ef299c48)

加载模型的代码：
```
        paddle_infer::Config infer_config;
	infer_config.SetModel(model_file, model_param);

	infer_config.EnableUseGpu(4096, 0);
	infer_config.EnableCUDNN();
	infer_config.SwitchIrOptim(true);
	infer_config.EnableMemoryOptim();

	auto predictor = paddle_infer::CreatePredictor(infer_config); // ---> 报错在这里
```
