### ISSUE TITLE
When using SegmentAnything 

### ISSUE THREAD

**Issue by Nuralill** [PaddlePaddle/PaddleSeg#3297]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

When I using the following steps [https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.8/contrib/SegmentAnything](https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.8/contrib/SegmentAnything) with SegmentAnything to run the  demo , there's a error.
``` shell
(project3.9) hid@hid-EC0-1822:/media/hid/project/pythonProject/PaddleSeg-release-2.8/contrib/SegmentAnything$ python scripts/text_to_sam_clip.py --model-type vit_h
/home/hid/anaconda3/envs/project3.9/lib/python3.9/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/home/hid/anaconda3/envs/project3.9/lib/python3.9/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/hid/anaconda3/envs/project3.9/lib/python3.9/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/hid/anaconda3/envs/project3.9/lib/python3.9/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
Loading model...
W0530 11:29:33.123697 3234552 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.1, Runtime API Version: 11.7
W0530 11:29:33.140290 3234552 gpu_resources.cc:91] device: 0, cuDNN Version: 8.5.
2023-05-30 11:29:34 [INFO]      Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/paddlesegAnything/vit_h/model.pdparams
2023-05-30 11:29:38 [INFO]      There are 594/594 variables loaded into Sam.
/home/hid/anaconda3/envs/project3.9/lib/python3.9/site-packages/gradio/inputs.py:26: UserWarning: Usage of gradio.inputs is deprecated, and will not be supported in the future, please import your component from gradio.components
  warnings.warn(
/home/hid/anaconda3/envs/project3.9/lib/python3.9/site-packages/gradio/deprecation.py:40: UserWarning: `optional` parameter is deprecated, and it has no effect
  warnings.warn(value)
/home/hid/anaconda3/envs/project3.9/lib/python3.9/site-packages/gradio/deprecation.py:40: UserWarning: `numeric` parameter is deprecated, and it has no effect
  warnings.warn(value)
/home/hid/anaconda3/envs/project3.9/lib/python3.9/site-packages/gradio/utils.py:70: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if StrictVersion(latest_pkg_version) > StrictVersion(current_pkg_version):
Traceback (most recent call last):
  File "/media/hid/project/pythonProject/PaddleSeg-release-2.8/contrib/SegmentAnything/scripts/text_to_sam_clip.py", line 239, in <module>
    gradio_display()
  File "/media/hid/project/pythonProject/PaddleSeg-release-2.8/contrib/SegmentAnything/scripts/text_to_sam_clip.py", line 219, in gradio_display
    demo = gr.TabbedInterface(
TypeError: __init__() got an unexpected keyword argument 'title'

```

And following changes could resolve this error.
 File "/media/hid/project/pythonProject/PaddleSeg-release-2.8/contrib/SegmentAnything/scripts/text_to_sam_clip.py", line 219,remove the 'title'.
``` python 
    demo = gr.TabbedInterface(
        [demo_mask_sam, ], ['SAM+CLIP(Text to Segment)']) #,
       # title=" 🔥 Text to Segment Anything with PaddleSeg 🔥")
```

### 复现环境 Environment

- OS : Linux
- Paddlepaddle : 2.4.2
-  python:  3.9.0
- PaddleSeg: 2.8.0
- CUDA : 11.6

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by DhruvAwasthi** [comment]
@Nuralill I faced the same issue while trying to run the demo. It is caused due to the updated gradio version. When we pass the `title` argument it raises the error because in gradio, the argument passed is now updated to `theme`. 

Hence instead of dropping this, the argument needs to be updated. 
I have raised a PR #3299 resolving the same.

**Comment by Nuralill** [comment]
> 

Yeah, you find the better way. Thank you!

**Comment by DhruvAwasthi** [comment]
You're welcome!
