### ISSUE TITLE
安装完之后如何打开GUI?

### ISSUE THREAD

**Issue by jaycecd** [PaddlePaddle/PaddleSeg#3368]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我的天啊，写了这么多的文档，居然没写安装完之后如何打开？？
本来是想用PaddleSeg标注数据，但是安装完之后，我搜索了文档，好像没看到，安装完之后如何打开GUI？？？

**Comment by zengshao0622** [comment]
请问具体是希望使用哪项功能呢？

**Comment by jaycecd** [comment]
我这边已经打开了（eiseg），因为是第一次用paddleseg，查了很久才知道如何打开，我建议能不能在主页上面列出有哪些程序是有GUI的以及如何打开这些带有GUI的应用？

**Comment by shiyutang** [comment]
可以参考安装说明文档，运行exe.py即可：https://github.com/PaddlePaddle/PaddleSeg/blob/develop/EISeg/docs/install.md#%E5%85%8B%E9%9A%86%E5%88%B0%E6%9C%AC%E5%9C%B0

**Comment by jaycecd** [comment]
我就是参考这个文档之后才打开的，关键是对于一个新手来说，一进来是不知道相应的工具的文档在哪里~~
你很清楚是因为你已经很熟悉啦，我觉得最好在主页要给出面向用户，特别是新手用户的整体功能的框图，尤其是带有GUI的功能需要重点突出一下。

**Comment by kssion** [comment]
我安装后打不开，报错信息如下

```
$ python exe.py                        (paddle-seg)
Traceback (most recent call last):
  File "/Users/cx/PycharmProjects/PaddleSeg/EISeg/eiseg/exe.py", line 20, in <module>
    from run import main
  File "/Users/cx/PycharmProjects/PaddleSeg/EISeg/eiseg/run.py", line 21, in <module>
    from qtpy.QtWidgets import QApplication  # 导入PyQt相关模块
  File "/Users/cx/miniconda3/envs/paddle-seg/lib/python3.9/site-packages/qtpy/__init__.py", line 287, in <module>
    raise QtBindingsNotFoundError from None
qtpy.QtBindingsNotFoundError: No Qt bindings could be found
```
搜索之后安装了 PySide6，又有其他报错

```
$ python exe.py                        (paddle-seg)
Traceback (most recent call last):
  File "/Users/cx/PycharmProjects/PaddleSeg/EISeg/eiseg/exe.py", line 20, in <module>
    from run import main
  File "/Users/cx/PycharmProjects/PaddleSeg/EISeg/eiseg/run.py", line 25, in <module>
    from app import APP_EISeg  # 导入带槽的界面
  File "/Users/cx/PycharmProjects/PaddleSeg/EISeg/eiseg/app.py", line 28, in <module>
    from qtpy.QtCore import Qt, QByteArray, QVariant, QCoreApplication
ImportError: cannot import name 'QVariant' from 'qtpy.QtCore' (/Users/cx/miniconda3/envs/paddle-seg/lib/python3.9/site-packages/qtpy/QtCore.py)
```

环境信息：
```
$ conda info                           (paddle-seg)

     active environment : paddle-seg
    active env location : /Users/cx/miniconda3/envs/paddle-seg
            shell level : 2
       user config file : /Users/cx/.condarc
 populated config files : /Users/cx/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.9.15.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.4=0
                          __unix=0=0
       base environment : /Users/cx/miniconda3  (writable)
      conda av data dir : /Users/cx/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/cx/miniconda3/pkgs
                          /Users/cx/.conda/pkgs
       envs directories : /Users/cx/miniconda3/envs
                          /Users/cx/.conda/envs
               platform : osx-arm64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.9.15 Darwin/22.5.0 OSX/13.4
                UID:GID : 501:20
             netrc file : /Users/cx/.netrc
           offline mode : False
```

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
