### ISSUE TITLE
Elseg标注的数据出现维度错误

### ISSUE THREAD

**Issue by x12901** [PaddlePaddle/PaddleSeg#3468]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

尝试使用EISeg标注出的数据作为数据集直接训练测试，但进行_pseudo.jpg和原图切分数据后训练出现维度错误，尝试改变数据增强参数可以改变维度错误数值但是依然不能成功训练，
数据集链接: https://pan.baidu.com/s/105jTdz0SyXcpmdvE8YR60w?pwd=rsg3 提取码: rsg3 复制这段内容后打开百度网盘手机App，操作更方便哦
```shell
(PP) C:\CODE\PaddleSeg-release-2.8>python tools/train.py --config C:\CODE\PaddleSeg-release-2.8\configs\pp_liteseg\pp_liteseg_stdc1_camvid_960x720_10k.yml  --save_dir output
2023-08-23 09:13:45 [WARNING]   Add the `num_classes` in train_dataset and val_dataset config to model config. We suggest you manually set `num_classes` in model config.
2023-08-23 09:13:45 [INFO]
------------Environment Information-------------
platform: Windows-10-10.0.19042-SP0
Python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
Paddle compiled with cuda: True
NVCC: Build cuda_12.1.r12.1/compiler.32688072_0
cudnn: 8.9
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce']
PaddleSeg: 2.8.0
PaddlePaddle: 2.5.1
OpenCV: 4.8.0
------------------------------------------------
2023-08-23 09:13:45 [INFO]
---------------Config Information---------------
batch_size: 6
iters: 10000
train_dataset:
  dataset_root: C:/CODE/dataset/JPEGImages
  mode: train
  num_classes: 4
  train_path: C:/CODE/dataset/JPEGImages/train.txt
  transforms:
  - max_scale_factor: 2.5
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 960
    - 720
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.5
    contrast_range: 0.5
    saturation_range: 0.5
    type: RandomDistort
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: C:/CODE/dataset/JPEGImages
  mode: val
  num_classes: 4
  transforms:
  - type: Normalize
  type: Dataset
  val_path: C:/CODE/dataset/JPEGImages/val.txt
optimizer:
  momentum: 0.9
  type: SGD
  weight_decay: 0.0005
lr_scheduler:
  end_lr: 0
  learning_rate: 0.01
  power: 0.9
  type: PolynomialDecay
  warmup_iters: 200
  warmup_start_lr: 1.0e-05
loss:
  coef:
  - 1
  - 1
  - 1
  types:
  - min_kept: 250000
    type: OhemCrossEntropyLoss
  - min_kept: 250000
    type: OhemCrossEntropyLoss
  - min_kept: 250000
    type: OhemCrossEntropyLoss
model:
  arm_out_chs:
  - 32
  - 64
  - 128
  backbone:
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet1.tar.gz
    type: STDC1
  num_classes: 4
  seg_head_inter_chs:
  - 32
  - 64
  - 64
  type: PPLiteSeg
------------------------------------------------

2023-08-23 09:13:45 [INFO]      Set device: gpu
2023-08-23 09:13:45 [INFO]      Use the following config to build model
model:
  arm_out_chs:
  - 32
  - 64
  - 128
  backbone:
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet1.tar.gz
    type: STDC1
  num_classes: 4
  seg_head_inter_chs:
  - 32
  - 64
  - 64
  type: PPLiteSeg
W0823 09:13:46.293418 11204 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 12.2, Runtime API Version: 12.0
W0823 09:13:46.293418 11204 gpu_resources.cc:149] device: 0, cuDNN Version: 8.9.
2023-08-23 09:13:46 [INFO]      Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet1.tar.gz
2023-08-23 09:13:46 [INFO]      There are 145/145 variables loaded into STDCNet.
2023-08-23 09:13:46 [INFO]      Use the following config to build train_dataset
train_dataset:
  dataset_root: C:/CODE/dataset/JPEGImages
  mode: train
  num_classes: 4
  train_path: C:/CODE/dataset/JPEGImages/train.txt
  transforms:
  - max_scale_factor: 2.5
    min_scale_factor: 0.5
    scale_step_size: 0.25
    type: ResizeStepScaling
  - crop_size:
    - 960
    - 720
    type: RandomPaddingCrop
  - type: RandomHorizontalFlip
  - brightness_range: 0.5
    contrast_range: 0.5
    saturation_range: 0.5
    type: RandomDistort
  - type: Normalize
  type: Dataset
2023-08-23 09:13:46 [INFO]      If the type is SGD and momentum in optimizer config, the type is changed to Momentum.
2023-08-23 09:13:46 [INFO]      Use the following config to build optimizer
optimizer:
  momentum: 0.9
  type: Momentum
  weight_decay: 0.0005
2023-08-23 09:13:46 [INFO]      Use the following config to build loss
loss:
  coef:
  - 1
  - 1
  - 1
  types:
  - min_kept: 250000
    type: OhemCrossEntropyLoss
  - min_kept: 250000
    type: OhemCrossEntropyLoss
  - min_kept: 250000
    type: OhemCrossEntropyLoss
C:\ProgramData\Anaconda3\envs\PP\lib\site-packages\paddle\nn\layer\norm.py:777: UserWarning: When training, we now always track global mean and variance.
  warnings.warn(
Traceback (most recent call last):
  File "tools/train.py", line 195, in <module>
    main(args)
  File "tools/train.py", line 170, in main
    train(
  File "c:\code\paddleseg-release-2.8\paddleseg\core\train.py", line 237, in train
    loss_list = loss_computation(
  File "c:\code\paddleseg-release-2.8\paddleseg\core\train.py", line 57, in loss_computation
    loss_list.append(coef_i * loss_i(logits, labels))
  File "C:\ProgramData\Anaconda3\envs\PP\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "c:\code\paddleseg-release-2.8\paddleseg\models\losses\ohem_cross_entropy_loss.py", line 68, in forward
    prob = prob + (1 - valid_mask)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [4, 4147200] and the shape of Y = [12441600]. Received [4147200] in X is not equal to [12441600] in Y at i:1.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at ..\paddle/phi/kernels/funcs/common_shape.h:86)

```

### 复现环境 Environment

Python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
Paddle compiled with cuda: True
NVCC: Build cuda_12.1.r12.1/compiler.32688072_0
cudnn: 8.9
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce']
PaddleSeg: 2.8.0
PaddlePaddle: 2.5.1
OpenCV: 4.8.0
Windows10

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
