### ISSUE TITLE
训练出错，错误显示：输入尺寸不一致，但是检查了图片输入尺寸是一致的，请大佬帮忙看看哪里出错了

### ISSUE THREAD

**Issue by loxoo6** [PaddlePaddle/PaddleSeg#3503]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

2023-09-16 19:21:49 [INFO]	There are 275/275 variables loaded into ResNet_vd.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 218, in _thread_loop
    self._thread_done_event)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 70, in default_collate_fn
    for key in sample
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 70, in <dictcomp>
    for key in sample
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/collate.py", line 58, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 6, in stack
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/numpy/core/shape_base.py", line 427, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape

### 复现环境 Environment

aistudio
项目地址：https://aistudio.baidu.com/projectdetail/5326180?contributionType=1&sUid=2667058&shared=1&ts=1694863474127

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by Asthestarsfalll** [comment]
看报错还是因为图片输入尺寸不一样，可以在dataset 的`getitem`方法里面加一个打印看看数据增强后的尺寸一不一致

**Comment by loxoo6** [comment]
> 看报错还是因为图片输入尺寸不一样，可以在dataset 的`getitem`方法里面加一个打印看看数据增强后的尺寸一不一致

    def __getitem__(self, idx):
        data = {}
        data['trans_info'] = []
        # 通过idx下标，在file_list里获取样本图片路径和标签图片路径。
        image_path, label_path = self.file_list[idx]
        data['img'] = image_path
        data['label'] = label_path
        # If key in gt_fields, the data[key] have transforms synchronous.
        data['gt_fields'] = []
        if self.mode == 'val':
            data = self.transforms(data)
            data['label'] = data['label'][np.newaxis, :, :]#三维数组

        else:
            data['gt_fields'].append('label')
            data = self.transforms(data)
            if self.edge:
                edge_mask = F.mask_to_binary_edge(
                    data['label'], radius=2, num_classes=self.num_classes)
                data['edge'] = edge_mask
        data['image_size'] = (data['img'].shape[1], data['img'].shape[2])
  
        return data
请问我加了一句        data['image_size'] = (data['img'].shape[1], data['img'].shape[2])
怎么能打印出它的结果呢
