### ISSUE TITLE
Cannot train using fp16

### ISSUE THREAD

**Issue by rpl-alan-shangguan** [PaddlePaddle/PaddleSeg#3515]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

Traceback (most recent call last):
  File "tools/train.py", line 195, in <module>
    main(args)
  File "tools/train.py", line 170, in main
    train(
  File "/home/alan/Downloads/PaddleSeg/paddleseg/core/train.py", line 225, in train
    scaler.minimize(optimizer, scaled)  # update parameters
  File "/home/alan/miniconda3/envs/pp/lib/python3.8/site-packages/paddle/amp/grad_scaler.py", line 715, in minimize
    return super().minimize(optimizer, *args, **kwargs)
  File "/home/alan/miniconda3/envs/pp/lib/python3.8/site-packages/paddle/amp/grad_scaler.py", line 249, in minimize
    optimize_ops, params_grads = optimizer.minimize(*args, **kwargs)
  File "/home/alan/miniconda3/envs/pp/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/alan/miniconda3/envs/pp/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 347, in _decorate_function
    return func(*args, **kwargs)
  File "/home/alan/miniconda3/envs/pp/lib/python3.8/site-packages/paddle/optimizer/optimizer.py", line 1476, in minimize
    params_grads = self.backward(
  File "/home/alan/miniconda3/envs/pp/lib/python3.8/site-packages/paddle/optimizer/optimizer.py", line 1132, in backward
    grads = core.eager.get_all_grads(parameter_list)
ValueError: (InvalidArgument) argument (position 1) must be list of Tensor, but got dict at pos 0 (at ../paddle/fluid/pybind/eager_utils.cc:268)

When I use fp16, my paddlepaddle-gpu=2.5.0. When I use fp32, everything is fine.

### 复现环境 Environment

linux
paddlepaddle 2.5.0
paddleseg 2.8
python 3.8
cuda 12.2
cudnn 8.4
gcc 9.4.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by shiyutang** [comment]
My suggestion is to try lower paddle version like 2.4 and see if the result is expected. We have done multiple fp16 tests and things are fine. So it is likely the bug introduced in the paddle. If this is the fact, please raise an issue to paddle repo: https://github.com/PaddlePaddle/Paddle/issues
