### ISSUE TITLE
训练官方数据集报错

### ISSUE THREAD

**Issue by suorui7** [PaddlePaddle/PaddleSeg#3520]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

按照官方教程搭建环境，输入sh tests/install/check_predict.sh是也返回了图片，
我按照官方教程训练optic_disc_seg数据集，训练返回报错：
Traceback (most recent call last):
  File "tools/train.py", line 195, in <module>
    main(args)
  File "tools/train.py", line 190, in main
    to_static_training=cfg.to_static_training)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddleseg\core\train.py", line 273, in train
    avg_loss_list = [l[0] / log_iters for l in avg_loss_list]
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddleseg\core\train.py", line 273, in <listcomp>
    avg_loss_list = [l[0] / log_iters for l in avg_loss_list]
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

数据集没有做任何修改，但是依旧报错。
另：我训练自己标注数据集，会自己退出，但是GPU占有率大概为70%。

**Comment by suorui7** [comment]
已解决 
将avg_loss_list = [l[0] / log_iters for l in avg_loss_list]
改为avg_loss_list = [l / log_iters for l in avg_loss_list]

**Comment by X-MingYang** [comment]
您好，请问这个是在train.py文件应该在哪些找到呀？谢谢！
