### ISSUE TITLE
SegmentAnything出现AttributeError

### ISSUE THREAD

**Issue by messy2333** [PaddlePaddle/PaddleSeg#3589]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

项目：PaddleSeg-release-2.9/contrib/SegmentAnything
我在根据官方文档的步骤进行python scripts/amg_paddle.py --model-type vit_h这一步时，发生了以下错误：
Loading model...
2023-12-04 15:23:17 [INFO]      Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/paddlesegAnything/vit_l/model.pdparams
2023-12-04 15:23:21 [INFO]      There are 482/482 variables loaded into Sam.
Traceback (most recent call last):
  File "scripts/amg_paddle.py", line 308, in <module>
    main(args)
  File "scripts/amg_paddle.py", line 303, in main
    gradio_display(generator)
  File "scripts/amg_paddle.py", line 257, in gradio_display
    img_out1 = gr.Image(
AttributeError: 'Image' object has no attribute 'style'
编译提示代码中这一句出现问题 img_out1 = gr.Image( label="Output image", interactive=False).style(height=300)
我不知道怎么解决

**Comment by hunagjingwei** [comment]
请问你解决了吗，我也一样遇到这个问题

**Comment by hunagjingwei** [comment]
我解决了，pip install gradio==3.50.2就可以

**Comment by messy2333** [comment]
> 我解决了，pip install gradio==3.50.2就可以

是的，非常感谢
