### ISSUE TITLE
unet3+训练过程中评估，直接退出

### ISSUE THREAD

**Issue by KangLifei** [PaddlePaddle/PaddleSeg#3595]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

but right dtype is paddle.int64, the right dtype will convert to paddle.float32
  warnings.warn(
2023-12-13 09:05:08 [INFO]      [TRAIN] epoch: 1, iter: 10/2000, loss: 1.9442, lr: 0.009959, batch_cost: 45.4164, reader_cost: 0.07806, ips: 0.0881 samples/sec | ETA 25:06:18
2023-12-13 09:10:58 [INFO]      [TRAIN] epoch: 1, iter: 20/2000, loss: 1.0820, lr: 0.009914, batch_cost: 34.9546, reader_cost: 0.28587, ips: 0.1144 samples/sec | ETA 19:13:30
2023-12-13 09:16:41 [INFO]      [TRAIN] epoch: 1, iter: 30/2000, loss: 0.8479, lr: 0.009869, batch_cost: 34.3344, reader_cost: 0.28655, ips: 0.1165 samples/sec | ETA 18:47:18
2023-12-13 09:22:49 [INFO]      [TRAIN] epoch: 1, iter: 40/2000, loss: 0.8959, lr: 0.009824, batch_cost: 36.7811, reader_cost: 0.28762, ips: 0.1088 samples/sec | ETA 20:01:31
2023-12-13 09:28:36 [INFO]      [TRAIN] epoch: 2, iter: 50/2000, loss: 0.9409, lr: 0.009779, batch_cost: 34.6817, reader_cost: 0.21170, ips: 0.1153 samples/sec | ETA 18:47:09
2023-12-13 09:28:36 [INFO]      Start evaluating (total_samples: 55, total_iters: 55)...
PS E:\paddle\PaddleSeg-release-unet3+> python tools/train.py  --config configs/unet_3plus/unet_3plus.yml --do_eval --use_vdl --save_interval 500 --save_dir output
2023-12-13 09:33:31 [INFO]

### 复现环境 Environment

platform: Windows-10-10.0.19041-SP0
Python: 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64 bit (AMD64)]
Paddle compiled with cuda: True
NVCC: Build cuda_11.2.r11.2/compiler.29618528_0
cudnn: 8.1
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce']
PaddleSeg: 2.8.0
PaddlePaddle: 2.4.2
OpenCV: 4.8.0

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by lizhe-951202** [comment]
我也出现了同样的问题，请问楼主是怎么解决的？

**Comment by seastronger** [comment]
我也出现了同样的问题，请问楼主是解决了吗？

**Comment by wjlhahaha** [comment]
> 我也出现了同样的问题，请问楼主是解决了吗？

我也是请问您解决了吗

**Comment by KangLifei** [comment]
没解决，至今这不知道什么问题

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.

**Comment by TianchouYin** [comment]
我也遇到同样问题使用unet
单独评估没有问题
训练时评估显示：
`[2025/02/25 16:45:20] INFO: Start evaluating (total_samples: 50, total_iters: 50)...
50/50 [==============================] - 457s 9s/step - batch_cost: 9.1357 - reader cost: 4.4094e-04
Traceback (most recent call last):
  File "/home/aistudio/PaddleSeg-2.10.0/tools/train.py", line 252, in <module>
    main(args)
  File "/home/aistudio/PaddleSeg-2.10.0/tools/train.py", line 222, in main
    train(model,
  File "/home/aistudio/PaddleSeg-2.10.0/paddleseg/core/train.py", line 342, in train
    mean_iou, acc, _, _, _ = evaluate(model,
  File "/home/aistudio/PaddleSeg-2.10.0/paddleseg/core/val.py", line 231, in evaluate
    auc_roc = metrics.auc_roc(
  File "/home/aistudio/PaddleSeg-2.10.0/paddleseg/utils/metrics.py", line 116, in auc_roc
    auc = skmetrics.roc_auc_score(label, logits, multi_class='ovr')
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/sklearn/metrics/_ranking.py", line 631, in roc_auc_score
    return _multiclass_roc_auc_score(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/sklearn/metrics/_ranking.py", line 748, in _multiclass_roc_auc_score
    raise ValueError(
ValueError: Number of classes in y_true not equal to the number of columns in 'y_score'`
