### ISSUE TITLE
SegmentAngthing 出现引用gradio错误

### ISSUE THREAD

**Issue by hunagjingwei** [PaddlePaddle/PaddleSeg#3601]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

按照https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.9/contrib/SegmentAnything执行，出现一下错误：
Traceback (most recent call last):
  File "scripts/text_to_sam_clip.py", line 243, in <module>
    gradio_display()
  File "scripts/text_to_sam_clip.py", line 191, in gradio_display
    import gradio as gr
  File "/home/hjw/anaconda3/envs/pp-gpu/lib/python3.8/site-packages/gradio/__init__.py", line 3, in <module>
    import gradio._simple_templates
  File "/home/hjw/anaconda3/envs/pp-gpu/lib/python3.8/site-packages/gradio/_simple_templates/__init__.py", line 1, in <module>
    from .simpledropdown import SimpleDropdown
  File "/home/hjw/anaconda3/envs/pp-gpu/lib/python3.8/site-packages/gradio/_simple_templates/simpledropdown.py", line 6, in <module>
    from gradio.components.base import FormComponent
  File "/home/hjw/anaconda3/envs/pp-gpu/lib/python3.8/site-packages/gradio/components/__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "/home/hjw/anaconda3/envs/pp-gpu/lib/python3.8/site-packages/gradio/components/annotated_image.py", line 12, in <module>
    from gradio.components.base import Component
  File "/home/hjw/anaconda3/envs/pp-gpu/lib/python3.8/site-packages/gradio/components/base.py", line 21, in <module>
    from gradio.blocks import Block, BlockContext
  File "/home/hjw/anaconda3/envs/pp-gpu/lib/python3.8/site-packages/gradio/blocks.py", line 28, in <module>
    from gradio import (
  File "/home/hjw/anaconda3/envs/pp-gpu/lib/python3.8/site-packages/gradio/networking.py", line 20, in <module>
    from gradio.routes import App
  File "/home/hjw/anaconda3/envs/pp-gpu/lib/python3.8/site-packages/gradio/routes.py", line 116, in <module>
    client = httpx.AsyncClient()
  File "/home/hjw/anaconda3/envs/pp-gpu/lib/python3.8/site-packages/httpx/_client.py", line 1395, in __init__
    proxy_map = self._get_proxy_map(proxies, allow_env_proxies)
  File "/home/hjw/anaconda3/envs/pp-gpu/lib/python3.8/site-packages/httpx/_client.py", line 216, in _get_proxy_map
    return {
  File "/home/hjw/anaconda3/envs/pp-gpu/lib/python3.8/site-packages/httpx/_client.py", line 217, in <dictcomp>
    key: None if url is None else Proxy(url=url)
  File "/home/hjw/anaconda3/envs/pp-gpu/lib/python3.8/site-packages/httpx/_config.py", line 334, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:8888/')

**Comment by hunagjingwei** [comment]
unset ALL_PROXY；unset all_proxy命令解决了

**Comment by shiyutang** [comment]
好的，感谢你的关注。
