### ISSUE TITLE
请问如何安装才不报错？ pip install paddle2onnx

### ISSUE THREAD

**Issue by 1a1aca** [PaddlePaddle/PaddleSeg#3636]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

(paddle22) PS E:\Python Projects\PaddleSegTest\protobuf\cmake\Paddle2ONNX> pip install paddle2onnx
Collecting paddle2onnx
  Using cached paddle2onnx-0.9.2-py3-none-any.whl (100 kB)
Requirement already satisfied: six in d:\users\administrator\anaconda3\envs\paddle22\lib\site-packages (from paddle2onnx) (1.16.0)
Requirement already satisfied: protobuf in d:\users\administrator\anaconda3\envs\paddle22\lib\site-packages (from paddle2onnx) (3.20.2)
Collecting onnx<=1.9.0 (from paddle2onnx)
  Using cached onnx-1.9.0.tar.gz (9.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.16.6 in d:\users\administrator\anaconda3\envs\paddle22\lib\site-packages (from onnx<=1.9.0->paddle2onnx) (1.26.3)
Requirement already satisfied: typing-extensions>=3.6.2.1 in d:\users\administrator\anaconda3\envs\paddle22\lib\site-packages (from onnx<=1.9.0->paddle2onnx) (4.9.0)
Building wheels for collected packages: onnx
  Building wheel for onnx (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for onnx (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [100 lines of output]
      fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
      Use '--' to separate paths from revisions, like this:
      'git <command> [<revision>...] -- [<file>...]'
      C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\dist.py:472: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'license-file' will not be supported in future
              versions. Please use the underscore name 'license_file' instead.

              By 2024-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      running bdist_wheel
      running build
      running build_py
      running create_version
      running cmake_build
      Using cmake args: ['D:\\Users\\Administrator\\anaconda3\\envs\\paddle22\\Library\\bin\\cmake.exe', '-DPYTHON_INCLUDE_DIR=D:\\Users\\Administrator\\anaconda3\\envs\\paddle22\\include', '-DPYTHON_EXECUTABLE=D:\\Users\\Administrator\\anaconda3\\envs\\paddle22\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp311-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.11', '-DONNX_USE_MSVC_STATIC_RUNTIME=ON', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-yl6d_mze\\onnx_7adfc2dae44c474dabbaef31a20ec52e']
      -- Building for: NMake Makefiles
      CMake Error at CMakeLists.txt:17 (project):
        Generator

          NMake Makefiles

        does not support platform specification, but platform

          x64

        was specified.

      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "D:\Users\Administrator\anaconda3\envs\paddle22\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\Users\Administrator\anaconda3\envs\paddle22\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Users\Administrator\anaconda3\envs\paddle22\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\build_meta.py", line 404, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 337, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 233, in run
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-szpgbizi\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 219, in run
        File "D:\Users\Administrator\anaconda3\envs\paddle22\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['D:\\Users\\Administrator\\anaconda3\\envs\\paddle22\\Library\\bin\\cmake.exe', '-DPYTHON_INCLUDE_DIR=D:\\Users\\Administrator\\anaconda3\\envs\\paddle22\\include', '-DPYTHON_EXECUTABLE=D:\\Users\\Administrator\\anaconda3\\envs\\paddle22\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp311-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.11', '-DONNX_USE_MSVC_STATIC_RUNTIME=ON', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-yl6d_mze\\onnx_7adfc2dae44c474dabbaef31a20ec52e']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for onnx
Failed to build onnx
ERROR: Could not build wheels for onnx, which is required to install pyproject.toml-based projects
(paddle22) PS E:\Python Projects\PaddleSegTest\protobuf\cmake\Paddle2ONNX>

**Comment by TingquanGao** [comment]
Please refer to this doc: https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9/docs/model_export_onnx.md

And recommend try 0.6 version firstly: `pip install paddle2onnx==0.6`

**Comment by 1a1aca** [comment]
> 请参考此文档：https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.9/docs/model_export_onnx.md
> 
> 并建议先尝试 0.6 版本：`pip install paddle2onnx==0.6`

谢谢，我再研究一下导出
