### ISSUE TITLE
当标签数量为2时, 多标签语义分割无法训练

### ISSUE THREAD

**Issue by qiangxinglin** [PaddlePaddle/PaddleSeg#3646]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

使用`multilabelseg`时, 如果标签数量为2 (不算背景), 则会在训练时报以下错误
```
Error: /paddle/paddle/phi/kernels/funcs/scatter.cu.h:46 Assertion `scatter_i >= 0 && scatter_i < output_count` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [8388608] and greater or equal to 0, but received [0]
Traceback (most recent call last):
  File "/home/jovyan/work/PaddleSeg/tools/train.py", line 213, in <module>
    main(args)
  File "/home/jovyan/work/PaddleSeg/tools/train.py", line 188, in main
    train(
  File "/home/jovyan/work/PaddleSeg/paddleseg/core/train.py", line 244, in train
    loss.backward()
  File "/opt/conda/envs/paddle/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/opt/conda/envs/paddle/lib/python3.9/site-packages/paddle/base/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/paddle/lib/python3.9/site-packages/paddle/base/framework.py", line 593, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/paddle/lib/python3.9/site-packages/paddle/base/dygraph/tensor_patch_methods.py", line 342, in backward
    core.eager.run_backward([self], grad_tensor, retain_graph)
OSError: (External) CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED. 
  [Hint: 'CUDNN_STATUS_EXECUTION_FAILED'.  The GPU program failed to execute. This is usually caused by a failure to launch some cuDNN kernel on the GPU, which can occur for multiple reasons.  To correct, check that the hardware, an appropriate version of the driver, and the cuDNN library are correctly installed.  Otherwise, this may indicate an internal error/bug in the library.  ] (at /paddle/paddle/phi/kernels/gpudnn/conv_cudnn_v7.h:892)
```

如果将数据集加入`Transform: AddMultiLabelAuxiliaryCategory`, 使`num_classes = 3`, 则问题消失
```
train_dataset:
  type: Dataset
  dataset_root: data/MY_DATASET
  transforms:
    - type: AddMultiLabelAuxiliaryCategory # <- 此行
    - type: Resize
      target_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
      mean: [0.0, 0.0, 0.0]
      std: [1.0, 1.0, 1.0]
  num_classes: 3 # 从2改成3
  train_path: data/MY_DATASET/train.txt
  mode: train
```

### 复现环境 Environment

```
platform: Linux-3.10.0-1160.80.1.el7.x86_64-x86_64-with-glibc2.27
Python: 3.9.18 (main, Sep 11 2023, 13:41:44) [GCC 11.2.0]
Paddle compiled with cuda: True
NVCC: Build cuda_11.1.TC455_06.29190527_0
cudnn: 8.4
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce', 'GPU 1: NVIDIA GeForce', 'GPU 2: NVIDIA GeForce', 'GPU 3: NVIDIA GeForce']
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PaddleSeg: 2.9.0
PaddlePaddle: 2.6.0
OpenCV: 4.5.5
```

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by KellyGodLv** [comment]
num_classes  包含背景 num_classes  =labels+1

**Comment by shiyutang** [comment]
你好，背景也需要占一个类别。

**Comment by qiangxinglin** [comment]
> 你好，背景也需要占一个类别。

1. 那么上面的配置是正确的么? 假如标签有2种, 需要加入一个`transform: AddMultiLabelAuxiliaryCategory`, 之后`num_classes=3`?
2. 加了上述内容后, 背景mask也会输出, 如果仅输出标签mask (导出到onnx)?

**Comment by shiyutang** [comment]
> 1. 那么上面的配置是正确的么? 假如标签有2种, 需要加入一个`transform: AddMultiLabelAuxiliaryCategory`, 之后`num_classes=3`?

是的

如果想对mask进行选择，可以使用bool矩阵筛选去除0的部分。
