### ISSUE TITLE
在跑PaddleSeg实现植物语义分割项目时遇到bug：ValueError: cannot reshape array of size 262144 into shape (3840,2658)，

### ISSUE THREAD

**Issue by zhangxiaoxuan39** [PaddlePaddle/PaddleSeg#3714]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

我使用的数据集是PlantSegDatasets，配置文件使用的是pp_liteseg_stdc1_camvid_960x720_10k.yml。报错Exception in thread Thread-2:
Traceback (most recent call last):
  File "D:\environment\anaconda\envs\paddleSeg\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "D:\environment\anaconda\envs\paddleSeg\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "D:\environment\anaconda\envs\paddleSeg\lib\site-packages\paddle\io\dataloader\dataloader_iter.py", line 235, in _thread_loop
    batch = self._dataset_fetcher.fetch(
  File "D:\environment\anaconda\envs\paddleSeg\lib\site-packages\paddle\io\dataloader\fetcher.py", line 77, in fetch
    data.append(self.dataset[idx])
  File "D:\PaddleSeg\paddleseg\datasets\dataset.py", line 163, in __getitem__
    data = self.transforms(data)
  File "D:\PaddleSeg\paddleseg\transforms\transforms.py", line 88, in __call__
    data['label'] = data['label'].reshape([-1, img_h, img_w]).transpose([1, 2, 0])
ValueError: cannot reshape array of size 262144 into shape (3840,2658)

### 复现环境 Environment

window-11 ，PaddleSeg：2.9，python：3.9，其他都按照requiresments.txt下载的

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by marshall-dteach** [comment]
我知道你的问题在哪，我可以帮你，但是是有偿的，可以吗

**Comment by PerLightFlow** [comment]
应该是因为你的训练集图片尺寸和标签图尺寸不一致导致的

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
