### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle.profiler'

### ISSUE THREAD

**Issue by FengfengLiang1112222** [PaddlePaddle/PaddleSeg#3732]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Traceback (most recent call last):
  File "PaddleSeg/train.py", line 22, in <module>
    from paddleseg.cvlibs import Config, SegBuilder
  File "/home/aistudio/PaddleSeg/paddleseg/__init__.py", line 15, in <module>
    from . import models, datasets, transforms, optimizers
  File "/home/aistudio/PaddleSeg/paddleseg/models/__init__.py", line 74, in <module>
    from .maskformer import MaskFormer
  File "/home/aistudio/PaddleSeg/paddleseg/models/maskformer.py", line 27, in <module>
    from paddleseg.core.train import check_logits_losses
  File "/home/aistudio/PaddleSeg/paddleseg/core/__init__.py", line 15, in <module>
    from .train import train
  File "/home/aistudio/PaddleSeg/paddleseg/core/train.py", line 24, in <module>
    from paddleseg.utils import (TimeAverager, calculate_eta, resume, logger,
  File "/home/aistudio/PaddleSeg/paddleseg/utils/train_profiler.py", line 16, in <module>
    import paddle.profiler as profiler
ModuleNotFoundError: No module named 'paddle.profiler'

**Comment by michaelowenliu** [comment]
paddle安装成功了吗？

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
