### ISSUE TITLE
执行 python src/download_inference_models.py 命令时，报以下错误

### ISSUE THREAD

**Issue by 1a1aca** [PaddlePaddle/PaddleSeg#3733]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

Installing collected packages: paddleseg
Successfully installed paddleseg-2.8.0
PS E:\Python Projects\PaddleSegTest5\PaddleSeg\contrib\PP-HumanSeg> python src/download_inference_models.py
Traceback (most recent call last):
  File "E:\Python Projects\PaddleSegTest5\PaddleSeg\contrib\PP-HumanSeg\src\download_inference_models.py", line 22, in <module>
    from paddleseg.utils.download import download_file_and_uncompress
  File "D:\Users\Administrator\anaconda3\envs\paddle22\lib\site-packages\paddleseg\__init__.py", line 15, in <module>
    from . import models, datasets, transforms, optimizers
  File "D:\Users\Administrator\anaconda3\envs\paddle22\lib\site-packages\paddleseg\models\__init__.py", line 15, in <module>
    from .backbones import *
  File "D:\Users\Administrator\anaconda3\envs\paddle22\lib\site-packages\paddleseg\models\backbones\__init__.py", line 15, in <module>    
    from .hrnet import *
  File "D:\Users\Administrator\anaconda3\envs\paddle22\lib\site-packages\paddleseg\models\backbones\hrnet.py", line 18, in <module>       
    import paddle.nn as nn
  File "D:\Users\Administrator\anaconda3\envs\paddle22\lib\site-packages\paddle\nn\__init__.py", line 15, in <module>
    from . import functional, initializer, quant, utils  # noqa: F401
  File "D:\Users\Administrator\anaconda3\envs\paddle22\lib\site-packages\paddle\nn\functional\__init__.py", line 18, in <module>
    from .activation import (
  File "D:\Users\Administrator\anaconda3\envs\paddle22\lib\site-packages\paddle\nn\functional\activation.py", line 16, in <module>        
    from paddle import _C_ops, _legacy_C_ops, in_dynamic_mode
ImportError: cannot import name 'in_dynamic_mode' from 'paddle' (D:\Users\Administrator\anaconda3\envs\paddle22\lib\site-packages\paddle\__init__.py)
PS E:\Python Projects\PaddleSegTest5\PaddleSeg\contrib\PP-HumanSeg>

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
