### ISSUE TITLE
ImportError: cannot import name 'in_dynamic_mode' from 'paddle' (unknown location)

### ISSUE THREAD

**Issue by 1a1aca** [PaddlePaddle/PaddleSeg#3735]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

执行导出预测模型时也出现此错误

### 复现环境 Environment

PS E:\Python Projects\PaddleSegTest2_8\PaddleSeg\contrib\PP-HumanSeg> cd PP-LiteSeg
PS E:\Python Projects\PaddleSegTest2_8\PaddleSeg\contrib\PP-HumanSeg\PP-LiteSeg> python ../../../tools/export.py --config configs/pp_liteseg/pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k.yml --model_path PP-LiteSeg/model.pdparams --save_dir inference_model
Traceback (most recent call last):
  File "E:\Python Projects\PaddleSegTest2_8\PaddleSeg\tools\export.py", line 21, in <module>
    from paddleseg.cvlibs import Config, SegBuilder
  File "D:\Users\Administrator\anaconda3\envs\paddle22\lib\site-packages\paddleseg\__init__.py", line 15, in <module>   
    from . import models, datasets, transforms, optimizers
  File "D:\Users\Administrator\anaconda3\envs\paddle22\lib\site-packages\paddleseg\models\__init__.py", line 15, in <module>
    from .backbones import *
  File "D:\Users\Administrator\anaconda3\envs\paddle22\lib\site-packages\paddleseg\models\backbones\__init__.py", line 15, in <module>
    from .hrnet import *
  File "D:\Users\Administrator\anaconda3\envs\paddle22\lib\site-packages\paddleseg\models\backbones\hrnet.py", line 18, in <module>
    import paddle.nn as nn
  File "D:\Users\Administrator\anaconda3\envs\paddle22\lib\site-packages\paddle\nn\__init__.py", line 15, in <module>
    from . import functional, initializer, quant, utils  # noqa: F401
  File "D:\Users\Administrator\anaconda3\envs\paddle22\lib\site-packages\paddle\nn\functional\__init__.py", line 18, in <module>
    from .activation import (
  File "D:\Users\Administrator\anaconda3\envs\paddle22\lib\site-packages\paddle\nn\functional\activation.py", line 16, in <module>
    from paddle import _C_ops, _legacy_C_ops, in_dynamic_mode
ImportError: cannot import name 'in_dynamic_mode' from 'paddle' (unknown location)
PS E:\Python Projects\PaddleSegTest2_8\PaddleSeg\contrib\PP-HumanSeg\PP-LiteSeg>

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by TingquanGao** [comment]
Thanks for this issue. As it has been inactive for a long time, we would close it. If you has any questions, please feel free to reopen or new issue, and we will follow up and resolve it.
