### ISSUE TITLE
我在使用自定义数据集进行quick训练时报错。

### ISSUE THREAD

**Issue by sunmer1rain** [PaddlePaddle/PaddleSeg#3748]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleSeg/issues)(包括open与closed)，没有发现相似的bug。I have searched the [open and closed issues](https://github.com/PaddlePaddle/PaddleSeg/issues) and found no similar bug report.

### Bug描述 Describe the Bug

我的数据集的标签是1-7，用于做图像语义分割的，当我改了pp_liteseg_optic_disc_512x512_1k.yml中的num_classes为7时，仍然报错

/home/hjy/anaconda3/envs/ppliteseg/lib/python3.8/site-packages/paddle/nn/layer/norm.py:824: UserWarning: When training, we now always track global mean and variance.
  warnings.warn(
Traceback (most recent call last):
  File "tools/train.py", line 195, in <module>
    main(args)
  File "tools/train.py", line 170, in main
    train(
  File "/home/hjy/anaconda3/envs/ppliteseg/lib/python3.8/site-packages/paddleseg/core/train.py", line 237, in train
    loss_list = loss_computation(
  File "/home/hjy/anaconda3/envs/ppliteseg/lib/python3.8/site-packages/paddleseg/core/train.py", line 57, in loss_computation
    loss_list.append(coef_i * loss_i(logits, labels))
  File "/home/hjy/anaconda3/envs/ppliteseg/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 1429, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/hjy/anaconda3/envs/ppliteseg/lib/python3.8/site-packages/paddleseg/models/losses/cross_entropy_loss.py", line 84, in forward
    loss = F.cross_entropy(
  File "/home/hjy/anaconda3/envs/ppliteseg/lib/python3.8/site-packages/paddle/nn/functional/loss.py", line 2818, in cross_entropy
    _, out = _C_ops.cross_entropy_with_softmax(
IndexError: (OutOfRange) label value should less than the shape of axis dimension when label value(7) not equal to ignore_index(255), But received label value as 7 and shape of axis dimension is 7
  [Hint: Expected lbl < axis_dim_, but received lbl:7 >= axis_dim_:7.] (at /paddle/paddle/phi/kernels/funcs/cross_entropy.cc:74)
我不知道应该怎么解决

### 复现环境 Environment

-OS: linux
-python 3.8

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [X] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by sunmer1rain** [comment]
我想要使用示例的单卡训练进行训练：
export CUDA_VISIBLE_DEVICES=0 # Linux上设置1张可用的卡
# set CUDA_VISIBLE_DEVICES=0  # Windows上设置1张可用的卡

python tools/train.py \
       --config configs/quick_start/pp_liteseg_optic_disc_512x512_1k.yml \
       --do_eval \
       --use_vdl \
       --save_interval 500 \
       --save_dir output

**Comment by yzyMichael** [comment]
@sunmer1rain 我也遇到同样的问题，咨询下这个问题你们是如何解决的
