### ISSUE TITLE
U-Net模型预测问题

### ISSUE THREAD

**Issue by gxqnba** [PaddlePaddle/PaddleSeg#375]
请问U-Net模型训练好了以后，如何进行预测，我用以下命令进行预测：
python pdseg/vis.py --use_gpu --cfg ./configs/unet_optic.yaml
好像要提供groundTruth图片才能预测，否则会报错

**Comment by nepeplwu** [comment]
@gxqnba 报错截图麻烦提供下

**Comment by gxqnba** [comment]
> @gxqnba 报错截图麻烦提供下

Traceback (most recent call last):
  File "pdseg/vis.py", line 209, in <module>
    visualize(cfg, **args.__dict__)
  File "pdseg/vis.py", line 131, in visualize
    for imgs, grts, img_names, valid_shapes, org_shapes in test_reader:
  File "/home/aistudio/work/PaddleSeg/pdseg/reader.py", line 136, in batch_reader
    for img, grt, img_name, valid_shape, org_shape in reader():
  File "/home/aistudio/work/PaddleSeg/pdseg/reader.py", line 81, in generator
    yield self.process_image(line, self.data_dir, self.mode)
  File "/home/aistudio/work/PaddleSeg/pdseg/reader.py", line 251, in process_image
    line, data_dir, mode=mode)
  File "/home/aistudio/work/PaddleSeg/pdseg/reader.py", line 210, in load_image
    "source img and label img must has the same size")
Exception: source img and label img must has the same size

**Comment by nepeplwu** [comment]
@gxqnba 从报错日志来看，应该是你传入的文件中就应该包含了GroundTruth的路径，但是读取后的groundTrush的shape和预测图片的shape对不上导致出现问题
