### ISSUE TITLE
padim评估模型报错，使用mvtec数据集，默认config  padim_resnet18_mvtec.yml

### ISSUE THREAD

**Issue by alanxinn** [PaddlePaddle/PaddleSeg#3806]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

paddle version  
paddlepaddle-gpu==2.6.1

paddleseg version
paddleseg2.9.0

python version
3.8.19

datasets
Mvtec

train commands
python contrib\QualityInspector\tools\uad\padim\train.py --config contrib\QualityInspector\configs\uad\padim\padim_resnet18_mvtec_copy.yml --category bottle

------------- Config Arguments ---------------
backbone: resnet18
batch_size: 1
category: bottle
config: contrib\QualityInspector\configs\uad\padim\padim_resnet18_mvtec.yml
crop_size:
- 224
- 224
data_path: data/mvtec_anomaly_detection
device: gpu
do_eval: true
img_path: data/mvtec_anomaly_detection/bottle/test/broken_large/000.png
model_path: output/resnet18/bottle/bottle.pdparams
num_workers: 0
print_freq: 20
resize:
- 256
- 256
save_model: true
save_path: output/
save_pic: true
seed: 3
threshold: 0.5

---------------------------------------------
W0925 09:07:30.107342  2056 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 12.4, Runtime API Version: 11.8
W0925 09:07:30.111300  2056 gpu_resources.cc:164] device: 0, cuDNN Version: 8.6.
Training model 1/1 for bottle
2024-09-25 09:07:31     Epoch 0[1/209]: loss:0.00000, lr:0.00000, batch time:0.2453, data time:0.1287
2024-09-25 09:07:31     Epoch 0[21/209]: loss:0.00000, lr:0.00000, batch time:0.0069, data time:0.0330
2024-09-25 09:07:32     Epoch 0[41/209]: loss:0.00000, lr:0.00000, batch time:0.0070, data time:0.0230
2024-09-25 09:07:33     Epoch 0[61/209]: loss:0.00000, lr:0.00000, batch time:0.0090, data time:0.0220
2024-09-25 09:07:33     Epoch 0[81/209]: loss:0.00000, lr:0.00000, batch time:0.0080, data time:0.0119
2024-09-25 09:07:34     Epoch 0[101/209]: loss:0.00000, lr:0.00000, batch time:0.0080, data time:0.0279
2024-09-25 09:07:34     Epoch 0[121/209]: loss:0.00000, lr:0.00000, batch time:0.0080, data time:0.0236
2024-09-25 09:07:35     Epoch 0[141/209]: loss:0.00000, lr:0.00000, batch time:0.0073, data time:0.0187
2024-09-25 09:07:36     Epoch 0[161/209]: loss:0.00000, lr:0.00000, batch time:0.0058, data time:0.0190
2024-09-25 09:07:36     Epoch 0[181/209]: loss:0.00000, lr:0.00000, batch time:0.0070, data time:0.0289
2024-09-25 09:07:37     Epoch 0[201/209]: loss:0.00000, lr:0.00000, batch time:0.0079, data time:0.0180
2024-09-25 09:13:16     Starting eval model...
| feature extraction | test | bottle |: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 83/83 [00:03<00:00, 25.35it/s] 
2024-09-25 09:13:19     Eval model...
Traceback (most recent call last):
    main()
  File "contrib\QualityInspector\tools\uad\padim\train.py", line 137, in main
    class_name, *val(args, model, test_dataloader, class_name, idx)
  File "E:\desktop\deepLearing\PaddleSeg-2.9.0\contrib\QualityInspector\tools\uad\padim\val.py", line 189, in val
    dist = [
  File "E:\desktop\deepLearing\PaddleSeg-2.9.0\contrib\QualityInspector\tools\uad\padim\val.py", line 190, in <listcomp>
    mahalanobis_pd(sample[:, i], mean, conv_inv).numpy()[0]
  File "E:\desktop\deepLearing\PaddleSeg-2.9.0\contrib\QualityInspector\tools\uad\padim\val.py", line 176, in mahalanobis_pd
    return paddle.sqrt(
  File "E:\anaconda3\envs\paddleseg290\lib\site-packages\paddle\base\dygraph\tensor_patch_methods.py", line 893, in __getitem__
    return self._getitem_dygraph(item)
IndexError: (OutOfRange) The starting index 0 of slice is out of bounds in tensor 0-th axis, it shound be in the range of [0, 0). (at ..\paddle/fluid/pybind/slice_utils.h:216)

在进行eval model时报上述错误

**Comment by TingquanGao** [comment]
该模型已较为久远，建议使用历史版本：paddleseg release/2.8分支 + paddlepaddle 2.4.2 。

另外，推荐使用[PaddleX](https://github.com/paddlepaddle/paddlex)，PaddleX 3.0 是基于飞桨框架构建的低代码开发工具。

**Comment by alanxinn** [comment]
请问STFPM模型可以用2.9的吗

Tingquan Gao ***@***.***>于2024年10月26日 周六14:40写道：

**Comment by TingquanGao** [comment]
可以试试，主要是paddle版本建议试下2.4.2

**Comment by alanxinn** [comment]
ok，thanks

Tingquan Gao ***@***.***> 于2024年10月27日周日 20:04写道：

**Comment by TingquanGao** [comment]
那该issue先关闭了，如仍有问题可reopen或new issue。
