### ISSUE TITLE
Error: cannot import name 'setup_logger' from 'paddleseg.utils.logger' 

### ISSUE THREAD

**Issue by AnTranHoai38** [PaddlePaddle/PaddleSeg#3875]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

I can't train my model on custom dataset because Error: cannot import name 'setup_logger' from 'paddleseg.utils.logger' on google colab.
PaddlePaddle 2.6.2
paddleseg 2.8.0
python 3.10.12
I run this code: 

python train.py \
        --config configs/quick_start/pp_liteseg_optic_disc_512x512_1k.yml \
        --do_eval \
        --use_vdl \
        --save_interval 500 \
        --save_dir output

Traceback (most recent call last):
  File "/content/PaddleSeg/tools/train.py", line 27, in <module>
    from paddleseg.utils.logger import setup_logger
ImportError: cannot import name 'setup_logger' from 'paddleseg.utils.logger' (/usr/local/lib/python3.10/dist-packages/paddleseg/utils/logger.py)

**Comment by Sunting78** [comment]
您好 辛苦切换到2.10分枝，pip install -e .安装后运行

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by lgg1234567890** [comment]
I've had the same problem. Is there a solution?

```
  File "D:\my-algo\PaddleSeg\tools\train.py", line 26, in <module>
    from paddleseg.utils.logger import setup_logger
ImportError: cannot import name 'setup_logger' from 'paddleseg.utils.logger' (D:\tools\anconda3\lib\site-packages\paddleseg\utils\logger.py)
```

**Comment by AnTranHoai38** [comment]
> I've had the same problem. Is there a solution?
> 
> ```
>   File "D:\my-algo\PaddleSeg\tools\train.py", line 26, in <module>
>     from paddleseg.utils.logger import setup_logger
> ImportError: cannot import name 'setup_logger' from 'paddleseg.utils.logger' (D:\tools\anconda3\lib\site-packages\paddleseg\utils\logger.py)
> ```

hmm I copy all code in file: /content/PaddleSeg/paddleseg/cvlibs/config.py to file train.py. You should try this.

**Comment by Jennie-Zhuge** [comment]
我也遇到了同样的问题，尝试多种解决办法无效。最终让pip install paddleseg的版本与git下载的paddleseg项目版本一致，解决了该问题。

**Comment by nhfujfgid** [comment]
获取 PaddleX 源码；
paddlex --install PaddleSeg 解决问题
