### ISSUE TITLE
OCRNet 配置参数有误

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/PaddleSeg#390]
在使用 OCRNet配置文件时，有参数
```
OCR_MID_CHANNELS: 512
OCR_KEY_CHANNELS: 256
```
但在执行 check.py 校验数据集时,报错：
`KeyError: 'Non-existent config key: MODEL.HRNET.OCR_MID_CHANNELS'`
完整报错信息：
```
Traceback (most recent call last):
  File "/home/aistudio/PaddleSeg/pdseg/utils/collect.py", line 88, in update_from_segconfig
    self.__setattr__(key, value, create_if_not_exist=False)
  File "/home/aistudio/PaddleSeg/pdseg/utils/collect.py", line 45, in __setattr__
    t.__getattr__(keylist[-1], create_if_not_exist)
  File "/home/aistudio/PaddleSeg/pdseg/utils/collect.py", line 54, in __getattr__
    raise KeyError
KeyError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./PaddleSeg/pdseg/check.py", line 657, in <module>
    main(args)
  File "./PaddleSeg/pdseg/check.py", line 626, in main
    cfg.update_from_file(args.cfg_file)
  File "/home/aistudio/PaddleSeg/pdseg/utils/collect.py", line 150, in update_from_file
    self.update_from_segconfig(dic)
  File "/home/aistudio/PaddleSeg/pdseg/utils/collect.py", line 90, in update_from_segconfig
    raise KeyError('Non-existent config key: {}'.format(key))
KeyError: 'Non-existent config key: MODEL.HRNET.OCR_MID_CHANNELS'
```

**Comment by nepeplwu** [comment]
@iceriver97 key应该是`MODEL.OCR.OCR_MID_CHANNELS`和`MODEL.OCR.OCR_KEY_CHANNELS`

**Comment by iceriver97** [comment]
@nepeplwu 谢谢！我还想问一下，出现这种情况影响训练吗？
```
[SKIP] Shape of pretrained weight aux_head_conv2_weights doesn't match.(Pretrained: (19, 270, 1, 1), Actual: (7, 270, 1, 1))
[SKIP] Shape of pretrained weight aux_head_conv2_bias doesn't match.(Pretrained: (19,), Actual: (7,))
[SKIP] Shape of pretrained weight cls_head_conv_weights doesn't match.(Pretrained: (19, 512, 1, 1), Actual: (7, 512, 1, 1))
[SKIP] Shape of pretrained weight cls_head_conv_bias doesn't match.(Pretrained: (19,), Actual: (7,))
There are 1570/1574 varaibles in ./PaddleSeg/pretrained_model/ocrnet_w18_bn_cityscapes/ are loaded.
```
OCRNet预训练模型的类别数是19吧？我自己的数据集分类是7类

**Comment by iceriver97** [comment]
应该不影响
