### ISSUE TITLE
LaneNet：报错文件列表格式不正确

### ISSUE THREAD

**Issue by iceriver97** [PaddlePaddle/PaddleSeg#407]
在是用LaneNet时报错：
Traceback (most recent call last):
  File "D:\anaconda3\envs\paddle\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\anaconda3\envs\paddle\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\reader.py", line 1145, in __thread_main__
    six.reraise(*sys.exc_info())
  File "D:\anaconda3\envs\paddle\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\reader.py", line 1125, in __thread_main__
    for tensors in self._tensor_reader():
  File "D:\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\data_feeder.py", line 196, in __call__
    for each_sample in self.generator():
  File "./train.py", line 170, in data_generator
    batch_data = []
  File "D:\competition\LaneNet\reader.py", line 68, in generator
    yield self.process_image(line, self.data_dir, self.mode)
  File "D:\competition\LaneNet\reader.py", line 249, in process_image
    line, data_dir, mode=mode)
  File "D:\competition\LaneNet\reader.py", line 175, in load_image
    cfg.DATASET.SEPARATOR))
Exception: File list format incorrect! It should be image_name|label_name\n

但我检查了文件列表，是没有错误的啊，下面是文件列表
[test.txt](https://github.com/PaddlePaddle/PaddleSeg/files/5273193/test.txt)
[train.txt](https://github.com/PaddlePaddle/PaddleSeg/files/5273195/train.txt)
[val.txt](https://github.com/PaddlePaddle/PaddleSeg/files/5273194/val.txt)

**Comment by iceriver97** [comment]
LaneNet的相关操作暂时还不能使用Seg的通用脚本来做

**Comment by luosiwu** [comment]
你的文件名包含空格
