### ISSUE TITLE
ocrnet中使用lovasz报错

### ISSUE THREAD

**Issue by deep-practice** [PaddlePaddle/PaddleSeg#453]
Traceback (most recent call last):
  File "pdseg/train.py", line 466, in <module>
    main(args)
  File "pdseg/train.py", line 453, in main
    train(cfg)
  File "pdseg/train.py", line 237, in train
    train_prog, startup_prog, phase=ModelPhase.TRAIN)
  File "/home/work/deep_learning/local/PaddleSeg/pdseg/models/model_builder.py", line 196, in build_model
    multi_lovasz_softmax_loss(logits, label, mask))
  File "/home/work/deep_learning/local/PaddleSeg/pdseg/lovasz_losses.py", line 222, in multi_lovasz_softmax_loss
    loss = lovasz_softmax(probas, logit_label, ignore=logit_mask)
  File "/home/work/deep_learning/local/PaddleSeg/pdseg/lovasz_losses.py", line 133, in lovasz_softmax
    loss = lovasz_softmax_flat(vprobas, vlabels, classes=classes)
  File "/home/work/deep_learning/local/PaddleSeg/pdseg/lovasz_losses.py", line 166, in lovasz_softmax_flat
    fg_sorted = fluid.layers.gather(fg, perm)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layers/nn.py", line 8282, in gather
    attrs={'overwrite': overwrite})
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 2880, in append_op
    attrs=kwargs.get("attrs", None))
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/framework.py", line 2086, in __init__
    self.desc.infer_shape(self.block.desc)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const
1   paddle::operators::GatherOp::InferShape(paddle::framework::InferShapeContext*) const
2   paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int)
3   std::string paddle::platform::GetTraceBackString<char const*>(char const*&&, char const*, int)
4   paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
Error: An error occurred here. There is no accurate error hint for this error yet. We are continuously in the process of increasing hint for this kind of error check. It would be helpful if you could inform us of how this conversion went by opening a github issue. And we will resolve it with high priority.
  - New issue link: https://github.com/PaddlePaddle/Paddle/issues/new
  - Recommended issue content: all error stack information (at /paddle/paddle/fluid/operators/gather_op.cc:41)
  [operator < gather > error]

**Comment by LutaoChu** [comment]
你好，请问你的PaddleSeg和Paddle版本是多少呢？

**Comment by deep-practice** [comment]
paddle:2.0.0-beta0
paddleseg:0.6.0

**Comment by LutaoChu** [comment]
PaddleSeg 0.6.0推荐的Paddle版本为1.8
未来的PaddleSeg 1.0会完全适配Paddle 2.0

**Comment by deep-practice** [comment]
好的，那我降个版本
