### ISSUE TITLE
FP16无法使用，请问是需要安装哪些前置依赖吗？

### ISSUE THREAD

**Issue by pengqianli** [PaddlePaddle/PaddleSeg#465]

**Comment by nepeplwu** [comment]
@pengqianli 请问遇到了什么问题

**Comment by pengqianli** [comment]
感谢您的回复，错误是ValueError: var lod_tensor_blocking_queue_0 not in this block

**Comment by nepeplwu** [comment]
麻烦贴下完整的报错堆栈

**Comment by pengqianli** [comment]
Traceback (most recent call last):
  File "pdseg/mytrain.py", line 474, in <module>
    main(args)
  File "pdseg/mytrain.py", line 461, in main
    train(cfg)
  File "pdseg/mytrain.py", line 239, in train
    train_prog, startup_prog, phase=ModelPhase.TRAIN)
  File "/home/lab-li.pengqian/workspace/Competitions/CCFyaogan/PaddleSeg/pdseg/models/model_builder.py", line 257, in build_model
    decayed_lr = optimizer.optimise(avg_loss)
  File "/home/lab-li.pengqian/workspace/Competitions/CCFyaogan/PaddleSeg/pdseg/solver.py", line 159, in optimise
    return self.sgd_optimizer(lr_policy, loss)
  File "/home/lab-li.pengqian/workspace/Competitions/CCFyaogan/PaddleSeg/pdseg/solver.py", line 137, in sgd_optimizer
    optimizer.minimize(loss)
  File "/home/lab-li.pengqian/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/contrib/mixed_precision/decorator.py", line 211, in minimize
    no_grad_set=no_grad_set)
  File "/home/lab-li.pengqian/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/contrib/mixed_precision/decorator.py", line 134, in backward
    rewrite_program(self._train_program, self._amp_lists)
  File "/home/lab-li.pengqian/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/contrib/mixed_precision/fp16_utils.py", line 266, in rewrite_program
    core.VarDesc.VarType.FP32)
  File "/home/lab-li.pengqian/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/contrib/mixed_precision/fp16_utils.py", line 76, in _insert_cast_op
    in_var = block.var(in_var_name)
  File "/home/lab-li.pengqian/anaconda3/envs/paddle/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2377, in var
    raise ValueError("var %s not in this block" % name)
ValueError: var lod_tensor_blocking_queue_0 not in this block

**Comment by pengqianli** [comment]
另外，其实我还有一个问题，我在训练的时候，发现，paddleseg的eval速度甚至比train的时候要慢一些。我查看了eval源码发现，测试逻辑是载入模型再逐batch进行推理，其实我并不明白为什么这么做会比训练要慢。我能想到的两个解释是1、推理时计算了梯度。2、测试的data loader慢。（个人刚刚测试同样迭代1250次20000张图，训练耗时6min，而推理同样多的图片竟然需要消耗8min多）
在使用pytorch时，同样train，val图片数量同样时，训练：测试时间约等于3min：20s。不知道paddle是否也能优化到这样呢？

**Comment by nepeplwu** [comment]
@pengqianli 
1. fp16运行不了的问题，我这边没有出现问题，麻烦提供下运行的配置和命令。
2. eval时可以观察下gpu的利用率，如果利用率不高，可以使用--use_mpio来提升数据读取的速度

**Comment by pengqianli** [comment]
1、硬件配置的话是2080ti，命令是CUDA_VISIBLE_DEVICES=gpu_id python pdseg/train.py --use_gpu --do_eval --cfg ./configs/myconfigs/deeplabv3p_resnet50_vd.yaml
2、利用率不高，我后续会尝试用--use_mpio

**Comment by nepeplwu** [comment]
`configs/myconfigs/deeplabv3p_resnet50_vd.yaml`
这个配置是否方便提供下？另外你运行的paddle版本是？

**Comment by pengqianli** [comment]
fp16只能多卡才能跑吗？我在AIstudio上也不能运行

**Comment by nepeplwu** [comment]
@pengqianli ，不需要多卡，你的aistudio教程是否方便公开下，我们这边试试看

**Comment by ChengYi1996** [comment]
Traceback (most recent call last):
  File "pdseg/train.py", line 466, in <module>
    main(args)
  File "pdseg/train.py", line 453, in main
    train(cfg)
  File "pdseg/train.py", line 237, in train
    train_prog, startup_prog, phase=ModelPhase.TRAIN)
  File "/home/aistudio/work/PaddleSeg-0.6.0/pdseg/models/model_builder.py", line 259, in build_model
    decayed_lr = optimizer.optimise(avg_loss)
  File "/home/aistudio/work/PaddleSeg-0.6.0/pdseg/solver.py", line 159, in optimise
    return self.sgd_optimizer(lr_policy, loss)
  File "/home/aistudio/work/PaddleSeg-0.6.0/pdseg/solver.py", line 137, in sgd_optimizer
    optimizer.minimize(loss)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/mixed_precision/decorator.py", line 211, in minimize
    no_grad_set=no_grad_set)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/mixed_precision/decorator.py", line 134, in backward
    rewrite_program(self._train_program, self._amp_lists)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/mixed_precision/fp16_utils.py", line 266, in rewrite_program
    core.VarDesc.VarType.FP32)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/mixed_precision/fp16_utils.py", line 76, in _insert_cast_op
    in_var = block.var(in_var_name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2377, in var
    raise ValueError("var %s not in this block" % name)
ValueError: var lod_tensor_blocking_queue_0 not in this block

**Comment by ChengYi1996** [comment]
> @pengqianli 
Traceback (most recent call last):
  File "pdseg/train.py", line 466, in <module>
    main(args)
  File "pdseg/train.py", line 453, in main
    train(cfg)
  File "pdseg/train.py", line 237, in train
    train_prog, startup_prog, phase=ModelPhase.TRAIN)
  File "/home/aistudio/work/PaddleSeg-0.6.0/pdseg/models/model_builder.py", line 259, in build_model
    decayed_lr = optimizer.optimise(avg_loss)
  File "/home/aistudio/work/PaddleSeg-0.6.0/pdseg/solver.py", line 159, in optimise
    return self.sgd_optimizer(lr_policy, loss)
  File "/home/aistudio/work/PaddleSeg-0.6.0/pdseg/solver.py", line 137, in sgd_optimizer
    optimizer.minimize(loss)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/mixed_precision/decorator.py", line 211, in minimize
    no_grad_set=no_grad_set)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/mixed_precision/decorator.py", line 134, in backward
    rewrite_program(self._train_program, self._amp_lists)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/mixed_precision/fp16_utils.py", line 266, in rewrite_program
    core.VarDesc.VarType.FP32)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/mixed_precision/fp16_utils.py", line 76, in _insert_cast_op
    in_var = block.var(in_var_name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2377, in var
    raise ValueError("var %s not in this block" % name)
ValueError: var lod_tensor_blocking_queue_0 not in this block

**Comment by ChengYi1996** [comment]
@nepeplwu ,Traceback (most recent call last):
  File "pdseg/train.py", line 466, in <module>
    main(args)
  File "pdseg/train.py", line 453, in main
    train(cfg)
  File "pdseg/train.py", line 237, in train
    train_prog, startup_prog, phase=ModelPhase.TRAIN)
  File "/home/aistudio/work/PaddleSeg-0.6.0/pdseg/models/model_builder.py", line 259, in build_model
    decayed_lr = optimizer.optimise(avg_loss)
  File "/home/aistudio/work/PaddleSeg-0.6.0/pdseg/solver.py", line 159, in optimise
    return self.sgd_optimizer(lr_policy, loss)
  File "/home/aistudio/work/PaddleSeg-0.6.0/pdseg/solver.py", line 137, in sgd_optimizer
    optimizer.minimize(loss)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/mixed_precision/decorator.py", line 211, in minimize
    no_grad_set=no_grad_set)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/mixed_precision/decorator.py", line 134, in backward
    rewrite_program(self._train_program, self._amp_lists)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/mixed_precision/fp16_utils.py", line 266, in rewrite_program
    core.VarDesc.VarType.FP32)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/contrib/mixed_precision/fp16_utils.py", line 76, in _insert_cast_op
    in_var = block.var(in_var_name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2377, in var
    raise ValueError("var %s not in this block" % name)
ValueError: var lod_tensor_blocking_queue_0 not in this block

**Comment by ChengYi1996** [comment]
@nepeplwu 
同样的问题， aistudio项目地址: https://aistudio.baidu.com/aistudio/projectdetail/1114116
运行命令
cd work/PaddleSeg-0.6.0 \
python pdseg/train.py --cfg configs/ocrnet_w18_bn.yaml --use_gpu --do_eval MODEL.FP16 True

**Comment by nepeplwu** [comment]
@ChengYi1996 你的项目没有公开，我这边无法打开

**Comment by ChengYi1996** [comment]
@nepeplwu 项目已经公开。

**Comment by Andy1621** [comment]
和@ChengYi1996 同样的问题，跑的遥感影像分割baseline（https://aistudio.baidu.com/aistudio/projectdetail/1090790 ），直接设置fp16为True报相同错误

**Comment by nepeplwu** [comment]
@Andy1621 @ChengYi1996 @pengqianli 感谢各位的反馈，这个问题经过排查，发现是paddle混合精度训练模块的一个bug，该问题正在修复中，后续会随着paddle的新版本发布。
