### ISSUE TITLE
PaddleSeg训练报错

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/PaddleSeg#496]
在aistudio 1.8.4环境下，训练中报错：

notebook里执行命令：
!python pdseg/train.py --use_gpu --cfg ./unet.yaml --do_eval --use_vdl --vdl_log_dir vdllog --log_steps 50 TRAIN.RESUME_MODEL_DIR  ./saved_model/unet/8  

报错信息：
#10000 visualize image path: visual/A155980.png
VisualDL visualization epoch 10
Traceback (most recent call last):
  File "pdseg/train.py", line 466, in <module>
    main(args)
  File "pdseg/train.py", line 453, in main
    train(cfg)
  File "pdseg/train.py", line 431, in train
    log_writer=log_writer)
  File "/home/aistudio/PaddleSeg/pdseg/vis.py", line 131, in visualize
    for imgs, grts, img_names, valid_shapes, org_shapes in test_reader:
  File "/home/aistudio/PaddleSeg/pdseg/reader.py", line 136, in batch_reader
    for img, grt, img_name, valid_shape, org_shape in reader():
  File "/home/aistudio/PaddleSeg/pdseg/reader.py", line 81, in generator
    yield self.process_image(line, self.data_dir, self.mode)
  File "/home/aistudio/PaddleSeg/pdseg/reader.py", line 251, in process_image
    line, data_dir, mode=mode)
  File "/home/aistudio/PaddleSeg/pdseg/reader.py", line 199, in load_image
    src_dir, img_path, grt_path))
UnboundLocalError: local variable 'grt_path' referenced before assignment

**Comment by LutaoChu** [comment]
请在"/home/aistudio/PaddleSeg/pdseg/reader.py" line 169 将load_image函数替换为下面的代码，重新运行试试
```python
     def load_image(self, line, src_dir, mode=ModelPhase.TRAIN):
        # original image cv2.imread flag setting
        cv2_imread_flag = cv2.IMREAD_COLOR
        if cfg.DATASET.IMAGE_TYPE == "rgba":
            # If use RBGA 4 channel ImageType, use IMREAD_UNCHANGED flags to
            # reserver alpha channel
            cv2_imread_flag = cv2.IMREAD_UNCHANGED

        parts = line.strip().split(cfg.DATASET.SEPARATOR)
        if len(parts) != 2:
            if mode == ModelPhase.TRAIN or mode == ModelPhase.EVAL:
                raise Exception("File list format incorrect! It should be"
                                " image_name{}label_name\\n".format(
                                    cfg.DATASET.SEPARATOR))
            img_name, grt_name = parts[0], None
        else:
            img_name, grt_name = parts[0], parts[1]

        img_path = os.path.join(src_dir, img_name)
        img = cv2_imread(img_path, cv2_imread_flag)

        if grt_name is not None:
            grt_path = os.path.join(src_dir, grt_name)
            grt = pil_imread(grt_path)
        else:
            grt = None

        if img is None:
            raise Exception(
                "Empty image, source image path: {}".format(img_path))

        img_height = img.shape[0]
        img_width = img.shape[1]

        if grt is not None:
            grt_height = grt.shape[0]
            grt_width = grt.shape[1]

            if img_height != grt_height or img_width != grt_width:
                raise Exception(
                    "Source img and label img must has the same size.")
        else:
            if mode == ModelPhase.TRAIN or mode == ModelPhase.EVAL:
                raise Exception(
                    "No laber image path for image '{}' when training or evaluating. ".format(img_path))

        if len(img.shape) < 3:
            img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)

        img_channels = img.shape[2]
        if img_channels < 3:
            raise Exception("PaddleSeg only supports gray, rgb or rgba image")
        if img_channels != cfg.DATASET.DATA_DIM:
            raise Exception(
                "Input image channel({}) is not match cfg.DATASET.DATA_DIM({}), img_name={}"
                .format(img_channels, cfg.DATASET.DATADIM, img_name))
        if img_channels != len(cfg.MEAN):
            raise Exception(
                "Image name {}, image channels {} do not equal the length of cfg.MEAN {}.".format(
                    img_name, img_channels, len(cfg.MEAN)))
        if img_channels != len(cfg.STD):
            raise Exception(
                "Image name {}, image channels {} do not equal the length of cfg.STD {}.".format(
                    img_name, img_channels, len(cfg.STD)))

        return img, grt, img_name, grt_name
```

**Comment by skywalk163** [comment]
非常感谢，问题解决了！
