### ISSUE TITLE
Error: Blocking queue is killed because the data reader raises an exception

### ISSUE THREAD

**Issue by liu824** [PaddlePaddle/PaddleSeg#508]
eval时报错，使用deeplabv3p_xception65_optic训练预测无错误，使用deeplabv3p_xception65_cityscapes训练无错误，但eval出错。
配置如下：
EVAL_CROP_SIZE: (2049, 1025) # (width, height), for unpadding rangescaling and stepscaling
TRAIN_CROP_SIZE: (769, 769) # (width, height), for unpadding rangescaling and stepscaling
AUG:
    AUG_METHOD: "stepscaling" # choice unpadding rangescaling and stepscaling
    FIX_RESIZE_SIZE: (2048, 1024) # (width, height), for unpadding
    INF_RESIZE_VALUE: 500  # for rangescaling
    MAX_RESIZE_VALUE: 600  # for rangescaling
    MIN_RESIZE_VALUE: 400  # for rangescaling
    MAX_SCALE_FACTOR: 2.0  # for stepscaling
    MIN_SCALE_FACTOR: 0.5  # for stepscaling
    SCALE_STEP_SIZE: 0.25  # for stepscaling
    MIRROR: True
BATCH_SIZE: 3
DATASET:
    DATA_DIR: "../work/data/"
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 20
    TEST_FILE_LIST: "../work/data/test_list.txt"
    TRAIN_FILE_LIST: "../work/data/train_list.txt"
    VAL_FILE_LIST: "../work/data/val_list.txt"
    IGNORE_INDEX: 255
    SEPARATOR: " "
FREEZE:
    MODEL_FILENAME: "model"
    PARAMS_FILENAME: "params"
MODEL:
    DEFAULT_NORM_TYPE: "bn"
    MODEL_NAME: "deeplabv3p"
    DEEPLAB:
        ASPP_WITH_SEP_CONV: True
        DECODER_USE_SEP_CONV: True
TRAIN:
    RESUME_MODEL_DIR: "saved_model/deeplabv3p_xception65_bn_cityscapes/15"
    PRETRAINED_MODEL_DIR: u"pretrained_model/deeplabv3p_xception65_bn_coco"
    MODEL_SAVE_DIR: "saved_model/deeplabv3p_xception65_bn_cityscapes"
    SNAPSHOT_EPOCH: 5
    SYNC_BATCH_NORM: True
TEST:
    TEST_MODEL: "saved_model/deeplabv3p_xception65_bn_cityscapes/10"
SOLVER:
    LR: 0.01
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"
    NUM_EPOCHS: 100

报错如下：
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1145, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1125, in __thread_main__
    for tensors in self._tensor_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 196, in __call__
    for each_sample in self.generator():
  File "pdseg/eval.py", line 88, in data_generator
    for b in data_gen:
  File "/home/aistudio/PaddleSeg-0.6.0/pdseg/reader.py", line 81, in generator
    yield self.process_image(line, self.data_dir, self.mode)
  File "/home/aistudio/PaddleSeg-0.6.0/pdseg/reader.py", line 311, in process_image
    img, grt = aug.rand_crop(img, grt, mode=mode)
  File "/home/aistudio/PaddleSeg-0.6.0/pdseg/data_aug.py", line 398, in rand_crop
    .format(crop_width, crop_height, img_width, img_height))
Exception: Crop size(2049,1025) must large than img size(1920,1080) when in EvalPhase.

[EVAL]step=1 loss=0.08086 acc=0.9814 IoU=0.1274 step/sec=0.66 | ETA 00:08:22
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "pdseg/eval.py", line 178, in <module>
    main()
  File "pdseg/eval.py", line 174, in main
    evaluate(cfg, **args.__dict__)
  File "pdseg/eval.py", line 135, in evaluate
    test_prog, fetch_list=fetch_list, return_numpy=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1080, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 978, in __init__
    self._init_non_iterable()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 620, in from_generator
    iterable, return_list, drop_last)
  File "/home/aistudio/PaddleSeg-0.6.0/pdseg/models/model_builder.py", line 144, in build_model
    use_double_buffer=True)
  File "pdseg/eval.py", line 92, in evaluate
    test_prog, startup_prog, phase=ModelPhase.EVAL)
  File "pdseg/eval.py", line 174, in main
    evaluate(cfg, **args.__dict__)
  File "pdseg/eval.py", line 178, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]

**Comment by wuyefeilin** [comment]
NUM_CLASSES: 20， cityscape数据集类别数是19， 
另外，确保一下你的数据集路径是否正确

**Comment by liu824** [comment]
我用的是另外一个数据集，里边总共19个类别，加上背景20个

**Comment by wuyefeilin** [comment]
你运行pdseg/check.py 检查一下数据集是否正确

**Comment by liu824** [comment]
路径应该没错，我运行之后出问题的地方：
Doing max image size statistics:
2020-10-22 15:27:17,570-INFO: max width and max height of images are (1920,1080)
max width and max height of images are (1920,1080)
2020-10-22 15:27:17,570-INFO: 
NOT PASS EVAL_CROP_SIZE check

NOT PASS EVAL_CROP_SIZE check
2020-10-22 15:27:17,570-INFO: EVAL_CROP_SIZE[1]: 1025 should >= max height of images 1080!
EVAL_CROP_SIZE[1]: 1025 should >= max height of images 1080!

Detailed error information can be viewed in detail.log file.

是不是把EVAL_CROP_SIZE 的height 改为大于1080

**Comment by liu824** [comment]
好了，可以eval了

**Comment by liguoyu666** [comment]
> 好了，可以eval了

你好，请问怎么解决的，我也遇到了相同的问题，训练ok，eval就报这个错，数据没问题，用另外一个模型就能正常eval。
eval的crop_size我设定的和训练一样大，报错里也有提示crop_size要大于img_size，提示信息的img_sized的w,h都变大了一倍，本来应该一样大小的

**Comment by liu824** [comment]
根据报的错误改，我这是需要大于1080，我就把输入图片都改成大于这个数

**Comment by liguoyu666** [comment]
> 根据报的错误改，我这是需要大于1080，我就把输入图片都改成大于这个数

我图片和eval_crop_size一样大，设置大于图片size要是跑通了才离谱

**Comment by wuyefeilin** [comment]
> > 根据报的错误改，我这是需要大于1080，我就把输入图片都改成大于这个数
> 
> 我图片和eval_crop_size一样大，设置大于图片size要是跑通了才离谱
麻烦你贴一下具体的报错信息， 以及运行pdseg/check.py的运行结果
