### ISSUE TITLE
训练存模型时MemoryError

### ISSUE THREAD

**Issue by abanger** [PaddlePaddle/PaddleSeg#533]
# 运行hrnet，训练存模型时MemoryError

- 约运行epoch=20~60之间出错，未出错前正常
`
  main(args)
  File "pdseg/train.py", line 453, in main
    train(cfg)
  File "pdseg/train.py", line 401, in train
    ckpt_dir = save_checkpoint(train_prog, epoch)
  File "pdseg/train.py", line 129, in save_checkpoint
    fluid.save(program, os.path.join(ckpt_dir, 'model'))
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/io.py", line 1614, in save
    pickle.dump(opt_dict, f, protocol=2)
MemoryError
`
- 目录内容如下：
`
drwxr-xr-x 2 root root      4096 Oct 31 20:45 ./
drwxr-xr-x 5 root root      4096 Oct 31 20:45 ../
-rw-r--r-- 1 root root         0 Oct 31 20:45 model.pdopt
-rw-r--r-- 1 root root 706916072 Oct 31 20:45 model.pdparams
`

**Comment by nepeplwu** [comment]
@abanger 麻烦贴下完整的堆栈

**Comment by abanger** [comment]
今天发现什么模型都可以出错
Traceback (most recent call last):
  File "pdseg/train.py", line 466, in <module>
    main(args)
  File "pdseg/train.py", line 453, in main
    train(cfg)
  File "pdseg/train.py", line 401, in train
    ckpt_dir = save_checkpoint(train_prog, epoch)
  File "pdseg/train.py", line 129, in save_checkpoint
    fluid.save(program, os.path.join(ckpt_dir, 'model'))
  File "/usr/local/lib/python3.6/dist-packages/paddle/fluid/io.py", line 1614, in save
    pickle.dump(opt_dict, f, protocol=2)
MemoryError

**Comment by abanger** [comment]
可能是系统资源太紧张，先关了。要是有跳过机制更好。
