### ISSUE TITLE
when I was training with multi-cards ,it occured error!

### ISSUE THREAD

**Issue by lytk01** [PaddlePaddle/PaddleSeg#537]
when I was training with multi-cards ,it occurs error. The error is:
```
Save model checkpoint to ./saved_model/unet/1
Traceback (most recent call last):
  File "pdseg/train.py", line 469, in <module>
    main(args)
  File "pdseg/train.py", line 455, in main
    train(cfg)
  File "pdseg/train.py", line 404, in train
    save_infer_program(test_prog, ckpt_dir)
  File "pdseg/train.py", line 167, in save_infer_program
    paddle.fluid.core.save_op_version_info(_test_program.desc)
AttributeError: module 'paddle.fluid.core_avx' has no attribute 'save_op_version_info'
```
os:ubuntu 18.04
paddle:1.8.5
paddle_seg:0.7.0

**Comment by lytk01** [comment]
It's ok with paddle version 2.0rc.

**Comment by nepeplwu** [comment]
@lytk01 We are very sorry about this, we have fixed this issue in the latest code.
