### ISSUE TITLE
使用deeplabv3p_xception65_cityscapes训练时，直接报错

### ISSUE THREAD

**Issue by choimroc** [PaddlePaddle/PaddleSeg#557]
实验环境：
Windows 10 2004
Python 3.8
paddlepaddle-gpu==2.0.0rc0
PaddleSeg release 0.7.0
cuda 10.2
cudnn 7.6.5

```
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(719), unspecified launch failure.
  [Advise: Please search for the error code(719) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA E
rror.] (at D:\2.0.0-rc0\paddle\paddle\fluid\operators\reader\buffered_reader.cc:144)
  [operator < read > error]


  Compile Traceback (most recent call last):
    File "pdseg/train.py", line 472, in <module>
      main(args)
    File "pdseg/train.py", line 458, in main
      train(cfg)
    File "pdseg/train.py", line 241, in train
      data_loader, avg_loss, lr, pred, grts, masks = build_model(
    File "E:\PycharmProjects\rsips\pdseg\models\model_builder.py", line 139, in build_model
      data_loader = fluid.io.DataLoader.from_generator(
    File "E:\PycharmProjects\rsips\venv\lib\site-packages\paddle\fluid\reader.py", line 681, in from_generator
      return GeneratorLoader(feed_list, capacity, use_double_buffer,
    File "E:\PycharmProjects\rsips\venv\lib\site-packages\paddle\fluid\reader.py", line 1022, in __init__
      self._init_non_iterable()
    File "E:\PycharmProjects\rsips\venv\lib\site-packages\paddle\fluid\reader.py", line 1120, in _init_non_iterable
      default_main_program().current_block().append_op(
    File "E:\PycharmProjects\rsips\venv\lib\site-packages\paddle\fluid\framework.py", line 2911, in append_op
      op = Operator(
    File "E:\PycharmProjects\rsips\venv\lib\site-packages\paddle\fluid\framework.py", line 2014, in __init__
      for frame in traceback.extract_stack():

```

`deeplabv3p_resnet50_vd_cityscapes`和`unet_optic`都是正常的

**Comment by wuyefeilin** [comment]
根据提示是cuda的问题， 你试一下用paddle1.8版本跑一下是否有问题
