### ISSUE TITLE
PSPNET训练异常！！

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleSeg#591]
预训练模型：pspnet50_bn_coco，利用自己数据集训练报错：（自己数据集在UNET训练OK，optic数据训练正常）
 'TRAIN_CROP_SIZE': (512, 512)}
#Device count: 1
batch_size_per_dev: 2
Traceback (most recent call last):
  File "pdseg/train.py", line 468, in <module>
    main(args)
  File "pdseg/train.py", line 454, in main
    train(cfg)
  File "pdseg/train.py", line 238, in train
    train_prog, startup_prog, phase=ModelPhase.TRAIN)
  File "G:\paddle\PaddleSeg\release-v0.7.0\pdseg\models\model_builder.py", line 256, in build_model
    optimizer = solver.Solver(main_prog, start_prog)
  File "G:\paddle\PaddleSeg\release-v0.7.0\pdseg\solver.py", line 41, in __init__
    self.decay_epochs = cfg.SOLVER.NUM_EPOCHS - self.warmup_step / self.step_per_epoch
ZeroDivisionError: division by zero

**Comment by wuyefeilin** [comment]
看提示，是因为你的分母为0。检查一下你的数据集路径是否配置正确
