### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by lyc1995452-star** [PaddlePaddle/PaddleSeg#607]
你好,我在可视化的时候出现这种情况  训练和验证的已经完了
 load_image
    grt_height = grt.shape[0]
IndexError: tuple index out of range

**Comment by wuyefeilin** [comment]
麻烦贴一下具体的报错堆栈

**Comment by lyc1995452-star** [comment]
ile "vis.py", line 212, in <module>
    visualize(cfg, **args.__dict__)
  File "vis.py", line 133, in visualize
    for imgs, grts, img_names, valid_shapes, org_shapes in test_reader:
  File "/home/lyc/models/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 136, in batch_reader
    for img, grt, img_name, valid_shape, org_shape in reader():
  File "/home/lyc/models/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 81, in generator
    yield self.process_image(line, self.data_dir, self.mode)
  File "/home/lyc/models/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 251, in process_image
    line, data_dir, mode=mode)
  File "/home/lyc/models/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 205, in load_image
    grt_height = grt.shape[0]

**Comment by lyc1995452-star** [comment]
Traceback (most recent call last):
  File "vis.py", line 212, in <module>
    visualize(cfg, **args.__dict__)
  File "vis.py", line 133, in visualize
    for imgs, grts, img_names, valid_shapes, org_shapes in test_reader:
  File "/home/lyc/models/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 136, in batch_reader
    for img, grt, img_name, valid_shape, org_shape in reader():
  File "/home/lyc/models/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 81, in generator
    yield self.process_image(line, self.data_dir, self.mode)
  File "/home/lyc/models/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 251, in process_image
    line, data_dir, mode=mode)
  File "/home/lyc/models/PaddleSeg-release-v0.7.0/pdseg/reader.py", line 205, in load_image
    grt_height = grt.shape[0]
IndexError: tuple index out of range
