### ISSUE TITLE
Remote Sensoring AttributeError

### ISSUE THREAD

**Issue by YH-49** [PaddlePaddle/PaddleSeg#698]
错误信息，Linux下会报这个错，而windows下可以运行至内存不足报错，数据已经通过检查，并可以得到相应的均方值和方差。
Traceback (most recent call last):
  File "train_demo.py", line 167, in <module>
    use_vdl=False)
  File "/home/yhao/yaogan/PaddleSeg/contrib/RemoteSensing/models/hrnet.py", line 154, in train
    use_vdl=use_vdl)
  File "/home/yhao/yaogan/PaddleSeg/contrib/RemoteSensing/models/base.py", line 341, in train
    regularization_coeff=regularization_coeff)
  File "/home/yhao/yaogan/PaddleSeg/contrib/RemoteSensing/models/base.py", line 310, in default_optimizer
    regularization_coeff=regularization_coeff))
  File "/home/yhao/anaconda3/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 1137, in __init__
    name=name)
  File "<decorator-gen-90>", line 2, in __init__
  File "/home/yhao/anaconda3/lib/python3.6/site-packages/paddle/fluid/dygraph/base.py", line 253, in __impl__
    return func(*args, **kwargs)
  File "/home/yhao/anaconda3/lib/python3.6/site-packages/paddle/fluid/optimizer.py", line 85, in __init__
    "parameter_list argument given to the Optimizer should not be None in dygraph mode."
AttributeError: parameter_list argument given to the Optimizer should not be None in dygraph mode.

**Comment by YH-49** [comment]
Environment Information
platform: Linux ubuntu 4.4.0-121-generic #145-Ubuntu SMP Fri Apr 13 13:47:23 UTC 2018 x86_64 GNU/Linux
python: 3.6.4
Paddle compiled with cuda: True
NVCC: Cuda compilation tools, release 10.2, V10.2.89
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: TITAN Xp-12GB
GCC: 5.3.0
PaddlePaddle: 2.0.0-rc0
numpy: 1.19.2
gdal: 3.2.0

**Comment by LutaoChu** [comment]
目前RemoteSensing为静态图版本，但从报错信息看你是在动态图模式下运行的。
请在代码最开头切换为静态图模式
```
paddle.enable_static()
```

**Comment by sunhufei** [comment]
好像还是报错

**Comment by YH-49** [comment]
我的这个报错确实是因为动静态图版本问题，之前的版本我也写错了，我用的是2.0.0a0
修改完后还会有一个错是 paddle.fluid.core.save_op_compatible_info 不存在的报错，这个是因为版本更新问题。具体参考链接 https://github.com/PaddlePaddle/PaddleSeg/commit/871ae92e1ff671a40b1952f8c943a1ca9fdd36b2
需要把PaddleSeg/pdseg/utils/paddle_utils.py移动到RemoteSensing/utils/下，然后再把报错的文件，我记得应该是base.py下的哪个paddle.fluid.core.save_op_compatible_info改成paddle_utils.save_op_version_info，后面的括号的内容不用变。

**Comment by YH-49** [comment]
> 目前RemoteSensing为静态图版本，但从报错信息看你是在动态图模式下运行的。
> 请在代码最开头切换为静态图模式
> 
> ```
> paddle.enable_static()
> ```

改了以后确实好了，谢谢，这个是正确改法。

**Comment by LutaoChu** [comment]
> 好像还是报错

报什么错呢？可以先参照YH-49同学的方法试试  https://github.com/PaddlePaddle/PaddleSeg/issues/698#issuecomment-750305166

**Comment by LutaoChu** [comment]
> > 目前RemoteSensing为静态图版本，但从报错信息看你是在动态图模式下运行的。
> > 请在代码最开头切换为静态图模式
> > ```
> > paddle.enable_static()
> > ```
> 
> 改了以后确实好了，谢谢，这个是正确改法。

也感谢你的反馈，正在使Remote Sensing适配paddle 2.0版本
