### ISSUE TITLE
关于filklock 模块导入问题

### ISSUE THREAD

**Issue by prj-jxust** [PaddlePaddle/PaddleSeg#721]
在windows里面训练没有问题，但是在ai studio里面出现ModuleNotFoundError: No module named 'filelock'
具体报错：
`You are using Paddle compiled with TensorRT, but TensorRT dynamic library is not found. Ignore this if TensorRT is not needed.
Traceback (most recent call last):
  File "train.py", line 19, in <module>
    from paddleseg.cvlibs import manager, Config
  File "/home/aistudio/work/PaddleSeg-release-v2.0.0-rc/paddleseg/__init__.py", line 15, in <module>
    from . import models, datasets, transforms
  File "/home/aistudio/work/PaddleSeg-release-v2.0.0-rc/paddleseg/models/__init__.py", line 15, in <module>
    from .backbones import *
  File "/home/aistudio/work/PaddleSeg-release-v2.0.0-rc/paddleseg/models/backbones/__init__.py", line 15, in <module>
    from .hrnet import *
  File "/home/aistudio/work/PaddleSeg-release-v2.0.0-rc/paddleseg/models/backbones/hrnet.py", line 23, in <module>
    from paddleseg.utils import utils
  File "/home/aistudio/work/PaddleSeg-release-v2.0.0-rc/paddleseg/utils/__init__.py", line 19, in <module>
    from .utils import *
  File "/home/aistudio/work/PaddleSeg-release-v2.0.0-rc/paddleseg/utils/utils.py", line 16, in <module>
    import filelock
ModuleNotFoundError: No module named 'filelock'`

paddleseg文件放在work下
环境是python3.7 paddlepaddle2.0.0rc
注释掉paddleseg/utils/utils.py中import filelock没问题，但是导入预训练模型时需要导入filelock，尝试!pip install lockfile 安装成功后依然报同样的错误。
版本为PaddleSeg-release-v2.0.0-rc/

**Comment by wuyefeilin** [comment]
"!pip install lockfile " , 你这个是打错了还是装的时候就是这个样子

**Comment by prj-jxust** [comment]
解决了，谢谢
