### ISSUE TITLE
跑模型humanseg出现问题

### ISSUE THREAD

**Issue by sunhufei** [PaddlePaddle/PaddleSeg#732]
Traceback (most recent call last):
  File "train.py", line 169, in <module>
    train(args)
  File "train.py", line 164, in train
    use_vdl=args.use_vdl)
  File "/home/ck/slu/koutu666/HumanSeg/models/humanseg.py", line 919, in train
    quant=quant)
  File "/home/ck/slu/koutu666/HumanSeg/models/humanseg.py", line 423, in train
    regularization_coeff=regularization_coeff)
  File "/home/ck/slu/koutu666/HumanSeg/models/humanseg.py", line 392, in default_optimizer
    regularization_coeff=regularization_coeff))
  File "/home/ck/.local/lib/python3.7/site-packages/paddle/fluid/optimizer.py", line 1135, in __init__
    name=name)
  File "<decorator-gen-96>", line 2, in __init__
  File "/home/ck/.local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 257, in __impl__
    return func(*args, **kwargs)
  File "/home/ck/.local/lib/python3.7/site-packages/paddle/fluid/optimizer.py", line 84, in __init__
    "parameter_list argument given to the Optimizer should not be None in dygraph mode."
AttributeError: parameter_list argument given to the Optimizer should not be None in dygraph mode.

**Comment by sunhufei** [comment]
这是为什么呀

**Comment by wuyefeilin** [comment]
你是用的什么版本的Paddle

**Comment by sunhufei** [comment]
2.0RC1

**Comment by sunhufei** [comment]
用户的环境是1.6，你用的应该是基于develop分支下的，最新develop分支下的动态图，optimizer需要指定要优化的参数，你看报错信息里是parameter_list为空。目前关于lookaheadoptimizer的最新结论是：动态图当前不支持lookaheadoptimizer。  这是我看官方的，但是这都时间这么长了，paddle还不支持吗

**Comment by wuyefeilin** [comment]
2.0RC1 默认使用动态图， HumanSeg是静态图网络，你可以是用paddle 1.8版本。 或者在代码里增加paddle.enable_static()

**Comment by sunhufei** [comment]
还是报同样的错

**Comment by wuyefeilin** [comment]
你是怎么修改的

**Comment by sunhufei** [comment]
我在train.py中加入您说的这个，

**Comment by wuyefeilin** [comment]
@sunhufei 我看一下你是怎么加的，你同时也试一下1.8版本的
