### ISSUE TITLE
realsr跑不起来

### ISSUE THREAD

**Issue by juzuo** [PaddlePaddle/PaddleSeg#771]
Record at 2021-01-12 15:51:11
==================================================
Traceback (most recent call last):
  File "/home/yingjun/anaconda3/envs/photo_restoration/lib/python3.7/site-packages/paddlehub/module/manager.py", line 222, in search
    module = self._local_modules[name] = HubModule.load(module_dir)
  File "/home/yingjun/anaconda3/envs/photo_restoration/lib/python3.7/site-packages/paddlehub/module/module.py", line 195, in load
    py_module = utils.load_py_module(dirname, '{}.module'.format(basename))
  File "/home/yingjun/anaconda3/envs/photo_restoration/lib/python3.7/site-packages/paddlehub/utils/utils.py", line 249, in load_py_module
    py_module = importlib.import_module(py_module_name)
  File "/home/yingjun/anaconda3/envs/photo_restoration/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 962, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'realsr.module'; 'realsr' is not a package

https://www.paddlepaddle.org.cn/hubdetail?name=realsr&en_category=ImageEditing
按照这个文档运行示例预测代码时出这个错误，请问该怎么处理。。

**Comment by nepeplwu** [comment]
@juzuo 该问题看着是PaddleHub的问题，麻烦将相关问题提到[PaddleHub issue](https://github.com/PaddlePaddle/PaddleHub/issues)
