### ISSUE TITLE
自己模仿OpticDiscSeg，写了一个类，并写了相应的配置文件，训练自己下载的数据，但是运行报错

### ISSUE THREAD

**Issue by David20160511** [PaddlePaddle/PaddleSeg#791]
你好啊,
训练我从网上下载的“BSDS500 轮廓检测与语义分割数据集”，我自己写了一个类，是根据原来官方提供的OpticDiscSeg类，改了类的名字，其他的没变。 
相应的配置文件，我自己也是模仿，重写了一个，把type、dataset_root改了一下，其他的就没改。配置内容如下：
batch_size: 4
iters: 1000

train_dataset:
  type: Bsds500
  dataset_root: E:\dataset\BSR\BSDS500\data
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: Normalize
  mode: train

val_dataset:
  type: Bsds500
  dataset_root: E:\dataset\BSR\BSDS500\data
  transforms:
    - type: Resize
      target_size: [512, 512]
    - type: Normalize
  mode: val

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

learning_rate:
  value: 0.01
  decay:
    type: poly
    power: 0.9
    end_lr: 0

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1, 1, 1, 1, 1]

model:
  type: BiSeNetV2
  num_classes: 2
  pretrained: Null

数据是能够正常加载的，但是运行时报错，报错信息如下：
Traceback (most recent call last):
  File "D:\Program Files (x86)\PyCharm 2020.2.3\plugins\python\helpers\pydev\pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files (x86)\PyCharm 2020.2.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/baidu_example/PaddleSeg/train.py", line 141, in <module>
    main(args)
  File "E:/baidu_example/PaddleSeg/train.py", line 136, in main
    losses=losses)
  File "E:\baidu_example\PaddleSeg\paddleseg\core\train.py", line 143, in train
    loss.backward()
  File "<decorator-gen-113>", line 2, in backward
  File "D:\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\framework.py", line 223, in __impl__
    return func(*args, **kwargs)
  File "D:\Anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 176, in backward
    self._run_backward(framework._dygraph_tracer(), retain_graph)
OSError: (External)  Cudnn error, CUDNN_STATUS_NOT_INITIALIZED  (at d:/2.0.0rc1/paddle/paddle/fluid/operators/conv_cudnn_op.cu:650)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]

python-BaseException
W0119 13:13:45.342010 14064 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.1, Runtime API Version: 11.0
W0119 13:13:45.342010 14064 device_context.cc:330] device: 0, cuDNN Version: 8.0.

**Comment by haoyuying** [comment]
loss写错了，如果只有一个交叉熵损失而没有其他的辅助loss,coef应该只有一个参数
```
loss:
types:
- type: CrossEntropyLoss
coef: [1]
```

**Comment by haoyuying** [comment]
如果您使用了bisenetv2, 在写loss时候请参考:https://github.com/PaddlePaddle/PaddleSeg/blob/release/v2.0.0-rc/configs/bisenet/bisenet_cityscapes_1024x1024_160k.yml

```
loss:
  types:
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
    - type: CrossEntropyLoss
  coef: [1, 1, 1, 1, 1]
```
