### ISSUE TITLE
cannot import paddle

### ISSUE THREAD

**Issue by yangdonghan50** [PaddlePaddle/PaddleSeg#827]
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Can not import avx core while this file exists: /home/vision/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vision/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/__init__.py", line 29, in <module>
    from .fluid import monkey_patch_variable
  File "/home/vision/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/__init__.py", line 35, in <module>
    from . import framework
  File "/home/vision/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/framework.py", line 36, in <module>
    from . import core
  File "/home/vision/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/core.py", line 289, in <module>
    raise e
  File "/home/vision/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/core.py", line 254, in <module>
    from .core_avx import *
ImportError: /home/vision/anaconda3/envs/paddle_env/lib/python3.6/site-packages/paddle/fluid/core_avx.so: symbol GOMP_parallel version VERSION not defined in file libiomp5.so with link time reference

**Comment by michaelowenliu** [comment]
@yangdonghan50 Hi, please make sure you have installed it properly.
