### ISSUE TITLE
PaddleSeg本地和Alstudio上运行，跑完第一轮左右报错

### ISSUE THREAD

**Issue by Taoboan1999** [PaddlePaddle/PaddleSeg#828]
[EVAL]step=21 loss=0.20495 acc=0.9797 IoU=0.0705 step/sec=0.55 | ETA 00:22:16
[EVAL]step=22 loss=0.22256 acc=0.9793 IoU=0.0704 step/sec=0.55 | ETA 00:22:11
[EVAL]step=23 loss=0.13534 acc=0.9796 IoU=0.0703 step/sec=0.54 | ETA 00:22:31
[EVAL]step=24 loss=0.17862 acc=0.9797 IoU=0.0703 step/sec=0.50 | ETA 00:24:18
[EVAL]step=25 loss=0.17866 acc=0.9797 IoU=0.0701 step/sec=0.49 | ETA 00:24:30
[EVAL]step=26 loss=0.17356 acc=0.9798 IoU=0.0700 step/sec=0.52 | ETA 00:23:12
[EVAL]step=27 loss=0.20691 acc=0.9794 IoU=0.0700 step/sec=0.50 | ETA 00:24:15
[EVAL]step=28 loss=0.12772 acc=0.9797 IoU=0.0699 step/sec=0.50 | ETA 00:24:11
[EVAL]step=29 loss=0.21657 acc=0.9795 IoU=0.0699 step/sec=0.45 | ETA 00:26:56
[EVAL]step=30 loss=0.22125 acc=0.9792 IoU=0.0699 step/sec=0.51 | ETA 00:23:27
[EVAL]step=31 loss=0.20101 acc=0.9792 IoU=0.0698 step/sec=0.54 | ETA 00:22:26
C:\Users\Tao Boan\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py:1070: UserWarni
ng: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "./PaddleSeg/pdseg/train.py", line 468, in <module>
    main(args)
  File "./PaddleSeg/pdseg/train.py", line 454, in main
    train(cfg)
  File "./PaddleSeg/pdseg/train.py", line 411, in train
    use_mpio=args.use_mpio)
  File "F:\16thSmartCarCompetition\Online\OfficialVersion\PaddleSeg\pdseg\eval.py", line 137, in evaluate
    test_prog, fetch_list=fetch_list, return_numpy=True)
  File "C:\Users\Tao Boan\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line
1071, in run
    six.reraise(*sys.exc_info())
  File "C:\Users\Tao Boan\AppData\Local\Programs\Python\Python37\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\Tao Boan\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line
1066, in run
    return_merged=return_merged)
  File "C:\Users\Tao Boan\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line
1154, in _run_impl
    use_program_cache=use_program_cache)
  File "C:\Users\Tao Boan\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\executor.py", line
1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "C:\Users\Tao Boan\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\framework.py", line
 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "C:\Users\Tao Boan\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\layer_helper.py", l
ine 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "C:\Users\Tao Boan\AppData\Local\Programs\Python\Python37\lib\site-packages\paddle\fluid\layers\nn.py", line
 14567, in py_func
    'backward_skip_vars': list(backward_skip_vars)
  File "F:\16thSmartCarCompetition\Online\OfficialVersion\PaddleSeg\pdseg\lovasz_losses.py", line 49, in lovasz_gra
d
    cumsum_ = fluid.layers.py_func(func=_cumsum, x=gt_sorted, out=tmp_var)
  File "F:\16thSmartCarCompetition\Online\OfficialVersion\PaddleSeg\pdseg\lovasz_losses.py", line 169, in lovasz_so
ftmax_flat
    grad = lovasz_grad(fg_sorted)
  File "F:\16thSmartCarCompetition\Online\OfficialVersion\PaddleSeg\pdseg\lovasz_losses.py", line 133, in lovasz_so
ftmax
    loss = lovasz_softmax_flat(vprobas, vlabels, classes=classes)
  File "F:\16thSmartCarCompetition\Online\OfficialVersion\PaddleSeg\pdseg\lovasz_losses.py", line 226, in multi_lov
asz_softmax_loss
    avg_loss = lovasz_softmax(probas, label, ignore=ignore_mask)
  File "F:\16thSmartCarCompetition\Online\OfficialVersion\PaddleSeg\pdseg\models\model_builder.py", line 196, in bu
ild_model
    multi_lovasz_softmax_loss(logits, label, mask))
  File "F:\16thSmartCarCompetition\Online\OfficialVersion\PaddleSeg\pdseg\eval.py", line 94, in evaluate
    test_prog, startup_prog, phase=ModelPhase.EVAL)
  File "./PaddleSeg/pdseg/train.py", line 411, in train
    use_mpio=args.use_mpio)
  File "./PaddleSeg/pdseg/train.py", line 454, in main
    train(cfg)
  File "./PaddleSeg/pdseg/train.py", line 468, in <module>
    main(args)

----------------------
Error Message Summary:
----------------------
Error: Fail to allocate CPU memory: size = 524288000 .
  [Hint: p should not be null.] at (D:\1.8.5\paddle\paddle\fluid\memory\detail\system_allocator.cc:61)
  [operator < py_func > error]

**Comment by LutaoChu** [comment]
你好，训练过程内存不足了。请关掉其他无用的进程，减少batchsize试试。

另外推荐用最新动态图版本的lovasz loss，应该不存在这个问题
https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/lovasz_loss.md
