### ISSUE TITLE
使用自定义数据集训练出现维度问题

### ISSUE THREAD

**Issue by yuemengrui** [PaddlePaddle/PaddleSeg#832]
使用的是这个，deeplabv3p_resnet50_os8_webCV_1024x512_80k 

Traceback (most recent call last):
  File "train.py", line 141, in <module>
    main(args)
  File "train.py", line 136, in main
    losses=losses)
  File "/home/aistudio/PaddleSeg/paddleseg/core/train.py", line 141, in train
    edges=edges)
  File "/home/aistudio/PaddleSeg/paddleseg/core/train.py", line 44, in loss_computation
    loss += losses['coef'][i] * loss_i(logits, labels)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleSeg/paddleseg/models/losses/cross_entropy_loss.py", line 55, in forward
    logit, label, ignore_index=self.ignore_index, axis=-1)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/loss.py", line 1264, in softmax_with_cross_entropy
    axis)
ValueError: (InvalidArgument) Input(Logits) and Input(Label) should in same shape in dimensions except axis.
  [Hint: Expected logits_dims[i] == labels_dims[i], but received logits_dims[i]:512 != labels_dims[i]:1024.] (at /paddle/paddle/fluid/operators/softmax_with_cross_entropy_op.cc:145)
  [operator < softmax_with_cross_entropy > error]

**Comment by wuyefeilin** [comment]
请问你的数据集总共多少个类别？ 最后网络输出的logit的通道数是要等于数据集的类别数的。

**Comment by yuemengrui** [comment]
> 请问你的数据集总数多少个类别？最后网络输出的logit的通道数是要等于数据集的类别数的。

2个
train_dataset:
  type: Dataset
  dataset_root: web_cv_data
  train_path: web_cv_data/train.txt
  num_classes: 2
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.5
      max_scale_factor: 2.0
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [1024, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.4
      contrast_range: 0.4
      saturation_range: 0.4
    - type: Normalize
  mode: train

**Comment by wuyefeilin** [comment]
标注图像的数值是0 和1 吗？

**Comment by yuemengrui** [comment]
> 标注图像的数值是0 和1 吗？

是的
不过是三通道的，要转成灰度吗

**Comment by wuyefeilin** [comment]
是的，转成灰度图，并存成png格式

**Comment by yuemengrui** [comment]
> 是的，转成灰度图，并存成png格式

谢谢！解决了
