### ISSUE TITLE
Aistudio运行PaddleSeg/train.py 使用resume_model 报错

### ISSUE THREAD

**Issue by wudiyidashi** [PaddlePaddle/PaddleSeg#837]
!python PaddleSeg/train.py --config ocrnet.yml \
                            --do_eval \
                            --use_vdl \
                            --save_interval 10000 \
                            --save_dir output \
                            --resume_model ./output/iter_70000

`2021-02-11 14:03:24 [INFO]	
------------Environment Information-------------
platform: Linux-4.4.0-166-generic-x86_64-with-debian-stretch-sid
Python: 3.7.4 (default, Aug 13 2019, 20:35:49) [GCC 7.3.0]
Paddle compiled with cuda: False
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
PaddlePaddle: 2.0.0
OpenCV: 4.1.1
------------------------------------------------
2021-02-11 14:03:24 [INFO]	
---------------Config Information---------------
batch_size: 2
iters: 160000
learning_rate:
  decay:
    end_lr: 0.0
    power: 0.9
    type: poly
  value: 0.01
loss:
  coef:
  - 1
  - 0.4
  types:
  - ignore_index: 255
    type: CrossEntropyLoss
  - ignore_index: 255
    type: CrossEntropyLoss
model:
  backbone:
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz
    type: HRNet_W48
  backbone_indices:
  - 0
  num_classes: 15
  type: OCRNet
optimizer:
  type: sgd
  weight_decay: 4.0e-05
train_dataset:
  dataset_root: /home/aistudio/
  mode: train
  num_classes: 15
  train_path: /home/aistudio/train_list.txt
  transforms:
  - im_padding_value:
    - 255
    - 255
    - 255
    label_padding_value: 0
    type: RandomRotation
  - crop_size:
    - 1024
    - 512
    type: RandomPaddingCrop
  - prob: 0.5
    type: RandomHorizontalFlip
  - prob: 0.2
    type: RandomBlur
  - type: Normalize
  type: Dataset
val_dataset:
  dataset_root: /home/aistudio/
  mode: val
  num_classes: 15
  transforms:
  - type: Normalize
  type: Dataset
  val_path: /home/aistudio/val_list.txt
------------------------------------------------
2021-02-11 14:03:28 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/hrnet_w48_ssld.tar.gz
2021-02-11 14:03:31 [INFO]	There are 1525/1525 variables loaded into HRNet.
2021-02-11 14:03:31 [INFO]	Resume model from ./output/iter_70000
Traceback (most recent call last):
  File "PaddleSeg/train.py", line 141, in <module>
    main(args)
  File "PaddleSeg/train.py", line 136, in main
    losses=losses)
  File "/home/aistudio/PaddleSeg/paddleseg/core/train.py", line 85, in train
    start_iter = resume(model, optimizer, resume_model)
  File "/home/aistudio/PaddleSeg/paddleseg/utils/utils.py", line 110, in resume
    optimizer.set_state_dict(opti_state_dict)
  File "</opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/decorator.py:decorator-gen-190>", line 2, in set_state_dict
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 225, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/optimizer/optimizer.py", line 224, in set_state_dict
    "optimizer Tensor {} not found".format( var_tmp.name )
AssertionError: optimizer Tensor batch_norm2d_0.w_0_velocity_0 not found`

**Comment by wudiyidashi** [comment]
重启后又能用了
