### ISSUE TITLE
unet_plusplus 训练验证时出现数据维度问题

### ISSUE THREAD

**Issue by yuemengrui** [PaddlePaddle/PaddleSeg#839]
Traceback (most recent call last):
  File "train.py", line 142, in <module>
    main(args)
  File "train.py", line 137, in main
    losses=losses)
  File "/home/aistudio/PaddleSeg/paddleseg/core/train.py", line 179, in train
    model, val_dataset, num_workers=num_workers)
  File "/home/aistudio/PaddleSeg/paddleseg/core/val.py", line 110, in evaluate
    crop_size=crop_size)
  File "/home/aistudio/PaddleSeg/paddleseg/core/infer.py", line 169, in inference
    logits = model(im)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleSeg/paddleseg/models/unet_plusplus.py", line 158, in forward
    X1_1 = self.up_cat1_1(X2_0, X1_0)  # n,64,h/2,w/2
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleSeg/paddleseg/models/unet_plusplus.py", line 233, in forward
    cat_features = paddle.concat(features, axis=1)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/manipulation.py", line 124, in concat
    return paddle.fluid.layers.concat(input=x, axis=axis, name=name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/tensor.py", line 306, in concat
    return core.ops.concat(input, 'axis', axis)
ValueError: (InvalidArgument) The 2-th dimension of input[0] and input[1] is expected to be equal.But received input[0]'s shape = [1, 64, 466, 960], input[1]'s shape = [1, 64, 467, 960].
  [Hint: Expected inputs_dims[0][j] == inputs_dims[i][j], but received inputs_dims[0][j]:466 != inputs_dims[i][j]:467.] (at /paddle/paddle/fluid/operators/concat_op.h:63)
  [operator < concat > error]
上面是报错信息
同样的训练验证数据在deeplabv3p上是没问题的。

**Comment by haoyuying** [comment]
您好，可参考https://github.com/PaddlePaddle/PaddleSeg/issues/812
