### ISSUE TITLE
使用Deeplab训练好自己的数据集之后，使用eval.py一直报错，求帮助！

### ISSUE THREAD

**Issue by eddieheyutong** [PaddlePaddle/PaddleSeg#854]
我使用Deeplab训练了自己的数据集，已经训练好了，想要进行测试，我的验证集也是按照要求进行规范的设置的，但是会报以下的错误，大神们帮忙看看是什么原因造成的？

2021-03-01 22:25:29,054-WARNING: Your reader has raised an exception!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/heyutong/.local/lib/python3.6/site-packages/paddle/fluid/reader.py", line 1145, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/home/heyutong/.local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/heyutong/.local/lib/python3.6/site-packages/paddle/fluid/reader.py", line 1125, in __thread_main__
    for tensors in self._tensor_reader():
  File "/home/heyutong/.local/lib/python3.6/site-packages/paddle/fluid/data_feeder.py", line 196, in __call__
    for each_sample in self.generator():
  File "pdseg/eval.py", line 90, in data_generator
    for b in data_gen:
  File "/home/heyutong/PaddleSeg/pdseg/reader.py", line 81, in generator
    yield self.process_image(line, self.data_dir, self.mode)
  File "/home/heyutong/PaddleSeg/pdseg/reader.py", line 310, in process_image
    img, grt = aug.rand_crop(img, grt, mode=mode)
  File "/home/heyutong/PaddleSeg/pdseg/data_aug.py", line 398, in rand_crop
    .format(crop_width, crop_height, img_width, img_height))
Exception: Crop size(2049,1025) must large than img size(6000,8000) when in EvalPhase.

/home/heyutong/.local/lib/python3.6/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "pdseg/eval.py", line 181, in <module>
    main()
  File "pdseg/eval.py", line 176, in main
    evaluate(cfg, **args.__dict__)
  File "pdseg/eval.py", line 137, in evaluate
    test_prog, fetch_list=fetch_list, return_numpy=True)
  File "/home/heyutong/.local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/heyutong/.local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/heyutong/.local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/heyutong/.local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/heyutong/.local/lib/python3.6/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/heyutong/.local/lib/python3.6/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/heyutong/.local/lib/python3.6/site-packages/paddle/fluid/reader.py", line 1080, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "/home/heyutong/.local/lib/python3.6/site-packages/paddle/fluid/reader.py", line 978, in __init__
    self._init_non_iterable()
  File "/home/heyutong/.local/lib/python3.6/site-packages/paddle/fluid/reader.py", line 620, in from_generator
    iterable, return_list, drop_last)
  File "/home/heyutong/PaddleSeg/pdseg/models/model_builder.py", line 143, in build_model
    use_double_buffer=True)
  File "pdseg/eval.py", line 94, in evaluate
    test_prog, startup_prog, phase=ModelPhase.EVAL)
  File "pdseg/eval.py", line 176, in main
    evaluate(cfg, **args.__dict__)
  File "pdseg/eval.py", line 181, in <module>
    main()

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
  [operator < read > error]

**Comment by michaelowenliu** [comment]
@eddieheyutong Hi, please check the error log.

**Comment by LutaoChu** [comment]
看起来跟你的EVAL_CROP_SIZE有关，可以提供一下配置文件吗
