### ISSUE TITLE
基于baseline项目更改模型报错

### ISSUE THREAD

**Issue by kyrios-sam** [PaddlePaddle/PaddleSeg#860]
项目里原来的模型是deeplabv3p，例如想更换成fscnn模型，更换失败，请问这个问题能怎么解决呢？或者说有什么文档可以教一下如何更换paddleseg里的其他已有模型吗？

W0307 20:40:16.634291  1222 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0307 20:40:16.634341  1222 device_context.cc:372] device: 0, cuDNN Version: 7.6.
2021-03-07 20:40:21 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/resnet50_vd_ssld_v2.tar.gz
2021-03-07 20:40:22 [INFO]	There are 275/275 variables loaded into ResNet_vd.
Traceback (most recent call last):
  File "PaddleSeg/train.py", line 141, in <module>
    main(args)
  File "PaddleSeg/train.py", line 136, in main
    losses=losses)
  File "/home/aistudio/PaddleSeg/paddleseg/core/train.py", line 141, in train
    edges=edges)
  File "/home/aistudio/PaddleSeg/paddleseg/core/train.py", line 35, in loss_computation
    check_logits_losses(logits_list, losses)
  File "/home/aistudio/PaddleSeg/paddleseg/core/train.py", line 31, in check_logits_losses
    .format(len_logits, len_losses))
RuntimeError: The length of logits_list should equal to the types of loss config: 4 != 1.

**Comment by michaelowenliu** [comment]
@kyrios-sam Hi, please check the error info.
