### ISSUE TITLE
静态图版本下启动训练后一直刷屏下面的错误，是什么问题啊？

### ISSUE THREAD

**Issue by lybcodes** [PaddlePaddle/PaddleSeg#862]
----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(4), unspecified launch failure.
  [Advise: An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. All existing device memory allocations are invalid. To con
tinue using CUDA, theprocess must be terminated and relaunched.] at (D:\1.8.5\paddle\paddle\fluid\operators\reader\buffered_reader.cc:107)
  [operator < read > error]Traceback (most recent call last):
  File "pdseg/train.py", line 385, in train
    return_numpy=True)
  File "G:\Anaconda\envs\paddle1.8.5\lib\site-packages\paddle\fluid\executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "G:\Anaconda\envs\paddle1.8.5\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "G:\Anaconda\envs\paddle1.8.5\lib\site-packages\paddle\fluid\executor.py", line 1066, in run
    return_merged=return_merged)
  File "G:\Anaconda\envs\paddle1.8.5\lib\site-packages\paddle\fluid\executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "G:\Anaconda\envs\paddle1.8.5\lib\site-packages\paddle\fluid\executor.py", line 879, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
Windows not support stack backtrace yet.

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "G:\Anaconda\envs\paddle1.8.5\lib\site-packages\paddle\fluid\framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "G:\Anaconda\envs\paddle1.8.5\lib\site-packages\paddle\fluid\reader.py", line 1080, in _init_non_iterable
    attrs={'drop_last': self._drop_last})
  File "G:\Anaconda\envs\paddle1.8.5\lib\site-packages\paddle\fluid\reader.py", line 978, in __init__
    self._init_non_iterable()
  File "G:\Anaconda\envs\paddle1.8.5\lib\site-packages\paddle\fluid\reader.py", line 620, in from_generator
    iterable, return_list, drop_last)
  File "G:\lyb\seg\PaddleSeg-release-v2.0\legacy\pdseg\models\model_builder.py", line 143, in build_model
    use_double_buffer=True)
  File "pdseg/train.py", line 252, in train
    train_prog, startup_prog, phase=ModelPhase.TRAIN)
  File "pdseg/train.py", line 472, in main
    train(cfg)
  File "pdseg/train.py", line 486, in <module>
    main(args)

**Comment by BeyondYourself** [comment]
![image](https://user-images.githubusercontent.com/12640462/110414224-6dded000-80ca-11eb-9e32-fdc04200a871.png)
根据你这个报错，应该是资源不足了，建议先用CPU版本试试

**Comment by lybcodes** [comment]
> ![image](https://user-images.githubusercontent.com/12640462/110414224-6dded000-80ca-11eb-9e32-fdc04200a871.png)
> 根据你这个报错，应该是资源不足了，建议先用CPU版本试试

就是我执行训练命令的时候不加--use_gpu参数吗，还是说换一个paddleSeg版本

**Comment by BeyondYourself** [comment]
可以先试试，你应该用的是2.0以前的版本吧
