### ISSUE TITLE
训练中val中出现的异常

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/PaddleSeg#864]
在用2.0的接口进行训练的时候出现的异常，
CPU环境下，Windows平台进行训练：
`2021-03-09 16:12:49 [INFO]	Start evaluating (total_samples=3, total_iters=3)...
Traceback (most recent call last):
  File "D:\PyCharm 2019.2.1\helpers\pydev\pydevd.py", line 2074, in <module>
    main()
  File "D:\PyCharm 2019.2.1\helpers\pydev\pydevd.py", line 2067, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\PyCharm 2019.2.1\helpers\pydev\pydevd.py", line 1411, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "D:\PyCharm 2019.2.1\helpers\pydev\pydevd.py", line 1418, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\PyCharm 2019.2.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:/oschinagitee/PaddleSeg/train.py", line 162, in <module>
    main(args)
  File "E:/oschinagitee/PaddleSeg/train.py", line 157, in main
    keep_checkpoint_max=args.keep_checkpoint_max)
  File "E:\oschinagitee\PaddleSeg\paddleseg\core\train.py", line 214, in train
    model, val_dataset, num_workers=num_workers)
  File "E:\oschinagitee\PaddleSeg\paddleseg\core\val.py", line 117, in evaluate
    crop_size=crop_size)
  File "E:\oschinagitee\PaddleSeg\paddleseg\core\infer.py", line 196, in inference
    pred = reverse_transform(pred, ori_shape, transforms)
  File "E:\oschinagitee\PaddleSeg\paddleseg\core\infer.py", line 71, in reverse_transform
    pred = F.interpolate(pred, (h, w), mode='nearest')
  File "D:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle\nn\functional\common.py", line 483, in interpolate
    out = core.ops.nearest_interp_v2(x, *dy_attr)

RuntimeError: (NotFound) Operator nearest_interp_v2 does not have kernel for data_type[int]:data_layout[ANY_LAYOUT]:place[CPUPlace]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at D:\v2.0.0\paddle\paddle\fluid\imperative\prepared_operator.cc:127)
  [operator < nearest_interp_v2 > error]`

**Comment by wuyefeilin** [comment]
看样子是op的问题，已提交给相关的同学进行处理。 目前你可以将函数改成如下形式进行规避：
函数位置：https://github.com/PaddlePaddle/PaddleSeg/blob/develop/paddleseg/core/infer.py#L65
```
def reverse_transform(pred, ori_shape, transforms):
    """recover pred to origin shape"""
    reverse_list = get_reverse_list(ori_shape, transforms)
    pred = pred.astype('float32')
    for item in reverse_list[::-1]:
        if item[0] == 'resize':
            h, w = item[1][0], item[1][1]
            pred = F.interpolate(pred, (h, w), mode='nearest')
        elif item[0] == 'padding':
            h, w = item[1][0], item[1][1]
            pred = pred[:, :, 0:h, 0:w]
        else:
            raise Exception("Unexpected info '{}' in im_info".format(item[0]))
    pred = pred.astype('int32')
    return pred
```
