### ISSUE TITLE
样例模型测试失败

### ISSUE THREAD

**Issue by changbaishan** [PaddlePaddle/PaddleSeg#877]
点击下载我们的样例模型用于测试

(paddle) yong@yong-virtual-machine:~/Documents/sandbox/paddle/PaddleSeg$ ls -al bisenet_demo_model
total 11096
drwxrwxr-x  2 yong yong     4096 Jan 20 08:04 .
drwxr-xr-x 15 yong yong     4096 Mar 12 09:34 ..
-rw-rw-r--  1 yong yong       91 Jan 20 07:58 deploy.yaml
-rw-rw-r--  1 yong yong 10137989 Jan 20 07:58 model.pdiparams
-rw-rw-r--  1 yong yong    31656 Jan 20 07:58 model.pdiparams.info
-rw-rw-r--  1 yong yong  1174867 Jan 20 07:58 model.pdmodel
(paddle) yong@yong-virtual-machine:~/Documents/sandbox/paddle/PaddleSeg$ 

(paddle) yong@yong-virtual-machine:~/Documents/sandbox/paddle/PaddleSeg$ python3 deploy/python/infer.py --config /home/yong/Documents/sandbox/paddle/PaddleSeg/bisenet_demo_model/deploy.yaml --image_path /home/yong/Pictures/samples/Hangzhou.jpg
Traceback (most recent call last):
  File "deploy/python/infer.py", line 192, in <module>
    main(args)
  File "deploy/python/infer.py", line 187, in main
    predictor.run(get_images(args.image_path))
  File "deploy/python/infer.py", line 100, in run
    self.predictor.run()
ValueError: In user code:

    File "export.py", line 88, in <module>
      main(args)
    File "export.py", line 66, in main
      out = net(in_var)
    File "/mnt/wuzewu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/mnt/wuzewu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 335, in __call__
      *args, **kwargs)
    File "/mnt/wuzewu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/mnt/wuzewu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/mnt/wuzewu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
      class_instance=cache_key.class_instance)
    File "<decorator-gen-58>", line 2, in from_func_spec
      
    File "/mnt/wuzewu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/mnt/wuzewu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
      return func(*args, **kwargs)
    File "/mnt/wuzewu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 652, in from_func_spec
      outputs = static_func(*inputs)
    File "/mnt/wuzewu/code/wzw-PaddleSeg/paddleseg/models/bisenet.py", line 75, in forward
      logit = self.head(self.bga(dfm, sfm))
    File "/mnt/wuzewu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/mnt/wuzewu/code/wzw-PaddleSeg/paddleseg/models/bisenet.py", line 275, in forward
      db_feat = db_feat_keep * sb_feat_up
    File "/mnt/wuzewu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 304, in __impl__
      attrs={'axis': axis})
    File "/mnt/wuzewu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3022, in append_op
      attrs=kwargs.get("attrs", None))
    File "/mnt/wuzewu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2106, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 128, 75, 150] and the shape of Y = [1, 128, 128, 256]. Received [75] in X is not equal to [128] in Y at i:2.
      [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:160)
      [operator < elementwise_mul > error]

**Comment by nepeplwu** [comment]
@changbaishan 感谢反馈，请问你使用的测试图片是什么？

**Comment by changbaishan** [comment]
![Hangzhou](https://user-images.githubusercontent.com/12687044/111468513-034a1780-86fc-11eb-8a60-247950acce2f.jpg)

**Comment by nepeplwu** [comment]
@changbaishan 该问题已经在最新代码中修复，并且我们也重新上传了测试样例，请更新到分支`release/v2.0`的最新代码，并且重新下载部署文档里的测试样例。

另外，该模型是使用cityscapes数据集训练的，适用于街景道路场景下的预测，对于上面所提供的图片，效果会比较差，可以使用我们部署文档里面提供的测试图片体验下效果。
