### ISSUE TITLE
使用量化时出现如下错误，请问如何解决IndexError: tuple index out of range

### ISSUE THREAD

**Issue by YAwei666** [PaddlePaddle/PaddleSeg#903]
admin@mk-NF5468M5:/data/wyw/PaddleSeg$ python slim/quant.py        --config configs/quick_start/hrnetocr_zm_128x128_3k.yml         --retraining_iters 100        --model_path output/best_model/model.pdparams        --save_dir quant_model
/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/matplotlib/backend_bases.py:55: DeprecationWarning: PILLOW_VERSION is deprecated and will be removed in Pillow 9 (2022-01-02). Use __version__ instead.
  from PIL import PILLOW_VERSION
W0319 14:09:36.752319 25045 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.0
W0319 14:09:36.752391 25045 device_context.cc:372] device: 0, cuDNN Version: 8.0.
2021-03-19 14:09:49 [INFO]	Loading pretrained model from https://bj.bcebos.com/paddleseg/dygraph/hrnet_w18_ssld.tar.gz
2021-03-19 14:09:52 [INFO]	There are 1525/1525 variables loaded into HRNet.
2021-03-19 14:09:54 [INFO]	Loaded trained params of model successfully
2021-03-19 14:09:54 [INFO]	Step 1/2: Start to quantify the model...
2021-03-19 14:09:56 [INFO]	Model quantification completed.
2021-03-19 14:09:56 [INFO]	Step 2/2: Start retraining the quantized model.
2021-03-19 14:10:26 [INFO]	[TRAIN] epoch=1, iter=10/100, loss=0.0627, lr=0.009186, batch_cost=2.9668, reader_cost=0.2527 | ETA 00:04:27
2021-03-19 14:10:44 [INFO]	[TRAIN] epoch=1, iter=20/100, loss=0.0839, lr=0.008272, batch_cost=1.7820, reader_cost=0.0030 | ETA 00:02:22
2021-03-19 14:11:04 [INFO]	[TRAIN] epoch=1, iter=30/100, loss=0.0846, lr=0.007347, batch_cost=1.9910, reader_cost=0.0030 | ETA 00:02:19
2021-03-19 14:11:24 [INFO]	[TRAIN] epoch=1, iter=40/100, loss=0.0828, lr=0.006409, batch_cost=1.9874, reader_cost=0.0043 | ETA 00:01:59
2021-03-19 14:11:43 [INFO]	[TRAIN] epoch=1, iter=50/100, loss=0.0860, lr=0.005455, batch_cost=1.9292, reader_cost=0.0020 | ETA 00:01:36
2021-03-19 14:12:03 [INFO]	[TRAIN] epoch=1, iter=60/100, loss=0.0857, lr=0.004482, batch_cost=1.9467, reader_cost=0.0005 | ETA 00:01:17
2021-03-19 14:12:21 [INFO]	[TRAIN] epoch=1, iter=70/100, loss=0.0812, lr=0.003485, batch_cost=1.8124, reader_cost=0.0043 | ETA 00:00:54
2021-03-19 14:12:40 [INFO]	[TRAIN] epoch=1, iter=80/100, loss=0.0882, lr=0.002455, batch_cost=1.9090, reader_cost=0.0042 | ETA 00:00:38
2021-03-19 14:13:02 [INFO]	[TRAIN] epoch=1, iter=90/100, loss=0.0823, lr=0.001372, batch_cost=2.1749, reader_cost=0.0026 | ETA 00:00:21
2021-03-19 14:13:20 [INFO]	[TRAIN] epoch=1, iter=100/100, loss=0.0830, lr=0.000158, batch_cost=1.8248, reader_cost=0.0039 | ETA 00:00:00
2021-03-19 14:13:28 [INFO]	Start evaluating (total_samples=1673, total_iters=1673)...
******************** [1, 3, 100, 128] (1, 1, 100, 128)
1673/1673 [==============================] - 988s 591ms/step - batch_cost: 0.5902 - reader cost: 0.0016************ [1, 3, 100, 128] (1, 1, 100, 128))))128)128)
2021-03-19 14:29:56 [INFO]	[EVAL] #Images=1673 mIoU=0.9496 Acc=0.9748 Kappa=0.9482 
2021-03-19 14:29:56 [INFO]	[EVAL] Class IoU: 
[0.9578 0.9413]
2021-03-19 14:29:56 [INFO]	[EVAL] Class Acc: 
[0.9814 0.9656]
/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  return (isinstance(seq, collections.Sequence) and
Traceback (most recent call last):
  File "slim/quant.py", line 186, in <module>
    main(args)
  File "slim/quant.py", line 161, in main
    quantizer.save_quantized_model(net, save_path, input_spec=[input_var])
  File "/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/paddleslim/dygraph/quant/quanter.py", line 225, in save_quantized_model
    layer=model, path=path, input_spec=input_spec)
  File "/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/paddle/fluid/contrib/slim/quantization/imperative/qat.py", line 317, in save_quantized_model
    self._out_scale.save_quantized_model(layer, path, input_spec, **config)
  File "/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/paddle/fluid/contrib/slim/quantization/imperative/qat.py", line 396, in save_quantized_model
    paddle.jit.save(layer=layer, path=path, input_spec=input_spec, **config)
  File "<decorator-gen-60>", line 2, in save
  File "/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 686, in save
    concrete_program = static_forward.concrete_program
  File "/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 454, in concrete_program
    return self.concrete_program_specify_input_spec(input_spec=None)
  File "/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-58>", line 2, in from_func_spec
  File "/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 658, in from_func_spec
    error_data.raise_new_exception()
  File "/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 189, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
IndexError: In transformed code:

    File "/data/wyw/PaddleSeg/paddleseg/models/ocrnet.py", line 73, in forward (* user code *)
	logit_list = self.head(feats)
    File "/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "/data/wyw/PaddleSeg/paddleseg/models/ocrnet.py", line 130, in forward (* user code *)
	object_regions = self.spatial_gather(pixels, soft_regions)
    File "/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 891, in __call__
	outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmp2ioo3o5s.py", line 18, in forward
	in_control_flow=False)))
    File "/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 289, in convert_var_shape
	idx)):
    File "/home/admin/anaconda3/envs/wyw/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 272, in has_negetive
	return list_shape[idx] < 0
    IndexError: tuple index out of range

**Comment by nepeplwu** [comment]
@YAwei666 感谢反馈，请使用paddlepaddle 2.0.1版本试试
