### ISSUE TITLE
DataLoader reader thread raised an exception!

### ISSUE THREAD

**Issue by pkuCactus** [PaddlePaddle/PaddleSeg#921]
When I run the val with 1 gpu and multiple workers occurs the problem.

python val.py --config configs/mscale_ocr_cityscapes_autolabel_mapillary_ms_val.yml --num_workers 0 --model_path /workspace/trained_models/paddleseg_params/cs_paddleseg_model.pdparams --aug_eval --flip_horizontal

2021-03-27 10:08:04,811 - ERROR - DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "val.py", line 137, in <module>
    main(args)
  File "val.py", line 131, in main
    num_workers=args.num_workers,
  File "/root/anaconda3/lib/python3.7/site-packages/paddleseg/core/val.py", line 92, in evaluate
    for iter, (im, label) in enumerate(loader):
  File "/root/anaconda3/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 779, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

But when I set the num_worker to 0, it can run normally.

**Comment by pkuCactus** [comment]
It should be the problem of server, when i use another one, there is no problem.

**Comment by chenzhaoqiJM** [comment]
在window下标注产生的train.txt中文件路径为\，查找替换改成/就好了，我的是这样的
